<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { http } from "@/utils/http";

const route = useRoute(); const router = useRouter(); const resource = ref<any>(null); const attachments = ref<any[]>([]); const metadata = ref<any[]>([]); const relations = ref<any[]>([]); const activities = ref<any[]>([]); const userState = ref<any>({ favorite: false }); const loading = ref(false); const saving = ref(false); const error = ref(""); const editDialog = ref(false); const form = ref({ primaryTitle: "", summary: "" });
async function load() { loading.value = true; error.value = ""; const id = route.params.resourceId; try { const [item, files, fields, links, state, activity] = await Promise.all([http.get(`/resources/${id}`), http.get(`/resources/${id}/attachments`).catch(() => []), http.get(`/resources/${id}/metadata`).catch(() => []), http.get(`/resources/${id}/relations`).catch(() => []), http.get(`/resources/${id}/user-state`).catch(() => ({ favorite: false })), http.get(`/activity?limit=200`).catch(() => [])]); resource.value = item; attachments.value = Array.isArray(files) ? files : []; metadata.value = Array.isArray(fields) ? fields : []; relations.value = Array.isArray(links) ? links : []; userState.value = state || { favorite: false }; activities.value = (Array.isArray(activity) ? activity : []).filter((entry: any) => String(entry.resourceId) === String(id)); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Resource Detail 加载失败"; } finally { loading.value = false; } }
function beginEdit() { form.value = { primaryTitle: resource.value?.primaryTitle || resource.value?.title || "", summary: resource.value?.summary || "" }; editDialog.value = true; }
async function save() { if (!resource.value) return; saving.value = true; try { resource.value = await http.request("patch", `/resources/${resource.value.id}`, { data: { primary_title: form.value.primaryTitle, summary: form.value.summary }, headers: { "Content-Type": "application/merge-patch+json", "If-Match": `"${resource.value.version ?? 0}"` } }); editDialog.value = false; } catch (e: any) { error.value = e?.response?.status === 409 ? "Resource 已被修改，请刷新后重试。" : e?.response?.data?.detail || e?.message || "保存失败"; } finally { saving.value = false; } }
async function archive() { if (!resource.value || !window.confirm("确认归档这个 Resource 吗？")) return; try { resource.value = await http.post(`/resources/${resource.value.id}/actions/archive`, { headers: { "If-Match": `"${resource.value.version ?? 0}"` } }); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "归档失败"; } }
async function trash() { if (!resource.value || !window.confirm("确认将这个 Resource 移入回收站吗？")) return; try { await http.post(`/resources/${resource.value.id}/actions/trash`, { headers: { "If-Match": `"${resource.value.version ?? 0}"` } }); router.push("/library"); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "移入回收站失败"; } }
async function toggleFavorite() { if (!resource.value) return; try { if (userState.value.favorite) await http.request("delete", `/resources/${resource.value.id}/favorite`); else await http.post(`/resources/${resource.value.id}/favorite`); userState.value.favorite = !userState.value.favorite; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "收藏状态更新失败"; } }
onMounted(load);
</script>

<template>
  <main class="p-4 md:p-6"><div class="flex flex-wrap justify-between items-start gap-4 mb-6"><div><p class="text-sm text-[var(--el-text-color-secondary)]">Library / Resource Detail</p><h1 class="mt-2 text-2xl font-semibold">{{ resource?.primaryTitle || resource?.title || route.params.resourceId }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">Canonical workspace：集中查看可用性、来源、关系和活动。</p></div><div class="flex gap-2"><el-button @click="router.push('/library')">返回 Library</el-button><el-button :loading="loading" @click="load">刷新</el-button><el-button v-if="resource" @click="toggleFavorite">{{ userState.favorite ? '取消收藏' : '收藏' }}</el-button><el-button v-if="resource" type="primary" @click="beginEdit">编辑元数据</el-button><el-button v-if="resource?.lifecycle === 'ACTIVE'" type="warning" @click="archive">归档</el-button><el-button v-if="resource && resource.lifecycle !== 'TRASH'" type="danger" @click="trash">移入回收站</el-button></div></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false"/><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else-if="resource" shadow="never" class="mt-4"><el-tabs><el-tab-pane label="Overview"><el-descriptions :column="1" border><el-descriptions-item label="标题">{{ resource.primaryTitle || resource.title || "—" }}</el-descriptions-item><el-descriptions-item label="类型">{{ resource.type || resource.resourceType || "—" }}</el-descriptions-item><el-descriptions-item label="Availability"><el-tag>{{ resource.availability || "—" }}</el-tag></el-descriptions-item><el-descriptions-item label="Lifecycle"><el-tag>{{ resource.lifecycle || resource.status || "ACTIVE" }}</el-tag></el-descriptions-item><el-descriptions-item label="用户状态">{{ userState.statusCode || "未设置" }}</el-descriptions-item><el-descriptions-item label="摘要">{{ resource.summary || "—" }}</el-descriptions-item></el-descriptions></el-tab-pane><el-tab-pane label="Files"><el-empty v-if="!attachments.length" description="暂无 Attachment"/><el-table v-else :data="attachments" stripe><el-table-column prop="fileName" label="业务角色 / 文件名" min-width="260"/><el-table-column prop="availability" label="Availability" width="150"/><el-table-column prop="sizeBytes" label="大小" width="140"/><el-table-column prop="blobId" label="Blob ID（Advanced）" min-width="240"/></el-table></el-tab-pane><el-tab-pane label="Metadata"><el-empty v-if="!metadata.length" description="暂无扩展字段"/><el-table v-else :data="metadata" stripe><el-table-column prop="fieldKey" label="字段" width="180"/><el-table-column prop="value" label="当前值" min-width="240"/><el-table-column prop="source" label="来源" width="160"/><el-table-column prop="manuallyLocked" label="人工确认" width="120"/></el-table></el-tab-pane><el-tab-pane label="Relations"><el-empty v-if="!relations.length" description="暂无 Resource 关系"/><el-table v-else :data="relations" stripe><el-table-column prop="type" label="关系类型" width="170"/><el-table-column prop="targetResourceId" label="目标 Resource" min-width="280"/></el-table></el-tab-pane><el-tab-pane label="Activity"><el-empty v-if="!activities.length" description="暂无该 Resource 活动"/><el-table v-else :data="activities" stripe><el-table-column prop="type" label="类型" width="150"/><el-table-column prop="details" label="详情" min-width="240"/><el-table-column prop="occurredAt" label="发生时间" min-width="180"/></el-table></el-tab-pane><el-tab-pane label="Advanced"><el-descriptions :column="1" border><el-descriptions-item label="Resource ID">{{ resource.id }}</el-descriptions-item><el-descriptions-item label="Revision">{{ resource.version ?? 0 }}</el-descriptions-item><el-descriptions-item label="External Identities">{{ resource.externalIdentities?.length || 0 }}</el-descriptions-item><el-descriptions-item label="更新时间">{{ resource.updatedAt || "—" }}</el-descriptions-item></el-descriptions></el-tab-pane></el-tabs></el-card><el-empty v-else description="暂无 Resource 数据"/>
    <el-dialog v-model="editDialog" title="编辑 Resource 元数据" width="520px"><el-form label-position="top"><el-form-item label="主标题" required><el-input v-model="form.primaryTitle"/></el-form-item><el-form-item label="摘要"><el-input v-model="form.summary" type="textarea" :rows="5"/></el-form-item></el-form><template #footer><el-button @click="editDialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </main>
</template>
