<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { http } from "@/utils/http";

type Resource = { id: string; type?: string; primaryTitle?: string; title?: string; lifecycle?: string; availability?: string; source?: string; updatedAt?: string; summary?: string };
type Filters = { q: string; type: string; availability: string; lifecycle: string; source: string; collection: string; tag: string; favorite: string; conflict: string };
const route = useRoute(); const router = useRouter(); const rows = ref<Resource[]>([]); const loading = ref(false); const error = ref(""); const dialog = ref(false); const saving = ref(false); const showAdvanced = ref(false);
const filters = ref<Filters>({ q: "", type: "", availability: "", lifecycle: "", source: "", collection: "", tag: "", favorite: "", conflict: "" }); const form = ref({ type: "OTHER", title: "", locale: "zh-CN" });
const types = [{ label: "视频", value: "VIDEO" }, { label: "漫画", value: "COMIC" }, { label: "图书", value: "BOOK" }, { label: "音乐", value: "MUSIC" }, { label: "图片", value: "PHOTO" }, { label: "文章", value: "ARTICLE" }, { label: "文档", value: "DOCUMENT" }, { label: "游戏", value: "GAME" }, { label: "其他", value: "OTHER" }];
const visibleRows = computed(() => rows.value.filter(row => !filters.value.q || `${row.primaryTitle || row.title || ""} ${row.summary || ""}`.toLowerCase().includes(filters.value.q.toLowerCase())));
function queryParams() { return Object.fromEntries(Object.entries(filters.value).filter(([, value]) => value)); }
function syncFromUrl() { for (const key of Object.keys(filters.value) as (keyof Filters)[]) filters.value[key] = typeof route.query[key] === "string" ? route.query[key] as string : ""; }
async function load() { loading.value = true; error.value = ""; try { const result: any = await http.get("/resources", { params: { page: 0, size: 100, ...queryParams() } }); rows.value = Array.isArray(result) ? result : (result?.items || result?.content || []); } catch (e: any) { error.value = e?.response?.status === 403 ? "没有权限浏览这些资源" : e?.response?.data?.detail || e?.message || "Resource 加载失败"; } finally { loading.value = false; } }
async function applyFilters() { await router.replace({ query: queryParams() }); await load(); }
function clearFilters() { filters.value = { q: "", type: "", availability: "", lifecycle: "", source: "", collection: "", tag: "", favorite: "", conflict: "" }; applyFilters(); }
async function create() { if (!form.value.title.trim()) { error.value = "标题不能为空"; return; } saving.value = true; try { const result: any = await http.post("/resources", { data: { ...form.value, title: form.value.title.trim() }, headers: { "Idempotency-Key": crypto.randomUUID() } }); dialog.value = false; await load(); if (result?.id) router.push(`/library/${result.id}`); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Resource 创建失败"; } finally { saving.value = false; } }
function open(row: Resource) { router.push(`/library/${row.id}`); }
watch(() => route.query, syncFromUrl, { immediate: true }); onMounted(load);
</script>

<template>
  <main class="p-4 md:p-6"><div class="flex flex-wrap justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">Library</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">统一浏览和管理所有 Resource；专业体验请从 Apps 进入。</p></div><div class="flex gap-2"><el-button type="primary" @click="router.push('/add')">Add Content</el-button><el-button @click="dialog = true">创建 Resource</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never" class="mb-4"><div class="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-5 gap-3"><el-input v-model="filters.q" clearable placeholder="搜索标题或摘要" @keyup.enter="applyFilters"/><el-select v-model="filters.type" clearable placeholder="内容类型"><el-option v-for="item in types" :key="item.value" v-bind="item"/></el-select><el-select v-model="filters.availability" clearable placeholder="Availability"><el-option v-for="item in ['AVAILABLE', 'CACHED', 'REMOTE', 'PROCESSING', 'RESTORING', 'MISSING', 'CORRUPTED']" :key="item" :label="item" :value="item"/></el-select><el-select v-model="filters.lifecycle" clearable placeholder="Lifecycle"><el-option v-for="item in ['ACTIVE', 'ARCHIVED', 'TRASH']" :key="item" :label="item" :value="item"/></el-select><el-input v-model="filters.source" clearable placeholder="Source"/></div><div v-if="showAdvanced" class="grid grid-cols-1 md:grid-cols-4 gap-3 mt-3"><el-input v-model="filters.collection" clearable placeholder="Collection"/><el-input v-model="filters.tag" clearable placeholder="Tag"/><el-select v-model="filters.favorite" clearable placeholder="收藏"><el-option label="已收藏" value="true"/><el-option label="未收藏" value="false"/></el-select><el-select v-model="filters.conflict" clearable placeholder="元数据冲突"><el-option label="有冲突" value="true"/><el-option label="无冲突" value="false"/></el-select></div><div class="flex gap-3 mt-3"><el-button type="primary" @click="applyFilters">应用筛选</el-button><el-button link @click="clearFilters">清除</el-button><el-button link @click="showAdvanced = !showAdvanced">{{ showAdvanced ? '收起 Advanced' : '更多筛选 / Advanced' }}</el-button></div></el-card>
    <el-skeleton v-if="loading" :rows="9" animated/><el-card v-else shadow="never"><el-empty v-if="!visibleRows.length" description="暂无匹配 Resource"/><template v-else><div class="grid grid-cols-1 gap-3 md:hidden"><el-card v-for="row in visibleRows" :key="row.id" shadow="hover" class="cursor-pointer" @click="open(row)"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="font-medium truncate">{{ row.primaryTitle || row.title || '未命名 Resource' }}</div><div class="mt-1 text-xs text-[var(--el-text-color-secondary)]">{{ row.type || 'OTHER' }} · {{ row.availability || '—' }}</div></div><el-tag size="small">{{ row.lifecycle || 'ACTIVE' }}</el-tag></div><div class="mt-3 text-xs text-[var(--el-text-color-secondary)]">来源：{{ row.source || '—' }} · 更新于 {{ row.updatedAt || '—' }}</div></el-card></div><div class="hidden md:block"><el-table :data="visibleRows" stripe @row-click="open"><el-table-column label="标题" min-width="280"><template #default="{ row }"><el-button link type="primary" @click.stop="open(row)">{{ row.primaryTitle || row.title || '未命名 Resource' }}</el-button></template></el-table-column><el-table-column prop="type" label="类型" width="130"/><el-table-column prop="availability" label="Availability" width="150"/><el-table-column label="Lifecycle" width="130"><template #default="{ row }"><el-tag>{{ row.lifecycle || 'ACTIVE' }}</el-tag></template></el-table-column><el-table-column prop="source" label="Source" min-width="150"/><el-table-column prop="updatedAt" label="更新时间" min-width="180"/></el-table></div></template></el-card>
    <el-dialog v-model="dialog" title="创建 Resource" width="480px"><el-form label-position="top"><el-form-item label="类型" required><el-input v-model="form.type" placeholder="OTHER"/></el-form-item><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item><el-form-item label="语言" required><el-input v-model="form.locale"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建并打开</el-button></template></el-dialog>
  </main>
</template>
