<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { http } from "@/utils/http";
type Resource = { id: string; type?: string; primaryTitle?: string; title?: string; lifecycle?: string; updatedAt?: string; summary?: string };
const router = useRouter(); const rows = ref<Resource[]>([]); const loading = ref(false); const error = ref(""); const query = ref(""); const lifecycle = ref(""); const dialog = ref(false); const saving = ref(false); const form = ref({ type: "OTHER", title: "", locale: "zh-CN" });
const filtered = computed(() => rows.value.filter(row => (!query.value || (row.primaryTitle || row.title || "").toLowerCase().includes(query.value.toLowerCase())) && (!lifecycle.value || row.lifecycle === lifecycle.value)));
async function load() { loading.value = true; try { const result: any = await http.get("/resources"); rows.value = Array.isArray(result) ? result : (result?.content || result?.items || []); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "资源加载失败"; } finally { loading.value = false; } }
async function create() { if (!form.value.title.trim()) { error.value = "资源标题不能为空"; return; } saving.value = true; try { const result: any = await http.post("/resources", { data: { ...form.value, title: form.value.title.trim() } }); dialog.value = false; await load(); if (result?.id) router.push(`/resource-center/library/${result.id}`); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "资源创建失败"; } finally { saving.value = false; } }
function open(row: Resource) { router.push(`/resource-center/library/${row.id}`); }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">统一资源库</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">Resource 表示逻辑内容，而不是物理存储位置。</p></div><div class="flex gap-2"><el-button type="primary" @click="dialog = true">创建资源</el-button><el-button>导入</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><div class="grid grid-cols-2 md:grid-cols-5 gap-4 mb-5"><el-card v-for="item in [{label:'资源总数',value:rows.length,filter:''},{label:'正常可用',value:rows.filter(row => row.lifecycle === 'ACTIVE' || !row.lifecycle).length,filter:'ACTIVE'},{label:'已归档',value:rows.filter(row => row.lifecycle === 'ARCHIVED').length,filter:'ARCHIVED'},{label:'回收站',value:rows.filter(row => row.lifecycle === 'TRASH').length,filter:'TRASH'},{label:'元数据冲突',value:'—',filter:''}]" :key="item.label" shadow="never" class="cursor-pointer" @click="lifecycle = item.filter"><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.label }}</div><div class="text-2xl font-semibold mt-2">{{ item.value }}</div></el-card></div><div class="flex flex-wrap gap-3 mb-4"><el-input v-model="query" clearable placeholder="搜索标题" class="max-w-sm"/><el-select v-model="lifecycle" clearable placeholder="生命周期"><el-option label="正常" value="ACTIVE"/><el-option label="已归档" value="ARCHIVED"/><el-option label="回收站" value="TRASH"/></el-select><el-select placeholder="类型"><el-option label="全部类型" value="all"/><el-option label="文档" value="DOCUMENT"/><el-option label="图片" value="IMAGE"/></el-select></div><el-skeleton v-if="loading" :rows="9" animated/><el-card v-else shadow="never"><el-empty v-if="!filtered.length" description="暂无匹配资源"/><el-table v-else :data="filtered" stripe @row-click="open"><el-table-column label="标题" min-width="260"><template #default="{ row }"><el-button link type="primary" @click.stop="open(row)">{{ row.primaryTitle || row.title || row.id }}</el-button></template></el-table-column><el-table-column prop="type" label="类型" width="140"/><el-table-column prop="lifecycle" label="生命周期" width="140"><template #default="{ row }"><el-tag>{{ row.lifecycle || 'ACTIVE' }}</el-tag></template></el-table-column><el-table-column prop="summary" label="摘要" min-width="240"/><el-table-column prop="updatedAt" label="更新时间" min-width="180"/></el-table></el-card><el-dialog v-model="dialog" title="创建资源" width="480px"><el-form label-position="top"><el-form-item label="类型" required><el-input v-model="form.type" placeholder="OTHER"/></el-form-item><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item><el-form-item label="语言" required><el-input v-model="form.locale"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建并打开</el-button></template></el-dialog></main></template>
