<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { http } from "@/utils/http";

type Resource = { id: string; type?: string; primaryTitle?: string; title?: string; lifecycle?: string; updatedAt?: string; summary?: string };
const router = useRouter(); const rows = ref<Resource[]>([]); const loading = ref(false); const error = ref(""); const query = ref(""); const resourceType = ref(""); const dialog = ref(false); const saving = ref(false); const form = ref({ type: "OTHER", title: "", locale: "zh-CN" });
const filtered = computed(() => rows.value.filter(row => !query.value || (row.primaryTitle || row.title || "").toLowerCase().includes(query.value.toLowerCase())));
async function load() { loading.value = true; error.value = ""; try { const result: any = await http.get("/resources", { params: { page: 0, size: 100, ...(resourceType.value ? { type: resourceType.value } : {}), ...(query.value.trim() ? { query: query.value.trim() } : {}) } }); rows.value = Array.isArray(result) ? result : (result?.items || result?.content || []); } catch (e: any) { error.value = e?.response?.status === 403 ? "没有权限浏览这些资源" : e?.response?.data?.detail || e?.message || "资源加载失败"; } finally { loading.value = false; } }
async function create() { if (!form.value.title.trim()) { error.value = "资源标题不能为空"; return; } saving.value = true; try { const result: any = await http.post("/resources", { data: { ...form.value, title: form.value.title.trim() }, headers: { "Idempotency-Key": crypto.randomUUID() } }); dialog.value = false; await load(); if (result?.id) router.push(`/resource-center/library/${result.id}`); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "资源创建失败"; } finally { saving.value = false; } }
function open(row: Resource) { router.push(`/resource-center/library/${row.id}`); }
onMounted(load);
</script>

<template>
  <main class="p-4 md:p-6"><div class="flex flex-wrap justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">统一资源库</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">移动端和桌面端共用服务端资源权限与分页查询。</p></div><div class="flex gap-2"><el-button type="primary" @click="dialog = true">创建资源</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><div class="grid grid-cols-2 md:grid-cols-3 gap-4 mb-5"><el-card v-for="item in [{label:'当前页资源',value:rows.length},{label:'正常可用',value:rows.filter(row => row.lifecycle === 'ACTIVE' || !row.lifecycle).length},{label:'元数据冲突',value:'—'}]" :key="item.label" shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.label }}</div><div class="text-2xl font-semibold mt-2">{{ item.value }}</div></el-card></div>
    <div class="flex flex-wrap gap-3 mb-4"><el-input v-model="query" clearable placeholder="搜索标题" class="max-w-sm"/><el-select v-model="resourceType" clearable placeholder="类型"><el-option label="视频" value="VIDEO"/><el-option label="漫画" value="COMIC"/><el-option label="图书" value="BOOK"/><el-option label="音乐" value="MUSIC"/><el-option label="图片" value="PHOTO"/><el-option label="文章" value="ARTICLE"/><el-option label="文档" value="DOCUMENT"/><el-option label="游戏" value="GAME"/><el-option label="其他" value="OTHER"/></el-select><el-button type="primary" plain @click="load">应用筛选</el-button></div>
    <el-skeleton v-if="loading" :rows="9" animated/><el-card v-else shadow="never"><el-empty v-if="!filtered.length" description="暂无匹配资源；归档和回收站资源请从存储中心管理"/><template v-else><div class="grid grid-cols-1 gap-3 md:hidden"><el-card v-for="row in filtered" :key="row.id" shadow="hover" class="cursor-pointer" @click="open(row)"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="font-medium truncate">{{ row.primaryTitle || row.title || row.id }}</div><div class="mt-1 text-xs text-[var(--el-text-color-secondary)]">{{ row.type || 'OTHER' }} · {{ row.lifecycle || 'ACTIVE' }}</div></div><el-tag size="small" :type="row.lifecycle === 'ACTIVE' || !row.lifecycle ? 'success' : 'info'">{{ row.lifecycle || 'ACTIVE' }}</el-tag></div><p v-if="row.summary" class="mt-3 text-sm line-clamp-2">{{ row.summary }}</p><div class="mt-3 text-xs text-[var(--el-text-color-secondary)]">更新于 {{ row.updatedAt || '—' }}</div><el-button class="mt-3" link type="primary" @click.stop="open(row)">打开资源</el-button></el-card></div><div class="hidden md:block"><el-table :data="filtered" stripe @row-click="open"><el-table-column label="标题" min-width="260"><template #default="{ row }"><el-button link type="primary" @click.stop="open(row)">{{ row.primaryTitle || row.title || row.id }}</el-button></template></el-table-column><el-table-column prop="type" label="类型" width="140"/><el-table-column prop="lifecycle" label="生命周期" width="140"><template #default="{ row }"><el-tag>{{ row.lifecycle || 'ACTIVE' }}</el-tag></template></el-table-column><el-table-column prop="summary" label="摘要" min-width="240"/><el-table-column prop="updatedAt" label="更新时间" min-width="180"/></el-table></div></template></el-card>
    <el-dialog v-model="dialog" title="创建资源" width="480px"><el-form label-position="top"><el-form-item label="类型" required><el-input v-model="form.type" placeholder="OTHER"/></el-form-item><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item><el-form-item label="语言" required><el-input v-model="form.locale"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建并打开</el-button></template></el-dialog>
  </main>
</template>
