<script setup lang="ts">
import { computed, ref } from "vue";
import { http } from "@/utils/http";
type Session = { id: string; title?: string; updatedAt?: string; persona?: string; model?: string };
const sessions = ref<Session[]>([]); const selected = ref<Session | null>(null); const message = ref(""); const loading = ref(false); const error = ref(""); const inspector = ref(true); const sessionQuery = ref(""); const streaming = ref(false); const contextSummary = ref("无显式上下文"); const visibleSessions = computed(() => sessions.value.filter(item => !sessionQuery.value || (item.title || "").toLowerCase().includes(sessionQuery.value.toLowerCase())));
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/ai/assistant/sessions"); sessions.value = Array.isArray(result) ? result as Session[] : []; selected.value = sessions.value[0] || null; } catch (e: any) { error.value = e?.response?.data?.detail || "AI 会话接口尚未接入"; } finally { loading.value = false; } }
function send() { if (!message.value.trim()) return; streaming.value = false; error.value = "消息发送接口尚未接入，请先完成 AI Provider 配置"; }
load();
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-5"><div><h1 class="text-2xl font-semibold">AI 助手</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">在明确的上下文和隐私边界内使用 AI。</p></div><div class="flex gap-2"><el-select placeholder="选择 Persona" class="w-40"><el-option label="默认 Persona" value="default"/></el-select><el-select placeholder="Model / Provider" class="w-48"><el-option label="当前路由策略" value="default"/></el-select><el-button>新建会话</el-button></div></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4"/><div class="grid grid-cols-1 lg:grid-cols-6 gap-4 min-h-[560px]"><el-card shadow="never" class="lg:col-span-1"><template #header><span>会话</span></template><el-input placeholder="搜索 AI 会话" class="mb-3"/><el-empty v-if="!sessions.length" description="暂无会话" :image-size="70"/><div v-for="item in sessions" :key="item.id" class="p-3 rounded cursor-pointer" :class="selected?.id === item.id ? 'bg-[var(--el-fill-color-light)]' : ''" @click="selected = item"><div class="truncate">{{ item.title || '未命名会话' }}</div><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">{{ item.model || '默认模型' }}</div></div></el-card><el-card shadow="never" class="lg:col-span-4 flex flex-col"><template #header><div class="flex justify-between"><span>{{ selected?.title || '新会话' }}</span><el-button link :loading="loading" @click="load">刷新</el-button></div></template><el-empty description="开始一个新会话" class="flex-1"/><div class="flex gap-2 items-end"><el-input v-model="message" type="textarea" :rows="3" placeholder="输入消息，发送前请检查上下文摘要" @keyup.ctrl.enter="send"/><el-button type="primary" @click="send">发送</el-button></div></el-card><el-card v-if="inspector" shadow="never" class="lg:col-span-1"><template #header><div class="flex justify-between"><span>Context Inspector</span><el-button link @click="inspector = false">收起</el-button></div></template><el-descriptions :column="1" border><el-descriptions-item label="Resource">未选择</el-descriptions-item><el-descriptions-item label="用户上下文">未显式添加</el-descriptions-item><el-descriptions-item label="Memory">未启用</el-descriptions-item><el-descriptions-item label="Tool">按权限显示</el-descriptions-item><el-descriptions-item label="隐私分类">发送前检查</el-descriptions-item></el-descriptions></el-card><el-button v-else class="self-start" @click="inspector = true">展开上下文</el-button></div></main></template>
