<script setup lang="ts">
import { ref } from "vue";
import { http } from "@/utils/http";
type Persona = { id: string; name?: string; description?: string; enabled?: boolean; modelPolicy?: string; memoryPolicy?: string; toolPolicy?: string; updatedAt?: string };
const rows = ref<Persona[]>([]); const selected = ref<Persona | null>(null); const loading = ref(false); const error = ref(""); const dialog = ref(false); const active = ref("identity"); const form = ref({ name: "", description: "", tone: "" });
async function load() { loading.value = true; try { const result = await http.get<unknown, unknown>("/ai/personas"); rows.value = Array.isArray(result) ? result as Persona[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || "AI Persona 接口尚未接入"; } finally { loading.value = false; } }
function create() { if (!form.value.name.trim()) { error.value = "Persona 名称不能为空"; return; } error.value = "Persona 保存接口尚未接入，请先配置 AI 后端能力"; }
load();
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">Persona 管理</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理身份、指令、模型、工具和隐私边界。</p></div><div class="flex gap-2"><el-button type="primary" @click="dialog = true">新建 Persona</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="8" animated/><div v-else class="grid grid-cols-1 md:grid-cols-3 gap-4"><el-empty v-if="!rows.length" class="col-span-full" description="暂无 Persona；后端配置接口接入后可在此管理"/><el-card v-for="persona in rows" :key="persona.id" shadow="never" class="cursor-pointer" @click="selected = persona"><div class="flex gap-3"><el-avatar>AI</el-avatar><div class="flex-1"><div class="font-medium">{{ persona.name || '未命名 Persona' }}</div><p class="text-sm text-[var(--el-text-color-secondary)] mt-2">{{ persona.description || '暂无描述' }}</p></div><el-tag size="small">{{ persona.enabled === false ? '禁用' : '启用' }}</el-tag></div><div class="text-xs text-[var(--el-text-color-secondary)] mt-5">模型：{{ persona.modelPolicy || '默认路由' }} · Memory：{{ persona.memoryPolicy || '受限' }}</div></el-card></div><el-dialog v-model="dialog" title="Persona 编辑器" width="720px"><el-tabs v-model="active"><el-tab-pane label="身份" name="identity"><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item><el-form-item label="Tone Tag"><el-input v-model="form.tone" placeholder="例如 concise, professional"/></el-form-item></el-form></el-tab-pane><el-tab-pane label="指令" name="instructions"><el-input type="textarea" :rows="8" placeholder="System Behavior / Instruction"/></el-tab-pane><el-tab-pane label="模型" name="model"><el-empty description="模型策略由 AI 路由配置提供"/></el-tab-pane><el-tab-pane label="工具" name="tools"><el-empty description="工具能力和风险级别由服务端权限提供"/></el-tab-pane><el-tab-pane label="记忆与上下文" name="memory"><el-alert title="Private Notes、Password Manager、Finance 默认禁止进入 Memory" type="warning" show-icon/></el-tab-pane><el-tab-pane label="安全与隐私" name="security"><el-alert title="保存前检查数据访问范围和隐私分类" type="info" show-icon/></el-tab-pane><el-tab-pane label="测试" name="test"><el-alert title="Sandbox 测试不会写入生产 Memory" type="info" show-icon/></el-tab-pane></el-tabs><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="create">保存</el-button></template></el-dialog></main></template>
