<script setup lang="ts">
import { ref } from "vue";
const tab = ref("context");
const policies = [
  { domain: "普通资源元数据", level: "普通", target: "已配置 Model / Provider", consent: "按请求确认", retention: "遵循 Provider 策略", enabled: true },
  { domain: "私密笔记", level: "高敏感", target: "禁止", consent: "必须显式授权", retention: "不共享", enabled: false },
  { domain: "密码与财务", level: "高敏感", target: "禁止", consent: "必须显式授权", retention: "不共享", enabled: false }
];
</script>
<template><main class="p-4 md:p-6"><div class="mb-6"><h1 class="text-2xl font-semibold">AI 上下文与隐私</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">查看数据使用边界；敏感内容不会因 UI 默认配置而自动共享。</p></div><el-alert title="当前页面展示的是前端安全默认策略；最终允许范围必须以后端 Policy 与 Provider 配置为准。" type="warning" show-icon :closable="false" class="mb-4"/><el-tabs v-model="tab"><el-tab-pane label="上下文策略" name="context"/><el-tab-pane label="记忆" name="memory"/><el-tab-pane label="数据共享" name="sharing"/></el-tabs><el-card shadow="never" class="mt-4"><template v-if="tab === 'context'"><el-table :data="policies" stripe><el-table-column prop="domain" label="数据域" min-width="180"/><el-table-column prop="level" label="敏感级别" width="120"/><el-table-column prop="target" label="允许目标" min-width="220"/><el-table-column prop="consent" label="显式同意" width="160"/><el-table-column prop="retention" label="保留策略" min-width="180"/><el-table-column label="启用状态" width="120"><template #default="{ row }"><el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '禁止' }}</el-tag></template></el-table-column></el-table><el-alert title="修改高敏感规则可能导致私密内容发送到 Provider，需重新认证或更高权限。" type="error" show-icon class="mt-4"/></template><template v-else-if="tab === 'memory'"><el-empty description="暂无可展示的 Memory；敏感域默认不进入记忆"/><el-button class="mt-2" type="danger" plain>清除记忆</el-button></template><template v-else><el-empty description="暂无已配置 Provider 的共享披露矩阵"/><el-descriptions :column="1" border class="mt-4"><el-descriptions-item label="可能离开服务器的数据类别">仅限经 Policy 明确允许的普通元数据</el-descriptions-item><el-descriptions-item label="Retention">由实际 Provider 配置决定</el-descriptions-item><el-descriptions-item label="Telemetry">由后端路由策略提供</el-descriptions-item><el-descriptions-item label="Credential">永不展示或发送到前端</el-descriptions-item></el-descriptions></template></el-card></main></template>
