<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { http } from "@/utils/http";
type Row = Record<string, unknown>; const route = useRoute(); const vault = ref<Row | null>(null); const notes = ref<Row[]>([]); const loading = ref(false); const error = ref("");
const recovery = computed(() => route.path.endsWith("recovery"));
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/private-notes/vaults"); vault.value = (Array.isArray(result) ? result[0] : null) as Row | null; if (!recovery.value && vault.value?.id && String(vault.value.status).toUpperCase() === "UNLOCKED") { const list = await http.get<unknown, unknown>(`/private-notes/vaults/${vault.value.id}/notes`); notes.value = Array.isArray(list) ? list as Row[] : []; } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "私密笔记安全数据加载失败"; } finally { loading.value = false; } }
async function exportVault() { if (!vault.value?.id) return; try { const result = await http.get<unknown, unknown>(`/private-notes/vaults/${vault.value.id}/export`); notes.value = [result as Row]; } catch (e: any) { error.value = "导出失败，请确认保险库已解锁"; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">{{ recovery ? '笔记恢复' : '笔记冲突' }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">{{ recovery ? '管理加密恢复材料与安全导出。' : '查看已解锁上下文中的同步与版本状态。' }}</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4"/><el-card shadow="never" class="mb-4"><div class="grid grid-cols-1 md:grid-cols-3 gap-4"><div><div class="text-sm text-[var(--el-text-color-secondary)]">保险库状态</div><div class="text-xl font-semibold mt-2">{{ vault?.status || '未配置' }}</div></div><div><div class="text-sm text-[var(--el-text-color-secondary)]">加密上下文</div><div class="mt-2">{{ vault?.cryptoContext || '不可用' }}</div></div><div><el-button v-if="recovery" type="primary" @click="exportVault">创建加密导出包</el-button><span v-else class="text-sm text-[var(--el-text-color-secondary)]">明文内容不会在锁定状态下展示</span></div></div></el-card><el-card shadow="never"><template #header>{{ recovery ? '恢复包状态' : '同步冲突与版本' }}</template><el-empty v-if="!notes.length" description="暂无可展示数据"/><el-table v-else :data="notes" stripe><el-table-column prop="id" label="技术标识" min-width="240"/><el-table-column prop="revision" label="版本" width="100"/><el-table-column prop="updatedAt" label="更新时间" min-width="180"/><el-table-column prop="tombstone" label="状态" width="120"/></el-table></el-card></main></template>
