<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const tab = ref("shares"); const shares = ref<Row[]>([]); const rooms = ref<Row[]>([]); const loading = ref(false); const error = ref("");
async function load() { loading.value = true; error.value = ""; try { const [s, r] = await Promise.all([http.get<unknown, unknown>("/shares"), http.get<unknown, unknown>("/rooms")]); shares.value = Array.isArray(s) ? s as Row[] : []; rooms.value = Array.isArray(r) ? r as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "分享协作数据加载失败"; } finally { loading.value = false; } }
async function revoke(row: Row) { if (!row.id || !window.confirm("确认撤销该分享链接吗？")) return; try { await http.post(`/shares/${row.id}/actions/revoke`); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "撤销分享失败"; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">分享与协作</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理分享链接、协作 Room 和协作状态。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="分享链接" name="shares"><el-empty v-if="!shares.length" description="暂无分享链接"/><el-table v-else :data="shares" stripe><el-table-column prop="resourceId" label="目标 Resource" min-width="220"/><el-table-column prop="permission" label="权限" width="130"/><el-table-column prop="expiresAt" label="过期时间" min-width="180"/><el-table-column prop="accessCount" label="访问次数" width="120"/><el-table-column prop="status" label="状态" width="120"/><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link type="danger" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="Room" name="rooms"><el-empty v-if="!rooms.length" description="暂无协作 Room"/><el-table v-else :data="rooms" stripe><el-table-column prop="id" label="Room" min-width="220"/><el-table-column prop="name" label="名称" min-width="200"/><el-table-column prop="status" label="状态" width="130"/><el-table-column prop="createdAt" label="创建时间" min-width="180"/></el-table></el-tab-pane><el-tab-pane label="协作" name="collaboration"><el-empty description="选择 Room 后查看成员、消息和事件"/></el-tab-pane></el-tabs></el-card></main></template>
