<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const roomId = ref(""); const events = ref<Row[]>([]); const queuePayload = ref("{}"); const commandPayload = ref("{}"); const sequence = ref(0); const stateVersion = ref(0); const loading = ref(false); const busy = ref(false); const error = ref(""); const message = ref(""); let timer: ReturnType<typeof setInterval> | undefined;
async function sync() { if (!roomId.value.trim()) { error.value = "请输入 Room ID"; return; } loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>(`/rooms/${roomId.value.trim()}/events`, { params: { afterSequence: sequence.value } }); const rows = Array.isArray(result) ? result as Row[] : []; if (rows.length) { events.value = [...events.value, ...rows]; sequence.value = Number(rows.at(-1)?.sequence || sequence.value); stateVersion.value = Number(rows.at(-1)?.stateVersion || stateVersion.value); } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Room 队列同步失败"; } finally { loading.value = false; } }
async function control(commandType: string, value: string) { if (!roomId.value.trim()) { error.value = "请输入 Room ID"; return; } busy.value = true; error.value = ""; try { const result: any = await http.post(`/rooms/${roomId.value.trim()}/control`, { data: { commandType, payload: value || "{}", expectedStateVersion: stateVersion.value } }); stateVersion.value = Number(result?.stateVersion ?? stateVersion.value + 1); message.value = `已提交 ${commandType}`; await sync(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Room 控制失败"; } finally { busy.value = false; } }
function reset() { events.value = []; sequence.value = 0; stateVersion.value = 0; sync(); }
onMounted(() => { timer = setInterval(() => { if (roomId.value.trim()) sync(); }, 5000); }); onBeforeUnmount(() => { if (timer) clearInterval(timer); });
</script>
<template><main class="p-4 md:p-6"><div class="mb-6"><h1 class="text-2xl font-semibold">一起听</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">通过 Room Control/Event API 同步音频队列、当前歌曲和播放状态。</p></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4"/><el-card shadow="never" class="mb-5"><div class="flex flex-wrap gap-3 items-end"><el-form-item label="Room ID"><el-input v-model="roomId" class="w-80" clearable/></el-form-item><el-button type="primary" :loading="loading" @click="reset">连接并同步</el-button><span class="text-sm">序列 {{ sequence }} · 状态版本 {{ stateVersion }}</span></div><div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-3"><el-form-item label="队列 Payload"><el-input v-model="queuePayload" type="textarea" :rows="3"/></el-form-item><el-form-item label="播放状态 Payload"><el-input v-model="commandPayload" type="textarea" :rows="3"/></el-form-item></div><div class="flex flex-wrap gap-2"><el-button :loading="busy" @click="control('QUEUE_UPDATE', queuePayload)">同步队列</el-button><el-button :loading="busy" @click="control('TRACK_CHANGE', commandPayload)">切换歌曲</el-button><el-button :loading="busy" @click="control('PLAY_STATE', commandPayload)">播放/暂停</el-button></div></el-card><el-card shadow="never"><template #header>队列与状态事件</template><el-empty v-if="!events.length" description="暂无同步事件"/><el-table v-else :data="events" stripe><el-table-column prop="sequence" label="序列" width="90"/><el-table-column prop="eventType" label="事件类型" min-width="180"/><el-table-column prop="payload" label="Payload" min-width="280"/><el-table-column prop="stateVersion" label="状态版本" width="110"/><el-table-column prop="occurredAt" label="时间" min-width="190"/></el-table></el-card></main></template>
