<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const roomId = ref(""); const events = ref<Row[]>([]); const stateVersion = ref(0); const sequence = ref(0); const payload = ref("{}"); const loading = ref(false); const busy = ref(false); const error = ref(""); const message = ref(""); let timer: ReturnType<typeof setInterval> | undefined;
async function replay() { if (!roomId.value.trim()) { error.value = "请输入 Room ID"; return; } loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>(`/rooms/${roomId.value.trim()}/events`, { params: { afterSequence: sequence.value } }); const rows = Array.isArray(result) ? result as Row[] : []; if (rows.length) { events.value = [...events.value, ...rows]; sequence.value = Number(rows[rows.length - 1].sequence || sequence.value); stateVersion.value = Number(rows[rows.length - 1].stateVersion || stateVersion.value); } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Room 状态同步失败"; } finally { loading.value = false; } }
async function control(commandType: string) { if (!roomId.value.trim()) { error.value = "请输入 Room ID"; return; } busy.value = true; error.value = ""; try { const result: any = await http.post(`/rooms/${roomId.value.trim()}/control`, { data: { commandType, payload: payload.value || "{}", expectedStateVersion: stateVersion.value } }); stateVersion.value = Number(result?.stateVersion ?? stateVersion.value + 1); sequence.value = Number(result?.sequence ?? sequence.value); message.value = `已提交 ${commandType} 控制命令`; await replay(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Room 控制命令失败"; } finally { busy.value = false; } }
function reset() { events.value = []; sequence.value = 0; stateVersion.value = 0; replay(); }
onMounted(() => { timer = setInterval(() => { if (roomId.value.trim()) replay(); }, 5000); }); onBeforeUnmount(() => { if (timer) clearInterval(timer); });
</script>
<template>
  <main class="p-4 md:p-6"><div class="mb-6"><h1 class="text-2xl font-semibold">一起看</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">通过 Room Control 和事件回放同步播放状态；权限由后端按成员角色校验。</p></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4"/><el-card shadow="never" class="mb-5"><div class="flex flex-wrap gap-3 items-end"><el-form-item label="Room ID"><el-input v-model="roomId" class="w-80" clearable/></el-form-item><el-button type="primary" :loading="loading" @click="reset">连接并同步</el-button><el-button :loading="loading" @click="replay">刷新事件</el-button><span class="text-sm">序列 {{ sequence }} · 状态版本 {{ stateVersion }}</span></div><el-form-item label="命令 Payload" class="mt-3 max-w-2xl"><el-input v-model="payload" type="textarea" :rows="2"/></el-form-item><div class="flex flex-wrap gap-2"><el-button :loading="busy" @click="control('PLAY')">播放</el-button><el-button :loading="busy" @click="control('PAUSE')">暂停</el-button><el-button :loading="busy" @click="control('SEEK')">跳转进度</el-button></div></el-card><el-card shadow="never"><template #header>事件回放</template><el-empty v-if="!events.length" description="暂无已同步事件"/><el-table v-else :data="events" stripe><el-table-column prop="sequence" label="序列" width="90"/><el-table-column prop="eventType" label="事件类型" min-width="180"/><el-table-column prop="actorId" label="操作者" min-width="280"/><el-table-column prop="payload" label="Payload" min-width="240"/><el-table-column prop="stateVersion" label="状态版本" width="110"/><el-table-column prop="occurredAt" label="时间" min-width="190"/></el-table></el-card></main>
</template>
