<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const tab = ref("continue"); const history = ref<Row[]>([]); const loading = ref(false); const error = ref(""); const settings = ref({ autoplay: false, quality: "服务端默认", subtitle: "服务端默认" });
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/media/playback/history"); history.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "播放历史加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">媒体消费</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">查看服务端播放历史；具体播放和队列管理请进入对应媒体页面。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="播放历史" name="history"><el-skeleton v-if="loading" :rows="6" animated/><el-empty v-else-if="!history.length" description="暂无播放历史"/><el-table v-else :data="history" stripe><el-table-column prop="resourceId" label="Resource ID" min-width="300"/><el-table-column prop="sessionId" label="Session ID" min-width="300"/><el-table-column prop="startedAt" label="开始时间" min-width="180"/><el-table-column prop="endedAt" label="结束时间" min-width="180"/><el-table-column prop="watchedSeconds" label="观看时长（秒）" width="140"/></el-table></el-tab-pane><el-tab-pane label="播放设置" name="settings"><el-descriptions :column="1" border><el-descriptions-item label="服务端默认画质">{{ settings.quality }}</el-descriptions-item><el-descriptions-item label="服务端字幕策略">{{ settings.subtitle }}</el-descriptions-item></el-descriptions><el-alert class="mt-4" title="仅展示服务端明确支持的默认项；播放与队列请使用音乐库或视频目录页面。" type="info" :closable="false"/></el-tab-pane></el-tabs></el-card></main></template>
