<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const tab = ref("continue"); const history = ref<Row[]>([]); const loading = ref(false); const error = ref("");
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/media/playback/history"); history.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "播放历史加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">媒体消费</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理继续观看、播放历史和播放设置，不提供客厅式全屏播放器。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="继续" name="continue"><el-empty v-if="!history.length" description="暂无可继续内容"/><div v-for="item in history.slice(0, 6)" :key="item.id" class="flex items-center justify-between py-3 border-b last:border-0"><div><div class="font-medium">{{ item.title || item.resourceId || 'Resource' }}</div><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.positionSeconds || 0 }} 秒 · {{ item.updatedAt || item.lastPlayedAt || '-' }}</div></div><el-button link>继续</el-button></div></el-tab-pane><el-tab-pane label="历史" name="history"><el-skeleton v-if="loading" :rows="6" animated/><el-empty v-else-if="!history.length" description="暂无播放历史"/><el-table v-else :data="history" stripe><el-table-column prop="resourceId" label="Resource" min-width="220"/><el-table-column prop="positionSeconds" label="最后位置" width="130"/><el-table-column prop="deviceId" label="设备/客户端" min-width="180"/><el-table-column prop="startedAt" label="开始时间" min-width="180"/><el-table-column prop="completed" label="是否完成" width="120"/></el-table></el-tab-pane><el-tab-pane label="播放列表 / 队列" name="queue"><el-empty description="暂无播放列表或队列"/></el-tab-pane><el-tab-pane label="播放设置" name="settings"><el-descriptions :column="1" border><el-descriptions-item label="服务端播放设置">使用服务端默认设置</el-descriptions-item><el-descriptions-item label="客户端私有设置">不在此处展示</el-descriptions-item></el-descriptions></el-tab-pane></el-tabs></el-card></main></template>
