<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { http } from "@/utils/http";

type Subject = { id: string; resourceId?: string; kind?: string; createdAt?: string; title?: string };
type Resource = { id: string; primaryTitle?: string; title?: string };
type Season = { id: string; seasonNumber?: number; name?: string };
type Episode = { id: string; resourceId?: string; episodeNumber?: number };
type Release = { id: string; attachmentId?: string; releaseGroup?: string; versionLabel?: string; state?: string; availability?: string; availabilityChecked?: boolean };
type Subtitle = { id: string; attachmentId?: string; language?: string; title?: string; format?: string; forced?: boolean; hearingImpaired?: boolean; url?: string; };
type Attachment = { id: string; kind?: string; fileName?: string; availability?: string; availabilityChecked?: boolean };
const router = useRouter(); const availabilityLoading = ref(false);
const rows = ref<Subject[]>([]); const loading = ref(false); const saving = ref(false); const orderLoading = ref(false); const metadataLoading = ref(false); const subtitleSaving = ref(false); const error = ref("");
const dialog = ref(false); const orderDialog = ref(false); const metadataDialog = ref(false); const playbackDialog = ref(false); const selectedSubject = ref<Subject | null>(null); const selectedRelease = ref<Release | null>(null); const selectedSubtitleId = ref(""); const selectedAudioTrackId = ref(""); const audioTracks = ref<{ id: string; index: number; label: string }[]>([]); const playbackVideo = ref<HTMLVideoElement>(); const playbackSession = ref<Record<string, any> | null>(null); const playbackUrl = ref(""); const playbackLoading = ref(false); const playbackSaving = ref(false); const lastSavedPosition = ref(0); const resumePosition = ref(0);
const seasons = ref<Season[]>([]); const episodes = ref<Episode[]>([]); const releases = ref<Release[]>([]); const subtitles = ref<Subtitle[]>([]); const covers = ref<Attachment[]>([]); const selectedSeasonId = ref("");
const form = ref({ title: "", kind: "SERIES", locale: "zh-CN" }); const subtitleForm = ref({ attachmentId: "", language: "zh-CN", title: "", format: "SRT", provider: "", offsetMillis: 0, forced: false, hearingImpaired: false });

async function load() { loading.value = true; error.value = ""; try { const [subjects, resources] = await Promise.all([http.get<unknown, unknown>("/media/subjects"), http.get<any, any>("/resources", { params: { type: "VIDEO", page: 0, size: 100 } })]); const resourceRows: Resource[] = Array.isArray(resources) ? resources : resources?.items || resources?.content || []; const titles = new Map(resourceRows.map(resource => [resource.id, resource.primaryTitle || resource.title || ""])); rows.value = (Array.isArray(subjects) ? subjects : []) as Subject[]; rows.value = rows.value.map(row => ({ ...row, title: titles.get(row.resourceId || "") || "未命名视频" })); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "视频条目加载失败"; } finally { loading.value = false; } }
async function create() { if (!form.value.title.trim()) { error.value = "视频标题不能为空"; return; } saving.value = true; try { const result: any = await http.post("/media/subjects", { data: { ...form.value, title: form.value.title.trim() } }); dialog.value = false; form.value = { title: "", kind: "SERIES", locale: "zh-CN" }; await load(); if (result?.resourceId) router.push(`/resource-center/library/${result.resourceId}`); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "视频条目创建失败"; } finally { saving.value = false; } }
async function openOrder(subject: Subject) { selectedSubject.value = subject; seasons.value = []; episodes.value = []; selectedSeasonId.value = ""; orderDialog.value = true; orderLoading.value = true; try { const result = await http.get<unknown, unknown>(`/media/subjects/${subject.id}/seasons`); seasons.value = Array.isArray(result) ? result as Season[] : []; if (seasons.value[0]?.id) { selectedSeasonId.value = seasons.value[0].id; await loadEpisodes(); } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "剧集季列表加载失败"; } finally { orderLoading.value = false; } }
async function loadEpisodes() { if (!selectedSubject.value || !selectedSeasonId.value) { episodes.value = []; return; } orderLoading.value = true; try { const result = await http.get<unknown, unknown>(`/media/subjects/${selectedSubject.value.id}/episodes`, { params: { seasonId: selectedSeasonId.value } }); episodes.value = Array.isArray(result) ? (result as Episode[]).sort((a, b) => Number(a.episodeNumber || 0) - Number(b.episodeNumber || 0)) : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "剧集列表加载失败"; } finally { orderLoading.value = false; } }
function moveEpisode(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= episodes.value.length) return; const next = [...episodes.value]; [next[index], next[target]] = [next[target], next[index]]; episodes.value = next; }
async function openReleases(subject: Subject) { selectedSubject.value = subject; releases.value = []; metadataLoading.value = true; try { const result = await http.get<unknown, unknown>(`/media/resources/${subject.resourceId}/releases`); releases.value = Array.isArray(result) ? result as Release[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "播放附件关联加载失败"; } finally { metadataLoading.value = false; } }
async function saveOrder() { if (!selectedSubject.value || !selectedSeasonId.value || !episodes.value.length) return; orderLoading.value = true; try { await http.post(`/media/subjects/${selectedSubject.value.id}/seasons/${selectedSeasonId.value}/actions/reorder-episodes`, { data: { episodeIds: episodes.value.map(episode => episode.id) } }); await loadEpisodes(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "剧集顺序保存失败"; } finally { orderLoading.value = false; } }
async function openMetadata(subject: Subject) { selectedSubject.value = subject; selectedRelease.value = null; releases.value = []; subtitles.value = []; covers.value = []; metadataDialog.value = true; metadataLoading.value = true; try { const [releaseResult, attachmentResult] = await Promise.all([http.get<unknown, unknown>(`/media/resources/${subject.resourceId}/releases`), http.get<unknown, unknown>(`/resources/${subject.resourceId}/attachments`)]); releases.value = Array.isArray(releaseResult) ? releaseResult as Release[] : []; covers.value = (Array.isArray(attachmentResult) ? attachmentResult as Attachment[] : []).filter(item => String(item.kind).toUpperCase() === "COVER"); if (releases.value[0]) await selectRelease(releases.value[0]); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "字幕和封面加载失败"; } finally { metadataLoading.value = false; } }
async function selectRelease(release: Release) { selectedRelease.value = release; selectedSubtitleId.value = ""; if (!release.id) return; try { const result = await http.get<unknown, unknown>(`/media/releases/${release.id}/subtitles`); const subtitleRows = Array.isArray(result) ? result as Subtitle[] : []; subtitles.value = await Promise.all(subtitleRows.map(async subtitle => { if (!subtitle.attachmentId) return subtitle; try { const preview: any = await http.get(`/attachments/${subtitle.attachmentId}/preview-url`); return { ...subtitle, url: String(preview?.url || "") }; } catch { return { ...subtitle, url: "" }; } })); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "字幕列表加载失败"; } }
async function addSubtitle() { if (!selectedRelease.value?.id || !subtitleForm.value.attachmentId.trim() || !subtitleForm.value.language.trim() || !subtitleForm.value.title.trim()) { error.value = "Release、字幕 Attachment、语言和标题不能为空"; return; } subtitleSaving.value = true; try { await http.post(`/media/releases/${selectedRelease.value.id}/subtitles`, { data: { ...subtitleForm.value, attachmentId: subtitleForm.value.attachmentId.trim(), language: subtitleForm.value.language.trim(), title: subtitleForm.value.title.trim() } }); subtitleForm.value = { attachmentId: "", language: "zh-CN", title: "", format: "SRT", provider: "", offsetMillis: 0, forced: false, hearingImpaired: false }; await selectRelease(selectedRelease.value); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "字幕关联失败"; } finally { subtitleSaving.value = false; } }
async function startPlayback(release: Release) { if (!selectedSubject.value?.resourceId || !release.id || !release.attachmentId) { error.value = "该 Release 缺少可播放附件"; return; } playbackLoading.value = true; error.value = ""; try { const resourceId = selectedSubject.value.resourceId; const source: any = await http.get(`/media/resources/${resourceId}/playback-source`, { params: { releaseId: release.id } }); let progress: any = null; try { progress = await http.get(`/media/playback/resources/${resourceId}/progress`); } catch { progress = null; } resumePosition.value = progress?.completed ? 0 : Math.max(0, Number(progress?.position || 0)); const chosenReleaseId = source?.releaseId || release.id; playbackSession.value = await http.post(`/media/playback/resources/${resourceId}/sessions`, { data: { releaseId: chosenReleaseId, startPositionSeconds: resumePosition.value } }); const preview: any = await http.get(`/attachments/${source?.attachmentId || release.attachmentId}/preview-url`); playbackUrl.value = String(preview?.url || ""); if (!playbackUrl.value) throw new Error("播放授权未返回地址"); metadataDialog.value = false; playbackDialog.value = true; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "开始播放失败"; } finally { playbackLoading.value = false; } }
async function savePlaybackProgress(force = false, event?: Event) { const session = playbackSession.value; const video = event?.target as HTMLVideoElement | undefined; const position = Math.floor(video?.currentTime || 0); const total = Number.isFinite(video?.duration) && video?.duration > 0 ? Math.floor(video.duration) : null; if (!session?.id || playbackSaving.value || (!force && Math.abs(position - lastSavedPosition.value) < 10)) return; playbackSaving.value = true; try { const updated: any = await http.request("patch", "/media/playback/sessions/" + session.id, { headers: session.version != null ? { "If-Match": '"' + session.version + '"' } : undefined, data: { positionSeconds: position, totalSeconds: total, completed: total != null && position >= total - 2 } }); playbackSession.value = updated; lastSavedPosition.value = position; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "播放进度保存失败"; } finally { playbackSaving.value = false; } }
function playbackTitle() { return "播放会话 " + (playbackSession.value?.id || "") + (resumePosition.value > 0 ? " · 从 " + resumePosition.value + " 秒续播" : "") + (playbackSaving.value ? " · 正在保存进度" : ""); }
function applyResumePosition(event: Event) { const video = event.target as HTMLVideoElement; if (resumePosition.value > 0 && video.currentTime < 1) video.currentTime = resumePosition.value; lastSavedPosition.value = resumePosition.value; }
async function closePlayback() { await savePlaybackProgress(true); const session = playbackSession.value; if (session?.id) { try { await http.post("/media/playback/sessions/" + session.id + "/actions/end", { headers: session.version != null ? { "If-Match": '"' + session.version + '"' } : undefined }); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "播放会话结束失败"; } } playbackUrl.value = ""; playbackSession.value = null; lastSavedPosition.value = 0; resumePosition.value = 0; }
function switchSubtitle() { const video = playbackVideo.value; const index = subtitles.value.findIndex(subtitle => subtitle.id === selectedSubtitleId.value); if (!video) return; Array.from(video.textTracks).forEach((track, trackIndex) => { track.mode = trackIndex === index && index >= 0 ? "showing" : "disabled"; }); }
function loadAudioTracks() { const tracks: any = (playbackVideo.value as any)?.audioTracks; audioTracks.value = tracks?.length ? Array.from({ length: tracks.length }, (_, index) => { const track = tracks[index]; return { id: String(track.id || index), index, label: String(track.label || track.language || "音轨 " + (index + 1)) }; }) : []; selectedAudioTrackId.value = audioTracks.value[0]?.id || ""; switchAudioTrack(); }
function switchAudioTrack() { const tracks: any = (playbackVideo.value as any)?.audioTracks; const selected = audioTracks.value.find(track => track.id === selectedAudioTrackId.value); if (!tracks || !selected) return; for (let index = 0; index < tracks.length; index += 1) tracks[index].enabled = index === selected.index; }
function onPlaybackMetadata(event: Event) { applyResumePosition(event); loadAudioTracks(); }
watch(metadataLoading, value => { if (value) metadataDialog.value = true; });
async function checkAvailability(attachmentId: string) { try { const result: any = await http.get(`/attachments/${attachmentId}/availability`); return String(result?.availability || "UNKNOWN").toUpperCase(); } catch { return "UNKNOWN"; } }
function releaseLabel(release: Release) { return `${release.versionLabel || release.id} · ${release.attachmentId || "无附件"} · ${release.availability || "UNKNOWN"}`; }
watch([covers, releases], async ([coverRows, releaseRows]) => { if (availabilityLoading.value) return; const coverItems = coverRows as Attachment[]; const releaseItems = releaseRows as Release[]; if (coverItems.every(item => item.availabilityChecked) && releaseItems.every(item => item.availabilityChecked)) return; availabilityLoading.value = true; try { if (coverItems.length) covers.value = await Promise.all(coverItems.map(async item => ({ ...item, availability: await checkAvailability(item.id), availabilityChecked: true }))); if (releaseItems.length) releases.value = await Promise.all(releaseItems.map(async item => ({ ...item, availability: item.attachmentId ? await checkAvailability(item.attachmentId) : "UNKNOWN", availabilityChecked: true }))); } finally { availabilityLoading.value = false; } }, { deep: false });
onMounted(load);
</script>

<template>
  <main class="p-4 md:p-6">
    <div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">视频条目</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">创建并管理视频、剧集、播放附件、字幕和封面；Resource 与物理附件生命周期保持分离。</p></div><div class="flex gap-2"><el-button type="primary" @click="dialog = true">创建视频条目</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" />
    <el-card shadow="never"><el-skeleton v-if="loading" :rows="8" animated /><el-empty v-else-if="!rows.length" description="暂无视频条目；请先创建一个视频或剧集" /><el-table v-else :data="rows" stripe><el-table-column prop="title" label="标题" min-width="240" /><el-table-column prop="kind" label="类型" width="120" /><el-table-column prop="resourceId" label="Resource ID" min-width="230" /><el-table-column prop="createdAt" label="创建时间" min-width="180" /><el-table-column label="操作" width="360"><template #default="{ row }"><el-button link type="primary" @click="openOrder(row)">维护剧集顺序</el-button><el-button link @click="openReleases(row)">播放附件</el-button><el-button link @click="openMetadata(row)">字幕 / 封面</el-button><el-button link :disabled="!row.resourceId" @click="router.push(`/resource-center/library/${row.resourceId}`)">打开 Resource</el-button></template></el-table-column></el-table></el-card>
    <el-dialog v-model="dialog" title="创建视频条目" width="520px"><el-form label-position="top"><el-form-item label="标题" required><el-input v-model="form.title" placeholder="例如：示例剧集" /></el-form-item><el-form-item label="类型" required><el-select v-model="form.kind" class="w-full"><el-option label="剧集" value="SERIES" /><el-option label="电影" value="MOVIE" /><el-option label="单个视频" value="VIDEO" /></el-select></el-form-item><el-form-item label="语言"><el-input v-model="form.locale" placeholder="zh-CN" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog>
    <el-dialog v-model="metadataDialog" title="字幕和封面" width="780px"><el-skeleton v-if="metadataLoading" :rows="6" animated /><template v-else><el-card shadow="never"><template #header>封面 Attachment</template><el-empty v-if="!covers.length" description="暂无 COVER Attachment；请在附件中心为该 Resource 上传并选择“封面”角色" /><el-table v-else :data="covers"><el-table-column prop="fileName" label="文件名" /><el-table-column prop="id" label="Attachment ID" min-width="250" /><el-table-column prop="availability" label="可用性" /></el-table></el-card><el-divider /><div class="flex items-center gap-3 mb-3"><span>字幕所属 Release</span><el-select class="flex-1" :model-value="selectedRelease?.id" placeholder="选择 Release" @change="id => selectRelease(releases.find(item => item.id === id)!)"><el-option v-for="release in releases" :key="release.id" :label="releaseLabel(release)" :value="release.id" /></el-select><el-button type="primary" :loading="playbackLoading" :disabled="!selectedRelease || selectedRelease.availability !== 'READY'" @click="startPlayback(selectedRelease!)">开始播放</el-button></div><el-empty v-if="!releases.length" description="暂无播放 Release；先关联播放附件" /><template v-else><el-table :data="subtitles" stripe><el-table-column prop="language" label="语言" width="100" /><el-table-column prop="title" label="标题" /><el-table-column prop="format" label="格式" width="100" /><el-table-column prop="attachmentId" label="Attachment ID" min-width="230" /></el-table><el-divider /><el-form label-position="top"><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><el-form-item label="字幕 Attachment ID" required><el-input v-model="subtitleForm.attachmentId" /></el-form-item><el-form-item label="语言" required><el-input v-model="subtitleForm.language" /></el-form-item><el-form-item label="标题" required><el-input v-model="subtitleForm.title" /></el-form-item><el-form-item label="格式" required><el-input v-model="subtitleForm.format" /></el-form-item></div><el-checkbox v-model="subtitleForm.forced">强制字幕</el-checkbox><el-checkbox v-model="subtitleForm.hearingImpaired" class="ml-4">听障字幕</el-checkbox></el-form></template></template><template #footer><el-button @click="metadataDialog = false">关闭</el-button><el-button type="primary" :loading="subtitleSaving" :disabled="!selectedRelease" @click="addSubtitle">关联字幕</el-button></template></el-dialog>
    <el-dialog v-model="playbackDialog" title="视频播放" width="900px" @closed="closePlayback"><el-alert v-if="playbackSession" :title="playbackTitle()" type="success" :closable="false" class="mb-3"/><div class="flex flex-wrap items-center gap-3 mb-3"><div v-if="subtitles.length" class="flex items-center gap-2"><span class="text-sm">字幕</span><el-select v-model="selectedSubtitleId" class="w-64" placeholder="关闭字幕" clearable @change="switchSubtitle"><el-option v-for="subtitle in subtitles" :key="subtitle.id" :label="subtitle.title || subtitle.language || subtitle.id" :value="subtitle.id" /></el-select></div><div v-if="audioTracks.length" class="flex items-center gap-2"><span class="text-sm">音轨</span><el-select v-model="selectedAudioTrackId" class="w-64" @change="switchAudioTrack"><el-option v-for="track in audioTracks" :key="track.id" :label="track.label" :value="track.id" /></el-select></div><span v-else-if="playbackUrl" class="text-sm text-[var(--el-text-color-secondary)]">当前文件未暴露可切换音轨</span></div><video v-if="playbackUrl" ref="playbackVideo" :src="playbackUrl" controls autoplay preload="metadata" class="w-full max-h-[70vh]" @loadedmetadata="onPlaybackMetadata" @timeupdate="savePlaybackProgress(false, $event)" @pause="savePlaybackProgress(true, $event)"><track v-for="subtitle in subtitles.filter(item => item.url)" :key="subtitle.id" :src="subtitle.url" kind="subtitles" :srclang="subtitle.language || subtitle.id" :label="subtitle.title || subtitle.language || subtitle.id" /></video><el-empty v-else description="播放地址为空" /></el-dialog>
    <el-drawer v-model="orderDialog" title="维护剧集顺序" size="620px"><el-skeleton v-if="orderLoading && !episodes.length" :rows="6" animated /><template v-else><div class="flex items-center gap-3 mb-4"><span class="text-sm">Season</span><el-select v-model="selectedSeasonId" class="flex-1" placeholder="选择 Season" @change="loadEpisodes"><el-option v-for="season in seasons" :key="season.id" :label="`第 ${season.seasonNumber ?? 0} 季 · ${season.name || season.id}`" :value="season.id" /></el-select></div><el-empty v-if="!seasons.length" description="暂无 Season；先创建 Season 后才能维护剧集顺序" /><el-empty v-else-if="!episodes.length" description="该 Season 暂无剧集" /><el-table v-else :data="episodes" row-key="id"><el-table-column label="顺序" width="90"><template #default="{ $index }">{{ $index + 1 }}</template></el-table-column><el-table-column prop="episodeNumber" label="当前编号" width="120" /><el-table-column prop="id" label="Episode ID" min-width="230" /><el-table-column label="调整" width="120"><template #default="{ $index }"><el-button link :disabled="$index === 0" @click="moveEpisode($index, -1)">上移</el-button><el-button link :disabled="$index === episodes.length - 1" @click="moveEpisode($index, 1)">下移</el-button></template></el-table-column></el-table><div class="flex justify-end mt-4"><el-button type="primary" :loading="orderLoading" :disabled="!episodes.length" @click="saveOrder">保存顺序</el-button></div></template></el-drawer>
  </main>
</template>
