<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const documents = ref<Row[]>([]); const selectedId = ref(""); const content = ref(""); const contentSchemaVersion = ref("v1"); const version = ref(0); const loading = ref(false); const saving = ref(false); const error = ref(""); const message = ref("");
async function loadDocuments() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/documents"); documents.value = Array.isArray(result) ? result as Row[] : []; if (!selectedId.value && documents.value[0]?.id) { selectedId.value = documents.value[0].id; await loadCopy(); } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文档列表加载失败"; } finally { loading.value = false; } }
async function loadCopy() { if (!selectedId.value) return; loading.value = true; error.value = ""; try { const result: any = await http.get(`/documents/${selectedId.value}/working-copy`); content.value = String(result?.content || ""); contentSchemaVersion.value = String(result?.contentSchemaVersion || "v1"); version.value = Number(result?.version || 0); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "工作副本加载失败"; } finally { loading.value = false; } }
async function save() { if (!selectedId.value) return; saving.value = true; error.value = ""; message.value = ""; try { const result: any = await http.request("put", `/documents/${selectedId.value}/working-copy`, { data: { content: content.value, contentSchemaVersion: contentSchemaVersion.value, expectedVersion: version.value } }); version.value = Number(result?.version ?? version.value + 1); message.value = `已保存工作副本（版本 ${version.value}）`; } catch (e: any) { error.value = e?.response?.status === 409 ? "工作副本已被其他编辑者修改，请重新加载后再保存。" : e?.response?.data?.detail || e?.message || "工作副本保存失败"; } finally { saving.value = false; } }
onMounted(loadDocuments);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">文档协作编辑</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">工作副本使用服务端版本校验；并发修改会明确提示，不会静默覆盖。</p></div><el-button :loading="loading" @click="loadDocuments">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><div class="flex flex-wrap gap-3 items-end mb-5"><el-form-item label="文档"><el-select v-model="selectedId" class="w-96" filterable @change="loadCopy"><el-option v-for="item in documents" :key="item.id" :label="item.title || item.id" :value="item.id"/></el-select></el-form-item><span class="text-sm">工作副本版本：{{ version }}</span><el-button :loading="loading" :disabled="!selectedId" @click="loadCopy">重新加载</el-button><el-button type="primary" :loading="saving" :disabled="!selectedId" @click="save">保存工作副本</el-button></div><el-input v-model="content" type="textarea" :rows="22" :disabled="!selectedId || loading" placeholder="选择文档后编辑工作副本"/></el-card></main></template>
