<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const documents = ref<Row[]>([]); const selectedId = ref(""); const content = ref(""); const baseContent = ref(""); const contentSchemaVersion = ref("v1"); const version = ref(0); const embeds = ref<Row[]>([]); const embedForm = ref({ attachmentId: "", displayName: "", caption: "", altText: "" }); const collaborators = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const embedSaving = ref(false); const presenceLoading = ref(false); const conflictPending = ref(false); const error = ref(""); const message = ref(""); const clientId = crypto.randomUUID(); let presenceTimer: ReturnType<typeof setInterval> | undefined;
async function loadDocuments() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/documents"); documents.value = Array.isArray(result) ? result as Row[] : []; if (!selectedId.value && documents.value[0]?.id) { selectedId.value = documents.value[0].id; await loadCopy(); } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文档列表加载失败"; } finally { loading.value = false; } }
async function loadEmbeds() { if (!selectedId.value) { embeds.value = []; return; } try { const result = await http.get<unknown, unknown>(`/documents/${selectedId.value}/embeds`); embeds.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "资源附件加载失败"; } }
async function loadCopy() { if (!selectedId.value) return; loading.value = true; error.value = ""; try { const result: any = await http.get(`/documents/${selectedId.value}/working-copy`); content.value = String(result?.content || ""); baseContent.value = content.value; contentSchemaVersion.value = String(result?.contentSchemaVersion || "v1"); version.value = Number(result?.version || 0); await loadEmbeds(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "工作副本加载失败"; } finally { loading.value = false; } }
async function mergeOfflineContent() { if (!selectedId.value) return; try { const result: any = await http.post(`/documents/${selectedId.value}/working-copy/actions/merge`, { data: { baseContent: baseContent.value, localContent: content.value, contentSchemaVersion: contentSchemaVersion.value } }); content.value = String(result?.content || ""); version.value = Number(result?.currentVersion ?? version.value); message.value = result?.conflict ? "检测到合并冲突，已插入冲突标记；请人工处理后再保存。" : "离线修改已与服务端副本合并，请确认后保存。"; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "工作副本合并失败"; } }
async function refreshPresence() { if (!selectedId.value) { collaborators.value = []; return; } presenceLoading.value = true; try { await http.request("put", `/documents/${selectedId.value}/presence`, { data: { clientId } }); const result = await http.get<unknown, unknown>(`/documents/${selectedId.value}/presence`); collaborators.value = Array.isArray(result) ? result as Row[] : []; message.value = `当前在线协作者：${collaborators.value.length} 人`; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "在线协作者加载失败"; } finally { presenceLoading.value = false; } }
async function save() { if (!selectedId.value) return; saving.value = true; error.value = ""; message.value = ""; try { const result: any = await http.request("put", `/documents/${selectedId.value}/working-copy`, { data: { content: content.value, contentSchemaVersion: contentSchemaVersion.value, expectedVersion: version.value } }); version.value = Number(result?.version ?? version.value + 1); baseContent.value = content.value; message.value = `已保存工作副本（版本 ${version.value}）`; } catch (e: any) { if (e?.response?.status === 409) { conflictPending.value = true; error.value = "工作副本已被其他编辑者修改，请选择合并本地内容或放弃本地修改。"; } else error.value = e?.response?.data?.detail || e?.message || "工作副本保存失败"; } finally { saving.value = false; } }
async function mergeConflict() { conflictPending.value = false; await mergeOfflineContent(); }
async function discardConflict() { conflictPending.value = false; await loadCopy(); message.value = "已放弃本地修改并重新加载服务端副本。"; }
async function insertEmbed() { if (!selectedId.value || !embedForm.value.attachmentId.trim()) { error.value = "Attachment ID 不能为空"; return; } embedSaving.value = true; error.value = ""; try { await http.post(`/documents/${selectedId.value}/embeds`, { data: { ...embedForm.value, attachmentId: embedForm.value.attachmentId.trim() } }); embedForm.value = { attachmentId: "", displayName: "", caption: "", altText: "" }; message.value = "资源附件已插入文档"; await loadEmbeds(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "资源附件插入失败"; } finally { embedSaving.value = false; } }
async function removeEmbed(embed: Row) { if (!window.confirm("确认移除这条资源附件引用吗？不会删除 Attachment 本身。")) return; try { await http.request("delete", `/documents/${selectedId.value}/embeds/${embed.id}`); message.value = "资源附件引用已移除"; await loadEmbeds(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "资源附件移除失败"; } }
watch(selectedId, () => { refreshPresence(); });
onMounted(() => { loadDocuments(); presenceTimer = setInterval(refreshPresence, 10000); }); onBeforeUnmount(async () => { if (presenceTimer) clearInterval(presenceTimer); if (selectedId.value) { try { await http.request("delete", `/documents/${selectedId.value}/presence/${clientId}`); } catch { /* leave is best effort during unload */ } } });
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">文档协作编辑</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">工作副本使用服务端版本校验；并发修改会明确提示，不会静默覆盖。</p></div><el-button :loading="loading" @click="loadDocuments">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4"/><el-alert v-if="conflictPending" title="检测到编辑冲突：服务端副本已经变化。请合并本地内容并人工确认，或放弃本地修改。" type="warning" show-icon :closable="false" class="mb-4"><template #default><div class="flex gap-2 mt-2"><el-button size="small" type="warning" @click="mergeConflict">合并本地内容</el-button><el-button size="small" @click="discardConflict">放弃本地修改</el-button></div></template></el-alert><el-card shadow="never"><div class="flex flex-wrap gap-3 items-end mb-5"><el-form-item label="文档"><el-select v-model="selectedId" class="w-96" filterable @change="loadCopy"><el-option v-for="item in documents" :key="item.id" :label="item.title || item.id" :value="item.id"/></el-select></el-form-item><span class="text-sm">工作副本版本：{{ version }}</span><el-button :loading="loading" :disabled="!selectedId" @click="loadCopy">重新加载</el-button><el-button type="primary" :loading="saving" :disabled="!selectedId" @click="save">保存工作副本</el-button></div><el-input v-model="content" type="textarea" :rows="22" :disabled="!selectedId || loading" placeholder="选择文档后编辑工作副本"/><el-divider/><div class="flex items-center justify-between mb-3"><span class="font-medium">资源附件</span><span class="text-sm text-[var(--el-text-color-secondary)]">只管理文档引用，不删除 Attachment</span></div><div class="grid grid-cols-1 md:grid-cols-2 gap-3"><el-input v-model="embedForm.attachmentId" placeholder="Attachment ID"/><el-input v-model="embedForm.displayName" placeholder="显示名称（可选）"/><el-input v-model="embedForm.caption" placeholder="说明（可选）"/><el-input v-model="embedForm.altText" placeholder="替代文本（可选）"/></div><el-button class="mt-3" type="primary" plain :loading="embedSaving" :disabled="!selectedId" @click="insertEmbed">插入资源附件</el-button><el-table v-if="embeds.length" :data="embeds" size="small" class="mt-4"><el-table-column prop="displayName" label="名称"/><el-table-column prop="attachmentId" label="Attachment ID" min-width="240"/><el-table-column prop="caption" label="说明"/><el-table-column label="操作" width="90"><template #default="{ row }"><el-button link type="danger" @click="removeEmbed(row)">移除</el-button></template></el-table-column></el-table><el-empty v-else description="暂无资源附件引用" :image-size="60" class="my-3"/></el-card></main></template>
