<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type DocumentItem = { id: string; resourceId?: string; kind?: string; currentRevisionId?: string };
const items = ref<DocumentItem[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const detail = ref<DocumentItem | null>(null); const detailLoading = ref(false);
const form = ref({ title: "", kind: "DOCUMENT", locale: "zh-CN", content: "" });
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/documents"); items.value = Array.isArray(result) ? result as DocumentItem[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文档加载失败"; } finally { loading.value = false; } }
async function createDocument() { if (!form.value.title.trim()) { error.value = "标题不能为空"; return; } saving.value = true; try { await http.post("/documents", { data: { ...form.value, title: form.value.title.trim() } }); dialog.value = false; form.value = { title: "", kind: "DOCUMENT", locale: "zh-CN", content: "" }; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文档创建失败"; } finally { saving.value = false; } }
async function openDetail(row: DocumentItem) { detail.value = row; detailLoading.value = true; try { const copy = await http.get<unknown, unknown>(`/documents/${row.id}/working-copy`); detail.value = { ...row, ...(copy as object) }; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "工作副本加载失败"; } finally { detailLoading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">文档管理</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">创建文档、查看工作副本，并进入修订与发布流程。</p></div><div class="flex gap-2"><el-button @click="dialog = true">新建文档</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else shadow="never"><el-empty v-if="!items.length" description="暂无文档，先创建一份文档吧"/><el-table v-else :data="items" stripe><el-table-column prop="id" label="ID" min-width="250"/><el-table-column prop="kind" label="类型" width="150"/><el-table-column prop="currentRevisionId" label="当前修订" min-width="250"/><el-table-column label="操作" width="90"><template #default="{ row }"><el-button link type="primary" @click="openDetail(row)">详情</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" title="新建文档" width="560px"><el-form label-position="top"><el-form-item label="标题" required><el-input v-model="form.title" maxlength="256"/></el-form-item><el-form-item label="类型" required><el-input v-model="form.kind" placeholder="DOCUMENT"/></el-form-item><el-form-item label="语言"><el-input v-model="form.locale"/></el-form-item><el-form-item label="初始内容"><el-input v-model="form.content" type="textarea" :rows="5"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="createDocument">创建</el-button></template></el-dialog><el-drawer v-model="detail" title="文档工作副本" size="520px"><el-skeleton v-if="detailLoading" :rows="6" animated/><el-descriptions v-else-if="detail" :column="1" border><el-descriptions-item label="文档 ID">{{ detail.id }}</el-descriptions-item><el-descriptions-item label="资源 ID">{{ detail.resourceId || '—' }}</el-descriptions-item><el-descriptions-item label="类型">{{ detail.kind || '—' }}</el-descriptions-item><el-descriptions-item label="当前修订">{{ detail.currentRevisionId || '—' }}</el-descriptions-item></el-descriptions></el-drawer></main></template>
