<script setup lang="ts">
import { ref } from "vue";
import { http } from "@/utils/http";
type Announcement = Record<string, any>; const rows = ref<Announcement[]>([]); const loading = ref(false); const error = ref(""); const dialog = ref(false); const form = ref({ title: "", summary: "", body: "", priority: "NORMAL", audience: "ALL" });
async function load() { loading.value = true; try { const result = await http.get<unknown, unknown>("/communications/announcements"); rows.value = Array.isArray(result) ? result as Announcement[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || "公告接口尚未接入"; } finally { loading.value = false; } }
function saveDraft() { if (!form.value.title.trim()) { error.value = "公告标题不能为空"; return; } error.value = "公告保存接口尚未接入；草稿不会被发布"; }
load();
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">公告</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">创建、预览和管理面向受众的系统公告。</p></div><div class="flex gap-2"><el-button type="primary" @click="dialog = true">新建公告</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4"/><div class="flex gap-3 mb-4"><el-select placeholder="状态"><el-option label="全部状态" value="all"/><el-option label="草稿" value="draft"/><el-option label="已发布" value="published"/></el-select><el-select placeholder="受众"><el-option label="全部受众" value="all"/><el-option label="指定角色" value="role"/></el-select><el-select placeholder="优先级"><el-option label="全部优先级" value="all"/><el-option label="重要" value="important"/></el-select></div><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else shadow="never"><el-empty v-if="!rows.length" description="暂无公告"/><el-table v-else :data="rows" stripe><el-table-column prop="title" label="标题" min-width="220"/><el-table-column prop="status" label="状态" width="120"/><el-table-column prop="priority" label="优先级" width="110"/><el-table-column prop="audience" label="受众摘要" min-width="180"/><el-table-column prop="publishedAt" label="发布时间" min-width="180"/><el-table-column prop="expiresAt" label="过期时间" min-width="180"/><el-table-column prop="updatedAt" label="更新时间" min-width="180"/></el-table></el-card><el-dialog v-model="dialog" title="新建公告" width="680px"><el-form label-position="top"><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item><el-form-item label="简短摘要"><el-input v-model="form.summary"/></el-form-item><el-form-item label="正文"><el-input v-model="form.body" type="textarea" :rows="8"/></el-form-item><el-form-item label="优先级"><el-select v-model="form.priority"><el-option label="普通" value="NORMAL"/><el-option label="重要" value="IMPORTANT"/><el-option label="紧急" value="URGENT"/></el-select></el-form-item><el-form-item label="受众"><el-select v-model="form.audience"><el-option label="全部用户" value="ALL"/><el-option label="指定角色" value="ROLE"/><el-option label="特定分组" value="GROUP"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button @click="saveDraft">保存草稿</el-button><el-button type="primary" @click="saveDraft">预览</el-button></template></el-dialog></main></template>
