spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ikaros
    username: ikaros
    password: ikaros
  sql:
    init:
      mode: always
      platform: mysql
