spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${user.home}/.ikaros/db/ikaros;AUTO_SERVER=TRUE
    username: ikaros
    password: ikaros
ikaros:
  work-dir: ${user.home}/ikaros