spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ikaros
    username: ikaros
    password: ikaros
  sql:
    init:
      mode: always
      platform: mysql
