ikaros:
  show-theme: false
  plugin:
    runtime-mode: development

  #    auto-start-plugin: false
  security:
    # 30 day for local dev token expire
    jwt-expiration-time: 18144000000
    initializer:
      master-username: tomoki
      master-password: tomoki
  work-dir: ${user.home}/ikaros-dev

spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

