ikaros:
  plugin:
#    runtime-mode: development
#    fixed-plugin-path: C:\Develop\GitRepos\ikaros-dev\plugins\plugin-starter
  security:
    initializer:
      master-username: tomoki
      master-password: tomoki
  work-dir: ${user.home}/ikaros-dev

spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    run.ikaros.server: DEBUG
    org.pf4j: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
