ikaros:
  plugin:
    runtime-mode: development
    fixed-plugin-path: C:\Develop\GitRepos\ikaros-dev\plugins\plugin-starter
    enabled-plugins:
      - PluginStarter
  security:
    initializer:
      master-username: tomoki
      master-password: tomoki
  work-dir: ${user.home}/ikaros-dev

spring:
  thymeleaf:
    cache: false

logging:
  level:
    run.ikaros.server: DEBUG
    org.pf4j: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
