ikaros:
  plugin:
    runtime-mode: development
    fixed-plugin-path:
    enabled-plugins:
  security:
    initializer:
      master-username: tomoki
      master-password: tomoki

spring:
  thymeleaf:
    cache: false

logging:
  level:
    run.ikaros.server: DEBUG
    org.pf4j: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
