<script setup lang="ts">
import { computed, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ArrowRight } from "@element-plus/icons-vue";
const route = useRoute(); const router = useRouter(); const range = ref("7d"); const compare = ref(false); const tableView = ref(false);
const tab = computed(() => ["analytics", "overview"].includes(String(route.path.split("/").pop())) ? "overview" : String(route.path.split("/").pop()));
const labels: Record<string, string> = { overview: "个人数据概览", content: "内容分析", storage: "存储分析", planning: "效率分析", system: "系统历史", metrics: "指标目录", reports: "报表与重建" };
const kpis = [["新增 Resource", "content"], ["消费时长 / 进度", "content"], ["已完成任务", "planning"], ["专注时长", "planning"], ["存储增长", "storage"], ["自动化 / 同步活动", "system"]];
function openKpi(path: string) { router.push({ path: `/console/analytics/${path}`, query: { range: range.value } }); }
</script>
<template><main class="p-4 md:p-6"><div class="flex flex-col gap-4 mb-6 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-sm text-[var(--el-text-color-secondary)]">数据分析 / {{ labels[tab] || "分析" }}</p><h1 class="mt-2 text-2xl font-semibold">{{ labels[tab] || "数据分析" }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">按授权范围查看聚合指标；不会展示私密内容或未经后端确认的推断数据。</p></div><div class="flex flex-wrap items-center gap-3"><el-select v-model="range" class="w-32" aria-label="分析周期"><el-option label="近 7 天" value="7d"/><el-option label="近 30 天" value="30d"/><el-option label="近 90 天" value="90d"/><el-option label="本年" value="year"/><el-option label="自定义" value="custom"/></el-select><el-switch v-model="compare" active-text="对比上一周期"/><el-button disabled>导出报表</el-button></div></div><el-alert title="分析接口尚未提供聚合数据" description="当前页面已保留指标、图表和报表布局；接入 analytics API 后会自动填充真实数据。" type="info" show-icon :closable="false" class="mb-5"/><section class="grid grid-cols-1 gap-4 mb-6 sm:grid-cols-2 xl:grid-cols-3"><el-card v-for="([label, path]) in kpis" :key="label" shadow="never" class="cursor-pointer" @click="openKpi(path as string)"><div class="flex items-start justify-between"><span class="text-sm text-[var(--el-text-color-secondary)]">{{ label }}</span><el-icon class="text-[var(--el-text-color-secondary)]"><ArrowRight /></el-icon></div><div class="mt-2 text-2xl font-semibold">—</div><div class="mt-1 text-xs text-[var(--el-text-color-secondary)]">暂无当前周期数据<span v-if="compare"> · 对比不可用</span></div></el-card></section><div class="flex justify-end mb-3"><el-button text @click="tableView = !tableView">{{ tableView ? "显示图表区域" : "显示数据表替代" }}</el-button></div><section v-if="!tableView" class="grid grid-cols-1 gap-4 lg:grid-cols-2"><el-card v-for="title in ['活动趋势', '内容类型分布', '完成 / 进度趋势', '存储增长']" :key="title" shadow="never" class="min-h-56"><template #header><div class="flex items-center justify-between"><span class="font-medium">{{ title }}</span><el-button text disabled>图例</el-button></div></template><el-empty description="暂无可视化数据" :image-size="72" /></el-card></section><el-card v-else shadow="never"><el-empty description="暂无可替代图表的数据" /></el-card></main></template>
