<script setup lang="ts">
import { computed, ref } from "vue";
import { http } from "@/utils/http";
const role = ref("role"); const subject = ref(""); const query = ref(""); const permissions = ref<string[]>([]); const selected = ref<Record<string, boolean>>({}); const loading = ref(false); const error = ref(""); const staged = computed(() => Object.keys(selected.value).filter(key => selected.value[key])); const groups = computed(() => { const result: Record<string, string[]> = {}; permissions.value.filter(key => !query.value || key.toLowerCase().includes(query.value.toLowerCase())).forEach(key => { const group = key.split('.')[0] || 'platform'; (result[group] ||= []).push(key); }); return result; });
async function load() { loading.value = true; try { const result = await http.get<unknown, unknown>("/admin/permissions"); permissions.value = Array.isArray(result) ? result as string[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "权限加载失败"; } finally { loading.value = false; } }
function toggle(key: string, value: boolean) { selected.value = { ...selected.value, [key]: value }; }
function discard() { selected.value = {}; }
load();
</script>
<template><main class="p-4 md:p-6"><div class="mb-6"><h1 class="text-2xl font-semibold">权限矩阵</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">查看能力注册表；权限修改先进入待审阅状态，不会立即保存。</p></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><div class="flex flex-wrap gap-3 mb-4"><el-radio-group v-model="role"><el-radio-button label="role">按 Role 查看</el-radio-button><el-radio-button label="user">按 User 查看</el-radio-button></el-radio-group><el-input v-model="subject" :placeholder="role === 'role' ? '选择 Role' : '输入 User ID'" class="w-56"/><el-input v-model="query" clearable placeholder="搜索 Capability / Resource" class="w-64"/><el-button :loading="loading" @click="load">刷新</el-button></div><el-skeleton v-if="loading" :rows="10" animated/><div v-else class="space-y-4"><el-card v-for="(keys, group) in groups" :key="group" shadow="never"><template #header><div class="font-medium capitalize">{{ group }}<span class="text-sm text-[var(--el-text-color-secondary)] ml-2">{{ keys.length }} 项能力</span></div></template><el-table :data="keys.map(code => ({ code }))" stripe><el-table-column prop="code" label="Capability Key" min-width="360"/><el-table-column label="查看" width="100"><template #default="{ row }"><el-checkbox :model-value="!!selected[row.code]" @update:model-value="value => toggle(row.code, !!value)"/></template></el-table-column><el-table-column label="来源" width="180">Role / Inherited</el-table-column><el-table-column label="风险" width="120"><template #default="{ row }"><el-tag v-if="row.code.includes('security') || row.code.includes('secret')" type="warning">高风险</el-tag><span v-else>普通</span></template></el-table-column></el-table></el-card><el-empty v-if="!Object.keys(groups).length" description="暂无匹配权限"/></div><div v-if="staged.length" class="fixed bottom-4 left-1/2 -translate-x-1/2 flex items-center gap-4 bg-[var(--el-bg-color)] border rounded-lg shadow-lg px-5 py-3"><span>已暂存 {{ staged.length }} 项修改</span><el-button @click="discard">放弃修改</el-button><el-button type="primary">审阅修改</el-button></div></main></template>
