<script setup lang="ts">
import { computed } from "vue";
import { getToken } from "@/utils/auth";
const token = getToken();
const expiresAt = computed(() => token?.expires ? new Date(Number(token.expires)).toLocaleString() : "未知");
const tokenPreview = computed(() => token?.accessToken ? `${token.accessToken.slice(0, 12)}…` : "未找到 Access Token");
function clearLocalToken() { localStorage.removeItem("authorized-token"); window.location.replace("/login"); }
function refresh() { window.location.reload(); }
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">JWT 认证状态</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">本项目使用 JWT，不维护可由服务端逐个撤销的 Session。</p></div><el-button @click="window.location.reload()">刷新</el-button></div><div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-5"><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">Access Token</div><div class="text-lg font-semibold mt-2">{{ token ? '已配置' : '未配置' }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">Refresh Token</div><div class="text-lg font-semibold mt-2">{{ token?.refreshToken ? '已配置' : '未配置' }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">Access Token 过期</div><div class="text-lg font-semibold mt-2">{{ expiresAt }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">撤销方式</div><div class="text-lg font-semibold mt-2">刷新 / 退出登录</div></el-card></div><el-alert title="JWT 已签发后通常无法像服务端 Session 一样单独撤销；退出登录会清理本地 Token，Refresh Token 续期由认证接口决定。" type="info" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-descriptions :column="1" border><el-descriptions-item label="Access Token 摘要">{{ tokenPreview }}</el-descriptions-item><el-descriptions-item label="Session ID">不适用：JWT 认证模型</el-descriptions-item><el-descriptions-item label="认证方法">Bearer JWT</el-descriptions-item><el-descriptions-item label="设备/网络">前端不持有服务端 Session 元数据</el-descriptions-item></el-descriptions><el-button type="danger" class="mt-5" @click="clearLocalToken">退出并清理本地 Token</el-button></el-card></main></template>
