<script setup lang="ts">
import { computed, ref } from "vue";
const step = ref(0); const accepted = ref(false); const password = ref(""); const confirm = ref("");
const environment = import.meta.env.MODE;
const steps = ["环境检查", "创建初始管理员", "安全与恢复", "基础偏好", "确认初始化"];
const canNext = computed(() => step.value !== 1 || (!!password.value && password.value === confirm.value));
function next() { if (canNext.value && step.value < steps.length - 1) step.value += 1; }
</script>
<template><main class="min-h-screen flex items-center justify-center p-4 bg-[var(--el-bg-color-page)]"><el-card shadow="never" class="w-full max-w-3xl"><div class="text-center mb-8"><div class="text-2xl font-semibold">Ikaros</div><h1 class="mt-3 text-2xl font-semibold">初始化 Ikaros</h1><p class="mt-2 text-[var(--el-text-color-secondary)]">完成首次部署配置后即可进入登录页。</p></div><el-steps :active="step" finish-status="success" class="mb-8"><el-step v-for="item in steps" :key="item" :title="item" /></el-steps><el-alert v-if="step === 0" title="环境检查通过" type="success" show-icon :closable="false"/><el-descriptions v-if="step === 0" :column="1" border class="mt-4"><el-descriptions-item label="版本">Ikaros Console</el-descriptions-item><el-descriptions-item label="部署环境">{{ environment }}</el-descriptions-item><el-descriptions-item label="系统时间">{{ new Date().toLocaleString() }}</el-descriptions-item><el-descriptions-item label="敏感路径">仅显示安全摘要</el-descriptions-item></el-descriptions><el-form v-else-if="step === 1" label-position="top" class="max-w-xl mx-auto"><el-form-item label="用户名" required><el-input placeholder="请输入初始管理员用户名" /></el-form-item><el-form-item label="显示名称"><el-input /></el-form-item><el-form-item label="邮箱" required><el-input type="email" /></el-form-item><el-form-item label="密码" required><el-input v-model="password" type="password" show-password /></el-form-item><el-form-item label="确认密码" required><el-input v-model="confirm" type="password" show-password /></el-form-item><el-alert v-if="password && password !== confirm" title="两次密码输入不一致" type="error" :closable="false" /></el-form><el-descriptions v-else-if="step === 2" :column="1" border><el-descriptions-item label="Email OTP">待初始化后检测</el-descriptions-item><el-descriptions-item label="恢复方式">由服务端策略决定</el-descriptions-item><el-descriptions-item label="Session 策略">使用服务端默认策略</el-descriptions-item></el-descriptions><el-form v-else-if="step === 3" label-position="top" class="max-w-xl mx-auto"><el-form-item label="默认语言"><el-select class="w-full" model-value="zh-CN"><el-option label="简体中文" value="zh-CN"/><el-option label="English" value="en-US"/></el-select></el-form-item><el-form-item label="默认时区"><el-input model-value="Asia/Shanghai" /></el-form-item><el-form-item label="主题"><el-radio-group><el-radio label="system">跟随系统</el-radio><el-radio label="light">浅色</el-radio><el-radio label="dark">深色</el-radio></el-radio-group></el-form-item></el-form><div v-else class="text-center"><el-alert title="请确认初始化摘要" type="info" :closable="false" class="mb-4"/><el-checkbox v-model="accepted">我已确认以上配置</el-checkbox></div><div class="flex justify-between mt-8"><el-button :disabled="step === 0" @click="step--">上一步</el-button><el-button type="primary" :disabled="!canNext || (step === steps.length - 1 && !accepted)" @click="step === steps.length - 1 ? $router.push('/login') : next()">{{ step === steps.length - 1 ? '完成初始化' : '下一步' }}</el-button></div></el-card></main></template>
