name: Ikaros Bug 报告
description: 中文选这个，给 Ikaros 项目报告一个BUG
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        感谢您愿意抽空报告这个问题！我们非常感谢您为改善 ikaros 做出的贡献。

        有红色的 * 号，代表这项必填，没有则可不填。

  - type: checkboxes
    id: searchBeforeAsking
    attributes:
      label: 提问前查询
      description: >
        请去我们的 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表里查询下，是否已经有类似的问题存在。
      options:
        - label: >
            我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。
          required: true

  - type: dropdown
    id: ikarosComponent
    attributes:
      label: 组件
      description: |
        请问是 Ikaros 哪个组件的问题 Ikaros 有很多子项目，请确认你选择的组件是对应这个BUG的组件。
      multiple: false
      options:
        - "服务端 (server)"
        - "控制台 (console)"
        - "插件 (plugin)"
        - "文档 (docs)"
        - "主题 (theme)"
    validations:
      required: true

  - type: textarea
    id: runtimeEnvironment
    attributes:
      label: 运行环境
      description: 描述下您的运行环境
      placeholder: >
        请提供问题发生时的运行环境，
        操作系统：
        数据库：
        部署方式: docker 或者 fastjar
        服务端版本: 
        客户端:
        更多 ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 报错相关的日志
      description: 请复制并粘贴任何相关的日志输出。这将自动格式化为代码，因此不需要反引号。
      render: shell

  - type: textarea
    id: whatHappend
    attributes:
      label: 发生了什么
      description: 描述下发生了什么
      placeholder: >
        请描述下发生了什么
    validations:
      required: true

  - type: textarea
    id: whatYouExpectedToHappen
    attributes:
      label: 预期是怎样
      description: 你预期是什么样的行为(或动作)，长日志格式  `<details><summary>x.log</summary> 很长的日志内容</details>`
      placeholder: >
        请解释下你为什么认为这个行为(或动作)是不符合预期的。并请您复制粘贴下 具体的错误日志或者UI截图
        
        UI截图您可以通过光标选中这个输入框，将文件拖放到这个输入已经选中的输入框上传文件。
        
        如果日志内容太长，可以用这个格式包裹起来：<details><summary>x.log</summary> 很长的日志内容</details>
        
        **注意**：请复制粘贴文本，不要上传一个日志截图，截图尽量不要用(除了UI问题外)，文本日志方便搜索定位问题
    validations:
      required: true

  - type: textarea
    id: howToReproduce
    attributes:
      label: 如何复现
      description: >
        这个问题如何去复现，如果您没法提供相对准确的复现步骤，请开个 [Discussion](https://github.com/li-guohao/ikaros/discussions)
      placeholder: >
        请确保您提供了能一步一步成功复现的 尽可能详细的 **复现步骤**，不可复现的 issue 将会被关闭，
        
        请在 [Discussion](https://github.com/li-guohao/ikaros/discussions) 发起一个讨论
    validations:
      required: true

  - type: textarea
    id: anythingElse
    attributes:
      label: 其它补充内容
      description: 其它的我们需要知道的补充内容，长日志格式  `<details><summary>x.log</summary> 很长的日志内容</details>`
      placeholder: >
        比如这个问题发生的频率? (一次? 多次? 经常发生)。
        
        如果日志内容太长，可以用这个格式包裹起来：<details><summary>x.log</summary> 很长的日志内容</details>

  - type: checkboxes
    id: submitPullRequest
    attributes:
      label: 您将要去提交PR吗？
      description: >
        这个不是必须的，但是如果您知道这个问题如何修复，并且愿意提交RP给这个项目做贡献，我们将非常欢迎。
      options:
        - label: 是的我想要提交个PR!
          required: false


  - type: markdown
    attributes:
      value: "感谢您填写这个表单！因为有您的贡献，项目才能越来越好。"
