name: Ikaros 新功能请求
description: 中文选这个，给这个项目提关于 新功能 的建议
title: "[Feature] "
labels: [ "feature" ]
body:
  - type: markdown
    attributes:
      value: |
        
        感谢您愿意花时间提一个新功能！
        
        我们非常感谢您为提高 Ikaros 做的贡献。

        有红色的 * 号，代表这项必填，没有则可不填。

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        请去我们的 [issues](https://github.com/li-guohao/ikaros/issues?q=is%3Aissue) 列表里查询下，是否已经有类似的问题存在。
      options:
        - label: >
            我已经在 [issues](https://github.com/li-guohao/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。
          required: true

  - type: textarea
    attributes:
      label: Description
      description: 您期望的新功能的描述

  - type: textarea
    attributes:
      label: Use case
      description: 你想要新功能有什么样的行为？
      placeholder: >
        这个新功能想要实现什么样的目标？对应实现思路有什么建议吗？

  - type: textarea
    attributes:
      label: Related issues
      description: 目前是否有与此新功能有关的 issue, 您可以填写 `#数字` 或者URL 方便我们快速定位到这个issue

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        这个不是必须的，但是如果您知道这个问题如何修复，并且原因提交RP给这个项目做贡献，我们将非常欢迎。
      options:
        - label: 是的我想要提交个PR!
          required: false

  - type: textarea
    attributes:
      label: Related pull requests
      description: 目前是否有与此新功能有关的 pull request, 您可以填写 `#数字` 或者URL 方便我们快速定位到这个pr, 未完成的PR请在PR的title加上前缀`[WIP]`
      placeholder: >
        - [ ] 组件名1: PR链接 

        - [ ] 组件名2: PR链接 

  - type: markdown
    attributes:
      value: "感谢您填写这个表单！因为有您的贡献，项目才能越来越好。"