<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type EbookImport = Record<string, any>;
const imports = ref<EbookImport[]>([]); const loading = ref(false); const submitting = ref(false); const parsing = ref<Record<string, boolean>>({}); const chaptersByImport = ref<Record<string, EbookImport[]>>({}); const chapterDialog = ref(false); const chapterLoading = ref(false); const selectedImportId = ref(""); const contentDialog = ref(false); const contentLoading = ref(false); const selectedContent = ref<EbookImport | null>(null); const selectedChapterContext = ref<EbookImport | null>(null); const readingSession = ref<EbookImport | null>(null); const progressSaving = ref(false); const progressRestoring = ref<Record<string, boolean>>({}); const bookmarkDialog = ref(false); const bookmarkLoading = ref(false); const bookmarkSaving = ref(false); const bookmarks = ref<EbookImport[]>([]); const settingsDialog = ref(false); const settingsLoading = ref(false); const settingsSaving = ref(false); const selectedSettingsWorkId = ref(""); const ebookSettings = ref({ fontSize: 18, lineHeight: 1.8, contentWidth: 720, theme: "LIGHT", pagination: "SCROLL" }); const infoDialog = ref(false); const infoLoading = ref(false); const selectedInfo = ref<EbookImport | null>(null); const error = ref(""); const message = ref("");
const form = ref({ attachmentId: "", title: "", language: "zh-CN" });
async function load() { loading.value = true; error.value = ""; try { const result: any = await http.get("/reading/ebook-imports"); imports.value = Array.isArray(result) ? result : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书导入记录加载失败"; } finally { loading.value = false; } }
async function submit() { if (!form.value.attachmentId.trim()) { error.value = "请输入电子书 Attachment ID"; return; } submitting.value = true; error.value = ""; message.value = ""; try { const result: any = await http.post("/reading/ebook-imports", { headers: { "Idempotency-Key": crypto.randomUUID() }, data: { attachmentId: form.value.attachmentId.trim(), title: form.value.title.trim() || undefined, language: form.value.language || undefined } }); message.value = `电子书导入已受理：${result?.id || "已创建"}`; form.value = { attachmentId: "", title: "", language: "zh-CN" }; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书导入失败"; } finally { submitting.value = false; } }
function statusType(status: string) { return status === "ACCEPTED" ? "warning" : status === "FAILED" ? "danger" : "success"; }
async function parseToc(row: EbookImport) { parsing.value = { ...parsing.value, [row.id]: true }; error.value = ""; try { await http.post(`/reading/ebook-imports/${row.id}/actions/parse-toc`); await showChapters(row); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书目录解析失败"; } finally { const next = { ...parsing.value }; delete next[row.id]; parsing.value = next; } }
async function showChapters(row: EbookImport) { selectedImportId.value = row.id; chapterDialog.value = true; chapterLoading.value = true; try { const result: any = await http.get(`/reading/ebook-imports/${row.id}/chapters`); chaptersByImport.value = { ...chaptersByImport.value, [row.id]: Array.isArray(result) ? result : [] }; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书目录加载失败"; } finally { chapterLoading.value = false; } }
async function openChapter(row: EbookImport) { selectedChapterContext.value = row; selectedContent.value = null; readingSession.value = null; contentDialog.value = true; contentLoading.value = true; error.value = ""; try { selectedContent.value = await http.get(`/reading/ebook-imports/${row.importId}/chapters/${row.chapterId}/content`) as EbookImport; readingSession.value = await http.post(`/reading/works/${row.workId}/sessions`, { data: { editionId: row.editionId, chapterId: row.chapterId, locatorKind: "EPUB_LOCATION", locatorValue: row.href, offline: false } }) as EbookImport; } catch (e: any) { contentDialog.value = false; error.value = e?.response?.data?.detail || e?.message || "电子书章节加载失败"; } finally { contentLoading.value = false; } }
async function saveReadingPosition() { const context = selectedChapterContext.value; const session = readingSession.value; if (!context || !session?.id) { error.value = "章节阅读会话尚未建立，无法保存位置"; return; } progressSaving.value = true; error.value = ""; try { readingSession.value = await http.request("patch", `/reading/sessions/${session.id}`, { headers: { "If-Match": `\"${session.version ?? 0}\"` }, data: { locatorKind: "EPUB_LOCATION", locatorValue: context.href, completed: false, intent: "NAVIGATE", contentVersion: null } }) as EbookImport; message.value = "阅读位置已保存"; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "阅读位置保存失败"; } finally { progressSaving.value = false; } }
async function resumeReading(row: EbookImport) { progressRestoring.value = { ...progressRestoring.value, [row.id]: true }; error.value = ""; try { const result: any = await http.get(`/reading/works/${row.workId}/progress?editionId=${row.editionId}`); const chapters = chaptersByImport.value[row.id] || await http.get(`/reading/ebook-imports/${row.id}/chapters`) as EbookImport[]; const chapter = chapters.find(item => item.chapterId === result?.chapterId); if (!chapter) throw new Error("上次阅读章节已不在当前电子书目录中"); await openChapter({ ...chapter, workId: row.workId, editionId: row.editionId }); message.value = `已恢复到：${chapter.title || result?.locatorValue || "上次位置"}`; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "上次阅读位置恢复失败"; } finally { const next = { ...progressRestoring.value }; delete next[row.id]; progressRestoring.value = next; } }
async function loadBookmarks(row: EbookImport) { bookmarkDialog.value = true; bookmarkLoading.value = true; error.value = ""; try { const result: any = await http.get(`/reading/works/${row.workId}/bookmarks`); bookmarks.value = Array.isArray(result) ? result : []; } catch (e: any) { bookmarkDialog.value = false; error.value = e?.response?.data?.detail || e?.message || "书签加载失败"; } finally { bookmarkLoading.value = false; } }
async function addBookmark() { const context = selectedChapterContext.value; if (!context) return; bookmarkSaving.value = true; error.value = ""; try { await http.post(`/reading/works/${context.workId}/editions/${context.editionId}/chapters/${context.chapterId}/bookmarks`, { data: { locatorKind: "EPUB_LOCATION", locatorValue: context.href, contentVersion: null, label: context.title } }); message.value = "书签已添加"; await loadBookmarks(context); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "书签添加失败"; } finally { bookmarkSaving.value = false; } }
async function removeBookmark(row: EbookImport) { try { await http.request("delete", `/reading/bookmarks/${row.id}`); bookmarks.value = bookmarks.value.filter(item => item.id !== row.id); message.value = "书签已移除"; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "书签移除失败"; } }
function defaultEbookSettings() { return { fontSize: 18, lineHeight: 1.8, contentWidth: 720, theme: "LIGHT", pagination: "SCROLL" }; }
async function showSettings(row: EbookImport) { selectedSettingsWorkId.value = row.workId; ebookSettings.value = defaultEbookSettings(); settingsDialog.value = true; settingsLoading.value = true; error.value = ""; try { const result: any = await http.get(`/reading/preferences?scope=WORK&kind=EBOOK&workId=${row.workId}`); ebookSettings.value = { ...ebookSettings.value, ...JSON.parse(result?.settings || "{}") }; } catch (e: any) { if (e?.response?.status !== 404) { settingsDialog.value = false; error.value = e?.response?.data?.detail || e?.message || "电子书阅读设置加载失败"; } } finally { settingsLoading.value = false; } }
async function saveSettings() { if (ebookSettings.value.fontSize < 10 || ebookSettings.value.fontSize > 48 || ebookSettings.value.lineHeight < 1 || ebookSettings.value.lineHeight > 3 || ebookSettings.value.contentWidth < 480 || ebookSettings.value.contentWidth > 1200) { error.value = "请检查字号、行高和内容宽度范围"; return; } settingsSaving.value = true; error.value = ""; try { await http.request("put", `/reading/preferences?scope=WORK&kind=EBOOK&workId=${selectedSettingsWorkId.value}`, { data: { settings: JSON.stringify(ebookSettings.value) } }); const result: any = await http.get(`/reading/preferences?scope=WORK&kind=EBOOK&workId=${selectedSettingsWorkId.value}`); ebookSettings.value = { ...ebookSettings.value, ...JSON.parse(result?.settings || "{}") }; message.value = "电子书阅读设置已保存并重新读取确认"; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书阅读设置保存失败"; } finally { settingsSaving.value = false; } }
async function showInfo(row: EbookImport) { selectedInfo.value = null; infoDialog.value = true; infoLoading.value = true; error.value = ""; try { selectedInfo.value = await http.get(`/reading/ebook-imports/${row.id}/info`) as EbookImport; } catch (e: any) { infoDialog.value = false; error.value = e?.response?.data?.detail || e?.message || "书籍信息加载失败"; } finally { infoLoading.value = false; } }
onMounted(load);
</script>
<template>
  <main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">电子书导入</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">导入 EPUB 电子书并创建可阅读的作品版本。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4"/>
    <el-card shadow="never" class="mb-4"><el-form label-position="top" class="max-w-2xl"><el-form-item label="EPUB Attachment ID" required><el-input v-model="form.attachmentId" placeholder="先在附件管理上传 .epub，再粘贴 Attachment ID" clearable/></el-form-item><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><el-form-item label="书名"><el-input v-model="form.title" placeholder="留空使用文件名"/></el-form-item><el-form-item label="语言"><el-input v-model="form.language" placeholder="zh-CN"/></el-form-item></div><el-button type="primary" :loading="submitting" @click="submit">提交 EPUB 导入</el-button></el-form></el-card>
    <el-card shadow="never"><el-empty v-if="!imports.length" description="暂无电子书导入记录"/><el-table v-else :data="imports" stripe><el-table-column prop="sourceAttachmentId" label="源附件" min-width="280"/><el-table-column prop="workId" label="Work ID" min-width="280"/><el-table-column prop="editionId" label="Edition ID" min-width="280"/><el-table-column label="状态" width="130"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="errorMessage" label="错误" min-width="240"/><el-table-column prop="createdAt" label="导入时间" min-width="180"/><el-table-column label="操作" width="520"><template #default="{ row }"><el-button link type="primary" @click="showInfo(row)">书籍信息</el-button><el-button link type="primary" @click="showSettings(row)">阅读设置</el-button><el-button link type="primary" @click="loadBookmarks(row)">书签</el-button><el-button link type="primary" :loading="progressRestoring[row.id]" :disabled="row.status !== 'SUCCEEDED'" @click="resumeReading(row)">恢复阅读</el-button><el-button link type="primary" :loading="parsing[row.id]" :disabled="row.status === 'PARSING'" @click="parseToc(row)">{{ row.status === 'FAILED' ? '重试解析目录' : '解析目录' }}</el-button><el-button link type="primary" :disabled="!chaptersByImport[row.id]?.length" @click="showChapters(row)">查看目录</el-button></template></el-table-column></el-table></el-card>
    <el-dialog v-model="chapterDialog" title="电子书目录" width="820px"><el-skeleton v-if="chapterLoading" :rows="5" animated/><el-empty v-else-if="!chaptersByImport[selectedImportId]?.length" description="尚未解析出章节"/><el-table v-else :data="chaptersByImport[selectedImportId]" stripe><el-table-column prop="sortOrder" label="#" width="80"/><el-table-column prop="title" label="章节" min-width="240"/><el-table-column prop="href" label="内容路径" min-width="260"/><el-table-column label="操作" width="110"><template #default="{ row }"><el-button link type="primary" @click="openChapter(row)">打开章节</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="contentDialog" :title="selectedContent?.title || '电子书章节'" width="760px"><el-skeleton v-if="contentLoading" :rows="8" animated/><el-empty v-else-if="!selectedContent?.content" description="章节没有可阅读正文"/><article v-else class="whitespace-pre-wrap leading-8 max-h-[65vh] overflow-auto px-2">{{ selectedContent.content }}</article><template #footer><el-button @click="contentDialog = false">关闭</el-button><el-button :loading="progressSaving" @click="saveReadingPosition">保存阅读位置</el-button><el-button type="primary" :loading="bookmarkSaving" @click="addBookmark">添加当前章节书签</el-button></template></el-dialog>
    <el-dialog v-model="settingsDialog" title="电子书阅读设置" width="560px"><el-skeleton v-if="settingsLoading" :rows="6" animated/><el-form v-else label-position="top"><div class="grid grid-cols-2 gap-4"><el-form-item label="字号"><el-input-number v-model="ebookSettings.fontSize" :min="10" :max="48" controls-position="right" class="w-full"/></el-form-item><el-form-item label="行高"><el-input-number v-model="ebookSettings.lineHeight" :min="1" :max="3" :step="0.1" controls-position="right" class="w-full"/></el-form-item><el-form-item label="内容宽度"><el-input-number v-model="ebookSettings.contentWidth" :min="480" :max="1200" :step="20" controls-position="right" class="w-full"/><span class="text-xs text-[var(--el-text-color-secondary)]">单位：px</span></el-form-item><el-form-item label="主题"><el-select v-model="ebookSettings.theme" class="w-full"><el-option label="浅色" value="LIGHT"/><el-option label="深色" value="DARK"/><el-option label="护眼" value="SEPIA"/></el-select></el-form-item></div><el-form-item label="阅读方式"><el-radio-group v-model="ebookSettings.pagination"><el-radio-button value="SCROLL">连续滚动</el-radio-button><el-radio-button value="PAGINATED">分页</el-radio-button></el-radio-group></el-form-item></el-form><template #footer><el-button @click="settingsDialog = false">取消</el-button><el-button type="primary" :loading="settingsSaving" @click="saveSettings">保存设置</el-button></template></el-dialog>
    <el-dialog v-model="bookmarkDialog" title="电子书书签" width="760px"><el-skeleton v-if="bookmarkLoading" :rows="5" animated/><el-empty v-else-if="!bookmarks.length" description="暂无书签"/><el-table v-else :data="bookmarks" stripe><el-table-column prop="label" label="章节" min-width="220"/><el-table-column prop="locatorValue" label="定位" min-width="280"/><el-table-column prop="createdAt" label="添加时间" min-width="180"/><el-table-column label="操作" width="90"><template #default="{ row }"><el-button link type="danger" @click="removeBookmark(row)">移除</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="infoDialog" title="基础书籍信息" width="560px"><el-skeleton v-if="infoLoading" :rows="6" animated/><el-descriptions v-else-if="selectedInfo" :column="1" border><el-descriptions-item label="书名">{{ selectedInfo.title || "—" }}</el-descriptions-item><el-descriptions-item label="语言">{{ selectedInfo.language || "—" }}</el-descriptions-item><el-descriptions-item label="出版社">{{ selectedInfo.publisher || "—" }}</el-descriptions-item><el-descriptions-item label="来源">{{ selectedInfo.source || "—" }}</el-descriptions-item><el-descriptions-item label="章节数">{{ selectedInfo.chapterCount ?? 0 }}</el-descriptions-item><el-descriptions-item label="导入状态"><el-tag :type="statusType(selectedInfo.importStatus)">{{ selectedInfo.importStatus }}</el-tag></el-descriptions-item><el-descriptions-item v-if="selectedInfo.errorMessage" label="错误">{{ selectedInfo.errorMessage }}</el-descriptions-item></el-descriptions></el-dialog>
  </main>
</template>
