<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type EbookImport = Record<string, any>;
const imports = ref<EbookImport[]>([]); const loading = ref(false); const submitting = ref(false); const parsing = ref<Record<string, boolean>>({}); const chaptersByImport = ref<Record<string, EbookImport[]>>({}); const chapterDialog = ref(false); const chapterLoading = ref(false); const selectedImportId = ref(""); const contentDialog = ref(false); const contentLoading = ref(false); const selectedContent = ref<EbookImport | null>(null); const infoDialog = ref(false); const infoLoading = ref(false); const selectedInfo = ref<EbookImport | null>(null); const error = ref(""); const message = ref("");
const form = ref({ attachmentId: "", title: "", language: "zh-CN" });
async function load() { loading.value = true; error.value = ""; try { const result: any = await http.get("/reading/ebook-imports"); imports.value = Array.isArray(result) ? result : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书导入记录加载失败"; } finally { loading.value = false; } }
async function submit() { if (!form.value.attachmentId.trim()) { error.value = "请输入电子书 Attachment ID"; return; } submitting.value = true; error.value = ""; message.value = ""; try { const result: any = await http.post("/reading/ebook-imports", { headers: { "Idempotency-Key": crypto.randomUUID() }, data: { attachmentId: form.value.attachmentId.trim(), title: form.value.title.trim() || undefined, language: form.value.language || undefined } }); message.value = `电子书导入已受理：${result?.id || "已创建"}`; form.value = { attachmentId: "", title: "", language: "zh-CN" }; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书导入失败"; } finally { submitting.value = false; } }
function statusType(status: string) { return status === "ACCEPTED" ? "warning" : status === "FAILED" ? "danger" : "success"; }
async function parseToc(row: EbookImport) { parsing.value = { ...parsing.value, [row.id]: true }; error.value = ""; try { await http.post(`/reading/ebook-imports/${row.id}/actions/parse-toc`); await showChapters(row); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书目录解析失败"; } finally { const next = { ...parsing.value }; delete next[row.id]; parsing.value = next; } }
async function showChapters(row: EbookImport) { selectedImportId.value = row.id; chapterDialog.value = true; chapterLoading.value = true; try { const result: any = await http.get(`/reading/ebook-imports/${row.id}/chapters`); chaptersByImport.value = { ...chaptersByImport.value, [row.id]: Array.isArray(result) ? result : [] }; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "电子书目录加载失败"; } finally { chapterLoading.value = false; } }
async function openChapter(row: EbookImport) { selectedContent.value = null; contentDialog.value = true; contentLoading.value = true; error.value = ""; try { selectedContent.value = await http.get(`/reading/ebook-imports/${row.importId}/chapters/${row.chapterId}/content`) as EbookImport; } catch (e: any) { contentDialog.value = false; error.value = e?.response?.data?.detail || e?.message || "电子书章节加载失败"; } finally { contentLoading.value = false; } }
async function showInfo(row: EbookImport) { selectedInfo.value = null; infoDialog.value = true; infoLoading.value = true; error.value = ""; try { selectedInfo.value = await http.get(`/reading/ebook-imports/${row.id}/info`) as EbookImport; } catch (e: any) { infoDialog.value = false; error.value = e?.response?.data?.detail || e?.message || "书籍信息加载失败"; } finally { infoLoading.value = false; } }
onMounted(load);
</script>
<template>
  <main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">电子书导入</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">导入 EPUB 电子书并创建可阅读的作品版本。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4"/>
    <el-card shadow="never" class="mb-4"><el-form label-position="top" class="max-w-2xl"><el-form-item label="EPUB Attachment ID" required><el-input v-model="form.attachmentId" placeholder="先在附件管理上传 .epub，再粘贴 Attachment ID" clearable/></el-form-item><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><el-form-item label="书名"><el-input v-model="form.title" placeholder="留空使用文件名"/></el-form-item><el-form-item label="语言"><el-input v-model="form.language" placeholder="zh-CN"/></el-form-item></div><el-button type="primary" :loading="submitting" @click="submit">提交 EPUB 导入</el-button></el-form></el-card>
    <el-card shadow="never"><el-empty v-if="!imports.length" description="暂无电子书导入记录"/><el-table v-else :data="imports" stripe><el-table-column prop="sourceAttachmentId" label="源附件" min-width="280"/><el-table-column prop="workId" label="Work ID" min-width="280"/><el-table-column prop="editionId" label="Edition ID" min-width="280"/><el-table-column label="状态" width="130"><template #default="{ row }"><el-tag :type="statusType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="errorMessage" label="错误" min-width="240"/><el-table-column prop="createdAt" label="导入时间" min-width="180"/><el-table-column label="操作" width="300"><template #default="{ row }"><el-button link type="primary" @click="showInfo(row)">书籍信息</el-button><el-button link type="primary" :loading="parsing[row.id]" :disabled="row.status === 'PARSING'" @click="parseToc(row)">{{ row.status === 'FAILED' ? '重试解析目录' : '解析目录' }}</el-button><el-button link type="primary" :disabled="!chaptersByImport[row.id]?.length" @click="showChapters(row)">查看目录</el-button></template></el-table-column></el-table></el-card>
    <el-dialog v-model="chapterDialog" title="电子书目录" width="820px"><el-skeleton v-if="chapterLoading" :rows="5" animated/><el-empty v-else-if="!chaptersByImport[selectedImportId]?.length" description="尚未解析出章节"/><el-table v-else :data="chaptersByImport[selectedImportId]" stripe><el-table-column prop="sortOrder" label="#" width="80"/><el-table-column prop="title" label="章节" min-width="240"/><el-table-column prop="href" label="内容路径" min-width="260"/><el-table-column label="操作" width="110"><template #default="{ row }"><el-button link type="primary" @click="openChapter(row)">打开章节</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="contentDialog" :title="selectedContent?.title || '电子书章节'" width="760px"><el-skeleton v-if="contentLoading" :rows="8" animated/><el-empty v-else-if="!selectedContent?.content" description="章节没有可阅读正文"/><article v-else class="whitespace-pre-wrap leading-8 max-h-[65vh] overflow-auto px-2">{{ selectedContent.content }}</article></el-dialog>
    <el-dialog v-model="infoDialog" title="基础书籍信息" width="560px"><el-skeleton v-if="infoLoading" :rows="6" animated/><el-descriptions v-else-if="selectedInfo" :column="1" border><el-descriptions-item label="书名">{{ selectedInfo.title || "—" }}</el-descriptions-item><el-descriptions-item label="语言">{{ selectedInfo.language || "—" }}</el-descriptions-item><el-descriptions-item label="出版社">{{ selectedInfo.publisher || "—" }}</el-descriptions-item><el-descriptions-item label="来源">{{ selectedInfo.source || "—" }}</el-descriptions-item><el-descriptions-item label="章节数">{{ selectedInfo.chapterCount ?? 0 }}</el-descriptions-item><el-descriptions-item label="导入状态"><el-tag :type="statusType(selectedInfo.importStatus)">{{ selectedInfo.importStatus }}</el-tag></el-descriptions-item><el-descriptions-item v-if="selectedInfo.errorMessage" label="错误">{{ selectedInfo.errorMessage }}</el-descriptions-item></el-descriptions></el-dialog>
  </main>
</template>
