<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const tab = ref("works"); const works = ref<Row[]>([]); const history = ref<Row[]>([]); const loading = ref(false); const error = ref("");
async function load() { loading.value = true; error.value = ""; try { const [w, h] = await Promise.all([http.get<unknown, unknown>("/reading/works"), http.get<unknown, unknown>("/reading/history")]); works.value = Array.isArray(w) ? w as Row[] : []; history.value = Array.isArray(h) ? h as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "阅读数据加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">阅读库</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理作品目录、继续阅读和阅读历史。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="作品目录" name="works"><el-skeleton v-if="loading" :rows="6" animated/><el-empty v-else-if="!works.length" description="暂无阅读作品"/><el-table v-else :data="works" stripe><el-table-column prop="title" label="标题" min-width="240"/><el-table-column prop="status" label="状态" width="130"/><el-table-column prop="author" label="作者" min-width="180"/><el-table-column prop="updatedAt" label="更新时间" min-width="180"/></el-table></el-tab-pane><el-tab-pane label="继续阅读" name="continue"><el-empty v-if="!history.length" description="暂无可继续阅读内容"/><div v-for="item in history.slice(0, 6)" :key="item.id" class="flex justify-between py-3 border-b last:border-0"><div><div class="font-medium">{{ item.title || item.workId || '作品' }}</div><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.position || item.chapterId || '未记录位置' }}</div></div><el-button link>继续</el-button></div></el-tab-pane><el-tab-pane label="阅读历史" name="history"><el-empty v-if="!history.length" description="暂无阅读历史"/><el-table v-else :data="history" stripe><el-table-column prop="workId" label="作品" min-width="220"/><el-table-column prop="chapterId" label="内容位置" min-width="180"/><el-table-column prop="startedAt" label="开始时间" min-width="180"/><el-table-column prop="updatedAt" label="最后位置" min-width="180"/></el-table></el-tab-pane></el-tabs></el-card></main></template>
