/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccessUrlCondition
 */
export interface AccessUrlCondition {
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  name?: any;
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  type?: any;
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  label?: any;
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  required?: any;
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  defaultValue?: any;
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  description?: any;
  /**
   *
   * @type {any}
   * @memberof AccessUrlCondition
   */
  options?: any;
}
