/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AttachmentDriver
 */
export interface AttachmentDriver {
  /**
   *
   * @type {number}
   * @memberof AttachmentDriver
   */
  id?: number;
  /**
   *
   * @type {boolean}
   * @memberof AttachmentDriver
   */
  enable?: boolean;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  type: AttachmentDriverTypeEnum;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof AttachmentDriver
   */
  order?: number;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  comment?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  avatar?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  mount_name?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  remote_path?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  refresh_token?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  access_token?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  expire_time?: string;
  /**
   *
   * @type {number}
   * @memberof AttachmentDriver
   */
  list_page_size?: number;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  root_dir_id?: string;
  /**
   *
   * @type {number}
   * @memberof AttachmentDriver
   */
  request_limit?: number;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  user_id?: string;
  /**
   *
   * @type {string}
   * @memberof AttachmentDriver
   */
  user_name?: string;
  /**
   *
   * @type {number}
   * @memberof AttachmentDriver
   */
  space_total?: number;
  /**
   *
   * @type {number}
   * @memberof AttachmentDriver
   */
  space_use?: number;
}

export const AttachmentDriverTypeEnum = {
  Local: "LOCAL",
  Webdav: "WEBDAV",
  Pan115: "PAN115",
  Custom: "CUSTOM",
} as const;

export type AttachmentDriverTypeEnum =
  (typeof AttachmentDriverTypeEnum)[keyof typeof AttachmentDriverTypeEnum];
