/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Attachment
 */
export interface Attachment {
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  id?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  parentId?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  type?: AttachmentTypeEnum;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  url?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  path?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  fsPath?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  name?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  size?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  updateTime?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  deleted?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  driverId?: any;
  /**
   *
   * @type {any}
   * @memberof Attachment
   */
  sha1?: any;
}

export const AttachmentTypeEnum = {
  File: "File",
  Directory: "Directory",
  DriverFile: "Driver_File",
  DriverDirectory: "Driver_Directory",
} as const;

export type AttachmentTypeEnum =
  (typeof AttachmentTypeEnum)[keyof typeof AttachmentTypeEnum];
