/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Author
 */
export interface Author {
	/**
	 *
	 * @type {string}
	 * @memberof Author
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Author
	 */
	website?: string;
}
