/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Episode } from "./episode";

/**
 *
 * @export
 * @interface EpisodeRecord
 */
export interface EpisodeRecord {
  /**
   *
   * @type {Episode}
   * @memberof EpisodeRecord
   */
  episode?: Episode;
  /**
   *
   * @type {any}
   * @memberof EpisodeRecord
   */
  resources?: any;
}
