/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FileHint
 */
export interface FileHint {
	/**
	 *
	 * @type {number}
	 * @memberof FileHint
	 */
	id?: number;
	/**
	 *
	 * @type {string}
	 * @memberof FileHint
	 */
	name?: string;
	/**
	 *
	 * @type {string}
	 * @memberof FileHint
	 */
	originalPath?: string;
	/**
	 *
	 * @type {string}
	 * @memberof FileHint
	 */
	url?: string;
	/**
	 *
	 * @type {string}
	 * @memberof FileHint
	 */
	type?: FileHintTypeEnum;
	/**
	 *
	 * @type {string}
	 * @memberof FileHint
	 */
	originalName?: string;
}

export const FileHintTypeEnum = {
	Image: 'IMAGE',
	Video: 'VIDEO',
	Document: 'DOCUMENT',
	Voice: 'VOICE',
	Unknown: 'UNKNOWN',
} as const;

export type FileHintTypeEnum =
	(typeof FileHintTypeEnum)[keyof typeof FileHintTypeEnum];
