/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MediaTrack
 */
export interface MediaTrack {
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  url?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  index?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  kind?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  language?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  title?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  codec?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  playable?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  attachment_id?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  default_track?: any;
  /**
   *
   * @type {any}
   * @memberof MediaTrack
   */
  failure_reason?: any;
}
