/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TotpValidateParam
 */
export interface TotpValidateParam {
  /**
   * 临时令牌(来自applyJwtToken返回)
   * @type {any}
   * @memberof TotpValidateParam
   */
  tempToken?: any;
  /**
   * TOTP验证码(6位数字)
   * @type {any}
   * @memberof TotpValidateParam
   */
  code?: any;
}
