/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  avatar?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  nickname?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  introduce?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  site?: string;
  /**
   *
   * @type {boolean}
   * @memberof UpdateUserRequest
   */
  enable?: boolean;
}
