/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VideoSubtitle
 */
export interface VideoSubtitle {
  /**
   *
   * @type {string}
   * @memberof VideoSubtitle
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof VideoSubtitle
   */
  url?: string;
  /**
   *
   * @type {number}
   * @memberof VideoSubtitle
   */
  master_attachment_id?: number;
  /**
   *
   * @type {number}
   * @memberof VideoSubtitle
   */
  attachment_id?: number;
}
