<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Item = { type?: string; id: string; sourceId?: string; title: string; startAt: string; endAt: string; timeZone?: string };
const date = ref(new Date()); const view = ref("day"); const items = ref<Item[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const form = ref({ title: "", startAt: "", endAt: "", kind: "FOCUS", timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone });
const dayText = computed(() => date.value.toLocaleDateString("zh-CN", { year: "numeric", month: "long", day: "numeric", weekday: "long" }));
function bounds() { const start = new Date(date.value); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + (view.value === "week" ? 7 : 1)); return { from: start.toISOString(), to: end.toISOString() }; }
async function load() { loading.value = true; error.value = ""; try { const b = bounds(); const result = await http.get<unknown, unknown>("/planning/calendar", { params: b }); items.value = Array.isArray(result) ? result as Item[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "日历加载失败"; } finally { loading.value = false; } }
function shift(amount: number) { const next = new Date(date.value); next.setDate(next.getDate() + amount * (view.value === "week" ? 7 : 1)); date.value = next; load(); }
async function createBlock() { if (!form.value.title.trim() || !form.value.startAt || !form.value.endAt || new Date(form.value.endAt) <= new Date(form.value.startAt)) { error.value = "请填写标题，并确保结束时间晚于开始时间"; return; } saving.value = true; try { await http.post("/planning/time-blocks", { data: { ...form.value, title: form.value.title.trim(), startAt: new Date(form.value.startAt).toISOString(), endAt: new Date(form.value.endAt).toISOString() } }); dialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "时间块创建失败"; } finally { saving.value = false; } }
function resetToday() { date.value = new Date(); load(); }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex flex-wrap justify-between items-center gap-3 mb-6"><div><h1 class="text-2xl font-semibold">日历与时间块</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">安排任务时间，识别冲突并保持计划节奏。</p></div><div class="flex items-center gap-2"><el-button @click="resetToday">今天</el-button><el-button circle @click="shift(-1)">‹</el-button><el-button circle @click="shift(1)">›</el-button><el-segmented v-model="view" :options="[{label:'日',value:'day'},{label:'周',value:'week'},{label:'月',value:'month'}]" @change="load"/><el-button type="primary" @click="dialog = true">新建时间块</el-button></div></div><div class="text-lg font-medium mb-4">{{ dayText }}</div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="9" animated/><el-card v-else shadow="never"><el-empty v-if="!items.length" description="当前日期没有计划事项"/><div v-for="item in items" :key="item.id" class="flex gap-4 p-4 border-b last:border-0"><div class="w-28 text-sm text-[var(--el-text-color-secondary)]">{{ new Date(item.startAt).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'}) }} – {{ new Date(item.endAt).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'}) }}</div><div class="flex-1"><div class="font-medium">{{ item.title }}</div><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">{{ item.type || '时间块' }} · {{ item.timeZone || '本地时区' }}</div></div></div></el-card><el-dialog v-model="dialog" title="新建时间块" width="520px"><el-form label-position="top"><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item><el-form-item label="开始时间" required><el-date-picker v-model="form.startAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" class="w-full"/></el-form-item><el-form-item label="结束时间" required><el-date-picker v-model="form.endAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" class="w-full"/></el-form-item><el-form-item label="类型"><el-input v-model="form.kind" placeholder="FOCUS"/></el-form-item><el-form-item label="时区"><el-input v-model="form.timeZone"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="createBlock">创建</el-button></template></el-dialog></main></template>
