<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Habit = { id: string; name: string; schedule?: string; status?: string; targetValue?: number; timeZone?: string };
type Session = { id: string; taskId?: string; mode?: string; status?: string; plannedMinutes?: number; actualMinutes?: number; startedAt?: string; endedAt?: string; note?: string; version?: number };
type Review = { id: string; period?: string; periodStart?: string; periodEnd?: string; note?: string; wins?: string; challenges?: string; nextFocus?: string };
const tab = ref("habits"); const habits = ref<Habit[]>([]); const sessions = ref<Session[]>([]); const reviews = ref<Review[]>([]); const loading = ref(false); const error = ref(""); const dialog = ref(false); const form = ref({ name: "", schedule: "DAILY", timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone });
async function load() { loading.value = true; error.value = ""; try { const [h, s, r] = await Promise.all([http.get<unknown, unknown>("/planning/habits"), http.get<unknown, unknown>("/planning/focus-sessions"), http.get<unknown, unknown>("/planning/reviews")]); habits.value = Array.isArray(h) ? h as Habit[] : []; sessions.value = Array.isArray(s) ? s as Session[] : []; reviews.value = Array.isArray(r) ? r as Review[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "计划数据加载失败"; } finally { loading.value = false; } }
async function createHabit() { if (!form.value.name.trim()) { error.value = "习惯名称不能为空"; return; } try { await http.post("/planning/habits", { data: { ...form.value, name: form.value.name.trim(), metric: "COMPLETION" } }); dialog.value = false; form.value = { name: "", schedule: "DAILY", timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "习惯创建失败"; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">习惯、专注与复盘</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">保持规律，记录专注投入，并回顾周期成果。</p></div><div class="flex gap-2"><el-button v-if="tab === 'habits'" @click="dialog = true">新建习惯</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-tabs v-model="tab"><el-tab-pane label="习惯" name="habits"/><el-tab-pane label="专注记录" name="sessions"/><el-tab-pane label="复盘" name="reviews"/></el-tabs><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else shadow="never" class="mt-4"><template v-if="tab === 'habits'"><el-empty v-if="!habits.length" description="暂无习惯"/><el-table v-else :data="habits" stripe><el-table-column prop="name" label="习惯名称" min-width="220"/><el-table-column prop="schedule" label="频率" width="140"/><el-table-column label="今天状态" width="130">未完成</el-table-column><el-table-column prop="targetValue" label="目标次数" width="110"/><el-table-column prop="timeZone" label="时区" min-width="180"/></el-table></template><template v-else-if="tab === 'sessions'"><el-empty v-if="!sessions.length" description="暂无专注记录"/><el-table v-else :data="sessions" stripe><el-table-column prop="taskId" label="关联任务" min-width="220"/><el-table-column prop="mode" label="模式" width="120"/><el-table-column prop="plannedMinutes" label="计划时长" width="110"/><el-table-column prop="actualMinutes" label="实际时长" width="110"/><el-table-column prop="startedAt" label="开始" min-width="180"/><el-table-column prop="status" label="结果" width="120"/></el-table></template><template v-else><el-empty v-if="!reviews.length" description="暂无复盘记录"/><el-table v-else :data="reviews" stripe><el-table-column prop="period" label="周期" width="120"/><el-table-column prop="periodStart" label="开始" width="170"/><el-table-column prop="periodEnd" label="结束" width="170"/><el-table-column prop="wins" label="成果" min-width="220"/><el-table-column prop="nextFocus" label="下一周期重点" min-width="220"/></el-table></template></el-card><el-dialog v-model="dialog" title="新建习惯" width="460px"><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="频率"><el-select v-model="form.schedule" class="w-full"><el-option label="每天" value="DAILY"/><el-option label="每周" value="WEEKLY"/></el-select></el-form-item><el-form-item label="时区"><el-input v-model="form.timeZone"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="createHabit">创建</el-button></template></el-dialog></main></template>
