<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Goal = { id: string; title: string; description?: string; type?: string; status?: string; progress?: number; startAt?: string; deadline?: string; ownerId?: string };
const activeTab = ref("goals"); const items = ref<Goal[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const form = ref({ title: "", description: "", type: "PERSONAL", startAt: "", deadline: "" });
const visible = computed(() => activeTab.value === "archived" ? items.value.filter(item => String(item.status).toUpperCase() === "ARCHIVED" || String(item.status).toUpperCase() === "COMPLETED") : items.value.filter(item => String(item.status).toUpperCase() !== "ARCHIVED" && String(item.status).toUpperCase() !== "COMPLETED"));
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/planning/goals"); items.value = Array.isArray(result) ? result as Goal[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "目标加载失败"; } finally { loading.value = false; } }
async function createGoal() { if (!form.value.title.trim()) { error.value = "目标标题不能为空"; return; } saving.value = true; try { await http.post("/planning/goals", { data: { ...form.value, title: form.value.title.trim(), startAt: form.value.startAt ? new Date(form.value.startAt).toISOString() : null, deadline: form.value.deadline ? new Date(form.value.deadline).toISOString() : null } }); dialog.value = false; form.value = { title: "", description: "", type: "PERSONAL", startAt: "", deadline: "" }; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "目标创建失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">目标与 OKR</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">定义周期目标，持续追踪进度和信心状态。</p></div><div class="flex gap-2"><el-button @click="dialog = true">新建目标</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-tabs v-model="activeTab"><el-tab-pane label="目标" name="goals"/><el-tab-pane label="OKR" name="okr"/><el-tab-pane label="归档" name="archived"/></el-tabs><template v-if="activeTab === 'okr'"><el-card shadow="never" class="mt-4"><el-empty description="暂无 Key Result；创建目标后可在详情中维护衡量结果"/></el-card></template><template v-else><el-skeleton v-if="loading" :rows="8" animated/><div v-else class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 mt-4"><el-empty v-if="!visible.length" class="col-span-full" :description="activeTab === 'archived' ? '暂无归档目标' : '暂无目标，先创建一个吧'"/><el-card v-for="goal in visible" :key="goal.id" shadow="never"><div class="flex justify-between gap-3"><div class="font-medium truncate">{{ goal.title }}</div><el-tag size="small">{{ goal.status || 'ACTIVE' }}</el-tag></div><p class="text-sm text-[var(--el-text-color-secondary)] mt-3 line-clamp-2">{{ goal.description || '暂无描述' }}</p><div class="flex justify-between text-xs mt-5 mb-2"><span>{{ goal.type || '目标' }}</span><span>{{ Math.round((goal.progress || 0) * 100) }}%</span></div><el-progress :percentage="Math.round((goal.progress || 0) * 100)" :show-text="false"/><div class="text-xs text-[var(--el-text-color-secondary)] mt-3">{{ goal.startAt ? new Date(goal.startAt).toLocaleDateString() : '未设置开始日期' }} → {{ goal.deadline ? new Date(goal.deadline).toLocaleDateString() : '未设置目标日期' }}</div></el-card></div></template><el-dialog v-model="dialog" title="新建目标" width="520px"><el-form label-position="top"><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item><el-form-item label="类型"><el-input v-model="form.type" placeholder="PERSONAL / OKR"/></el-form-item><el-form-item label="开始日期"><el-date-picker v-model="form.startAt" type="date" value-format="YYYY-MM-DD" class="w-full"/></el-form-item><el-form-item label="目标日期"><el-date-picker v-model="form.deadline" type="date" value-format="YYYY-MM-DD" class="w-full"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="createGoal">创建</el-button></template></el-dialog></main></template>
