<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { http } from "@/utils/http";
const route = useRoute(); const data = ref<Record<string, any> | null>(null); const loading = ref(false); const actionLoading = ref(false); const error = ref(""); const resourceId = ref("");
async function load() { loading.value = true; error.value = ""; try { data.value = await http.get(`/attachments/${route.params.attachmentId}`); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "附件详情加载失败"; } finally { loading.value = false; } }
async function content(download: boolean) { actionLoading.value = true; try { const blob = await http.get<Blob, unknown>(`/attachments/${route.params.attachmentId}/content`, { responseType: "blob" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.target = download ? "_self" : "_blank"; if (download) { link.download = data.value?.fileName || "attachment"; } link.click(); URL.revokeObjectURL(url); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "附件内容读取失败"; } finally { actionLoading.value = false; } }
async function archive() { if (!resourceId.value.trim()) { error.value = "归档前请输入 Resource ID"; return; } actionLoading.value = true; try { await http.post(`/attachments/${route.params.attachmentId}/archive?resourceId=${encodeURIComponent(resourceId.value.trim())}`); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "附件归档失败"; } finally { actionLoading.value = false; } }
async function removeRelation() { if (!resourceId.value.trim()) { error.value = "移除附件关系前请输入 Resource ID"; return; } if (!window.confirm("确认移除该 Resource 的 Attachment 关系吗？此操作不会直接删除 Blob。")) return; actionLoading.value = true; try { await http.request("delete", `/resources/${resourceId.value.trim()}/attachments/${route.params.attachmentId}`); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "附件关系移除失败"; } finally { actionLoading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex flex-wrap justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">{{ data?.fileName || '附件详情' }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">Attachment {{ route.params.attachmentId }}</p></div><div class="flex flex-wrap gap-2"><el-button @click="$router.back()">返回</el-button><el-button :loading="loading" @click="load">刷新</el-button><el-button :loading="actionLoading" @click="content(false)">预览/打开</el-button><el-button :loading="actionLoading" @click="content(true)">下载</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"/><el-skeleton v-if="loading" :rows="8" animated/><template v-else-if="data"><el-card shadow="never" class="mt-4"><template #header><span class="font-medium">概览</span></template><el-descriptions :column="1" border><el-descriptions-item label="Attachment ID">{{ data.id }}</el-descriptions-item><el-descriptions-item label="文件名">{{ data.fileName }}</el-descriptions-item><el-descriptions-item label="角色">{{ data.kind }}</el-descriptions-item><el-descriptions-item label="MIME">{{ data.mediaType || '-' }}</el-descriptions-item><el-descriptions-item label="大小">{{ data.sizeBytes }} Bytes</el-descriptions-item><el-descriptions-item label="Blob ID">{{ data.blobId || '-' }}</el-descriptions-item><el-descriptions-item label="SHA-256">{{ data.sha256 || '-' }}</el-descriptions-item><el-descriptions-item label="可用性"><el-tag :type="String(data.availability).toUpperCase() === 'AVAILABLE' ? 'success' : 'danger'">{{ data.availability || '未知' }}</el-tag></el-descriptions-item></el-descriptions></el-card><el-card shadow="never" class="mt-4"><template #header><span class="font-medium">Resource 关系操作</span></template><p class="text-sm text-[var(--el-text-color-secondary)] mb-3">归档和移除关系需要 Resource ID。移除 Attachment 关系不会直接删除 Blob。</p><div class="flex flex-wrap gap-2"><el-input v-model="resourceId" placeholder="Resource ID" clearable /><el-button :loading="actionLoading" @click="archive">归档附件</el-button><el-button type="danger" plain :loading="actionLoading" @click="removeRelation">移除附件关系</el-button></div></el-card></template><el-empty v-else description="暂无附件数据"/></main></template>
