<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Ledger = { id: string; name: string; baseCurrency?: string }; type Account = { id: string; name: string; type?: string; currency?: string; currentBalance?: number; maskedIdentifier?: string; archived?: boolean; institution?: string };
const ledgers = ref<Ledger[]>([]); const selected = ref<Ledger | null>(null); const accounts = ref<Account[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const hidden = ref(false); const form = ref({ name: "", type: "BANK", currency: "CNY", openingBalance: "", institution: "", maskedIdentifier: "" });
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/finance/ledgers"); ledgers.value = Array.isArray(result) ? result as Ledger[] : []; selected.value = selected.value || ledgers.value[0] || null; if (selected.value) { const rows = await http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/accounts`); accounts.value = Array.isArray(rows) ? rows as Account[] : []; } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "账户加载失败"; } finally { loading.value = false; } }
async function choose(value: Ledger) { selected.value = value; await load(); }
async function createAccount() { if (!selected.value || !form.value.name.trim()) { error.value = "请选择账本并填写账户名称"; return; } saving.value = true; try { await http.post(`/finance/ledgers/${selected.value.id}/accounts`, { data: { ...form.value, name: form.value.name.trim(), openingBalance: form.value.openingBalance ? Number(form.value.openingBalance) : null } }); dialog.value = false; form.value = { name: "", type: "BANK", currency: "CNY", openingBalance: "", institution: "", maskedIdentifier: "" }; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "账户创建失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">账户</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理账户余额、币种和对账状态。</p></div><div class="flex gap-2"><el-select v-model="selected" value-key="id" placeholder="选择账本" @change="choose"><el-option v-for="item in ledgers" :key="item.id" :label="item.name" :value="item"/></el-select><el-button :disabled="!selected" @click="dialog = true">添加账户</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else shadow="never"><el-empty v-if="!selected || !accounts.length" description="暂无账户"/><el-table v-else :data="accounts" stripe><el-table-column prop="name" label="账户名称" min-width="200"/><el-table-column prop="type" label="类型" width="150"/><el-table-column prop="maskedIdentifier" label="账户标识" width="150"/><el-table-column prop="currency" label="币种" width="100"/><el-table-column label="当前余额" width="160"><template #default="{ row }">{{ hidden ? '••••' : `${row.currentBalance ?? 0} ${row.currency || ''}` }}</template></el-table-column><el-table-column prop="institution" label="金融机构" min-width="160"/><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.archived ? 'info' : 'success'">{{ row.archived ? '已归档' : '正常' }}</el-tag></template></el-table-column></el-table><el-button v-if="accounts.length" link class="mt-3" @click="hidden = !hidden">{{ hidden ? '显示金额' : '隐藏金额' }}</el-button></el-card><el-drawer v-model="dialog" title="添加账户" size="480px"><el-form label-position="top"><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="账户类型" required><el-select v-model="form.type" class="w-full"><el-option label="银行账户" value="BANK"/><el-option label="现金" value="CASH"/><el-option label="电子钱包" value="WALLET"/><el-option label="信用账户" value="CREDIT"/><el-option label="投资/其他" value="OTHER"/></el-select></el-form-item><el-form-item label="币种" required><el-input v-model="form.currency"/></el-form-item><el-form-item label="初始余额"><el-input v-model="form.openingBalance" type="number"/></el-form-item><el-form-item label="金融机构"><el-input v-model="form.institution"/></el-form-item><el-form-item label="遮罩标识"><el-input v-model="form.maskedIdentifier"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="createAccount">创建</el-button></template></el-drawer></main></template>
