<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Ledger = { id: string; name: string }; type Category = { id: string; name: string }; type Budget = { id: string; categoryId?: string; month?: string; budget?: number; actual?: number; remaining?: number };
const tab = ref("budgets"); const ledgers = ref<Ledger[]>([]); const categories = ref<Category[]>([]); const selected = ref<Ledger | null>(null); const month = ref(new Date().toISOString().slice(0, 7)); const rows = ref<Budget[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const form = ref({ categoryId: "", amount: "" });
async function load() { loading.value = true; error.value = ""; try { const l = await http.get<unknown, unknown>("/finance/ledgers"); ledgers.value = Array.isArray(l) ? l as Ledger[] : []; selected.value = selected.value || ledgers.value[0] || null; if (selected.value) { const [b, c] = await Promise.all([http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/budgets`, { params: { month: `${month.value}-01` } }), http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/categories`)]); rows.value = Array.isArray(b) ? b as Budget[] : []; categories.value = Array.isArray(c) ? c as Category[] : []; } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "预算加载失败"; } finally { loading.value = false; } }
async function saveBudget() { if (!selected.value || !form.value.categoryId || !form.value.amount) { error.value = "请选择分类并填写预算金额"; return; } saving.value = true; try { await http.request("put", `/finance/ledgers/${selected.value.id}/budgets`, { data: { categoryId: form.value.categoryId, month: `${month.value}-01`, amount: Number(form.value.amount) } }); dialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "预算保存失败"; } finally { saving.value = false; } }
function categoryName(id?: string) { return categories.value.find(item => item.id === id)?.name || id || "未分类"; }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">预算与周期账</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">按周期规划支出，并观察实际执行进度。</p></div><div class="flex gap-2"><el-select v-model="selected" value-key="id" placeholder="选择账本" @change="load"><el-option v-for="item in ledgers" :key="item.id" :label="item.name" :value="item"/></el-select><el-button v-if="tab === 'budgets'" :disabled="!selected" type="primary" @click="dialog = true">新增预算</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-tabs v-model="tab"><el-tab-pane label="预算" name="budgets"/><el-tab-pane label="周期账" name="scheduled"/></el-tabs><div class="flex items-center gap-3 my-4"><span>预算周期</span><el-date-picker v-model="month" type="month" value-format="YYYY-MM" @change="load"/></div><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else shadow="never"><template v-if="tab === 'budgets'"><el-empty v-if="!rows.length" description="当前周期暂无预算"/><el-table v-else :data="rows" stripe><el-table-column label="分类/分组" min-width="220"><template #default="{ row }">{{ categoryName(row.categoryId) }}</template></el-table-column><el-table-column prop="budget" label="预算金额" width="150"/><el-table-column prop="actual" label="实际金额" width="150"/><el-table-column prop="remaining" label="剩余" width="150"/><el-table-column label="使用率" width="180"><template #default="{ row }"><el-progress :percentage="Math.min(100, Math.round(Number(row.actual || 0) / Math.max(1, Number(row.budget || 0)) * 100))"/></template></el-table-column><el-table-column label="预测" min-width="130">—</el-table-column></el-table></template><template v-else><el-empty description="暂无周期账规则"/></template></el-card><el-dialog v-model="dialog" title="新增预算" width="460px"><el-form label-position="top"><el-form-item label="分类" required><el-select v-model="form.categoryId" class="w-full"><el-option v-for="item in categories" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="金额" required><el-input v-model="form.amount" type="number"/></el-form-item><el-form-item label="周期">{{ month }}</el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveBudget">保存</el-button></template></el-dialog></main></template>
