<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Ledger = { id: string; name: string }; type Account = { id: string; name: string; currency?: string }; type Reconcile = { id: string; accountId?: string; statementDate?: string; statementBalance?: number; calculatedBalance?: number; difference?: number; status?: string; note?: string };
const tab = ref("reconcile"); const ledgers = ref<Ledger[]>([]); const accounts = ref<Account[]>([]); const rows = ref<Reconcile[]>([]); const selected = ref<Ledger | null>(null); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const form = ref({ accountId: "", statementDate: "", statementBalance: "", note: "" });
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/finance/ledgers"); ledgers.value = Array.isArray(result) ? result as Ledger[] : []; selected.value = selected.value || ledgers.value[0] || null; if (selected.value) { const [a, r] = await Promise.all([http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/accounts`), http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/reconciliations`)]); accounts.value = Array.isArray(a) ? a as Account[] : []; rows.value = Array.isArray(r) ? r as Reconcile[] : []; form.value.accountId = form.value.accountId || accounts.value[0]?.id || ""; } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "对账数据加载失败"; } finally { loading.value = false; } }
async function create() { if (!selected.value || !form.value.accountId || !form.value.statementDate || !form.value.statementBalance) { error.value = "请填写账户、结算日期和结算余额"; return; } saving.value = true; try { await http.post(`/finance/ledgers/${selected.value.id}/reconciliations`, { data: { ...form.value, statementBalance: Number(form.value.statementBalance) } }); dialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "对账创建失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">对账与导入</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">核对账户结算余额与系统交易，差异必须显式处理。</p></div><div class="flex gap-2"><el-select v-model="selected" value-key="id" placeholder="选择账本" @change="load"><el-option v-for="item in ledgers" :key="item.id" :label="item.name" :value="item"/></el-select><el-button v-if="tab === 'reconcile'" :disabled="!selected" type="primary" @click="dialog = true">开始对账</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-tabs v-model="tab"><el-tab-pane label="对账" name="reconcile"/><el-tab-pane label="导入批次" name="imports"/></el-tabs><el-skeleton v-if="loading" :rows="8" animated/><el-card v-else shadow="never" class="mt-4"><template v-if="tab === 'reconcile'"><el-empty v-if="!rows.length" description="暂无对账记录"/><el-table v-else :data="rows" stripe><el-table-column prop="statementDate" label="结算日期" width="150"/><el-table-column prop="accountId" label="账户" min-width="220"/><el-table-column prop="statementBalance" label="结算余额" width="150"/><el-table-column prop="calculatedBalance" label="计算余额" width="150"/><el-table-column label="差额" width="140"><template #default="{ row }"><el-tag :type="Number(row.difference || 0) === 0 ? 'success' : 'danger'">{{ row.difference ?? 0 }}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="130"/></el-table></template><template v-else><el-empty description="暂无导入批次；导入功能将在选择账本后接入 CSV 向导"/></template></el-card><el-dialog v-model="dialog" title="开始对账" width="480px"><el-form label-position="top"><el-form-item label="账户" required><el-select v-model="form.accountId" class="w-full"><el-option v-for="account in accounts" :key="account.id" :label="account.name" :value="account.id"/></el-select></el-form-item><el-form-item label="Statement Ending Date" required><el-date-picker v-model="form.statementDate" type="date" value-format="YYYY-MM-DD" class="w-full"/></el-form-item><el-form-item label="Statement Ending Balance" required><el-input v-model="form.statementBalance" type="number"/></el-form-item><el-form-item label="备注"><el-input v-model="form.note" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建对账</el-button></template></el-dialog></main></template>
