<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Ledger = { id: string; name: string; baseCurrency?: string }; type Account = { id: string; name: string; currency?: string }; type Transaction = { id: string; type?: string; accountId?: string; amount?: number; currency?: string; occurredAt?: string; payee?: string; note?: string; status?: string; source?: string };
const ledgers = ref<Ledger[]>([]); const accounts = ref<Account[]>([]); const selected = ref<Ledger | null>(null); const rows = ref<Transaction[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const dialog = ref(false); const query = ref(""); const form = ref({ type: "EXPENSE", accountId: "", amount: "", currency: "CNY", payee: "", note: "", occurredAt: "" });
const filtered = computed(() => { const q = query.value.trim().toLowerCase(); return q ? rows.value.filter(row => [row.payee, row.note, row.type, row.source].some(value => String(value || "").toLowerCase().includes(q))) : rows.value; });
async function load() { loading.value = true; error.value = ""; try { const led = await http.get<unknown, unknown>("/finance/ledgers"); ledgers.value = Array.isArray(led) ? led as Ledger[] : []; selected.value = selected.value || ledgers.value[0] || null; if (selected.value) { const [a, t] = await Promise.all([http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/accounts`), http.get<unknown, unknown>(`/finance/ledgers/${selected.value.id}/transactions`)]); accounts.value = Array.isArray(a) ? a as Account[] : []; rows.value = Array.isArray(t) ? t as Transaction[] : []; form.value.accountId = form.value.accountId || accounts.value[0]?.id || ""; } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "交易加载失败"; } finally { loading.value = false; } }
async function createTransaction() { if (!selected.value || !form.value.accountId || !form.value.amount || !form.value.occurredAt) { error.value = "请选择账户并填写金额、时间"; return; } saving.value = true; try { await http.post(`/finance/ledgers/${selected.value.id}/transactions`, { data: { ...form.value, amount: Number(form.value.amount), occurredAt: new Date(form.value.occurredAt).toISOString(), currency: form.value.currency || selected.value.baseCurrency } }); dialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "交易创建失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start gap-4 mb-6"><div><h1 class="text-2xl font-semibold">交易记录</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">按当前账本查看收支、转账和对账状态。</p></div><div class="flex gap-2"><el-select v-model="selected" value-key="id" placeholder="选择账本" @change="load"><el-option v-for="item in ledgers" :key="item.id" :label="item.name" :value="item"/></el-select><el-button :disabled="!selected" type="primary" @click="dialog = true">新增交易</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><div class="flex gap-3 mb-4"><el-input v-model="query" clearable placeholder="搜索收付款方、备注、类型或来源" class="max-w-md"/><el-button>筛选</el-button><el-button>导入</el-button></div><el-skeleton v-if="loading" :rows="9" animated/><el-card v-else shadow="never"><el-empty v-if="!selected || !filtered.length" description="暂无交易"/><el-table v-else :data="filtered" stripe><el-table-column prop="occurredAt" label="日期/时间" min-width="180"/><el-table-column prop="type" label="交易类型" width="120"/><el-table-column prop="accountId" label="账户" min-width="220"/><el-table-column prop="payee" label="收付款方" min-width="160"/><el-table-column prop="note" label="备注" min-width="180"/><el-table-column label="金额" width="150"><template #default="{ row }"><span :class="row.type === 'INCOME' ? 'text-green-600' : 'text-red-600'">{{ row.type === 'INCOME' ? '+' : '-' }}{{ row.amount ?? 0 }} {{ row.currency || selected.baseCurrency || '' }}</span></template></el-table-column><el-table-column prop="source" label="来源" width="120"/><el-table-column prop="status" label="对账状态" width="130"/></el-table></el-card><el-dialog v-model="dialog" title="新增交易" width="520px"><el-form label-position="top"><el-form-item label="类型" required><el-select v-model="form.type" class="w-full"><el-option label="支出" value="EXPENSE"/><el-option label="收入" value="INCOME"/><el-option label="转账" value="TRANSFER"/></el-select></el-form-item><el-form-item label="账户" required><el-select v-model="form.accountId" class="w-full"><el-option v-for="account in accounts" :key="account.id" :label="account.name" :value="account.id"/></el-select></el-form-item><el-form-item label="金额" required><el-input v-model="form.amount" type="number"/></el-form-item><el-form-item label="日期/时间" required><el-date-picker v-model="form.occurredAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" class="w-full"/></el-form-item><el-form-item label="收付款方"><el-input v-model="form.payee"/></el-form-item><el-form-item label="备注"><el-input v-model="form.note" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="createTransaction">创建</el-button></template></el-dialog></main></template>
