<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const bindings = ref<Row[]>([]); const files = ref<Row[]>([]); const selectedBindingId = ref(""); const sourceItemId = ref(""); const state = ref("DISCOVERED"); const contentFingerprint = ref(""); const loading = ref(false); const saving = ref(false); const error = ref(""); const message = ref("");
async function loadBindings() { try { const result = await http.get<unknown, unknown>("/drive/bindings"); bindings.value = Array.isArray(result) ? (result as Row[]).filter(item => item.mode === "BACKUP") : []; if (!selectedBindingId.value && bindings.value[0]?.id) selectedBindingId.value = String(bindings.value[0].id); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "备份配置加载失败"; } }
async function loadFiles() { if (!selectedBindingId.value) { files.value = []; return; } loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>(`/drive/bindings/${selectedBindingId.value}/camera-backups`); files.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "备份检测结果加载失败"; } finally { loading.value = false; } }
async function refreshBinding() { await loadBindings(); await loadFiles(); }
async function recordFile() { if (!selectedBindingId.value || !sourceItemId.value.trim()) { error.value = "请选择备份配置并填写本地文件标识"; return; } saving.value = true; error.value = ""; message.value = ""; try { await http.request("put", `/drive/bindings/${selectedBindingId.value}/camera-backups`, { data: { sourceItemId: sourceItemId.value.trim(), state: state.value, contentFingerprint: contentFingerprint.value.trim() || undefined } }); sourceItemId.value = ""; contentFingerprint.value = ""; message.value = "文件检测结果已保存"; await loadFiles(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文件检测结果保存失败"; } finally { saving.value = false; } }
onMounted(async () => { await loadBindings(); await loadFiles(); });
</script>
<template>
  <main class="p-4 md:p-6"><div class="flex items-start justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">备份文件检测</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">查看并登记设备上报的新增或修改文件，后续由备份流程处理。</p></div><el-button :loading="loading" @click="refreshBinding">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" /><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4" /><el-card shadow="never" class="mb-4"><template #header><span>登记检测结果</span></template><div class="flex flex-wrap gap-3 items-end"><el-form-item label="备份配置" required><el-select v-model="selectedBindingId" class="w-96" @change="loadFiles"><el-option v-for="binding in bindings" :key="binding.id" :label="`${binding.localDisplayPath || binding.localScopeId} → ${binding.driveSpaceId}`" :value="binding.id" /></el-select></el-form-item><el-form-item label="本地文件标识" required><el-input v-model="sourceItemId" class="w-72" placeholder="客户端稳定 source item ID" clearable /></el-form-item><el-form-item label="检测状态"><el-select v-model="state" class="w-52"><el-option label="新增（已发现）" value="DISCOVERED" /><el-option label="等待备份" value="QUEUED" /><el-option label="来源不可用" value="SOURCE_UNAVAILABLE" /><el-option label="忽略" value="IGNORED" /></el-select></el-form-item><el-form-item label="内容指纹"><el-input v-model="contentFingerprint" class="w-72" placeholder="可选，用于识别修改" clearable /></el-form-item><el-button type="primary" :loading="saving" @click="recordFile">保存检测结果</el-button></div></el-card><el-card shadow="never"><template #header><span>已检测文件</span></template><el-skeleton v-if="loading" :rows="5" animated /><el-empty v-else-if="!files.length" description="暂无检测记录" /><el-table v-else :data="files" stripe><el-table-column prop="sourceItemId" label="本地文件标识" min-width="260" /><el-table-column prop="state" label="状态" width="190" /><el-table-column prop="contentFingerprint" label="内容指纹" min-width="220" /><el-table-column prop="remoteNodeId" label="远端节点" min-width="220" /><el-table-column prop="updatedAt" label="更新时间" min-width="190" /></el-table></el-card></main>
</template>
