<script setup lang="ts">
import { onMounted, ref, computed } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, unknown>;
const spaces = ref<Row[]>([]); const nodes = ref<Row[]>([]); const selected = ref<Row | null>(null); const loading = ref(false); const nodeLoading = ref(false); const error = ref(""); const nodePage = ref(0); const nodePageSize = ref(20); const nodeTotal = ref(0);
const folderName = ref(""); const folderSaving = ref(false);
const renameDialog = ref(false); const renameSaving = ref(false); const renameNode = ref<Row | null>(null); const renameName = ref("");
const moveDialog = ref(false); const moveSaving = ref(false); const moveNode = ref<Row | null>(null); const moveParentId = ref("");
const used = computed(() => Number(selected.value?.usedBytes || 0)); const quota = computed(() => Number(selected.value?.quotaBytes || 0)); const percent = computed(() => quota.value ? Math.min(100, Math.round(used.value / quota.value * 100)) : 0);
async function loadSpaces() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/drive/spaces"); spaces.value = Array.isArray(result) ? result as Row[] : []; if (spaces.value.length) await selectSpace(spaces.value[0]); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "云盘空间加载失败"; } finally { loading.value = false; } }
async function selectSpace(space: Row, page = 0) { selected.value = space; nodePage.value = page; nodeLoading.value = true; try { const result: any = await http.get(`/drive/spaces/${space.id}/children/page`, { params: { page, size: nodePageSize.value } }); nodes.value = Array.isArray(result?.items) ? result.items : []; nodeTotal.value = Number(result?.total || 0); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文件列表加载失败"; } finally { nodeLoading.value = false; } }
async function createFolder() { if (!selected.value?.id || !folderName.value.trim()) { error.value = "请选择空间并填写目录名称"; return; } folderSaving.value = true; error.value = ""; try { await http.post(`/drive/spaces/${selected.value.id}/nodes`, { data: { nodeType: "FOLDER", name: folderName.value.trim() } }); folderName.value = ""; await selectSpace(selected.value); } catch (e: any) { error.value = e?.response?.status === 409 ? "同一目录下已存在同名节点，请更换名称。" : e?.response?.data?.detail || e?.message || "目录创建失败"; } finally { folderSaving.value = false; } }
function openRename(node: Row) { renameNode.value = node; renameName.value = String(node.name || ""); renameDialog.value = true; }
async function rename() { if (!renameNode.value?.id || !renameName.value.trim()) { error.value = "名称不能为空"; return; } renameSaving.value = true; error.value = ""; try { await http.request("patch", `/drive/nodes/${renameNode.value.id}`, { headers: { "If-Match": `"${renameNode.value.nodeVersion ?? 0}"` }, data: { name: renameName.value.trim(), expectedVersion: renameNode.value.nodeVersion ?? 0 } }); renameDialog.value = false; if (selected.value) await selectSpace(selected.value, nodePage.value); } catch (e: any) { error.value = e?.response?.status === 409 ? "同一目录下已存在同名节点，或节点版本已变化，请刷新后重试。" : e?.response?.data?.detail || e?.message || "重命名失败"; } finally { renameSaving.value = false; } }
function openMove(node: Row) { moveNode.value = node; moveParentId.value = String(node.parentId || ""); moveDialog.value = true; }
async function move() { if (!moveNode.value?.id || !moveParentId.value.trim()) { error.value = "请输入目标父目录 ID"; return; } moveSaving.value = true; error.value = ""; try { await http.post(`/drive/nodes/${moveNode.value.id}/move`, { headers: { "If-Match": `"${moveNode.value.nodeVersion ?? 0}"` }, data: { parentId: moveParentId.value.trim(), expectedVersion: moveNode.value.nodeVersion ?? 0 } }); moveDialog.value = false; if (selected.value) await selectSpace(selected.value, nodePage.value); } catch (e: any) { error.value = e?.response?.status === 409 ? "目标目录下已存在同名节点，或节点版本已变化，请刷新后重试。" : e?.response?.data?.detail || e?.message || "移动失败"; } finally { moveSaving.value = false; } }
onMounted(loadSpaces);
</script>

<template>
  <main class="p-4 md:p-6"><div class="flex items-start justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">个人云盘</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理文件空间、文件夹和同步状态。</p></div><el-button :loading="loading" @click="loadSpaces">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" />
    <el-skeleton v-if="loading && !spaces.length" :rows="6" animated />
    <template v-else><section class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">空间数量</div><div class="text-2xl font-semibold mt-2">{{ spaces.length }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">已使用</div><div class="text-2xl font-semibold mt-2">{{ used.toLocaleString() }} B</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">空间配额</div><el-progress class="mt-3" :percentage="percent" :status="percent > 90 ? 'exception' : undefined" /></el-card></section>
      <el-card shadow="never" class="mb-4"><template #header><span class="font-medium">Drive Space</span></template><el-empty v-if="!spaces.length" description="暂无云盘空间" /><div v-else class="flex flex-wrap gap-3"><el-button v-for="space in spaces" :key="String(space.id)" :type="selected?.id === space.id ? 'primary' : 'default'" @click="selectSpace(space)">{{ space.name || space.title || space.id }}</el-button></div></el-card>
      <el-card shadow="never"><template #header><div class="flex justify-between"><span class="font-medium">根目录</span><span class="text-sm text-[var(--el-text-color-secondary)]">{{ selected?.name || '请选择空间' }}</span></div></template><div class="flex flex-wrap gap-2 mb-4"><el-input v-model="folderName" placeholder="新目录名称" clearable class="w-64" @keyup.enter="createFolder" /><el-button type="primary" :loading="folderSaving" :disabled="!selected" @click="createFolder">创建目录</el-button></div><el-skeleton v-if="nodeLoading" :rows="5" animated /><el-empty v-else-if="!nodes.length" description="此空间暂无文件" /><el-table v-else :data="nodes" stripe @row-click="row => row.id && $router.push(`/storage-center/drive/nodes/${row.id}`)"><el-table-column prop="name" label="名称" min-width="240" /><el-table-column prop="nodeType" label="类型" width="140" /><el-table-column prop="sizeBytes" label="大小" width="140" /><el-table-column prop="updatedAt" label="修改时间" min-width="180" /><el-table-column label="操作" width="180"><template #default="scope"><el-button link type="primary" @click.stop="openRename(scope.row)">重命名</el-button><el-button link type="primary" @click.stop="openMove(scope.row)">移动</el-button></template></el-table-column></el-table><el-pagination v-if="nodeTotal > nodePageSize" class="mt-4" background layout="prev, pager, next, sizes, total" :current-page="nodePage + 1" :page-size="nodePageSize" :page-sizes="[10, 20, 50]" :total="nodeTotal" @current-change="page => selected && selectSpace(selected, page - 1)" @size-change="size => { nodePageSize = size; selected && selectSpace(selected, 0); }" /></el-card>
    </template><el-dialog v-model="renameDialog" title="重命名节点" width="460px"><el-form @submit.prevent="rename"><el-form-item label="新名称" required><el-input v-model="renameName" clearable @keyup.enter="rename" /></el-form-item></el-form><template #footer><el-button @click="renameDialog = false">取消</el-button><el-button type="primary" :loading="renameSaving" @click="rename">保存</el-button></template></el-dialog><el-dialog v-model="moveDialog" title="移动节点" width="460px"><el-form @submit.prevent="move"><el-form-item label="目标父目录 ID" required><el-input v-model="moveParentId" clearable placeholder="Drive Folder UUID" @keyup.enter="move" /></el-form-item></el-form><template #footer><el-button @click="moveDialog = false">取消</el-button><el-button type="primary" :loading="moveSaving" @click="move">移动</el-button></template></el-dialog></main>
</template>
