<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { http } from "@/utils/http";

type Row = Record<string, unknown>;
const route = useRoute(); const revisions = ref<Row[]>([]); const node = ref<Row | null>(null); const loading = ref(false); const revisionSaving = ref(false); const error = ref(""); const message = ref(""); const revisionForm = ref({ attachmentId: "", contentFingerprint: "", operationId: "" });
const currentRevision = computed(() => revisions.value.find(item => String(item.id) === String(node.value?.currentRevisionId)) || null);
async function load() { loading.value = true; error.value = ""; try { const [nodeResult, result] = await Promise.all([http.get<unknown, unknown>(`/drive/nodes/${route.params.nodeId}`), http.get<unknown, unknown>(`/drive/nodes/${route.params.nodeId}/revisions`)]); node.value = nodeResult as Row; revisions.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "文件详情加载失败"; } finally { loading.value = false; } }
async function uploadNewVersion() { if (!node.value?.id || node.value.nodeType !== "FILE" || !revisionForm.value.attachmentId.trim()) { error.value = "仅文件节点可上传新版本，且 Attachment ID 不能为空"; return; } revisionSaving.value = true; error.value = ""; message.value = ""; try { await http.post(`/drive/nodes/${node.value.id}/revisions`, { data: { attachmentId: revisionForm.value.attachmentId.trim(), expectedNodeVersion: Number(node.value.nodeVersion ?? 0), contentFingerprint: revisionForm.value.contentFingerprint.trim() || undefined, operationId: revisionForm.value.operationId.trim() || undefined } }); revisionForm.value = { attachmentId: "", contentFingerprint: "", operationId: "" }; message.value = "新文件版本已上传"; await load(); } catch (e: any) { error.value = e?.response?.status === 409 ? "文件版本已变化，请刷新后重试。" : e?.response?.data?.detail || e?.message || "新版本上传失败"; } finally { revisionSaving.value = false; } }
onMounted(load);
</script>
<template>
  <el-card v-if="node?.nodeType === 'FILE'" shadow="never" class="mx-4 mt-4"><template #header><span>上传新文件版本</span></template><el-alert title="新版本会创建不可变 Revision，并更新文件当前版本。" type="info" show-icon :closable="false" class="mb-4" /><el-form inline @submit.prevent="uploadNewVersion"><el-form-item label="Attachment ID" required><el-input v-model="revisionForm.attachmentId" placeholder="新的 Attachment UUID" class="w-80" clearable /></el-form-item><el-form-item label="内容指纹"><el-input v-model="revisionForm.contentFingerprint" placeholder="可选" class="w-72" /></el-form-item><el-form-item label="幂等键"><el-input v-model="revisionForm.operationId" placeholder="可选 operation ID" class="w-64" /></el-form-item><el-button type="primary" :loading="revisionSaving" @click="uploadNewVersion">上传新版本</el-button></el-form></el-card>
  <el-card shadow="never" class="mx-4 mt-4"><template #header><span>当前版本与历史</span></template><el-descriptions :column="2" border><el-descriptions-item label="当前 Revision">{{ currentRevision?.revisionNo || '暂无' }}</el-descriptions-item><el-descriptions-item label="历史版本数">{{ revisions.length }}</el-descriptions-item><el-descriptions-item label="当前 Attachment" :span="2">{{ currentRevision?.attachmentId || node?.currentRevisionId || '暂无' }}</el-descriptions-item><el-descriptions-item label="内容指纹" :span="2">{{ currentRevision?.contentFingerprint || '未提供' }}</el-descriptions-item></el-descriptions></el-card>
  <main class="p-4 md:p-6"><div class="flex items-start justify-between gap-4 mb-6"><div><p class="text-sm text-[var(--el-text-color-secondary)]">个人云盘 / 文件详情</p><h1 class="mt-2 text-2xl font-semibold">{{ route.params.nodeId }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">查看文件当前版本、修订历史和引用关系。</p></div><div class="flex gap-2"><el-button @click="$router.back()">返回</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" /><section class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">文件类型</div><div class="mt-2 font-medium">Drive File</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">修订版本</div><div class="mt-2 text-2xl font-semibold">{{ revisions.length }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">当前状态</div><div class="mt-2"><el-tag type="success">可用</el-tag></div></el-card></section><el-card shadow="never"><template #header><span class="font-medium">Revision History</span></template><el-skeleton v-if="loading" :rows="6" animated /><el-empty v-else-if="!revisions.length" description="暂无修订历史" /><el-table v-else :data="revisions" stripe><el-table-column prop="revision" label="版本" width="120" /><el-table-column prop="createdAt" label="创建时间" min-width="180" /><el-table-column prop="source" label="来源" min-width="160" /><el-table-column prop="logicalSize" label="逻辑大小" width="140" /><el-table-column prop="attachmentId" label="附件" min-width="220" /><el-table-column prop="integrityState" label="完整性" width="140" /></el-table></el-card></main>
</template>
