<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { http } from "@/utils/http";

type Row = Record<string, unknown>;
const route = useRoute(); const rows = ref<Row[]>([]); const spaces = ref<Row[]>([]); const loading = ref(false); const error = ref(""); const message = ref(""); const actionBusy = ref<Set<string>>(new Set());
const kind = computed(() => route.path.includes("/trash") ? "trash" : route.path.includes("/transfers") ? "transfers" : route.path.includes("/sync") ? "sync" : route.path.includes("/conflicts") ? "conflicts" : route.path.includes("/quota") ? "quota" : route.path.includes("/revisions") ? "revisions" : String(route.path.split("/").pop()));
const config = computed(() => ({
  trash: ["回收站", "已删除节点", ["id", "name", "deletedAt", "expiresAt"]],
  transfers: ["传输中心", "上传、下载与同步传输状态", ["id", "name", "status", "progress"]],
  sync: ["同步绑定", "设备绑定、同步游标与运行状态", ["id", "deviceId", "status", "lastSyncAt"]],
  conflicts: ["冲突处理", "需要人工决策的同步冲突", ["id", "nodeId", "state", "createdAt"]],
  quota: ["配额与用量", "Drive Space 的逻辑用量", ["spaceId", "usedBytes", "quotaBytes", "updatedAt"]],
  revisions: ["文件版本", "节点的 revision 历史", ["id", "nodeId", "revision", "createdAt"]]
}[kind.value] || ["Drive 运维", "Drive 诊断信息", ["id", "status", "updatedAt"]]));
async function load() { loading.value = true; error.value = ""; try { if (kind.value === "policies") { rows.value = []; error.value = "云盘策略接口尚未接入；请在后端策略服务启用后管理"; return; } if (route.path.includes("/sync/")) { const result = await http.get<unknown, unknown>("/drive/bindings"); rows.value = (Array.isArray(result) ? result as Row[] : []).filter(row => String(row.id) === String(route.params.bindingId)); return; } if (route.path.includes("/spaces/") && route.params.spaceId) { const result = await http.get<unknown, unknown>(`/drive/spaces/${route.params.spaceId}/children`); rows.value = Array.isArray(result) ? result as Row[] : []; return; } const s = await http.get<unknown, unknown>("/drive/spaces"); spaces.value = Array.isArray(s) ? s as Row[] : []; const space = spaces.value[0]; if (!space) return; let endpoint = `/drive/spaces/${space.id}/quota`; if (kind.value === "trash") endpoint = `/drive/spaces/${space.id}/tombstones`; if (kind.value === "sync") endpoint = "/drive/bindings"; if (kind.value === "conflicts") { const b = await http.get<unknown, unknown>("/drive/bindings"); const binding = Array.isArray(b) ? (b as Row[])[0] : null; endpoint = binding?.id ? `/drive/bindings/${binding.id}/conflicts` : "/drive/bindings"; } if (kind.value === "revisions" && route.params.nodeId) endpoint = `/drive/nodes/${route.params.nodeId}/revisions`; const result = await http.get<unknown, unknown>(endpoint); rows.value = Array.isArray(result) ? result as Row[] : result ? [result as Row] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Drive 数据加载失败"; } finally { loading.value = false; } }
async function runAction(id: string, action: "restore" | "pause" | "resume" | "resync", row?: Row) { if (!id || actionBusy.value.has(id)) return; const currentRow = row || rows.value.find(item => String(item.nodeId) === id); const next = new Set(actionBusy.value); next.add(id); actionBusy.value = next; message.value = ""; try { const endpoint = action === "restore" ? `/drive/nodes/${id}/restore` : action === "pause" ? `/drive/bindings/${id}/pause` : action === "resume" ? `/drive/bindings/${id}/resume` : `/drive/bindings/${id}/full-resync`; const result: any = await http.post(endpoint, { headers: action === "restore" && currentRow?.nodeVersion != null ? { "If-Match": `"${currentRow.nodeVersion}"` } : undefined }); if (action === "restore" && currentRow?.previousParentId && String(result?.parentId) !== String(currentRow.previousParentId)) message.value = "原目录已不存在，节点已安全恢复到 Drive 根目录。"; await load(); } catch (e: any) { error.value = e?.response?.status === 409 ? "文件版本已变化，请刷新后重试。" : e?.response?.data?.detail || e?.message || "Drive 操作失败"; } finally { const done = new Set(actionBusy.value); done.delete(id); actionBusy.value = done; } }
async function resolveConflict(id: string, state: "RESOLVED" | "DISMISSED") { if (!id) return; try { await http.post(`/drive/conflicts/${id}/resolve`, { params: { state } }); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "冲突处理失败"; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex items-start justify-between mb-6"><div><h1 class="text-2xl font-semibold">{{ config[0] }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">{{ config[1] }}</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4" /><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4" /><el-card shadow="never"><el-skeleton v-if="loading" :rows="6" animated /><el-empty v-else-if="!rows.length" description="暂无可展示数据" /><el-table v-else :data="rows" stripe><el-table-column v-for="column in config[2]" :key="column" :prop="column" :label="column" min-width="160" show-overflow-tooltip /><el-table-column v-if="kind === 'trash'" label="操作" width="100"><template #default="{ row }"><el-button link type="primary" :loading="actionBusy.has(String(row.nodeId))" @click="runAction(String(row.nodeId), 'restore', row)">恢复</el-button></template></el-table-column><el-table-column v-if="kind === 'sync'" label="操作" width="190"><template #default="{ row }"><el-button link @click="runAction(String(row.id), row.enabled ? 'pause' : 'resume')">{{ row.enabled ? '暂停' : '恢复' }}</el-button><el-button link type="primary" @click="runAction(String(row.id), 'resync')">全量同步</el-button></template></el-table-column><el-table-column v-if="kind === 'conflicts'" label="操作" width="190"><template #default="{ row }"><el-button link type="primary" @click="resolveConflict(String(row.id), 'RESOLVED')">标记已解决</el-button><el-button link @click="resolveConflict(String(row.id), 'DISMISSED')">忽略</el-button></template></el-table-column></el-table></el-card></main></template>
