<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const bindings = ref<Row[]>([]); const changes = ref<Row[]>([]); const selectedBindingId = ref(""); const loading = ref(false); const advancing = ref(false); const resuming = ref(false); const error = ref(""); const message = ref("");
const selectedBinding = () => bindings.value.find(item => String(item.id) === selectedBindingId.value);
async function loadBindings() { try { const result = await http.get<unknown, unknown>("/drive/bindings"); bindings.value = Array.isArray(result) ? (result as Row[]).filter(item => item.mode !== "BACKUP") : []; if (!selectedBindingId.value && bindings.value[0]?.id) selectedBindingId.value = String(bindings.value[0].id); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "同步配置加载失败"; } }
async function loadChanges() { const binding = selectedBinding(); if (!binding?.driveSpaceId) { changes.value = []; return; } loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>(`/drive/spaces/${binding.driveSpaceId}/changes`, { params: { afterSequence: binding.cursor || 0 } }); changes.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "服务端变更加载失败"; } finally { loading.value = false; } }
async function acknowledgeChanges() { const binding = selectedBinding(); const last = changes.value[changes.value.length - 1]; if (!binding?.id || !last?.sequence) { error.value = "没有可确认的服务端变更"; return; } advancing.value = true; error.value = ""; message.value = ""; try { await http.post(`/drive/bindings/${binding.id}/cursor`, { data: { cursor: last.sequence } }); message.value = `已确认至序号 ${last.sequence}`; await loadBindings(); await loadChanges(); } catch (e: any) { error.value = e?.response?.status === 409 ? "同步游标已变化，请刷新后重试" : e?.response?.data?.detail || e?.message || "同步游标确认失败"; } finally { advancing.value = false; } }
async function resumeSync() { const binding = selectedBinding(); if (!binding?.id) { error.value = "请选择同步配置"; return; } resuming.value = true; error.value = ""; message.value = ""; try { await http.post(`/drive/bindings/${binding.id}/resume`); message.value = "同步已恢复，将从持久化游标继续拉取"; await loadBindings(); await loadChanges(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "同步恢复失败"; } finally { resuming.value = false; } }
onMounted(async () => { await loadBindings(); await loadChanges(); });
</script>
<template>
  <main class="p-4 md:p-6"><div class="flex items-start justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">服务端变更</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">按同步游标拉取服务端 Drive 变更，处理完成后确认推进游标。</p></div><el-button :loading="loading" @click="loadChanges">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" /><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4" /><el-card shadow="never" class="mb-4"><template #header><span>同步范围</span></template><div class="flex flex-wrap gap-3 items-end"><el-form-item label="同步配置" required><el-select v-model="selectedBindingId" class="w-96" @change="loadChanges"><el-option v-for="binding in bindings" :key="binding.id" :label="`${binding.localDisplayPath || binding.localScopeId} → ${binding.driveSpaceId}`" :value="binding.id" /></el-select></el-form-item><el-form-item label="当前状态"><el-tag>{{ selectedBinding()?.state || "-" }}</el-tag></el-form-item><el-form-item label="当前游标"><el-input :model-value="selectedBinding()?.cursor ?? 0" readonly class="w-40" /></el-form-item><el-button :loading="resuming" @click="resumeSync">恢复同步</el-button><el-button type="primary" :loading="advancing" @click="acknowledgeChanges">确认已处理并推进游标</el-button></div></el-card><el-card shadow="never"><template #header><span>待处理变更</span></template><el-skeleton v-if="loading" :rows="5" animated /><el-empty v-else-if="!changes.length" description="暂无新的服务端变更" /><el-table v-else :data="changes" stripe><el-table-column prop="sequence" label="序号" width="100" /><el-table-column prop="mutationKind" label="变更类型" width="220" /><el-table-column prop="nodeId" label="节点 ID" min-width="260" /><el-table-column prop="nodeVersion" label="节点版本" width="120" /><el-table-column prop="revisionId" label="版本 ID" min-width="260" /><el-table-column prop="occurredAt" label="发生时间" min-width="190" /></el-table></el-card></main>
</template>
