ikaros:
  log-level: DEBUG
  server-port: 9090
  qbittorrent-base-url: http://172.28.83.148:9091/api/v2/

spring:
  datasource:
    # mariadb database configuration.
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.28.83.148:3306/ikaros
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  file:
    name: ./logs/ikaros.log


