ikaros:
  log-level: DEBUG
  server-port: 9090

spring:
  datasource:
    # postgresql database configuration.
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ikaros
    username: ikaros
    password: openpostgresql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  file:
    name: ./build/logs/ikaros.log


