ikaros:
  log-level: DEBUG
  server-port: 9090

spring:
  datasource:
    # mariadb database configuration.
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ikaros
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  file:
    name: ./build/logs/ikaros.log


