<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>run.ikaros</groupId>
        <artifactId>ikaros</artifactId>
        <version>2.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>platform</artifactId>
    <packaging>pom</packaging>
    <name>Ikaros Platform</name>

    <modules>
        <module>foundation-api</module>
        <module>foundation</module>
        <module>resource-api</module>
        <module>resource</module>
        <module>integration-api</module>
        <module>integration</module>
        <module>operations-api</module>
        <module>operations</module>
        <module>authorization-api</module>
        <module>authentication-api</module>
        <module>authentication</module>
        <module>authorization</module>
        <module>storage-api</module>
        <module>media-api</module>
        <module>media</module>
        <module>storage</module>
        <module>document</module>
        <module>game</module>
        <module>music</module>
        <module>photo</module>
        <module>private-notes</module>
        <module>finance</module>
        <module>ingestion</module>
        <module>planning</module>
    </modules>
</project>
