/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { PagingWrap } from "../models";
/**
 * V1CollectionApi - axios parameter creator
 * @export
 */
export const V1CollectionApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Get collections with conditions.
     * @param {any} [category] Collection category, default is EPISODE.
     * @param {any} [type] Collection type, default is null.
     * @param {any} [page] 第几页，从1开始, 默认为1.
     * @param {any} [size] 每页条数，默认为10.
     * @param {any} [time] 时间范围，格式: 开始时间戳-结束时间戳
     * @param {any} [updateTimeDesc] 是否根据更新时间倒序，默认为 true.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCollectionsWithCondition: async (
      category?: any,
      type?: any,
      page?: any,
      size?: any,
      time?: any,
      updateTimeDesc?: any,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/collections/condition`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (category !== undefined) {
        localVarQueryParameter["category"] = category;
      }

      if (type !== undefined) {
        localVarQueryParameter["type"] = type;
      }

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (size !== undefined) {
        localVarQueryParameter["size"] = size;
      }

      if (time !== undefined) {
        localVarQueryParameter["time"] = time;
      }

      if (updateTimeDesc !== undefined) {
        localVarQueryParameter["updateTimeDesc"] = updateTimeDesc;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get collection type by subject id.
     * @param {any} id Subject id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTypeBySubjectId: async (
      id: any,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("getTypeBySubjectId", "id", id);
      const localVarPath = `/api/v1/collection/type/subjectId/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * V1CollectionApi - functional programming interface
 * @export
 */
export const V1CollectionApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    V1CollectionApiAxiosParamCreator(configuration);
  return {
    /**
     * Get collections with conditions.
     * @param {any} [category] Collection category, default is EPISODE.
     * @param {any} [type] Collection type, default is null.
     * @param {any} [page] 第几页，从1开始, 默认为1.
     * @param {any} [size] 每页条数，默认为10.
     * @param {any} [time] 时间范围，格式: 开始时间戳-结束时间戳
     * @param {any} [updateTimeDesc] 是否根据更新时间倒序，默认为 true.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCollectionsWithCondition(
      category?: any,
      type?: any,
      page?: any,
      size?: any,
      time?: any,
      updateTimeDesc?: any,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagingWrap>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getCollectionsWithCondition(
          category,
          type,
          page,
          size,
          time,
          updateTimeDesc,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     * Get collection type by subject id.
     * @param {any} id Subject id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTypeBySubjectId(
      id: any,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getTypeBySubjectId(id, options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * V1CollectionApi - factory interface
 * @export
 */
export const V1CollectionApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = V1CollectionApiFp(configuration);
  return {
    /**
     * Get collections with conditions.
     * @param {V1CollectionApiGetCollectionsWithConditionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCollectionsWithCondition(
      requestParameters: V1CollectionApiGetCollectionsWithConditionRequest = {},
      options?: AxiosRequestConfig
    ): AxiosPromise<PagingWrap> {
      return localVarFp
        .getCollectionsWithCondition(
          requestParameters.category,
          requestParameters.type,
          requestParameters.page,
          requestParameters.size,
          requestParameters.time,
          requestParameters.updateTimeDesc,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Get collection type by subject id.
     * @param {V1CollectionApiGetTypeBySubjectIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTypeBySubjectId(
      requestParameters: V1CollectionApiGetTypeBySubjectIdRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<any> {
      return localVarFp
        .getTypeBySubjectId(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for getCollectionsWithCondition operation in V1CollectionApi.
 * @export
 * @interface V1CollectionApiGetCollectionsWithConditionRequest
 */
export interface V1CollectionApiGetCollectionsWithConditionRequest {
  /**
   * Collection category, default is EPISODE.
   * @type {any}
   * @memberof V1CollectionApiGetCollectionsWithCondition
   */
  readonly category?: any;

  /**
   * Collection type, default is null.
   * @type {any}
   * @memberof V1CollectionApiGetCollectionsWithCondition
   */
  readonly type?: any;

  /**
   * 第几页，从1开始, 默认为1.
   * @type {any}
   * @memberof V1CollectionApiGetCollectionsWithCondition
   */
  readonly page?: any;

  /**
   * 每页条数，默认为10.
   * @type {any}
   * @memberof V1CollectionApiGetCollectionsWithCondition
   */
  readonly size?: any;

  /**
   * 时间范围，格式: 开始时间戳-结束时间戳
   * @type {any}
   * @memberof V1CollectionApiGetCollectionsWithCondition
   */
  readonly time?: any;

  /**
   * 是否根据更新时间倒序，默认为 true.
   * @type {any}
   * @memberof V1CollectionApiGetCollectionsWithCondition
   */
  readonly updateTimeDesc?: any;
}

/**
 * Request parameters for getTypeBySubjectId operation in V1CollectionApi.
 * @export
 * @interface V1CollectionApiGetTypeBySubjectIdRequest
 */
export interface V1CollectionApiGetTypeBySubjectIdRequest {
  /**
   * Subject id
   * @type {any}
   * @memberof V1CollectionApiGetTypeBySubjectId
   */
  readonly id: any;
}

/**
 * V1CollectionApi - object-oriented interface
 * @export
 * @class V1CollectionApi
 * @extends {BaseAPI}
 */
export class V1CollectionApi extends BaseAPI {
  /**
   * Get collections with conditions.
   * @param {V1CollectionApiGetCollectionsWithConditionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1CollectionApi
   */
  public getCollectionsWithCondition(
    requestParameters: V1CollectionApiGetCollectionsWithConditionRequest = {},
    options?: AxiosRequestConfig
  ) {
    return V1CollectionApiFp(this.configuration)
      .getCollectionsWithCondition(
        requestParameters.category,
        requestParameters.type,
        requestParameters.page,
        requestParameters.size,
        requestParameters.time,
        requestParameters.updateTimeDesc,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get collection type by subject id.
   * @param {V1CollectionApiGetTypeBySubjectIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1CollectionApi
   */
  public getTypeBySubjectId(
    requestParameters: V1CollectionApiGetTypeBySubjectIdRequest,
    options?: AxiosRequestConfig
  ) {
    return V1CollectionApiFp(this.configuration)
      .getTypeBySubjectId(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
