/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { SubjectRecord } from "../models";
/**
 * V1MetaInfoApi - axios parameter creator
 * @export
 */
export const V1MetaInfoApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Get subject record from third-party metadata platform by platform id.
     * @param {any} platform Platform.
     * @param {any} platformId Platform id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMetaInfoSubjectByPlatformId: async (
      platform: any,
      platformId: any,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'platform' is not null or undefined
      assertParamExists("getMetaInfoSubjectByPlatformId", "platform", platform);
      // verify required parameter 'platformId' is not null or undefined
      assertParamExists(
        "getMetaInfoSubjectByPlatformId",
        "platformId",
        platformId,
      );
      const localVarPath = `/api/v1/metaInfo/subject`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (platform !== undefined) {
        localVarQueryParameter["platform"] = platform;
      }

      if (platformId !== undefined) {
        localVarQueryParameter["platformId"] = platformId;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Search subjects from third-party metadata platform by keyword.
     * @param {any} platform Platform.
     * @param {any} keyword Search keyword.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchMetaInfoSubjects: async (
      platform: any,
      keyword: any,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'platform' is not null or undefined
      assertParamExists("searchMetaInfoSubjects", "platform", platform);
      // verify required parameter 'keyword' is not null or undefined
      assertParamExists("searchMetaInfoSubjects", "keyword", keyword);
      const localVarPath = `/api/v1/metaInfo/search`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (platform !== undefined) {
        localVarQueryParameter["platform"] = platform;
      }

      if (keyword !== undefined) {
        localVarQueryParameter["keyword"] = keyword;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * V1MetaInfoApi - functional programming interface
 * @export
 */
export const V1MetaInfoApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    V1MetaInfoApiAxiosParamCreator(configuration);
  return {
    /**
     * Get subject record from third-party metadata platform by platform id.
     * @param {any} platform Platform.
     * @param {any} platformId Platform id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getMetaInfoSubjectByPlatformId(
      platform: any,
      platformId: any,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubjectRecord>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getMetaInfoSubjectByPlatformId(
          platform,
          platformId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     * Search subjects from third-party metadata platform by keyword.
     * @param {any} platform Platform.
     * @param {any} keyword Search keyword.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchMetaInfoSubjects(
      platform: any,
      keyword: any,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.searchMetaInfoSubjects(
          platform,
          keyword,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * V1MetaInfoApi - factory interface
 * @export
 */
export const V1MetaInfoApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = V1MetaInfoApiFp(configuration);
  return {
    /**
     * Get subject record from third-party metadata platform by platform id.
     * @param {V1MetaInfoApiGetMetaInfoSubjectByPlatformIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMetaInfoSubjectByPlatformId(
      requestParameters: V1MetaInfoApiGetMetaInfoSubjectByPlatformIdRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<SubjectRecord> {
      return localVarFp
        .getMetaInfoSubjectByPlatformId(
          requestParameters.platform,
          requestParameters.platformId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Search subjects from third-party metadata platform by keyword.
     * @param {V1MetaInfoApiSearchMetaInfoSubjectsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchMetaInfoSubjects(
      requestParameters: V1MetaInfoApiSearchMetaInfoSubjectsRequest,
      options?: AxiosRequestConfig,
    ): AxiosPromise<any> {
      return localVarFp
        .searchMetaInfoSubjects(
          requestParameters.platform,
          requestParameters.keyword,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for getMetaInfoSubjectByPlatformId operation in V1MetaInfoApi.
 * @export
 * @interface V1MetaInfoApiGetMetaInfoSubjectByPlatformIdRequest
 */
export interface V1MetaInfoApiGetMetaInfoSubjectByPlatformIdRequest {
  /**
   * Platform.
   * @type {any}
   * @memberof V1MetaInfoApiGetMetaInfoSubjectByPlatformId
   */
  readonly platform: any;

  /**
   * Platform id.
   * @type {any}
   * @memberof V1MetaInfoApiGetMetaInfoSubjectByPlatformId
   */
  readonly platformId: any;
}

/**
 * Request parameters for searchMetaInfoSubjects operation in V1MetaInfoApi.
 * @export
 * @interface V1MetaInfoApiSearchMetaInfoSubjectsRequest
 */
export interface V1MetaInfoApiSearchMetaInfoSubjectsRequest {
  /**
   * Platform.
   * @type {any}
   * @memberof V1MetaInfoApiSearchMetaInfoSubjects
   */
  readonly platform: any;

  /**
   * Search keyword.
   * @type {any}
   * @memberof V1MetaInfoApiSearchMetaInfoSubjects
   */
  readonly keyword: any;
}

/**
 * V1MetaInfoApi - object-oriented interface
 * @export
 * @class V1MetaInfoApi
 * @extends {BaseAPI}
 */
export class V1MetaInfoApi extends BaseAPI {
  /**
   * Get subject record from third-party metadata platform by platform id.
   * @param {V1MetaInfoApiGetMetaInfoSubjectByPlatformIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1MetaInfoApi
   */
  public getMetaInfoSubjectByPlatformId(
    requestParameters: V1MetaInfoApiGetMetaInfoSubjectByPlatformIdRequest,
    options?: AxiosRequestConfig,
  ) {
    return V1MetaInfoApiFp(this.configuration)
      .getMetaInfoSubjectByPlatformId(
        requestParameters.platform,
        requestParameters.platformId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Search subjects from third-party metadata platform by keyword.
   * @param {V1MetaInfoApiSearchMetaInfoSubjectsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1MetaInfoApi
   */
  public searchMetaInfoSubjects(
    requestParameters: V1MetaInfoApiSearchMetaInfoSubjectsRequest,
    options?: AxiosRequestConfig,
  ) {
    return V1MetaInfoApiFp(this.configuration)
      .searchMetaInfoSubjects(
        requestParameters.platform,
        requestParameters.keyword,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
