/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
/**
 * V1alpha1CollectionApi - axios parameter creator
 * @export
 */
export const V1alpha1CollectionApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Get collection type by subject id.
     * @param {number} id Subject id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTypeBySubjectId: async (
      id: number,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("getTypeBySubjectId", "id", id);
      const localVarPath = `/api/v1alpha1/collection/subjectId/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * V1alpha1CollectionApi - functional programming interface
 * @export
 */
export const V1alpha1CollectionApiFp = function (
  configuration?: Configuration
) {
  const localVarAxiosParamCreator =
    V1alpha1CollectionApiAxiosParamCreator(configuration);
  return {
    /**
     * Get collection type by subject id.
     * @param {number} id Subject id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTypeBySubjectId(
      id: number,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getTypeBySubjectId(id, options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * V1alpha1CollectionApi - factory interface
 * @export
 */
export const V1alpha1CollectionApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = V1alpha1CollectionApiFp(configuration);
  return {
    /**
     * Get collection type by subject id.
     * @param {V1alpha1CollectionApiGetTypeBySubjectIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTypeBySubjectId(
      requestParameters: V1alpha1CollectionApiGetTypeBySubjectIdRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<string> {
      return localVarFp
        .getTypeBySubjectId(requestParameters.id, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for getTypeBySubjectId operation in V1alpha1CollectionApi.
 * @export
 * @interface V1alpha1CollectionApiGetTypeBySubjectIdRequest
 */
export interface V1alpha1CollectionApiGetTypeBySubjectIdRequest {
  /**
   * Subject id
   * @type {number}
   * @memberof V1alpha1CollectionApiGetTypeBySubjectId
   */
  readonly id: number;
}

/**
 * V1alpha1CollectionApi - object-oriented interface
 * @export
 * @class V1alpha1CollectionApi
 * @extends {BaseAPI}
 */
export class V1alpha1CollectionApi extends BaseAPI {
  /**
   * Get collection type by subject id.
   * @param {V1alpha1CollectionApiGetTypeBySubjectIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1CollectionApi
   */
  public getTypeBySubjectId(
    requestParameters: V1alpha1CollectionApiGetTypeBySubjectIdRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1CollectionApiFp(this.configuration)
      .getTypeBySubjectId(requestParameters.id, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
