/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { EpisodeCollection } from "../models";
/**
 * V1alpha1EpisodeCollectionApi - axios parameter creator
 * @export
 */
export const V1alpha1EpisodeCollectionApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteEpisodeCollection: async (
      userId: number,
      episodeId: number,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("deleteEpisodeCollection", "userId", userId);
      // verify required parameter 'episodeId' is not null or undefined
      assertParamExists("deleteEpisodeCollection", "episodeId", episodeId);
      const localVarPath =
        `/api/v1alpha1/episode/collection/{userId}/{episodeId}`
          .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
          .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findEpisodeCollection: async (
      userId: number,
      episodeId: number,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("findEpisodeCollection", "userId", userId);
      // verify required parameter 'episodeId' is not null or undefined
      assertParamExists("findEpisodeCollection", "episodeId", episodeId);
      const localVarPath =
        `/api/v1alpha1/episode/collection/{userId}/{episodeId}`
          .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
          .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} subjectId Subject id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findEpisodeCollectionsByUserIdAndSubjectId: async (
      userId: number,
      subjectId: number,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists(
        "findEpisodeCollectionsByUserIdAndSubjectId",
        "userId",
        userId
      );
      // verify required parameter 'subjectId' is not null or undefined
      assertParamExists(
        "findEpisodeCollectionsByUserIdAndSubjectId",
        "subjectId",
        subjectId
      );
      const localVarPath =
        `/api/v1alpha1/episode/collections/subjectId/{userId}/{subjectId}`
          .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
          .replace(`{${"subjectId"}}`, encodeURIComponent(String(subjectId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    saveEpisodeCollection: async (
      userId: number,
      episodeId: number,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("saveEpisodeCollection", "userId", userId);
      // verify required parameter 'episodeId' is not null or undefined
      assertParamExists("saveEpisodeCollection", "episodeId", episodeId);
      const localVarPath =
        `/api/v1alpha1/episode/collection/{userId}/{episodeId}`
          .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
          .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {number} progress Episode collection progress, unit is milliseconds.
     * @param {number} [duration] Episode collection duration, unit is milliseconds.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEpisodeCollection: async (
      userId: number,
      episodeId: number,
      progress: number,
      duration?: number,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("updateEpisodeCollection", "userId", userId);
      // verify required parameter 'episodeId' is not null or undefined
      assertParamExists("updateEpisodeCollection", "episodeId", episodeId);
      // verify required parameter 'progress' is not null or undefined
      assertParamExists("updateEpisodeCollection", "progress", progress);
      const localVarPath =
        `/api/v1alpha1/episode/collection/{userId}/{episodeId}`
          .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
          .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (progress !== undefined) {
        localVarQueryParameter["progress"] = progress;
      }

      if (duration !== undefined) {
        localVarQueryParameter["duration"] = duration;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {boolean} finish Episode collection finish.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEpisodeCollectionFinish: async (
      userId: number,
      episodeId: number,
      finish: boolean,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists("updateEpisodeCollectionFinish", "userId", userId);
      // verify required parameter 'episodeId' is not null or undefined
      assertParamExists(
        "updateEpisodeCollectionFinish",
        "episodeId",
        episodeId
      );
      // verify required parameter 'finish' is not null or undefined
      assertParamExists("updateEpisodeCollectionFinish", "finish", finish);
      const localVarPath =
        `/api/v1alpha1/episode/collection/finish/{userId}/{episodeId}/{finish}`
          .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
          .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)))
          .replace(`{${"finish"}}`, encodeURIComponent(String(finish)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * V1alpha1EpisodeCollectionApi - functional programming interface
 * @export
 */
export const V1alpha1EpisodeCollectionApiFp = function (
  configuration?: Configuration
) {
  const localVarAxiosParamCreator =
    V1alpha1EpisodeCollectionApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteEpisodeCollection(
      userId: number,
      episodeId: number,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<EpisodeCollection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteEpisodeCollection(
          userId,
          episodeId,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async findEpisodeCollection(
      userId: number,
      episodeId: number,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<EpisodeCollection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.findEpisodeCollection(
          userId,
          episodeId,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} subjectId Subject id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async findEpisodeCollectionsByUserIdAndSubjectId(
      userId: number,
      subjectId: number,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<EpisodeCollection>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.findEpisodeCollectionsByUserIdAndSubjectId(
          userId,
          subjectId,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async saveEpisodeCollection(
      userId: number,
      episodeId: number,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<EpisodeCollection>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.saveEpisodeCollection(
          userId,
          episodeId,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {number} progress Episode collection progress, unit is milliseconds.
     * @param {number} [duration] Episode collection duration, unit is milliseconds.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateEpisodeCollection(
      userId: number,
      episodeId: number,
      progress: number,
      duration?: number,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateEpisodeCollection(
          userId,
          episodeId,
          progress,
          duration,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
    /**
     *
     * @param {number} userId User id
     * @param {number} episodeId Episode id
     * @param {boolean} finish Episode collection finish.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateEpisodeCollectionFinish(
      userId: number,
      episodeId: number,
      finish: boolean,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.updateEpisodeCollectionFinish(
          userId,
          episodeId,
          finish,
          options
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * V1alpha1EpisodeCollectionApi - factory interface
 * @export
 */
export const V1alpha1EpisodeCollectionApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = V1alpha1EpisodeCollectionApiFp(configuration);
  return {
    /**
     *
     * @param {V1alpha1EpisodeCollectionApiDeleteEpisodeCollectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteEpisodeCollection(
      requestParameters: V1alpha1EpisodeCollectionApiDeleteEpisodeCollectionRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<EpisodeCollection> {
      return localVarFp
        .deleteEpisodeCollection(
          requestParameters.userId,
          requestParameters.episodeId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {V1alpha1EpisodeCollectionApiFindEpisodeCollectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findEpisodeCollection(
      requestParameters: V1alpha1EpisodeCollectionApiFindEpisodeCollectionRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<EpisodeCollection> {
      return localVarFp
        .findEpisodeCollection(
          requestParameters.userId,
          requestParameters.episodeId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    findEpisodeCollectionsByUserIdAndSubjectId(
      requestParameters: V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectIdRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<Array<EpisodeCollection>> {
      return localVarFp
        .findEpisodeCollectionsByUserIdAndSubjectId(
          requestParameters.userId,
          requestParameters.subjectId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {V1alpha1EpisodeCollectionApiSaveEpisodeCollectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    saveEpisodeCollection(
      requestParameters: V1alpha1EpisodeCollectionApiSaveEpisodeCollectionRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<EpisodeCollection> {
      return localVarFp
        .saveEpisodeCollection(
          requestParameters.userId,
          requestParameters.episodeId,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEpisodeCollection(
      requestParameters: V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .updateEpisodeCollection(
          requestParameters.userId,
          requestParameters.episodeId,
          requestParameters.progress,
          requestParameters.duration,
          options
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinishRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEpisodeCollectionFinish(
      requestParameters: V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinishRequest,
      options?: AxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .updateEpisodeCollectionFinish(
          requestParameters.userId,
          requestParameters.episodeId,
          requestParameters.finish,
          options
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for deleteEpisodeCollection operation in V1alpha1EpisodeCollectionApi.
 * @export
 * @interface V1alpha1EpisodeCollectionApiDeleteEpisodeCollectionRequest
 */
export interface V1alpha1EpisodeCollectionApiDeleteEpisodeCollectionRequest {
  /**
   * User id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiDeleteEpisodeCollection
   */
  readonly userId: number;

  /**
   * Episode id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiDeleteEpisodeCollection
   */
  readonly episodeId: number;
}

/**
 * Request parameters for findEpisodeCollection operation in V1alpha1EpisodeCollectionApi.
 * @export
 * @interface V1alpha1EpisodeCollectionApiFindEpisodeCollectionRequest
 */
export interface V1alpha1EpisodeCollectionApiFindEpisodeCollectionRequest {
  /**
   * User id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiFindEpisodeCollection
   */
  readonly userId: number;

  /**
   * Episode id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiFindEpisodeCollection
   */
  readonly episodeId: number;
}

/**
 * Request parameters for findEpisodeCollectionsByUserIdAndSubjectId operation in V1alpha1EpisodeCollectionApi.
 * @export
 * @interface V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectIdRequest
 */
export interface V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectIdRequest {
  /**
   * User id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectId
   */
  readonly userId: number;

  /**
   * Subject id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectId
   */
  readonly subjectId: number;
}

/**
 * Request parameters for saveEpisodeCollection operation in V1alpha1EpisodeCollectionApi.
 * @export
 * @interface V1alpha1EpisodeCollectionApiSaveEpisodeCollectionRequest
 */
export interface V1alpha1EpisodeCollectionApiSaveEpisodeCollectionRequest {
  /**
   * User id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiSaveEpisodeCollection
   */
  readonly userId: number;

  /**
   * Episode id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiSaveEpisodeCollection
   */
  readonly episodeId: number;
}

/**
 * Request parameters for updateEpisodeCollection operation in V1alpha1EpisodeCollectionApi.
 * @export
 * @interface V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionRequest
 */
export interface V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionRequest {
  /**
   * User id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollection
   */
  readonly userId: number;

  /**
   * Episode id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollection
   */
  readonly episodeId: number;

  /**
   * Episode collection progress, unit is milliseconds.
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollection
   */
  readonly progress: number;

  /**
   * Episode collection duration, unit is milliseconds.
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollection
   */
  readonly duration?: number;
}

/**
 * Request parameters for updateEpisodeCollectionFinish operation in V1alpha1EpisodeCollectionApi.
 * @export
 * @interface V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinishRequest
 */
export interface V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinishRequest {
  /**
   * User id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinish
   */
  readonly userId: number;

  /**
   * Episode id
   * @type {number}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinish
   */
  readonly episodeId: number;

  /**
   * Episode collection finish.
   * @type {boolean}
   * @memberof V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinish
   */
  readonly finish: boolean;
}

/**
 * V1alpha1EpisodeCollectionApi - object-oriented interface
 * @export
 * @class V1alpha1EpisodeCollectionApi
 * @extends {BaseAPI}
 */
export class V1alpha1EpisodeCollectionApi extends BaseAPI {
  /**
   *
   * @param {V1alpha1EpisodeCollectionApiDeleteEpisodeCollectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1EpisodeCollectionApi
   */
  public deleteEpisodeCollection(
    requestParameters: V1alpha1EpisodeCollectionApiDeleteEpisodeCollectionRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1EpisodeCollectionApiFp(this.configuration)
      .deleteEpisodeCollection(
        requestParameters.userId,
        requestParameters.episodeId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {V1alpha1EpisodeCollectionApiFindEpisodeCollectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1EpisodeCollectionApi
   */
  public findEpisodeCollection(
    requestParameters: V1alpha1EpisodeCollectionApiFindEpisodeCollectionRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1EpisodeCollectionApiFp(this.configuration)
      .findEpisodeCollection(
        requestParameters.userId,
        requestParameters.episodeId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1EpisodeCollectionApi
   */
  public findEpisodeCollectionsByUserIdAndSubjectId(
    requestParameters: V1alpha1EpisodeCollectionApiFindEpisodeCollectionsByUserIdAndSubjectIdRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1EpisodeCollectionApiFp(this.configuration)
      .findEpisodeCollectionsByUserIdAndSubjectId(
        requestParameters.userId,
        requestParameters.subjectId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {V1alpha1EpisodeCollectionApiSaveEpisodeCollectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1EpisodeCollectionApi
   */
  public saveEpisodeCollection(
    requestParameters: V1alpha1EpisodeCollectionApiSaveEpisodeCollectionRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1EpisodeCollectionApiFp(this.configuration)
      .saveEpisodeCollection(
        requestParameters.userId,
        requestParameters.episodeId,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1EpisodeCollectionApi
   */
  public updateEpisodeCollection(
    requestParameters: V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1EpisodeCollectionApiFp(this.configuration)
      .updateEpisodeCollection(
        requestParameters.userId,
        requestParameters.episodeId,
        requestParameters.progress,
        requestParameters.duration,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinishRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1EpisodeCollectionApi
   */
  public updateEpisodeCollectionFinish(
    requestParameters: V1alpha1EpisodeCollectionApiUpdateEpisodeCollectionFinishRequest,
    options?: AxiosRequestConfig
  ) {
    return V1alpha1EpisodeCollectionApiFp(this.configuration)
      .updateEpisodeCollectionFinish(
        requestParameters.userId,
        requestParameters.episodeId,
        requestParameters.finish,
        options
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
