/* tslint:disable */
/* eslint-disable */
/**
 * Ikaros Open API Documentation
 * Documentation for Ikaros Open API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
/**
 * V1alpha1NotifyApi - axios parameter creator
 * @export
 */
export const V1alpha1NotifyApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Test mail send
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testMailSend: async (
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1alpha1/notify/mail/test`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * V1alpha1NotifyApi - functional programming interface
 * @export
 */
export const V1alpha1NotifyApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    V1alpha1NotifyApiAxiosParamCreator(configuration);
  return {
    /**
     * Test mail send
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testMailSend(
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.testMailSend(
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * V1alpha1NotifyApi - factory interface
 * @export
 */
export const V1alpha1NotifyApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = V1alpha1NotifyApiFp(configuration);
  return {
    /**
     * Test mail send
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testMailSend(options?: AxiosRequestConfig): AxiosPromise<void> {
      return localVarFp
        .testMailSend(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * V1alpha1NotifyApi - object-oriented interface
 * @export
 * @class V1alpha1NotifyApi
 * @extends {BaseAPI}
 */
export class V1alpha1NotifyApi extends BaseAPI {
  /**
   * Test mail send
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof V1alpha1NotifyApi
   */
  public testMailSend(options?: AxiosRequestConfig) {
    return V1alpha1NotifyApiFp(this.configuration)
      .testMailSend(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
