<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { useRoute } from "vue-router"; import { http } from "@/utils/http";
type Row = Record<string, unknown>; const route = useRoute(); const rows = ref<Row[]>([]); const devices = ref<Row[]>([]); const loading = ref(false); const error = ref(""); const length = ref(20); const generated = ref("");
const page = computed(() => String(route.path.split("/").pop())); const title = computed(() => ({ passwords: "密码保险库", generator: "密码生成器", health: "密码健康", devices: "密码设备" }[page.value] || "密码管理"));
async function load() { loading.value = true; error.value = ""; try { if (page.value === "devices") { const r = await http.get<unknown, unknown>("/password/devices"); devices.value = Array.isArray(r) ? r as Row[] : []; } else { const r = await http.get<unknown, unknown>("/password/vaults"); rows.value = Array.isArray(r) ? r as Row[] : []; } } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "密码数据加载失败"; } finally { loading.value = false; } }
async function generate() { try { const r = await http.post<unknown, unknown>("/password/generator/password", { data: { length: length.value } }); generated.value = String((r as Row)?.value || (r as Row)?.secret || "已生成（仅当前页面显示）"); } catch { error.value = "生成器接口暂不可用"; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">{{ title }}</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">敏感字段默认不显示，解锁和导出遵循密码保险库安全策略。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4"/><el-card v-if="page === 'generator'" shadow="never"><el-form inline><el-form-item label="长度"><el-input-number v-model="length" :min="8" :max="128"/></el-form-item><el-button type="primary" @click="generate">生成密码</el-button></el-form><el-alert v-if="generated" :title="generated" type="success" show-icon class="mt-4"/></el-card><el-card v-else shadow="never"><el-empty v-if="!(page === 'devices' ? devices : rows).length" description="暂无数据或保险库尚未解锁"/><el-table v-else :data="page === 'devices' ? devices : rows" stripe><el-table-column prop="id" label="技术标识" min-width="240"/><el-table-column prop="name" label="名称" min-width="180"/><el-table-column prop="status" label="状态" width="140"/><el-table-column prop="securityProfile" label="安全策略" min-width="160"/><el-table-column prop="lastSeenAt" label="最近同步" min-width="180"/></el-table></el-card></main></template>
