#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Sep 09 21:58:28 CST 2026
maven-metadata-central.xml.error=Could not transfer metadata org.jetbrains.kotlin/maven-metadata.xml from/to central (https\://repo.maven.apache.org/maven2)\: Permission denied\: getsockopt
maven-metadata-central.xml/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1788962308432
