ikaros:
  persistence:
    incompact:
      file-dir-prefix: build/upload

server:
  port: 9090
  shutdown: graceful
  forward-headers-strategy: native
  compression:
    enabled: true


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./build/db/ikaros;AUTO_SERVER=TRUE
    username: admin
    password: 123456


  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB


  thymeleaf:
    cache: false

logging:
  level:
    cn.liguohao.ikaros: DEBUG
  file:
    name: ./build/logs/ikaros.log


