<script setup lang="ts">
import { onMounted, ref } from "vue"; import { http } from "@/utils/http";
type User = { id?: string; username?: string; displayName?: string; email?: string; bio?: string; locale?: string; timeZone?: string; status?: string; roleCodes?: string[]; createdAt?: string; lastLoginAt?: string };
const user = ref<User | null>(null); const loading = ref(false); const saving = ref(false); const error = ref(""); const editing = ref(false); const form = ref({ displayName: "", bio: "", locale: "zh-CN", timeZone: "Asia/Shanghai" });
async function load() { loading.value = true; error.value = ""; try { user.value = await http.get<unknown, User>("/me"); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "个人资料加载失败"; } finally { loading.value = false; } }
function beginEdit() { form.value = { displayName: user.value?.displayName || "", bio: user.value?.bio || "", locale: user.value?.locale || "zh-CN", timeZone: user.value?.timeZone || "Asia/Shanghai" }; editing.value = true; } async function save() { saving.value = true; try { await http.request("put", "/me", { data: form.value }); editing.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "个人资料保存失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">个人资料</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理你的显示信息与个人账号资料。</p></div><div class="flex gap-2"><el-button v-if="user && !editing" type="primary" @click="beginEdit">编辑资料</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="7" animated/><el-card v-else shadow="never"><el-empty v-if="!user" description="暂无个人资料"/><template v-else-if="!editing"><div class="flex items-center gap-4 mb-6"><el-avatar :size="64">{{ (user.displayName || user.username || '?').slice(0, 1) }}</el-avatar><div><div class="text-xl font-medium">{{ user.displayName || '未设置显示名称' }}</div><div class="text-sm text-[var(--el-text-color-secondary)]">{{ user.username || '—' }}</div></div></div><el-descriptions :column="1" border><el-descriptions-item label="主邮箱">{{ user.email || '未设置' }} <el-tag size="small" class="ml-2">验证状态由服务端提供</el-tag></el-descriptions-item><el-descriptions-item label="个人简介">{{ user.bio || '未设置' }}</el-descriptions-item><el-descriptions-item label="语言 / 时区">{{ user.locale || '—' }} / {{ user.timeZone || '—' }}</el-descriptions-item><el-descriptions-item label="用户名 / 登录名">{{ user.username || '—' }}（只读）</el-descriptions-item><el-descriptions-item label="账号状态"><el-tag>{{ user.status || '未知' }}</el-tag></el-descriptions-item><el-descriptions-item label="角色">{{ user.roleCodes?.join('、') || '—' }}</el-descriptions-item><el-descriptions-item label="账号创建时间">{{ user.createdAt || '—' }}</el-descriptions-item><el-descriptions-item label="最近登录时间">{{ user.lastLoginAt || '—' }}</el-descriptions-item></el-descriptions></template><el-form v-else label-position="top" class="max-w-xl"><el-form-item label="显示名称"><el-input v-model="form.displayName" maxlength="100"/></el-form-item><el-form-item label="个人简介"><el-input v-model="form.bio" type="textarea" maxlength="500"/></el-form-item><el-form-item label="语言"><el-select v-model="form.locale" class="w-full"><el-option label="简体中文" value="zh-CN"/><el-option label="English" value="en-US"/></el-select></el-form-item><el-form-item label="时区"><el-select v-model="form.timeZone" class="w-full"><el-option label="Asia/Shanghai" value="Asia/Shanghai"/><el-option label="UTC" value="UTC"/></el-select></el-form-item><el-alert title="用户名和主邮箱需通过独立安全流程修改" type="info" :closable="false"/><div class="flex gap-2 mt-5"><el-button @click="editing = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></div></el-form></el-card></main></template>
