<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type User = { id?: string; username?: string; displayName?: string; email?: string; status?: string; roleCodes?: string[]; createdAt?: string; lastLoginAt?: string };
const user = ref<User | null>(null); const loading = ref(false); const error = ref("");
async function load() { loading.value = true; error.value = ""; try { user.value = await http.get<unknown, User>("/me"); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "个人资料加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">个人资料</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理你的显示信息与个人账号资料。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="7" animated/><el-card v-else shadow="never"><el-empty v-if="!user" description="暂无个人资料"/><el-descriptions v-else :column="1" border><el-descriptions-item label="头像"><el-avatar>{{ (user.displayName || user.username || '?').slice(0, 1) }}</el-avatar></el-descriptions-item><el-descriptions-item label="显示名称">{{ user.displayName || '未设置' }}</el-descriptions-item><el-descriptions-item label="用户名 / 登录名">{{ user.username || '—' }}</el-descriptions-item><el-descriptions-item label="主邮箱">{{ user.email || '未设置' }} <el-tag size="small" class="ml-2">验证状态由服务端提供</el-tag></el-descriptions-item><el-descriptions-item label="账号状态"><el-tag>{{ user.status || '未知' }}</el-tag></el-descriptions-item><el-descriptions-item label="角色">{{ user.roleCodes?.join('、') || '—' }}</el-descriptions-item><el-descriptions-item label="账号创建时间">{{ user.createdAt || '—' }}</el-descriptions-item><el-descriptions-item label="最近登录时间">{{ user.lastLoginAt || '—' }}</el-descriptions-item></el-descriptions></el-card></main></template>
