<script setup lang="ts">
import { ref, watch } from 'vue'
import { ElButton, ElSwitch, ElTag } from 'element-plus'
const storageKey = 'ikaros-console-security-preferences'; const stored = (() => { try { return JSON.parse(localStorage.getItem(storageKey) || '{}') as Partial<{ mfa: boolean; stepUp: boolean }> } catch { return {} } })(); const toast = ref(''); const mfa = ref(stored.mfa ?? true); const stepUp = ref(stored.stepUp ?? true)
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
function save() { localStorage.setItem(storageKey, JSON.stringify({ mfa: mfa.value, stepUp: stepUp.value })); notify('安全偏好已保存为本地草稿；后端尚未提供同步接口') }
watch([mfa, stepUp], () => localStorage.setItem(storageKey, JSON.stringify({ mfa: mfa.value, stepUp: stepUp.value })))
</script>
<template><div class="account-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">账户安全</span><span class="mini-avatar">陈</span></header><main class="account-main"><p class="eyebrow">个人账户</p><h1>我的安全</h1><p class="account-subtitle">管理登录凭据、验证级别与个人会话；Secret Material 不会在页面展示。</p><nav class="account-tabs"><RouterLink to="/console/account/profile">个人资料</RouterLink><RouterLink to="/console/account/preferences">偏好设置</RouterLink><RouterLink to="/console/account/security" class="active">安全</RouterLink><RouterLink to="/console/account/notifications">通知</RouterLink></nav><section class="account-security-grid"><article class="account-card surface-card"><div class="card-heading"><div><h2>登录保护</h2><p>高风险操作会要求重新验证。</p></div><el-tag type="success">已启用</el-tag></div><div class="switch-line"><span><b>多因素认证（MFA）</b><small>管理员账户必须完成额外验证</small></span><el-switch v-model="mfa" /></div><div class="switch-line"><span><b>Step-up Verification</b><small>权限、密钥和恢复操作提升验证等级</small></span><el-switch v-model="stepUp" /></div><el-button @click="notify('修改密码流程已打开')">修改密码</el-button></article><article class="account-card surface-card"><div class="card-heading"><div><h2>当前会话</h2><p>仅展示摘要，不暴露 Token。</p></div><el-tag type="info">1 个活跃</el-tag></div><div class="security-session"><span class="session-dot"></span><div><b>当前浏览器</b><small>本地环境 · 刚刚活跃</small></div><el-tag type="success">当前</el-tag></div><RouterLink class="text-button" to="/console/security/sessions">管理全部会话 →</RouterLink></article></section><div class="account-actions"><el-button type="primary" @click="save">保存设置</el-button></div></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
