<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElButton, ElForm, ElFormItem, ElInput, ElOption, ElSelect, ElSwitch } from 'element-plus'

const route = useRoute(); const saved = ref(false); const storageKey = 'ikaros-console-account-preferences'; const stored = (() => { try { return JSON.parse(localStorage.getItem(storageKey) || '{}') as Partial<{ language: string; density: string; displayName: string; email: string }> } catch { return {} } })(); const language = ref(stored.language || '简体中文'); const density = ref(stored.density || '舒适'); const displayName = ref(stored.displayName || '陈昊'); const email = ref(stored.email || 'name@example.com')
const preferences = computed(() => route.path.endsWith('/preferences'))
function save() { localStorage.setItem(storageKey, JSON.stringify({ language: language.value, density: density.value, displayName: displayName.value, email: email.value })); saved.value = true; window.setTimeout(() => saved.value = false, 2400) }
</script>

<template><div class="account-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">账户设置</span><span class="mini-avatar">陈</span></header><main class="account-main"><p class="eyebrow">个人账户</p><h1>{{ preferences ? '偏好设置' : '个人资料' }}</h1><p class="account-subtitle">{{ preferences ? '管理 Console 的显示、语言与工作习惯。' : '管理你的公开资料和登录身份信息。' }}</p><nav class="account-tabs"><RouterLink to="/console/account/profile" :class="{ active: !preferences }">个人资料</RouterLink><RouterLink to="/console/account/preferences" :class="{ active: preferences }">偏好设置</RouterLink></nav><section class="account-card surface-card"><el-form label-position="top"><template v-if="!preferences"><div class="account-avatar">陈</div><el-form-item label="显示名称"><el-input v-model="displayName" /></el-form-item><el-form-item label="登录邮箱"><el-input v-model="email" type="email" /></el-form-item><el-form-item label="账户角色"><el-input model-value="管理员" disabled /></el-form-item><p class="account-note">登录身份变更可能需要重新验证；敏感凭据不会在此页面展示。</p></template><template v-else><el-form-item label="语言"><el-select v-model="language"><el-option label="简体中文" value="简体中文" /><el-option label="English" value="English" /></el-select></el-form-item><el-form-item label="列表密度"><el-select v-model="density"><el-option label="舒适" value="舒适" /><el-option label="紧凑" value="紧凑" /></el-select></el-form-item><div class="switch-line"><span><b>操作后显示确认提示</b><small>重要操作完成后显示 Snackbar 反馈</small></span><el-switch :model-value="true" /></div><div class="switch-line"><span><b>跟随系统主题</b><small>也可通过侧边栏主题按钮切换</small></span><el-switch :model-value="true" /></div></template><div class="account-actions"><span v-if="saved" class="success-text">✓ 已保存</span><el-button type="primary" @click="save">保存设置</el-button></div></el-form></section></main></div></template>
