<script setup lang="ts">
import { ref } from 'vue'
import { ElButton, ElForm, ElFormItem, ElOption, ElSelect, ElSwitch, ElTimePicker } from 'element-plus'

type NotificationPreferences = { product: boolean; task: boolean; security: boolean; quietHours: boolean; quietStart: string; quietEnd: string; timeZone: string; digest: string }
const storageKey = 'ikaros-console-notification-preferences'
const defaults: NotificationPreferences = { product: true, task: true, security: true, quietHours: false, quietStart: '22:00', quietEnd: '07:00', timeZone: 'Asia/Shanghai', digest: 'off' }
function readPreferences(): NotificationPreferences { try { return { ...defaults, ...JSON.parse(localStorage.getItem(storageKey) || '{}') } } catch { return { ...defaults } } }
const saved = readPreferences(); const toast = ref(''); const product = ref(saved.product); const task = ref(saved.task); const security = ref(saved.security); const quietHours = ref(saved.quietHours); const quietStart = ref(saved.quietStart); const quietEnd = ref(saved.quietEnd); const timeZone = ref(saved.timeZone); const digest = ref(saved.digest)
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
function save() { localStorage.setItem(storageKey, JSON.stringify({ product: product.value, task: task.value, security: security.value, quietHours: quietHours.value, quietStart: quietStart.value, quietEnd: quietEnd.value, timeZone: timeZone.value, digest: digest.value })); notify('通知偏好已保存到当前浏览器（未同步后端）') }
</script>
<template><div class="account-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">通知偏好</span><span class="mini-avatar">陈</span></header><main class="account-main"><p class="eyebrow">个人账户</p><h1>通知偏好</h1><p class="account-subtitle">管理个人通知渠道；强制安全通知不可关闭。</p><nav class="account-tabs"><RouterLink to="/console/account/profile">个人资料</RouterLink><RouterLink to="/console/account/preferences">偏好设置</RouterLink><RouterLink to="/console/account/security">安全</RouterLink><RouterLink to="/console/account/notifications" class="active">通知</RouterLink></nav><section class="account-card surface-card"><h2>通知类别</h2><div class="switch-line"><span><b>产品与资源动态</b><small>资源同步、分享和内容更新</small></span><el-switch v-model="product" /></div><div class="switch-line"><span><b>后台任务通知</b><small>备份、导入、恢复和失败任务</small></span><el-switch v-model="task" /></div><div class="switch-line"><span><b>安全通知</b><small>登录异常、会话撤销和权限变更；由安全策略强制启用</small></span><el-switch v-model="security" disabled /></div><p class="account-note">安全通知始终允许穿透免打扰；私密域和财务域内容不会因开启通知而绕过授权。</p></section><section class="account-card surface-card"><div class="card-heading"><div><h2>免打扰时段</h2><p>跨午夜时段按本地时区解释，例如 22:00–07:00。</p></div><el-switch v-model="quietHours" active-text="启用免打扰" /></div><el-form label-position="top" class="preference-fields"><el-form-item label="开始时间"><el-time-picker v-model="quietStart" format="HH:mm" value-format="HH:mm" :disabled="!quietHours" /></el-form-item><el-form-item label="结束时间"><el-time-picker v-model="quietEnd" format="HH:mm" value-format="HH:mm" :disabled="!quietHours" /></el-form-item><el-form-item label="时区"><el-select v-model="timeZone" :disabled="!quietHours"><el-option label="Asia/Shanghai" value="Asia/Shanghai" /><el-option label="UTC" value="UTC" /><el-option label="America/Los_Angeles" value="America/Los_Angeles" /></el-select></el-form-item></el-form></section><section class="account-card surface-card"><h2>摘要</h2><p class="account-subtitle">即时通知关闭后不会自动进入摘要；两项设置独立生效。</p><el-select v-model="digest"><el-option label="关闭摘要" value="off" /><el-option label="每日" value="daily" /><el-option label="每周" value="weekly" /></el-select></section><div class="account-actions"><span v-if="toast" class="success-text">✓ 已保存</span><el-button type="primary" @click="save">保存偏好</el-button></div></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
