<script setup lang="ts">
import { ref } from 'vue'

type NotificationPreferences = { product: boolean; task: boolean; security: boolean; quietHours: boolean; quietStart: string; quietEnd: string; timeZone: string; digest: string }
const storageKey = 'ikaros-console-notification-preferences'
const defaults: NotificationPreferences = { product: true, task: true, security: true, quietHours: false, quietStart: '22:00', quietEnd: '07:00', timeZone: 'Asia/Shanghai', digest: 'off' }
function readPreferences(): NotificationPreferences { try { return { ...defaults, ...JSON.parse(localStorage.getItem(storageKey) || '{}') } } catch { return { ...defaults } } }
const saved = readPreferences(); const toast = ref(''); const product = ref(saved.product); const task = ref(saved.task); const security = ref(saved.security); const quietHours = ref(saved.quietHours); const quietStart = ref(saved.quietStart); const quietEnd = ref(saved.quietEnd); const timeZone = ref(saved.timeZone); const digest = ref(saved.digest)
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
function save() { localStorage.setItem(storageKey, JSON.stringify({ product: product.value, task: task.value, security: security.value, quietHours: quietHours.value, quietStart: quietStart.value, quietEnd: quietEnd.value, timeZone: timeZone.value, digest: digest.value })); notify('通知偏好已保存到当前浏览器（未同步后端）') }
</script>
<template><div class="account-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">通知偏好</span><span class="mini-avatar">陈</span></header><main class="account-main"><p class="eyebrow">个人账户</p><h1>通知偏好</h1><p class="account-subtitle">管理个人通知渠道；强制安全通知不可关闭。</p><nav class="account-tabs"><RouterLink to="/console/account/profile">个人资料</RouterLink><RouterLink to="/console/account/preferences">偏好设置</RouterLink><RouterLink to="/console/account/security">安全</RouterLink><RouterLink to="/console/account/notifications" class="active">通知</RouterLink></nav><section class="account-card surface-card"><h2>通知类别</h2><label class="switch-line"><span><b>产品与资源动态</b><small>资源同步、分享和内容更新</small></span><input v-model="product" type="checkbox" /></label><label class="switch-line"><span><b>后台任务通知</b><small>备份、导入、恢复和失败任务</small></span><input v-model="task" type="checkbox" /></label><label class="switch-line"><span><b>安全通知</b><small>登录异常、会话撤销和权限变更；由安全策略强制启用</small></span><input v-model="security" type="checkbox" disabled /></label><p class="account-note">安全通知始终允许穿透免打扰；私密域和财务域内容不会因开启通知而绕过授权。</p></section><section class="account-card surface-card"><div class="card-heading"><div><h2>免打扰时段</h2><p>跨午夜时段按本地时区解释，例如 22:00–07:00。</p></div><label class="switch-line compact-switch"><span><b>启用免打扰</b></span><input v-model="quietHours" type="checkbox" /></label></div><div class="preference-fields"><label>开始时间<input v-model="quietStart" type="time" :disabled="!quietHours" /></label><label>结束时间<input v-model="quietEnd" type="time" :disabled="!quietHours" /></label><label>时区<select v-model="timeZone" :disabled="!quietHours"><option>Asia/Shanghai</option><option>UTC</option><option>America/Los_Angeles</option></select></label></div></section><section class="account-card surface-card"><h2>摘要</h2><p class="account-subtitle">即时通知关闭后不会自动进入摘要；两项设置独立生效。</p><label>摘要频率<select v-model="digest"><option value="off">关闭摘要</option><option value="daily">每日</option><option value="weekly">每周</option></select></label></section><div class="account-actions"><span v-if="toast" class="success-text">✓ 已保存</span><button class="filled-button" @click="save">保存偏好</button></div></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
