<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute(); const query = ref(''); const toast = ref(''); const selected = ref<string | null>(null)
const catalogs: Record<string, { eyebrow: string; title: string; description: string; columns: string[]; rows: { id: string; name: string; detail: string; status: string; updated: string }[] }> = {
  parameters: { eyebrow: '平台配置', title: '参数', description: '管理可审计的运行参数；外部部署锁定的值会明确标识。', columns: ['参数名', '当前值', '来源', '最近更新'], rows: [{ id: 'default-timezone', name: 'default.timezone', detail: 'Asia/Shanghai', status: '部署配置', updated: '今天 09:10' }, { id: 'session-idle', name: 'security.session.idle', detail: '30 分钟', status: '平台默认', updated: '昨天' }, { id: 'upload-limit', name: 'storage.upload.limit', detail: '5 GB', status: '部署配置', updated: '2026-08-28' }] },
  dictionaries: { eyebrow: '平台配置', title: '字典', description: '维护受约束的展示选项，变更会影响表单与状态标签。', columns: ['字典编码', '条目数量', '用途', '状态'], rows: [{ id: 'resource-type', name: 'resource.type', detail: '8 项', status: '资源分类', updated: '已启用' }, { id: 'task-state', name: 'task.state', detail: '6 项', status: '后台任务', updated: '已启用' }, { id: 'notification-channel', name: 'notification.channel', detail: '4 项', status: '通知渠道', updated: '草稿' }] },
  menus: { eyebrow: '平台配置', title: '菜单', description: '维护 Console 导航结构、排序与可见性；权限校验仍由后端独立执行。', columns: ['菜单名称', '路由', '可见性', '排序'], rows: [{ id: 'dashboard', name: '概览', detail: '/console/dashboard', status: '所有管理员', updated: '01' }, { id: 'security', name: '身份与安全', detail: '/console/security/*', status: '需要权限', updated: '10' }, { id: 'operations', name: '系统运维', detail: '/console/ops/*', status: '需要权限', updated: '20' }] },
  audit: { eyebrow: '沟通与审计', title: '审计日志', description: '只读查看关键操作引用；敏感字段不会在普通列表中展开。', columns: ['动作', '主体', '目标', '时间'], rows: [{ id: 'audit-1', name: 'identity.role.create', detail: '管理员 · 陈昊', status: 'ROLE · 已记录', updated: '刚刚' }, { id: 'audit-2', name: 'identity.session.revoke', detail: '管理员 · 陈昊', status: 'SESSION · 已记录', updated: '今天 08:42' }, { id: 'audit-3', name: 'resource.archive', detail: '用户 · 陈昊', status: 'RESOURCE · 已记录', updated: '昨天 18:24' }] }
}
const kind = computed(() => route.path.includes('/parameters') ? 'parameters' : route.path.includes('/dictionaries') ? 'dictionaries' : route.path.includes('/menus') ? 'menus' : 'audit')
const catalog = computed(() => catalogs[kind.value])
const rows = computed(() => catalog.value.rows.filter(row => `${row.name} ${row.detail} ${row.status}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2600) }
</script>

<template><div class="catalog-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">本地环境 · 管理控制台</span><button class="icon-button" @click="notify('主题设置请从头像菜单进入')">◐</button><span class="mini-avatar">陈</span></header><main class="catalog-main"><div class="catalog-heading"><div><p class="eyebrow">{{ catalog.eyebrow }}</p><h1>{{ catalog.title }}</h1><p>{{ catalog.description }}</p></div><button v-if="kind !== 'audit'" class="filled-button" @click="notify('已打开新建表单')">＋ 新建</button></div><div class="catalog-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" placeholder="筛选当前列表" /></div><span class="status-chip neutral">{{ rows.length }} 项</span><button class="outlined-button small" @click="query = ''; notify('筛选已清除')">重置</button></div><section class="catalog-table surface-card"><table><thead><tr><th v-for="column in catalog.columns" :key="column">{{ column }}</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id" @click="selected = row.id"><td><b>{{ row.name }}</b></td><td>{{ row.detail }}</td><td><span class="status-chip" :class="row.status.includes('草稿') ? 'warning' : 'success'">● {{ row.status }}</span></td><td class="muted-text">{{ row.updated }}</td><td><button class="icon-button compact" @click.stop="selected = row.id">⋮</button></td></tr><tr v-if="rows.length === 0"><td :colspan="catalog.columns.length + 1" class="no-results">没有匹配结果</td></tr></tbody></table><div class="catalog-footer"><span>显示 {{ rows.length }} 项</span><button class="text-button" @click="notify('已刷新目录')">⟳ 刷新</button></div></section><aside v-if="selected" class="catalog-detail surface-card"><div><p class="eyebrow">只读详情</p><h2>{{ catalog.rows.find(row => row.id === selected)?.name }}</h2><p>{{ catalog.rows.find(row => row.id === selected)?.detail }}</p></div><button class="icon-button" @click="selected = null">×</button><div class="detail-callout"><span>i</span><p>此页面遵循最小权限与审计策略。修改操作将在后续确认流程中执行。</p></div></aside></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
