<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ApiError, api, unwrapPage } from './services/api'
import { getRouteMeta } from './config/route-meta'

type Item = { label: string; path: string; icon: string; capability?: string }
type Group = { label: string; icon: string; items: Item[] }
const router = useRouter(); const route = useRoute()
const groups: Group[] = [
  { label: '工作台', icon: '⌂', items: [{ label: '概览', path: 'dashboard', icon: '▦' }, { label: '全局搜索', path: 'search', icon: '⌕' }, { label: '我的活动与收藏', path: 'activity', icon: '◷' }] },
  { label: '内容与创作', icon: '▤', items: [{ label: '统一资源库', path: 'library', icon: '◈' }, { label: '集合与标签', path: 'collections', icon: '▧' }, { label: '文章与文档', path: 'documents', icon: '□' }, { label: '媒体消费', path: 'media', icon: '▶' }, { label: '分享与协作', path: 'sharing', icon: '♧' }] },
  { label: '个人网盘', icon: '☁', items: [{ label: '文件空间', path: 'drive', icon: '▰' }, { label: '空间治理', path: 'drive/spaces', icon: '◫' }, { label: '传输中心', path: 'drive/transfers', icon: '⇄' }, { label: '同步关系', path: 'drive/sync', icon: '⟳' }, { label: '冲突处理', path: 'drive/conflicts', icon: '⚠' }, { label: '版本历史', path: 'drive/revisions', icon: '↶' }, { label: '回收站', path: 'drive/trash', icon: '⌫' }, { label: '配额与策略', path: 'drive/quota', icon: '◫' }, { label: 'Drive Policies', path: 'drive/policies', icon: '⚙' }] },
  { label: '附件与存储', icon: '▣', items: [{ label: '附件与 Blob', path: 'attachments', icon: '⊙' }, { label: '存储层', path: 'storage/tiers', icon: '▥' }, { label: '缓存与下载', path: 'storage/cache', icon: '⇩' }, { label: '归档与恢复', path: 'storage/archive', icon: '↶' }, { label: '备份与恢复', path: 'storage/backup', icon: '⟳' }] },
  { label: '效率与计划', icon: '✓', items: [{ label: '收集箱与今天', path: 'planning/today', icon: '☀' }, { label: '项目与任务', path: 'planning/projects', icon: '▤' }, { label: '日历与时间块', path: 'planning/calendar', icon: '▦' }, { label: '目标与 OKR', path: 'planning/goals', icon: '↗' }, { label: '习惯与专注', path: 'planning/focus', icon: '◉' }] },
  { label: '个人记账', icon: '¥', items: [{ label: '账本总览', path: 'finance', icon: '◉' }, { label: '账户', path: 'finance/accounts', icon: '▣' }, { label: '交易', path: 'finance/transactions', icon: '⇄' }, { label: '预算与周期账', path: 'finance/budgets', icon: '▤' }, { label: '对账与导入', path: 'finance/reconcile', icon: '↔' }] },
  { label: '私密笔记', icon: '▤', items: [{ label: '保险库', path: 'private-notes', icon: '▣' }, { label: '版本与冲突', path: 'private-notes/conflicts', icon: '↻' }, { label: '恢复与导出', path: 'private-notes/recovery', icon: '↶' }] },
  { label: '密码管理', icon: '♢', items: [{ label: '密码保险库', path: 'passwords', icon: '▣' }, { label: '生成器', path: 'passwords/generator', icon: '✦' }, { label: '健康与安全发送', path: 'passwords/health', icon: '♥' }, { label: '设备与访问', path: 'passwords/devices', icon: '⌁' }] },
  { label: 'AI 智能', icon: '✦', items: [{ label: '助手', path: 'ai/assistant', icon: '✦' }, { label: '模型与提供方', path: 'ai/models', icon: '◇' }, { label: '人格', path: 'ai/personas', icon: '♙' }, { label: '上下文与隐私', path: 'ai/privacy', icon: '▣' }, { label: '作业与用量', path: 'ai/jobs', icon: '◷' }] },
  { label: '数据分析', icon: '⌁', items: [{ label: '个人概览', path: 'analytics', icon: '◒' }, { label: '内容分析', path: 'analytics/content', icon: '▥' }, { label: '存储分析', path: 'analytics/storage', icon: '▥' }, { label: '效率分析', path: 'analytics/planning', icon: '✓' }, { label: '系统历史', path: 'analytics/system', icon: '⌁' }, { label: '指标目录', path: 'analytics/metrics', icon: '≡' }, { label: '报表与重建', path: 'analytics/reports', icon: '▤' }] },
  { label: '集成与自动化', icon: '⚙', items: [{ label: '自动化规则', path: 'integration/automation', icon: '⟳' }, { label: '执行与 Trace', path: 'integration/executions', icon: '▷' }, { label: '事件与失败队列', path: 'integration/events', icon: '⚠' }, { label: '导入与同步', path: 'integration/sync', icon: '⇄' }, { label: '插件与连接器', path: 'integration/plugins', icon: '⊕' }] },
  { label: '身份与安全', icon: '♢', items: [{ label: '用户与角色', path: 'security/users', icon: '♙' }, { label: '权限矩阵', path: 'security/permissions', icon: '▦' }, { label: '活跃会话', path: 'security/sessions', icon: '⌁' }, { label: '认证、密钥与恢复', path: 'security/authentication', icon: '▣' }] },
  { label: '平台配置', icon: '⚙', items: [{ label: '参数', path: 'platform/parameters', icon: '≡' }, { label: '字典', path: 'platform/dictionaries', icon: '▤' }, { label: '菜单', path: 'platform/menus', icon: '☷' }] },
  { label: '沟通与审计', icon: '✉', items: [{ label: '公告', path: 'communications/announcements', icon: '▰' }, { label: '通知中心', path: 'communications/notifications', icon: '♧' }, { label: '通知模板', path: 'communications/templates', icon: '□' }, { label: '通知 Provider', path: 'communications/providers', icon: '⊕' }, { label: '审计日志', path: 'communications/audit', icon: '≡' }, { label: '登录日志', path: 'communications/login-logs', icon: '⌁' }, { label: '安全事件', path: 'communications/security-events', icon: '⚠' }] },
  { label: '系统运维', icon: '♨', items: [{ label: '系统健康与告警', path: 'ops/health', icon: '♥' }, { label: '子系统', path: 'ops/subsystems', icon: '◫' }, { label: '存储健康', path: 'ops/storage-health', icon: '▥' }, { label: '定时任务', path: 'ops/jobs', icon: '◷' }, { label: '后台任务', path: 'ops/background', icon: '⇄' }, { label: '插件运行时', path: 'ops/plugins', icon: '⊕' }] }
]
const preferenceKey = 'ikaros-console-preferences'
const storedPreferences = (() => { try { return JSON.parse(localStorage.getItem(preferenceKey) || '{}') as { expanded?: string[]; theme?: Theme } } catch { return {} } })()
type Theme = 'system' | 'light' | 'dark'
const expanded = ref<string[]>(storedPreferences.expanded || []); const theme = ref<Theme>(storedPreferences.theme || 'system'); const drawer = ref(false); const dialog = ref(''); const toast = ref(''); const query = ref(String(route.query.q || '')); const statusFilter = ref('全部状态'); const selectedRows = ref<string[]>([]); const selectedTab = ref('概览'); const loading = ref(false); const apiConnected = ref(false); const errorState = ref<{ status: number; title: string; detail: string } | null>(null)
const currentPath = computed(() => Array.isArray(route.params.pathMatch) ? route.params.pathMatch.join('/') : String(route.params.pathMatch || 'dashboard'))
const current = computed(() => groups.flatMap(g => g.items).find(i => i.path === currentPath.value) || groups[0].items[0])
const currentGroup = computed(() => groups.find(g => g.items.some(i => i.path === currentPath.value)) || groups[0])
const currentMeta = computed(() => getRouteMeta(currentPath.value))
const pageTitle = computed(() => current.value.label)
function go(path: string) { router.push(path === 'login' ? '/login' : '/console/' + path); drawer.value = false }
function toggle(label: string) { expanded.value = expanded.value.includes(label) ? expanded.value.filter(v => v !== label) : [...expanded.value, label] }
function notify(message: string) { if (message === '已全部标为已读') notifications.value = notifications.value.map(item => ({ ...item, unread: false })); if (message === '账号恢复流程即将开放') { router.push('/recovery'); return } toast.value = message; setTimeout(() => toast.value = '', 2800) }
function openDialog(kind: string) { dialog.value = kind }
const systemThemeQuery = window.matchMedia('(prefers-color-scheme: dark)')
function applyTheme(value: Theme) { const dark = value === 'dark' || (value === 'system' && systemThemeQuery.matches); document.documentElement.dataset.theme = value; document.documentElement.classList.toggle('dark', dark); localStorage.setItem(preferenceKey, JSON.stringify({ expanded: expanded.value, theme: value })) }
function handleSystemThemeChange() { if (theme.value === 'system') applyTheme('system') }
function cycleTheme() { theme.value = theme.value === 'system' ? 'light' : theme.value === 'light' ? 'dark' : 'system'; applyTheme(theme.value); notify(`主题：${theme.value === 'system' ? '跟随系统' : theme.value === 'light' ? '浅色' : '深色'}`) }
function submitSearch() { if (!isSearch.value) go('search'); router.replace({ query: query.value ? { q: query.value } : {} }); notify(query.value ? `已搜索：${query.value}` : '已恢复全部结果') }
function handleShortcut(event: KeyboardEvent) { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); go('search'); requestAnimationFrame(() => document.querySelector<HTMLInputElement>('.search-box input')?.focus()) } }
const filteredRows = computed(() => rows.value.filter(row => { const matchesQuery = !query.value || `${row.name} ${row.owner} ${row.status}`.toLowerCase().includes(query.value.toLowerCase()); const matchesStatus = statusFilter.value === '全部状态' || row.status === statusFilter.value; return matchesQuery && matchesStatus }))
function setStatusFilter(value: string) { statusFilter.value = statusFilter.value === value ? '全部状态' : value }
const allVisibleSelected = computed(() => filteredRows.value.length > 0 && filteredRows.value.every(row => selectedRows.value.includes(row.name)))
function toggleRow(name: string) { selectedRows.value = selectedRows.value.includes(name) ? selectedRows.value.filter(item => item !== name) : [...selectedRows.value, name] }
function toggleAll() { selectedRows.value = allVisibleSelected.value ? selectedRows.value.filter(name => !filteredRows.value.some(row => row.name === name)) : [...new Set([...selectedRows.value, ...filteredRows.value.map(row => row.name)])] }
function clearSelection() { selectedRows.value = [] }
const isDashboard = computed(() => currentPath.value === 'dashboard'); const isSearch = computed(() => currentPath.value === 'search')
const isHealth = computed(() => currentPath.value === 'ops/health')
const isUsers = computed(() => currentPath.value === 'security/users')
const isPermissions = computed(() => currentPath.value === 'security/permissions')
const isNotifications = computed(() => currentPath.value === 'communications/notifications')
const isAnnouncements = computed(() => currentPath.value === 'communications/announcements')
const securityStats = [{ label: '活跃用户', value: '24', detail: '最近 7 天有活动', tone: 'teal' }, { label: '已启用 MFA', value: '21', detail: '覆盖率 87.5%', tone: 'primary' }, { label: '待激活', value: '2', detail: '需要发送邀请', tone: 'orange' }, { label: '安全提醒', value: '1', detail: '建议及时处理', tone: 'pink' }]
const permissionGroups = [{ name: '内容与创作', items: [{ key: 'resource.read', label: '读取资源', enabled: true }, { key: 'resource.write', label: '编辑资源', enabled: true }, { key: 'resource.delete', label: '删除资源', enabled: false }] }, { name: '身份与安全', items: [{ key: 'system.user.read', label: '查看用户', enabled: true }, { key: 'system.role.manage', label: '管理角色', enabled: false }, { key: 'system.session.manage', label: '管理会话', enabled: false }] }, { name: '存储管理', items: [{ key: 'storage.provider.manage', label: '管理存储 Provider', enabled: false }, { key: 'resource.download', label: '下载资源', enabled: true }] }]
const stagedPermissions = ref<Record<string, boolean>>({})
const hasStagedPermissions = computed(() => Object.keys(stagedPermissions.value).length > 0)
function togglePermission(key: string, current: boolean) { stagedPermissions.value = { ...stagedPermissions.value, [key]: !current } }
function discardPermissions() { stagedPermissions.value = {}; notify('已放弃权限修改') }
function reviewPermissions() { dialog.value = 'permission-review' }
function applyPermissions() { stagedPermissions.value = {}; dialog.value = ''; notify('权限修改已提交并写入审计') }
const services = [{ name: 'Application / API', status: '健康', latency: '42 ms', icon: '◇' }, { name: 'PostgreSQL', status: '健康', latency: '8 ms', icon: '▣' }, { name: '持久化存储', status: '健康', latency: '116 ms', icon: '▥' }, { name: 'Scheduler / Worker', status: '降级', latency: '队列 12', icon: '◷' }]
const alerts = [{ severity: 'warning', name: '备份任务延迟', component: 'Scheduler / Worker', condition: '队列深度 > 10', time: '2 小时前' }, { severity: 'info', name: '存储容量提醒', component: '持久化存储', condition: '使用率 68%', time: '昨天' }]
const notifications = ref([{ title: '备份任务执行失败', text: '每周资料备份需要你的关注', time: '2 小时前', type: 'error', unread: true }, { title: '资源同步完成', text: '12 个资源的元数据已更新', time: '昨天', type: 'success', unread: true }, { title: '系统健康检查', text: '所有核心服务运行正常', time: '昨天', type: 'info', unread: false }])
const notificationTab = ref('全部')
const unreadNotificationCount = computed(() => notifications.value.filter(item => item.unread).length)
const visibleNotifications = computed(() => notifications.value.filter(item => notificationTab.value === '全部' || (notificationTab.value === '未读' && item.unread) || (notificationTab.value === '系统' && item.type === 'info')))
function markNotificationRead(title?: string) { notifications.value = notifications.value.map(item => title && item.title !== title ? item : { ...item, unread: false }); notify(title ? '已标记为已读' : '已全部标为已读') }
const announcements = [{ title: 'Ikaros Console 维护通知', audience: '全部用户', status: '已发布', publishedAt: '2026-09-01 18:00', expiresAt: '2026-09-08 18:00', tone: 'info' }, { title: '新版本媒体索引已上线', audience: '内容创作者', status: '已发布', publishedAt: '2026-08-28 09:30', expiresAt: '长期有效', tone: 'success' }, { title: '存储策略调整预告', audience: '管理员', status: '草稿', publishedAt: '未发布', expiresAt: '—', tone: 'warning' }]
const announcementTab = ref('全部')
const visibleAnnouncements = computed(() => announcements.filter(item => announcementTab.value === '全部' || item.status === announcementTab.value))
const isLogin = computed(() => route.path === '/login'); const loginEmail = ref(''); const loginPassword = ref(''); const rememberLogin = ref(true); const loginError = ref('')
function submitLogin() { loginError.value = ''; if (!loginEmail.value.trim()) { loginError.value = '请输入用户名或邮箱'; return } if (loginPassword.value.length < 6) { loginError.value = '密码至少需要 6 位'; return } router.push('/console/dashboard'); notify('登录成功，欢迎回来') }
const kpis = [{ label: '资源', value: '12,486', trend: '+8.4%', icon: '◈', tone: 'primary' }, { label: '存储', value: '68.4 GB', trend: '已配置 100 GB', icon: '▥', tone: 'teal' }, { label: '今天', value: '8 / 12', trend: '4 项待完成', icon: '✓', tone: 'orange' }, { label: '后台任务', value: '3', trend: '1 项失败', icon: '⇄', tone: 'purple' }, { label: '通知', value: '6', trend: '2 条重要', icon: '✉', tone: 'pink' }]
const activities = [{ icon: '✦', text: '完成了媒体资源的元数据同步', target: '《星际穿越》', time: '12 分钟前', color: 'purple' }, { icon: '✓', text: '完成任务', target: '整理本周阅读清单', time: '1 小时前', color: 'teal' }, { icon: '↗', text: '更新了项目', target: 'Ikaros V2 产品设计', time: '昨天 18:24', color: 'orange' }, { icon: '♧', text: '收藏了资源', target: 'Material Design 3', time: '昨天 15:08', color: 'blue' }]
const resources = [{ name: '《星际穿越》', type: '电影', tags: ['科幻', '收藏'], status: '进行中', progress: 72, updated: '12 分钟前' }, { name: 'Ikaros V2 产品设计', type: '文档', tags: ['项目'], status: '已更新', progress: 100, updated: '昨天' }, { name: 'Material Design 3', type: '网页', tags: ['设计系统'], status: '收藏', progress: 34, updated: '3 天前' }, { name: '2026 年读书计划', type: '集合', tags: ['计划'], status: '草稿', progress: 18, updated: '5 天前' }]
type TableRow = { id?: string; name: string; owner: string; status: string; updated: string }
const rows = ref<TableRow[]>([{ id: 'demo-backup', name: '媒体资源索引', owner: '系统', status: '已启用', updated: '刚刚' }, { id: 'demo-weekly-backup', name: '每周资料备份', owner: '你', status: '运行中', updated: '8 分钟前' }, { id: 'demo-reading-sync', name: '阅读进度同步', owner: '你', status: '已暂停', updated: '昨天' }, { id: 'demo-storage-health', name: '存储健康检查', owner: '系统', status: '已启用', updated: '昨天' }, { id: 'demo-weekly-report', name: '活动周报', owner: '你', status: '失败', updated: '2 天前' }])
const demoRows = rows.value
const actorId = String(import.meta.env.VITE_ACTOR_ID || '')
async function loadResources() {
  if (isDashboard.value) return
  loading.value = true
  errorState.value = null
  try {
    if (currentPath.value === 'library') {
      const result = unwrapPage(await api.listResources('?limit=5'))
      if (result.length) rows.value = result.map(item => ({ name: item.title || `Resource ${item.id.slice(0, 8)}`, owner: '当前用户', status: item.lifecycle || '已启用', updated: item.updated_at ? new Date(item.updated_at).toLocaleString('zh-CN') : '刚刚' }))
    } else if (currentPath.value === 'security/users') {
      const result = unwrapPage(await api.listUsers('?page=0&size=5'))
      if (result.length) rows.value = result.map(item => ({ name: item.display_name || item.username || item.id.slice(0, 8), owner: item.username || '平台用户', status: item.status || 'ACTIVE', updated: item.last_active_at ? new Date(item.last_active_at).toLocaleString('zh-CN') : '暂无记录' }))
    } else if (currentPath.value === 'ops/background') {
      const result = await api.listBackgroundTasks()
      if (result.length) rows.value = result.slice(0, 5).map(item => ({ id: item.id, name: item.task_type || item.id.slice(0, 8), owner: item.owning_subsystem || '系统', status: item.state || '排队中', updated: item.created_at ? new Date(item.created_at).toLocaleString('zh-CN') : '刚刚' }))
    } else if (currentPath.value === 'security/permissions') {
      const result = await api.listRoles()
      if (result.length) rows.value = result.slice(0, 5).map(item => ({ name: item.name || item.code || item.id.slice(0, 8), owner: `${item.permissions?.length || 0} 项权限`, status: item.builtIn ? '系统角色' : '自定义角色', updated: '权限注册表' }))
    } else if (currentPath.value === 'storage/tiers') {
      const result = await api.listStorageProviders()
      if (result.length) rows.value = result.slice(0, 5).map(item => ({ name: item.providerKey || item.id.slice(0, 8), owner: `${item.providerType || '存储'} · ${item.tier || '默认层'}`, status: item.status || 'DISABLED', updated: item.updatedAt ? new Date(item.updatedAt).toLocaleString('zh-CN') : '刚刚' }))
    } else if (currentPath.value === 'drive' || currentPath.value === 'drive/spaces') {
      const result = await api.listDriveSpaces(actorId)
      if (result.length) rows.value = result.slice(0, 5).map(item => ({ id: item.id, name: item.name || `Drive Space ${item.id.slice(0, 8)}`, owner: '当前用户', status: item.status || 'ACTIVE', updated: item.updated_at ? new Date(item.updated_at).toLocaleString('zh-CN') : '刚刚' }))
    } else if (currentPath.value === 'planning/today') {
      const result = await api.listTodayTasks(actorId)
      if (result.length) rows.value = result.slice(0, 5).map(item => ({ id: item.id, name: item.title || `Task ${item.id.slice(0, 8)}`, owner: item.priority || '普通', status: item.status || 'OPEN', updated: item.due_at ? new Date(item.due_at).toLocaleString('zh-CN') : '今天' }))
    } else return
    apiConnected.value = true
  } catch (error) {
    apiConnected.value = false
    if (error instanceof ApiError && [401, 403, 404, 409, 412].includes(error.status)) {
      errorState.value = { status: error.status, title: error.status === 401 ? '会话已失效' : error.status === 403 ? '你没有权限访问此页面' : error.status === 404 ? '页面或资源不存在' : '数据发生并发冲突', detail: error.problem?.detail || error.message }
    } else { rows.value = demoRows; notify('后端暂不可用，已保留演示数据') }
  } finally { loading.value = false }
}
onMounted(loadResources); watch(currentPath, loadResources)
onMounted(() => applyTheme(theme.value)); watch(expanded, () => applyTheme(theme.value), { deep: true })
watch(() => route.query.q, value => { query.value = String(value || '') })
onMounted(() => window.addEventListener('keydown', handleShortcut)); onBeforeUnmount(() => window.removeEventListener('keydown', handleShortcut))
onMounted(() => systemThemeQuery.addEventListener('change', handleSystemThemeChange)); onBeforeUnmount(() => systemThemeQuery.removeEventListener('change', handleSystemThemeChange))
let refreshTimer: number | undefined
watch(currentPath, value => {
  if (refreshTimer) window.clearInterval(refreshTimer)
  if (value === 'ops/background') refreshTimer = window.setInterval(loadResources, 30000)
}, { immediate: true })
onBeforeUnmount(() => { if (refreshTimer) window.clearInterval(refreshTimer) })
function genericTitle() { return current.value.label }
async function bulkTaskAction(action: 'cancel' | 'retry') {
  if (currentPath.value !== 'ops/background') { dialog.value = ''; notify('已打开批量操作'); return }
  if (action === 'retry') { dialog.value = ''; notify('已提交重试请求'); return }
  const targets = rows.value.filter(row => selectedRows.value.includes(row.name) && row.id && !row.id.startsWith('demo-'))
  try { await Promise.all(targets.map(row => api.cancelBackgroundTask(row.id!))); dialog.value = ''; clearSelection(); await loadResources(); notify(`${targets.length || selectedRows.value.length} 项任务已取消`) } catch (error) { notify(error instanceof Error ? error.message : '取消任务失败') }
}
</script>

<template>
  <div v-if="isLogin" class="login-page"><div class="login-decoration"><div class="login-orb one"></div><div class="login-orb two"></div><span>✦</span></div><main class="login-card"><div class="login-brand"><div class="brand-mark">i</div><div><strong>Ikaros</strong><small>Console</small></div></div><p class="eyebrow">安全访问</p><h1>欢迎回来</h1><p class="login-subtitle">登录你的 Ikaros 工作空间</p><form @submit.prevent="submitLogin"><label>用户名或邮箱<input v-model="loginEmail" type="text" autocomplete="username" placeholder="name@example.com" /></label><label>密码<div class="password-input"><input v-model="loginPassword" type="password" autocomplete="current-password" placeholder="输入密码" /><span>⌁</span></div></label><p v-if="loginError" class="login-error" role="alert">{{ loginError }}</p><div class="login-options"><label class="checkbox-label"><input v-model="rememberLogin" type="checkbox" /> 记住此设备</label><button type="button" class="text-button" @click="notify('账号恢复流程即将开放')">忘记密码？</button></div><button class="filled-button login-button" type="submit">登录 <span>→</span></button></form><p class="login-footnote">首次使用？请联系工作空间管理员完成初始化。</p></main></div><div v-else class="app-shell">
    <aside class="sidebar" :class="{ open: drawer }">
      <div class="brand" @click="go('dashboard')"><div class="brand-mark">i</div><div><strong>Ikaros</strong><span>Console</span></div><span class="env-chip">本地</span></div>
      <div class="quick-actions"><button class="tonal-button" @click="go('search')"><span>⌕</span> 全局搜索 <kbd>⌘ K</kbd></button><button class="icon-button" aria-label="创建" @click="openDialog('create')">＋</button></div>
      <nav class="nav-scroll">
        <div v-for="group in groups" :key="group.label" class="nav-group">
          <button class="group-toggle" @click="toggle(group.label)"><span class="nav-icon">{{ group.icon }}</span><span>{{ group.label }}</span><span class="chevron" :class="{ rotated: expanded.includes(group.label) || currentGroup.label === group.label }">⌄</span></button>
          <div v-if="expanded.includes(group.label) || currentGroup.label === group.label" class="nav-items">
            <button v-for="item in group.items" :key="item.path" class="nav-item" :class="{ active: currentPath === item.path }" @click="go(item.path)"><span class="nav-icon">{{ item.icon }}</span>{{ item.label }}</button>
          </div>
        </div>
      </nav>
      <div class="sidebar-bottom"><button class="bottom-link" @click="notify('帮助中心即将开放')">? <span>帮助中心</span></button><button class="bottom-link" @click="cycleTheme">◐ <span>主题：{{ theme === 'system' ? '跟随系统' : theme === 'light' ? '浅色' : '深色' }}</span></button><div class="profile" @click="openDialog('profile')"><div class="avatar">陈</div><div><b>陈昊</b><small>管理员</small></div><span>•••</span></div></div>
    </aside>
    <main class="main-content">
      <header class="topbar"><button class="menu-button icon-button" @click="drawer = !drawer">☰</button><div class="breadcrumbs"><span>Ikaros Console</span><span>/</span><b>{{ currentGroup.label }}</b><span>/</span><strong>{{ pageTitle }}</strong></div><div class="top-actions"><button class="icon-button" @click="openDialog('tasks')" aria-label="后台任务">⇄<i class="badge">3</i></button><button class="icon-button" @click="openDialog('notifications')" aria-label="通知">♧<i class="badge pink">6</i></button><button class="icon-button" @click="notify('这是当前页面的帮助提示')">?</button><div class="mini-avatar">陈</div></div></header>
      <div class="page-wrap">
        <section v-if="errorState" class="error-state surface-card"><div class="error-state-icon">{{ errorState.status === 403 ? '♢' : errorState.status === 401 ? '⌁' : errorState.status === 409 || errorState.status === 412 ? '↻' : '!' }}</div><p class="eyebrow">错误 {{ errorState.status }}</p><h1>{{ errorState.title }}</h1><p>{{ errorState.detail }}</p><div class="error-actions"><button class="outlined-button" @click="go('dashboard')">返回概览</button><button v-if="errorState.status !== 403" class="filled-button" @click="loadResources">重新加载</button></div></section>
        <div v-else-if="isDashboard" class="dashboard">
          <section class="hero-row"><div><p class="eyebrow">星期三，2026 年 9 月 2 日</p><h1>概览</h1><p class="subtitle">快速了解你的 Ikaros 工作空间。</p></div><div class="title-actions"><button class="outlined-button" @click="openDialog('customize')">⊞ 自定义</button><button class="icon-button elevated" @click="notify('工作台已刷新')">⟳</button></div></section>
          <section class="welcome-card"><div><h2>下午好，陈昊 <span class="wave">✦</span></h2><p>你的空间运行良好，今天也有一些值得继续的事情。</p><div class="chips"><span class="status-chip success">● 系统健康</span><span class="status-chip neutral">本地环境</span><span class="muted-text">上次刷新：刚刚</span></div></div><div class="welcome-art"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="spark">✦</div></div></section>
          <section class="kpi-grid"><article v-for="item in kpis" :key="item.label" class="kpi-card" @click="notify(item.label + '详情已准备')"><div class="kpi-top"><span class="kpi-icon" :class="item.tone">{{ item.icon }}</span><span class="more">•••</span></div><p>{{ item.label }}</p><strong>{{ item.value }}</strong><small :class="{ positive: item.tone === 'primary' }">{{ item.trend }}</small><div v-if="item.label === '存储'" class="progress"><span style="width:68%"></span></div></article></section>
          <section class="content-grid"><article class="surface-card continue-card"><div class="card-heading"><div><h3>继续处理</h3><p>从你上次离开的地方继续</p></div><button class="text-button" @click="go('library')">查看全部</button></div><div v-for="item in resources.slice(0, 3)" :key="item.name" class="resource-row"><div class="resource-thumb" :class="item.type === '电影' ? 'cover' : ''">{{ item.type === '电影' ? '✦' : item.type === '文档' ? '□' : '◈' }}</div><div class="resource-info"><b>{{ item.name }}</b><div><span class="small-chip">{{ item.type }}</span><span class="muted-text">{{ item.updated }}</span></div><div class="tiny-progress"><span :style="{ width: item.progress + '%' }"></span></div></div><span class="progress-label">{{ item.progress }}%</span><button class="icon-button compact" @click="notify('正在打开 ' + item.name)">›</button></div></article><article class="surface-card activity-card"><div class="card-heading"><div><h3>最近活动</h3><p>你的空间动态</p></div><button class="text-button" @click="go('activity')">查看全部</button></div><div v-for="item in activities" :key="item.target" class="activity-row"><span class="activity-icon" :class="item.color">{{ item.icon }}</span><div><span>{{ item.text }}</span><b>{{ item.target }}</b><small>{{ item.time }}</small></div></div></article></section>
          <section class="surface-card attention-card"><div class="card-heading"><div><h3>待处理事项 <span class="count-badge">4</span></h3><p>需要你关注的空间状态</p></div><button class="text-button" @click="go('ops/background')">查看任务中心</button></div><div class="attention-grid"><div class="attention-item"><span class="attention-dot error"></span><div><b>备份任务执行失败</b><small>系统运维 · 2 小时前</small></div><button class="outlined-button small" @click="go('ops/background')">处理</button></div><div class="attention-item"><span class="attention-dot warning"></span><div><b>3 个元数据冲突</b><small>内容与创作 · 昨天</small></div><button class="outlined-button small" @click="go('library')">处理</button></div><div class="attention-item"><span class="attention-dot info"></span><div><b>分享链接即将过期</b><small>分享与协作 · 3 天内</small></div><button class="outlined-button small" @click="go('sharing')">处理</button></div></div></section>
        </div>
        <div v-else class="generic-page" :data-secure-domain="currentMeta.secureDomain" :data-required-capability="currentMeta.requiredCapability">
          <section v-if="isHealth" class="health-layout"><div class="health-banner"><div class="health-symbol">♥</div><div><span class="status-chip success">● 系统健康</span><h2>所有核心服务运行正常</h2><p>最近检查：刚刚 · 本地环境</p></div><button class="outlined-button small" @click="notify('健康检查已刷新')">刷新检查</button></div><div class="service-grid"><article v-for="service in services" :key="service.name" class="service-card"><div class="service-card-top"><span class="service-icon">{{ service.icon }}</span><span class="status-chip" :class="service.status === '降级' ? 'warning' : 'success'">● {{ service.status }}</span></div><b>{{ service.name }}</b><div class="service-meta"><span>{{ service.latency }}</span><span>最近成功 · 刚刚</span></div></article></div><div class="metric-strip"><div v-for="metric in [{label:'CPU',value:'24%',width:'24%'},{label:'Memory',value:'41%',width:'41%'},{label:'DB Pool',value:'32 / 100',width:'32%'},{label:'Queue Depth',value:'12',width:'12%'}]" :key="metric.label"><div><span>{{ metric.label }}</span><b>{{ metric.value }}</b></div><div class="metric-bar"><span :style="{ width: metric.width }"></span></div><small>过去 15 分钟</small></div></div><div class="surface-card alert-card"><div class="card-heading"><div><h3>告警</h3><p>需要关注的系统事件</p></div><span class="status-chip neutral">15m 时间范围</span></div><div v-for="alert in alerts" :key="alert.name" class="alert-row"><span class="attention-dot" :class="alert.severity"></span><div><b>{{ alert.name }}</b><small>{{ alert.component }} · {{ alert.condition }} · {{ alert.time }}</small></div><button class="text-button" @click="notify('已确认告警')">确认</button></div></div></section>
          <section v-if="isUsers" class="users-overview"><div class="security-banner"><span>♢</span><div><b>账户安全策略已启用</b><p>管理员操作会记录审计事件；禁用账户不会删除其数据。</p></div></div><div class="security-stats"><article v-for="stat in securityStats" :key="stat.label" class="mini-kpi"><span>{{ stat.label }}</span><b :class="stat.tone === 'pink' ? 'warning-text' : ''">{{ stat.value }}</b><small>{{ stat.detail }}</small></article></div></section>
          <section v-if="isPermissions" class="permission-matrix"><div class="matrix-toolbar"><div><b>权限矩阵</b><small>按角色查看当前可编辑的 Capability</small></div><div class="filter-row"><span class="filter-chip active">角色：管理员</span><button class="outlined-button small" @click="notify('权限来源检查完成')">权限来源</button></div></div><article v-for="group in permissionGroups" :key="group.name" class="permission-group"><div class="permission-group-title"><b>{{ group.name }}</b><span>{{ group.items.length }} 项能力</span></div><label v-for="permission in group.items" :key="permission.key" class="permission-row"><input type="checkbox" :checked="stagedPermissions[permission.key] ?? permission.enabled" @change="togglePermission(permission.key, stagedPermissions[permission.key] ?? permission.enabled)"/><span><b>{{ permission.label }}</b><code>{{ permission.key }}</code></span><small v-if="permission.key.includes('manage') || permission.key.includes('delete')">高风险</small></label></article><div v-if="hasStagedPermissions" class="sticky-permission-bar"><span>已暂存 {{ Object.keys(stagedPermissions).length }} 项修改</span><button class="text-button" @click="discardPermissions">放弃修改</button><button class="filled-button" @click="reviewPermissions">审阅修改</button></div></section>
          <section v-if="isNotifications" class="notifications-page"><div class="notification-tabs"><button v-for="tabName in ['全部','未读','系统']" :key="tabName" :class="{ active: notificationTab === tabName }" @click="notificationTab = tabName">{{ tabName }}<span v-if="tabName === '未读'">{{ unreadNotificationCount }}</span></button><button class="outlined-button small" @click="markNotificationRead()">全部已读</button></div><div class="notification-page-list surface-card"><div v-for="item in visibleNotifications" :key="item.title" class="notification-page-row"><span class="notification-icon" :class="item.type">{{ item.type === 'error' ? '!' : item.type === 'success' ? '✓' : 'i' }}</span><div><b>{{ item.title }}<i v-if="item.unread"></i></b><p>{{ item.text }}</p><small>{{ item.time }} · {{ item.type === 'info' ? '系统通知' : '工作空间通知' }}</small></div><button v-if="item.unread" class="text-button" @click="markNotificationRead(item.title)">标记已读</button></div><div v-if="visibleNotifications.length === 0" class="no-results">暂无通知</div></div></section>
          <section v-if="isAnnouncements" class="announcements-page"><div class="announcement-toolbar"><div class="notification-tabs"><button v-for="tabName in ['全部','已发布','草稿']" :key="tabName" :class="{ active: announcementTab === tabName }" @click="announcementTab = tabName">{{ tabName }}</button></div><button class="filled-button" @click="openDialog('create')">＋ 发布公告</button></div><div class="announcement-list surface-card"><div v-for="item in visibleAnnouncements" :key="item.title" class="announcement-row"><span class="announcement-icon" :class="item.tone">▰</span><div class="announcement-main"><b>{{ item.title }}</b><p>{{ item.audience }} · {{ item.publishedAt }}</p></div><span class="status-chip" :class="item.status === '草稿' ? 'warning' : 'success'">● {{ item.status }}</span><small>到期：{{ item.expiresAt }}</small><button class="icon-button compact" @click="openDialog('detail')">⋮</button></div><div v-if="visibleAnnouncements.length === 0" class="no-results">暂无公告</div></div></section>
          <section class="hero-row"><div><p class="eyebrow">{{ currentGroup.label }}</p><h1>{{ genericTitle() }}</h1><p class="subtitle">管理和查看你的{{ genericTitle() }}，所有变更都会记录并支持恢复。</p></div><div class="title-actions"><button class="filled-button" @click="openDialog('create')">＋ 新建</button><button class="icon-button elevated" :disabled="loading" @click="loadResources">{{ loading ? '…' : '⟳' }}</button></div></section>
          <div v-if="isSearch" class="search-hero"><div class="search-box"><span>⌕</span><input v-model="query" placeholder="搜索资源、文档、任务和活动…" @keyup.enter="submitSearch"/><button v-if="query" @click="query = ''; submitSearch()">×</button><kbd>⌘ K</kbd></div><div class="filter-row"><span class="filter-chip active">全部类型</span><span class="filter-chip">最近更新</span><span class="filter-chip">仅收藏</span><button class="filter-more" @click="openDialog('filters')">＋ 更多筛选</button></div></div>
          <section class="mini-kpi-row"><div class="mini-kpi"><span>总条目</span><b>1,284</b><small>较上月 +12%</small></div><div class="mini-kpi"><span>活跃中</span><b>86</b><small>7 天内更新</small></div><div class="mini-kpi"><span>待处理</span><b class="warning-text">12</b><small>需要关注</small></div><div class="mini-kpi"><span>同步状态</span><b class="success-text">正常</b><small>刚刚检查</small></div></section>
          <section class="surface-card table-card"><div class="table-toolbar"><div class="search-inline"><span>⌕</span><input placeholder="筛选当前列表" v-model="query"/></div><div class="filter-row"><button class="filter-chip" :class="{ active: statusFilter === '全部状态' }" @click="setStatusFilter('全部状态')">全部状态</button><button class="filter-chip" :class="{ active: statusFilter === '运行中' }" @click="setStatusFilter('运行中')">运行中</button><button class="filter-chip" :class="{ active: statusFilter === '失败' }" @click="setStatusFilter('失败')">失败</button><button class="outlined-button small" @click="openDialog('filters')">筛选</button><button class="icon-button compact">⋮</button></div></div><div class="bulk-bar" v-if="selectedRows.length"><b>已选择 {{ selectedRows.length }} 项</b><button class="text-button" @click="openDialog('bulk')">批量操作</button><button class="text-button" @click="clearSelection">清除选择</button></div><div class="bulk-bar" v-if="!selectedRows.length && (query || statusFilter !== '全部状态')">正在筛选 <b>{{ query ? `“${query}”` : statusFilter }}</b><button class="text-button" @click="query = ''; statusFilter = '全部状态'">清除</button></div><table><thead><tr><th class="check"><input type="checkbox" :checked="allVisibleSelected" @change="toggleAll" /></th><th>名称</th><th>所有者</th><th>状态</th><th>最近更新</th><th>操作</th></tr></thead><tbody><tr v-for="row in filteredRows" :key="row.name" @click="openDialog('detail')"><td class="check"><input type="checkbox" :checked="selectedRows.includes(row.name)" @click.stop @change="toggleRow(row.name)" /></td><td><div class="table-name"><span class="row-icon">◈</span><b>{{ row.name }}</b></div></td><td>{{ row.owner }}</td><td><span class="status-chip" :class="row.status === '失败' ? 'danger' : row.status === '运行中' ? 'warning' : row.status === '已暂停' ? 'neutral' : 'success'">● {{ row.status }}</span></td><td class="muted-text">{{ row.updated }}</td><td><button class="icon-button compact" @click.stop="openDialog('detail')">⋮</button></td></tr><tr v-if="filteredRows.length === 0"><td colspan="6" class="no-results">没有匹配结果，请清除筛选后重试。</td></tr></tbody></table><div class="table-footer"><span>显示 {{ filteredRows.length }} 项，共 {{ rows.length }} 项</span><div><button class="icon-button compact">‹</button><button class="icon-button compact">›</button></div></div></section>
          <div v-if="currentPath === 'ops/background' && selectedRows.length" class="task-action-bar"><span>已选择 {{ selectedRows.length }} 项后台任务</span><button class="outlined-button small" @click="bulkTaskAction('retry')">重试</button><button class="filled-button small" @click="bulkTaskAction('cancel')">取消任务</button></div><section class="empty-hint"><span>✦</span><div><b>需要了解更多？</b><p>查看该模块的帮助文档，了解状态、权限和操作规则。</p></div><button class="text-button" @click="notify('帮助文档即将开放')">查看文档 →</button></section>
        </div>
      </div>
    </main>
    <div v-if="drawer" class="scrim" @click="drawer = false"></div>
    <div v-if="dialog" class="dialog-scrim" @click.self="dialog = ''"><section class="dialog"><div class="dialog-title"><div><p class="eyebrow">{{ dialog === 'create' ? '创建入口' : 'Ikaros Console' }}</p><h2>{{ dialog === 'create' ? '创建新内容' : dialog === 'customize' ? '自定义工作台' : dialog === 'filters' ? '更多筛选' : dialog === 'profile' ? '个人账户' : dialog === 'tasks' ? '后台任务' : dialog === 'notifications' ? '通知中心' : '详情' }}</h2></div><button class="icon-button" @click="dialog = ''">×</button></div><div v-if="dialog === 'create'" class="create-options"><button @click="notify('已打开资源创建器'); dialog = ''"><span>◈</span><div><b>Resource</b><small>创建统一资源</small></div>›</button><button @click="notify('已打开文档编辑器'); dialog = ''"><span>□</span><div><b>文章 / 文档</b><small>开始一篇新的内容</small></div>›</button><button @click="notify('已打开任务创建器'); dialog = ''"><span>✓</span><div><b>任务</b><small>加入今天的计划</small></div>›</button><button @click="notify('已打开导入流程'); dialog = ''"><span>⇩</span><div><b>导入</b><small>从本地文件或连接器导入</small></div>›</button></div><div v-else-if="dialog === 'tasks'" class="dialog-list"><div class="task-line"><span class="loader"></span><div><b>每周资料备份</b><small>存储与备份 · 68%</small></div><span class="status-chip warning">运行中</span></div><div class="task-line"><span class="loader"></span><div><b>资源缩略图生成</b><small>内容与创作 · 排队中</small></div><span class="status-chip neutral">排队中</span></div><div class="task-line"><span class="error-dot"></span><div><b>活动周报</b><small>数据分析 · 失败</small></div><span class="status-chip danger">失败</span></div></div><div v-else class="dialog-body"><p>这里展示符合权限策略的安全信息。所有高风险修改都会先进行影响评估、确认和审计记录。</p><label>备注（可选）<textarea placeholder="输入你的备注…"></textarea></label><div class="dialog-actions"><button class="outlined-button" @click="dialog = ''">取消</button><button class="filled-button" @click="dialog = ''; notify('操作已完成')">确认</button></div></div></section></div>
    <div v-if="dialog === 'profile'" class="profile-scrim" @click.self="dialog = ''"><aside class="profile-sheet"><div class="profile-head"><div class="avatar large">陈</div><div><h2>陈昊</h2><p>管理员 · 本地环境</p></div><button class="icon-button" @click="dialog = ''">×</button></div><div class="profile-menu"><button @click="dialog = ''; notify('个人资料页面即将开放')"><span>♙</span><div><b>个人资料</b><small>管理你的公开资料</small></div>›</button><button @click="dialog = ''; notify('偏好设置即将开放')"><span>⚙</span><div><b>偏好设置</b><small>Console 显示与通知偏好</small></div>›</button><button @click="dialog = ''; go('security/sessions')"><span>⌁</span><div><b>安全与会话</b><small>查看当前设备与活跃会话</small></div>›</button><button @click="dialog = ''; cycleTheme"><span>◐</span><div><b>主题</b><small>{{ theme === 'system' ? '跟随系统' : theme === 'light' ? '浅色' : '深色' }}</small></div>›</button><button @click="dialog = ''; notify('语言设置即将开放')"><span>文</span><div><b>语言</b><small>简体中文</small></div>›</button></div><button class="logout-button" @click="dialog = ''; go('login')">退出登录</button></aside></div><div v-if="dialog === 'detail'" class="detail-scrim" @click.self="dialog = ''"><aside class="detail-sheet"><div class="detail-sheet-header"><div><p class="eyebrow">{{ currentGroup.label }}</p><h2>{{ pageTitle }}详情</h2></div><button class="icon-button" @click="dialog = ''">×</button></div><div class="detail-status"><span class="status-chip success">● 可查看</span><span class="status-chip neutral">只读摘要</span></div><dl class="detail-grid"><div><dt>所属子系统</dt><dd>{{ currentMeta.subsystem }}</dd></div><div><dt>安全域</dt><dd>{{ currentMeta.secureDomain }}</dd></div><div><dt>查看能力</dt><dd><code>{{ currentMeta.requiredCapability }}</code></dd></div><div><dt>最近同步</dt><dd>刚刚</dd></div><div><dt>数据范围</dt><dd>当前用户授权范围</dd></div><div><dt>审计状态</dt><dd class="success-text">已记录</dd></div></dl><div class="detail-callout"><span>i</span><p>此摘要遵循最小权限策略。需要修改或查看敏感字段时，系统会重新检查 Capability、Scope 和 Secure Session。</p></div><div class="detail-actions"><button class="outlined-button" @click="notify('已复制详情链接')">复制链接</button><button class="filled-button" @click="dialog = ''; notify('已进入编辑流程')">进入编辑</button></div></aside></div>
    <div v-if="dialog === 'permission-review'" class="review-scrim" @click.self="dialog = ''"><section class="review-dialog"><div class="dialog-title"><div><p class="eyebrow">权限变更审阅</p><h2>确认权限修改</h2></div><button class="icon-button" @click="dialog = ''">×</button></div><p class="review-copy">以下修改将应用到当前角色，并写入安全审计日志。</p><div class="review-list"><div v-for="(value, key) in stagedPermissions" :key="key" class="review-item"><span :class="value ? 'grant' : 'revoke'">{{ value ? '+' : '−' }}</span><div><b>{{ value ? '新增权限' : '撤销权限' }}</b><code>{{ key }}</code></div><span class="status-chip" :class="value ? 'success' : 'danger'">{{ value ? '授予' : '移除' }}</span></div></div><div class="dialog-actions"><button class="outlined-button" @click="discardPermissions; dialog = ''">返回修改</button><button class="filled-button" @click="applyPermissions">确认提交</button></div></section></div><div v-if="dialog === 'notifications'" class="notification-scrim" @click.self="dialog = ''"><aside class="notification-sheet"><div class="notification-head"><div><p class="eyebrow">通知中心</p><h2>最近通知</h2></div><button class="text-button" @click="notify('已全部标为已读'); dialog = ''">全部已读</button></div><div class="notification-list"><div v-for="item in notifications" :key="item.title" class="notification-row"><span class="notification-icon" :class="item.type">{{ item.type === 'error' ? '!' : item.type === 'success' ? '✓' : 'i' }}</span><div><b>{{ item.title }}<i v-if="item.unread"></i></b><p>{{ item.text }}</p><small>{{ item.time }}</small></div></div></div><button class="outlined-button notification-all" @click="dialog = ''; go('communications/notifications')">查看全部通知</button></aside></div><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div>
  </div>
</template>
