<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElAlert, ElButton, ElForm, ElFormItem, ElInput } from 'element-plus'
import { api, saveAuthSession, syncRuntimeActorId } from './services/api'

const route = useRoute(); const router = useRouter()
const email = ref(''); const code = ref(''); const password = ref(''); const confirmPassword = ref(''); const username = ref(''); const displayName = ref(''); const error = ref(''); const submitted = ref(false); const loading = ref(false)
const mode = computed(() => route.path.startsWith('/setup') ? 'setup' : route.path.startsWith('/login/verify') ? 'verify' : route.path.startsWith('/recovery') ? 'recovery' : 'login')
const content = computed(() => mode.value === 'setup' ? { eyebrow: '首次初始化 · 演示', title: '创建工作空间管理员', subtitle: '当前仅演示初始化表单；后端初始化接口尚未接入。' } : mode.value === 'verify' ? { eyebrow: '安全验证 · 演示', title: '输入验证码', subtitle: '当前仅演示验证码流程；后端验证接口尚未接入。' } : mode.value === 'recovery' ? { eyebrow: '账号恢复 · 演示', title: '恢复你的账号', subtitle: '当前仅演示恢复表单；后端恢复接口尚未接入。' } : { eyebrow: '安全访问', title: '欢迎回来', subtitle: '登录你的 Ikaros 工作空间' })
async function submit() { error.value = ''; if (mode.value === 'setup') { username.value = email.value.trim(); displayName.value = displayName.value.trim() || username.value; if (!username.value) { error.value = '请输入用户名'; return }; if (password.value.length < 8) { error.value = '管理员密码至少需要 8 位'; return }; if (password.value !== confirmPassword.value) { error.value = '两次输入的密码不一致'; return }; loading.value = true; try { const session = await api.register({ username: username.value, displayName: displayName.value, email: undefined, password: password.value }); saveAuthSession(session); syncRuntimeActorId(); router.replace('/console/dashboard') } catch (e) { error.value = e instanceof Error ? e.message : '注册失败，请稍后重试' } finally { loading.value = false }; return }; if (mode.value === 'verify' && code.value.length !== 6) { error.value = '请输入 6 位验证码'; return }; error.value = '当前认证流程仅支持用户名密码注册和登录' }
function backToLogin() { router.push('/login') }
</script>

<template>
  <div class="login-page auth-entry"><div class="login-decoration"><div class="login-orb one"></div><div class="login-orb two"></div><span>✦</span></div><main class="login-card"><div class="login-brand"><div class="brand-mark">i</div><div><strong>Ikaros</strong><small>Console</small></div></div><p class="eyebrow">{{ content.eyebrow }}</p><h1>{{ content.title }}</h1><p class="login-subtitle">{{ content.subtitle }}</p><div v-if="submitted" class="auth-success"><span>✓</span><div><b>{{ mode === 'setup' ? '初始化已提交' : mode === 'verify' ? '验证成功' : '请检查你的邮箱' }}</b><p>{{ mode === 'setup' ? '正在准备你的 Console 环境。' : mode === 'verify' ? '认证完成，正在进入工作台。' : '如果邮箱存在，我们已发送后续步骤。' }}</p></div></div><el-form v-else label-position="top" @submit.prevent="submit"><el-form-item v-if="mode !== 'verify'" label="邮箱"><el-input v-model="email" type="email" autocomplete="email" placeholder="name@example.com" /></el-form-item><el-form-item v-if="mode === 'verify'" label="验证码"><el-input v-model="code" inputmode="numeric" maxlength="6" placeholder="输入 6 位验证码" /></el-form-item><template v-if="mode === 'setup'"><el-form-item label="管理员密码"><el-input v-model="password" type="password" show-password autocomplete="new-password" placeholder="至少 8 位" /></el-form-item><el-form-item label="确认密码"><el-input v-model="confirmPassword" type="password" show-password autocomplete="new-password" placeholder="再次输入密码" /></el-form-item></template><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" /><el-button class="login-button" type="primary" native-type="submit">{{ mode === 'setup' ? '完成初始化' : mode === 'verify' ? '完成验证' : mode === 'recovery' ? '发送恢复链接' : '继续' }} <span>→</span></el-button></el-form><el-button link class="auth-back" @click="backToLogin">返回登录</el-button><p class="login-footnote">所有认证与恢复动作都会遵循安全策略并写入审计记录。</p></main></div>
</template>
