<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from './services/api'
type Block = { id: string; title: string; start: string; end: string; kind: string; status: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const blocks = ref<Block[]>([{ id: 'demo-deep', title: '深度工作', start: '09:00', end: '11:00', kind: 'FOCUS', status: 'SCHEDULED' }, { id: 'demo-sync', title: '团队同步', start: '14:00', end: '15:00', kind: 'MEETING', status: 'CONFIRMED' }]); const title = ref(''); const start = ref('09:00'); const end = ref('10:00'); const dialog = ref(false); const loading = ref(false); const toast = ref('')
const ordered = computed(() => [...blocks.value].sort((a, b) => a.start.localeCompare(b.start)))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
function formatTime(value?: string) { return value ? new Date(value).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) : '—' }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listPlanningTimeBlocks(actorId); if (result.length) blocks.value = result.map(item => ({ id: item.id, title: item.title || item.id.slice(0, 8), start: formatTime(item.startAt), end: formatTime(item.endAt), kind: item.kind || 'FOCUS', status: item.status || 'SCHEDULED' })) } catch { notify('时间块 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!title.value.trim() || start.value >= end.value) { notify('请填写标题并确认结束时间晚于开始时间'); return } const today = new Date().toISOString().slice(0, 10); try { const item = actorId ? await api.createPlanningTimeBlock({ title: title.value.trim(), startAt: `${today}T${start.value}:00+08:00`, endAt: `${today}T${end.value}:00+08:00`, kind: 'FOCUS', timeZone: 'Asia/Shanghai' }, actorId) : { id: `demo-${Date.now()}`, title: title.value.trim(), startAt: `${today}T${start.value}:00`, endAt: `${today}T${end.value}:00`, kind: 'FOCUS', status: 'SCHEDULED' }; blocks.value.push({ id: item.id, title: item.title || title.value.trim(), start: formatTime(item.startAt), end: formatTime(item.endAt), kind: item.kind || 'FOCUS', status: item.status || 'SCHEDULED' }); dialog.value = false; title.value = ''; notify('时间块已创建') } catch (error) { notify(error instanceof Error ? error.message : '时间块创建失败') } }
onMounted(load)
</script>
<template><div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>日历与时间块</h1><p>Time Block 用于安排时间；Task 的截止时间和日历事件保持独立。</p></div><button class="filled-button" @click="dialog = true">＋ 新建时间块</button></div><nav class="planning-tabs"><RouterLink to="/console/planning/today">今天</RouterLink><RouterLink to="/console/planning/projects">项目与任务</RouterLink><RouterLink to="/console/planning/calendar" class="active">日历与时间块</RouterLink><RouterLink to="/console/planning/goals">目标与 OKR</RouterLink></nav><div class="calendar-day surface-card"><div class="calendar-day-head"><div><p class="eyebrow">今天</p><h2>{{ new Date().toLocaleDateString('zh-CN', { weekday: 'long', month: 'long', day: 'numeric' }) }}</h2></div><button class="outlined-button small" :disabled="loading" @click="load">{{ loading ? '加载中…' : '⟳ 刷新' }}</button></div><div class="timeline"><div v-for="block in ordered" :key="block.id" class="timeline-row"><time>{{ block.start }}</time><span class="timeline-line"></span><article><div class="project-card-top"><b>{{ block.title }}</b><span class="status-chip success">● {{ block.status }}</span></div><p>{{ block.kind }} · {{ block.start }}–{{ block.end }} · Asia/Shanghai</p><button class="text-button" @click="notify('时间块详情已打开')">查看详情 →</button></article></div><div v-if="ordered.length === 0" class="no-results">今天没有时间块</div></div></div></main><div v-if="dialog" class="role-create-scrim" @click.self="dialog = false"><section class="role-create-dialog"><div class="dialog-title"><div><p class="eyebrow">效率与计划</p><h2>新建时间块</h2></div><button class="icon-button" @click="dialog = false">×</button></div><label>标题 *<input v-model="title" maxlength="160" placeholder="例如：深度工作" @keyup.enter="create" /></label><div class="time-inputs"><label>开始<input v-model="start" type="time" /></label><label>结束<input v-model="end" type="time" /></label></div><p class="account-note">时间块只表达时间安排，不会自动修改 Task 截止时间或创建 Calendar Event。</p><div class="dialog-actions"><button class="outlined-button" @click="dialog = false">取消</button><button class="filled-button" @click="create">创建时间块</button></div></section></div><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
