<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from './services/api'

type CollectionRow = { id: string; name: string; description: string; count: string; updated: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const tab = ref('集合'); const query = ref(''); const dialog = ref(false); const name = ref(''); const description = ref(''); const toast = ref(''); const loading = ref(false)
const collections = ref<CollectionRow[]>([{ id: 'demo-reading', name: '阅读清单', description: '本周想读和正在阅读的内容', count: '24 个资源', updated: '今天' }, { id: 'demo-design', name: '设计参考', description: 'Material Design 与产品参考', count: '18 个资源', updated: '昨天' }, { id: 'demo-inbox', name: '待整理资源', description: '尚未归档到其他集合的内容', count: '7 个资源', updated: '3 天前' }])
const tags = [{ name: '科幻', namespace: '内容', count: '38 次', color: '#647bb5' }, { name: '项目', namespace: '规划', count: '16 次', color: '#2d8a6c' }, { name: '收藏', namespace: '系统', count: '42 次', color: '#c47b34' }]
const relations = [{ name: '引用', detail: '文档 → 资源', count: '12 条' }, { name: '关联', detail: '资源 ↔ 资源', count: '28 条' }, { name: '衍生', detail: '资源 → 文档', count: '6 条' }]
const visibleCollections = computed(() => collections.value.filter(item => `${item.name} ${item.description}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listCollections(actorId); if (result.length) collections.value = result.map(item => ({ id: item.id, name: item.name, description: item.description || '暂无描述', count: '—', updated: item.updatedAt ? new Date(item.updatedAt).toLocaleString('zh-CN') : '刚刚' })) } catch { notify('集合 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!name.value.trim()) { notify('请输入集合名称'); return } try { const item = actorId ? await api.createCollection({ name: name.value.trim(), description: description.value.trim() || undefined }, actorId) : { id: `demo-${Date.now()}`, name: name.value.trim(), description: description.value.trim(), updatedAt: new Date().toISOString() }; collections.value.unshift({ id: item.id, name: item.name, description: item.description || '暂无描述', count: '0 个资源', updated: '刚刚' }); dialog.value = false; name.value = ''; description.value = ''; notify('集合已创建') } catch (error) { notify(error instanceof Error ? error.message : '集合创建失败') } }
onMounted(load)
</script>

<template><div class="catalog-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">内容与创作 · 集合与标签</span><span class="mini-avatar">陈</span></header><main class="catalog-main collection-main"><div class="catalog-heading"><div><p class="eyebrow">内容与创作</p><h1>集合与标签</h1><p>使用逻辑关系组织 Resource，不改变物理存储位置。</p></div><button v-if="tab === '集合'" class="filled-button" @click="dialog = true">＋ 新建集合</button></div><nav class="collection-tabs"><button v-for="name in ['集合','标签','关系类型']" :key="name" :class="{ active: tab === name }" @click="tab = name">{{ name }}</button></nav><div class="catalog-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" placeholder="搜索当前目录" /></div><span class="status-chip neutral">{{ tab === '集合' ? visibleCollections.length : tab === '标签' ? tags.length : relations.length }} 项</span></div><section v-if="tab === '集合'" class="collection-list surface-card"><div v-for="item in visibleCollections" :key="item.id" class="collection-row"><span class="collection-icon">▧</span><div><b>{{ item.name }}</b><p>{{ item.description }}</p></div><span>{{ item.count }}</span><small>{{ item.updated }}</small><button class="icon-button compact" @click="notify('集合操作菜单已打开')">⋮</button></div><div v-if="visibleCollections.length === 0" class="no-results">没有匹配的集合</div></section><section v-else-if="tab === '标签'" class="tag-grid"><article v-for="tag in tags" :key="tag.name" class="surface-card tag-card"><span class="tag-dot" :style="{ background: tag.color }"></span><div><b>{{ tag.name }}</b><small>{{ tag.namespace }} · {{ tag.count }}</small></div><button class="icon-button compact" @click="notify('标签操作菜单已打开')">⋮</button></article></section><section v-else class="relation-list surface-card"><div v-for="relation in relations" :key="relation.name" class="relation-row"><span class="relation-icon">↔</span><div><b>{{ relation.name }}</b><small>{{ relation.detail }}</small></div><span>{{ relation.count }}</span><button class="text-button" @click="notify('关系浏览器即将打开')">浏览 →</button></div></section></main><div v-if="dialog" class="role-create-scrim" @click.self="dialog = false"><section class="role-create-dialog"><div class="dialog-title"><div><p class="eyebrow">内容与创作</p><h2>新建集合</h2></div><button class="icon-button" @click="dialog = false">×</button></div><label>名称<input v-model="name" maxlength="128" placeholder="例如：本周阅读" /></label><label>描述（可选）<textarea v-model="description" maxlength="2000" placeholder="说明这个集合的用途…"></textarea></label><div class="dialog-actions"><button class="outlined-button" @click="dialog = false">取消</button><button class="filled-button" @click="create">创建集合</button></div></section></div><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
