<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from './services/api'
import { ElButton, ElButtonGroup, ElDialog, ElForm, ElFormItem, ElInput, ElTag } from 'element-plus'

type CollectionRow = { id: string; name: string; description: string; count: string; updated: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const tab = ref('集合'); const query = ref(''); const dialog = ref(false); const name = ref(''); const description = ref(''); const toast = ref(''); const loading = ref(false)
const collections = ref<CollectionRow[]>([{ id: 'demo-reading', name: '阅读清单', description: '本周想读和正在阅读的内容', count: '24 个资源', updated: '今天' }, { id: 'demo-design', name: '设计参考', description: 'Material Design 与产品参考', count: '18 个资源', updated: '昨天' }, { id: 'demo-inbox', name: '待整理资源', description: '尚未归档到其他集合的内容', count: '7 个资源', updated: '3 天前' }])
const tags = [{ name: '科幻', namespace: '内容', count: '38 次', color: '#647bb5' }, { name: '项目', namespace: '规划', count: '16 次', color: '#2d8a6c' }, { name: '收藏', namespace: '系统', count: '42 次', color: '#c47b34' }]
const relations = [{ name: '引用', detail: '文档 → 资源', count: '12 条' }, { name: '关联', detail: '资源 ↔ 资源', count: '28 条' }, { name: '衍生', detail: '资源 → 文档', count: '6 条' }]
const visibleCollections = computed(() => collections.value.filter(item => `${item.name} ${item.description}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listCollections(actorId); if (result.length) collections.value = result.map(item => ({ id: item.id, name: item.name, description: item.description || '暂无描述', count: '—', updated: item.updatedAt ? new Date(item.updatedAt).toLocaleString('zh-CN') : '刚刚' })) } catch { notify('集合 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!name.value.trim()) { notify('请输入集合名称'); return } try { const item = actorId ? await api.createCollection({ name: name.value.trim(), description: description.value.trim() || undefined }, actorId) : { id: `demo-${Date.now()}`, name: name.value.trim(), description: description.value.trim(), updatedAt: new Date().toISOString() }; collections.value.unshift({ id: item.id, name: item.name, description: item.description || '暂无描述', count: '0 个资源', updated: '刚刚' }); dialog.value = false; name.value = ''; description.value = ''; notify('集合已创建') } catch (error) { notify(error instanceof Error ? error.message : '集合创建失败') } }
onMounted(load)
</script>

<template><div class="catalog-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">内容与创作 · 集合与标签</span><span class="mini-avatar">陈</span></header><main class="catalog-main collection-main"><div class="catalog-heading"><div><p class="eyebrow">内容与创作</p><h1>集合与标签</h1><p>使用逻辑关系组织 Resource，不改变物理存储位置。</p></div><el-button v-if="tab === '集合'" type="primary" @click="dialog = true">＋ 新建集合</el-button></div><el-button-group class="collection-tabs"><el-button v-for="name in ['集合','标签','关系类型']" :key="name" :type="tab === name ? 'primary' : 'default'" @click="tab = name">{{ name }}</el-button></el-button-group><div class="catalog-toolbar surface-card"><el-input v-model="query" clearable placeholder="搜索当前目录" style="max-width:360px" /><el-tag type="info">{{ tab === '集合' ? visibleCollections.length : tab === '标签' ? tags.length : relations.length }} 项</el-tag></div><section v-if="tab === '集合'" class="collection-list surface-card"><div v-for="item in visibleCollections" :key="item.id" class="collection-row"><span class="collection-icon">▧</span><div><b>{{ item.name }}</b><p>{{ item.description }}</p></div><span>{{ item.count }}</span><small>{{ item.updated }}</small><el-button link @click="notify('集合操作菜单已打开')">更多</el-button></div><div v-if="visibleCollections.length === 0" class="no-results">没有匹配的集合</div></section><section v-else-if="tab === '标签'" class="tag-grid"><article v-for="tag in tags" :key="tag.name" class="surface-card tag-card"><span class="tag-dot" :style="{ background: tag.color }"></span><div><b>{{ tag.name }}</b><small>{{ tag.namespace }} · {{ tag.count }}</small></div><el-button link @click="notify('标签操作菜单已打开')">更多</el-button></article></section><section v-else class="relation-list surface-card"><div v-for="relation in relations" :key="relation.name" class="relation-row"><span class="relation-icon">↔</span><div><b>{{ relation.name }}</b><small>{{ relation.detail }}</small></div><span>{{ relation.count }}</span><el-button link type="primary" @click="notify('关系浏览器即将打开')">浏览 →</el-button></div></section></main><el-dialog v-model="dialog" title="新建集合" width="460px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="name" maxlength="128" placeholder="例如：本周阅读" /></el-form-item><el-form-item label="描述（可选）"><el-input v-model="description" type="textarea" maxlength="2000" placeholder="说明这个集合的用途…" /></el-form-item><div class="dialog-actions"><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="create">创建集合</el-button></div></el-form></el-dialog><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
