<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElButton, ElButtonGroup, ElDrawer, ElInput, ElTable, ElTableColumn, ElTag } from 'element-plus'

const route = useRoute(); const query = ref(''); const severity = ref('全部'); const toast = ref(''); const selected = ref<string | null>(null)
const mode = computed(() => route.path.includes('/templates') ? 'templates' : route.path.includes('/providers') ? 'providers' : route.path.includes('/login-logs') ? 'login-logs' : 'security-events')
const catalogs = {
  templates: { title: '通知模板', description: '管理模板化通知内容与变量；模板修改需要审计。', action: '新建模板', columns: ['模板名称', '事件类型', '渠道', '状态'], rows: [] },
  providers: { title: '通知 Provider', description: 'Provider 配置预览；后端暂未提供渠道健康检查与投递结果查询接口。', action: '添加 Provider', columns: ['Provider', '渠道', '健康状态', '最近投递'], rows: [] },
  'login-logs': { title: '登录日志', description: '记录认证结果和 Session 建立事件；不展示密码、OTP 或 Token。', action: '', columns: ['结果', '登录身份', '认证方式', '时间'], rows: [] },
  'security-events': { title: '安全事件', description: '集中查看需要管理员关注的认证、会话和敏感操作事件。', action: '', columns: ['事件', '主体', '严重级别', '时间'], rows: [] }
} as const
const catalog = computed(() => catalogs[mode.value as keyof typeof catalogs]); const rows = computed(() => catalog.value.rows.filter(row => { const textMatch = `${row.name} ${row.detail} ${row.channel} ${row.status}`.toLowerCase().includes(query.value.toLowerCase()); const severityMatch = mode.value !== 'security-events' || severity.value === '全部' || row.channel === severity.value; return textMatch && severityMatch }))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
</script>

<template><div class="catalog-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">沟通与审计 · 本地环境</span><span class="mini-avatar">陈</span></header><main class="catalog-main"><div class="catalog-heading"><div><p class="eyebrow">沟通与审计</p><h1>{{ catalog.title }}</h1><p>{{ catalog.description }}</p></div><el-button v-if="catalog.action" type="primary" @click="notify('当前为演示目录，后端尚未提供写入接口')">＋ {{ catalog.action }}</el-button></div><el-alert class="catalog-demo-note" title="当前页面展示演示数据；后端尚未提供该模块的读取或投递接口。" type="info" :closable="false" /><div class="catalog-toolbar surface-card"><el-input v-model="query" clearable placeholder="筛选当前列表" style="max-width:360px" /><el-button-group v-if="mode === 'security-events'"><el-button v-for="value in ['全部','高','中','低']" :key="value" :type="severity === value ? 'primary' : 'default'" @click="severity = value">{{ value }}</el-button></el-button-group><el-tag type="info">{{ rows.length }} 项</el-tag></div><section class="catalog-table surface-card"><el-table :data="rows" stripe @row-click="row => selected = row.id"><el-table-column prop="name" :label="catalog.columns[0]" min-width="220" /><el-table-column prop="detail" :label="catalog.columns[1]" min-width="180" /><el-table-column :label="catalog.columns[2]" width="160"><template #default="{ row }"><el-tag :type="row.channel === '高' || row.status === '失败' ? 'danger' : row.status === '草稿' || row.status === '未配置' ? 'warning' : 'info'">{{ row.channel }}</el-tag></template></el-table-column><el-table-column prop="status" :label="catalog.columns[3]" width="160" /><el-table-column label="操作" width="90"><template #default="{ row }"><el-button link type="primary" @click.stop="selected = row.id">详情</el-button></template></el-table-column></el-table><div class="catalog-footer"><span>显示 {{ rows.length }} 项 · 敏感字段已脱敏</span><el-button link @click="notify('演示目录已刷新')">刷新</el-button></div></section><el-drawer :model-value="Boolean(selected)" title="安全摘要" size="360px" @close="selected = null"><h2>{{ catalog.rows.find(row => row.id === selected)?.name }}</h2><p>{{ catalog.rows.find(row => row.id === selected)?.detail }}</p><el-alert title="完整凭据、Token 与敏感网络元数据不会在普通管理页面展示。" type="info" :closable="false" /></el-drawer></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
