<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute(); const query = ref(''); const severity = ref('全部'); const toast = ref(''); const selected = ref<string | null>(null)
const mode = computed(() => route.path.includes('/templates') ? 'templates' : route.path.includes('/providers') ? 'providers' : route.path.includes('/login-logs') ? 'login-logs' : 'security-events')
const catalogs = {
  templates: { title: '通知模板', description: '管理模板化通知内容与变量；模板修改需要审计。', action: '新建模板', columns: ['模板名称', '事件类型', '渠道', '状态'], rows: [{ id: 'security-login', name: '新设备登录提醒', detail: 'security.login', channel: '站内 · Email', status: '已启用' }, { id: 'task-failed', name: '后台任务失败', detail: 'task.failed', channel: '站内', status: '已启用' }, { id: 'share-expiring', name: '分享即将过期', detail: 'share.expiring', channel: 'Email', status: '草稿' }] },
  providers: { title: '通知 Provider', description: '查看通知渠道的可用性、健康检查与最近投递结果。', action: '添加 Provider', columns: ['Provider', '渠道', '健康状态', '最近投递'], rows: [{ id: 'in-app', name: 'In-app Notifications', detail: '站内通知', channel: '本地', status: '健康' }, { id: 'email', name: 'SMTP Workspace', detail: 'Email', channel: 'smtp', status: '健康' }, { id: 'webhook', name: 'Operations Webhook', detail: 'Webhook', channel: 'https', status: '未配置' }] },
  'login-logs': { title: '登录日志', description: '记录认证结果和 Session 建立事件；不展示密码、OTP 或 Token。', action: '', columns: ['结果', '登录身份', '认证方式', '时间'], rows: [{ id: 'login-1', name: '成功', detail: 'chen@example.com', channel: 'Password + MFA', status: '今天 09:12' }, { id: 'login-2', name: '失败', detail: 'unknown@example.com', channel: 'Password', status: '今天 08:57' }, { id: 'login-3', name: '成功', detail: 'chen@example.com', channel: 'Session Refresh', status: '昨天 18:22' }] },
  'security-events': { title: '安全事件', description: '集中查看需要管理员关注的认证、会话和敏感操作事件。', action: '', columns: ['事件', '主体', '严重级别', '时间'], rows: [{ id: 'event-1', name: '多次登录失败', detail: 'unknown@example.com', channel: '高', status: '今天 08:57' }, { id: 'event-2', name: '管理员授予角色权限', detail: '陈昊 · ROLE', channel: '中', status: '昨天 18:24' }, { id: 'event-3', name: '新设备登录', detail: '陈昊 · Chrome', channel: '低', status: '昨天 09:10' }] }
} as const
const catalog = computed(() => catalogs[mode.value as keyof typeof catalogs]); const rows = computed(() => catalog.value.rows.filter(row => { const textMatch = `${row.name} ${row.detail} ${row.channel} ${row.status}`.toLowerCase().includes(query.value.toLowerCase()); const severityMatch = mode.value !== 'security-events' || severity.value === '全部' || row.channel === severity.value; return textMatch && severityMatch }))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
</script>

<template><div class="catalog-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">沟通与审计 · 本地环境</span><span class="mini-avatar">陈</span></header><main class="catalog-main"><div class="catalog-heading"><div><p class="eyebrow">沟通与审计</p><h1>{{ catalog.title }}</h1><p>{{ catalog.description }}</p></div><button v-if="catalog.action" class="filled-button" @click="notify('已打开' + catalog.action + '表单')">＋ {{ catalog.action }}</button></div><div class="catalog-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" placeholder="筛选当前列表" /></div><div v-if="mode === 'security-events'" class="filter-row"><button v-for="value in ['全部','高','中','低']" :key="value" class="filter-chip" :class="{ active: severity === value }" @click="severity = value">{{ value }}</button></div><span class="status-chip neutral">{{ rows.length }} 项</span></div><section class="catalog-table surface-card"><table><thead><tr><th v-for="column in catalog.columns" :key="column">{{ column }}</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id" @click="selected = row.id"><td><b>{{ row.name }}</b></td><td>{{ row.detail }}</td><td><span class="status-chip" :class="row.channel === '高' || row.status === '失败' ? 'danger' : row.status === '草稿' || row.status === '未配置' || row.channel === '中' ? 'warning' : 'success'">● {{ row.channel }}</span></td><td class="muted-text">{{ row.status }}</td><td><button class="icon-button compact" @click.stop="selected = row.id">⋮</button></td></tr><tr v-if="rows.length === 0"><td :colspan="catalog.columns.length + 1" class="no-results">没有匹配结果</td></tr></tbody></table><div class="catalog-footer"><span>显示 {{ rows.length }} 项 · 敏感字段已脱敏</span><button class="text-button" @click="notify('日志目录已刷新')">⟳ 刷新</button></div></section><aside v-if="selected" class="catalog-detail surface-card"><div><p class="eyebrow">安全摘要</p><h2>{{ catalog.rows.find(row => row.id === selected)?.name }}</h2><p>{{ catalog.rows.find(row => row.id === selected)?.detail }}</p></div><button class="icon-button" @click="selected = null">×</button><div class="detail-callout"><span>i</span><p>完整凭据、Token 与敏感网络元数据不会在普通管理页面展示。</p></div></aside></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
