<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'

type Entry = { name: string; detail: string; status: string; metric: string; action?: string }
const route = useRoute(); const query = ref(''); const toast = ref('')
const pages: Record<string, { eyebrow: string; title: string; description: string; entries: Entry[]; locked?: boolean }> = {
  media: { eyebrow: '内容与创作', title: '媒体消费', description: '统一查看视频、阅读、音乐与图片内容的消费状态。', entries: [{ name: '最近播放', detail: '视频 · 继续观看', status: 'Available', metric: '3 个资源' }, { name: '待处理媒体', detail: '转码与字幕派生', status: 'Processing', metric: '2 个任务' }] },
  sharing: { eyebrow: '内容与创作', title: '分享与协作', description: '管理分享、Room、评论与协作成员。', entries: [{ name: '产品设计评审', detail: 'Room · 4 位成员', status: 'ACTIVE', metric: '昨天更新' }, { name: '资源分享链接', detail: 'Share · 只读', status: 'ACTIVE', metric: '7 天后过期' }] },
  'storage/tiers': { eyebrow: '附件与存储', title: '存储层', description: '查看 Attachment、Blob 与持久化 Placement 的健康状态。', entries: [{ name: '本地对象存储', detail: 'Storage Provider · HOT', status: 'Healthy', metric: '68 GB' }, { name: '归档层', detail: 'Storage Provider · ARCHIVE', status: 'Healthy', metric: '1.2 TB' }] },
  'storage/cache': { eyebrow: '附件与存储', title: '缓存与下载', description: '区分用户主动下载与可回收缓存，追踪本地占用。', entries: [{ name: '我的下载', detail: 'Download · 本地可用', status: 'Downloaded', metric: '18 项' }, { name: '媒体缓存', detail: 'Cache · 可回收', status: 'Cached', metric: '4.8 GB' }] },
  'storage/archive': { eyebrow: '附件与存储', title: '归档与恢复', description: '观察归档对象恢复进度与可用性状态。', entries: [{ name: '季度媒体归档', detail: 'Archive Restore', status: 'Restoring', metric: '62%' }, { name: '旧附件集合', detail: 'Placement', status: 'ARCHIVE', metric: '可按需恢复' }] },
  'storage/backup': { eyebrow: '附件与存储', title: '备份与恢复', description: '管理 Backup Artifact、Restore Point 与可验证的恢复任务。', entries: [{ name: '最近恢复点', detail: 'Restore Point · 自动', status: 'Verified', metric: '今天 03:00' }, { name: '周度备份', detail: 'Backup Artifact', status: 'Completed', metric: '可恢复' }] },
  'planning/today': { eyebrow: '效率与计划', title: '收集箱与今天', description: '将 Inbox、今天到期和后台任务放在同一执行面。', entries: [{ name: '整理阅读清单', detail: 'Task · 今天 18:00', status: 'OPEN', metric: '高优先级' }, { name: '产品复盘', detail: 'Task · 今天 20:00', status: 'IN_PROGRESS', metric: '25%' }] },
  'planning/projects': { eyebrow: '效率与计划', title: '项目与任务', description: '按 Project 管理任务，不把任务与日历事件混为一体。', entries: [{ name: 'Ikaros V2', detail: 'Project · 12 个任务', status: 'ACTIVE', metric: '68%' }, { name: '家庭资料整理', detail: 'Project · 5 个任务', status: 'PAUSED', metric: '待继续' }] },
  'planning/calendar': { eyebrow: '效率与计划', title: '日历与时间块', description: '规划 Time Block 与预约，截止时间仍归属于 Task。', entries: [{ name: '深度工作', detail: 'Time Block · 09:00–11:00', status: 'SCHEDULED', metric: '今天' }, { name: '团队同步', detail: 'Calendar Event · 14:00', status: 'CONFIRMED', metric: '线上' }] },
  'planning/goals': { eyebrow: '效率与计划', title: '目标与 OKR', description: '连接目标、关键结果与项目进展。', entries: [{ name: '完成 V2 Console', detail: 'Objective · Q3', status: 'ACTIVE', metric: '72%' }, { name: '建立个人知识库', detail: 'Key Result · 资源数', status: 'ON_TRACK', metric: '184 / 240' }] },
  'planning/focus': { eyebrow: '效率与计划', title: '习惯与专注', description: '记录 Habit、Focus Session 与 Review，不改变任务事实。', entries: [{ name: '阅读习惯', detail: 'Habit · 连续 6 天', status: 'ACTIVE', metric: '本周 5 / 7' }, { name: '专注时段', detail: 'Focus Session', status: 'COMPLETED', metric: '45 分钟' }] },
  finance: { eyebrow: '个人记账', title: '账本总览', description: '查看 Ledger、净资产趋势与近期交易。', entries: [{ name: '个人账本', detail: 'Ledger · CNY', status: 'ACTIVE', metric: '¥ 28,640.00' }, { name: '本月支出', detail: 'Transaction projection', status: 'CONFIRMED', metric: '¥ 3,240.00' }] },
  'finance/accounts': { eyebrow: '个人记账', title: '账户', description: '管理现金、银行卡与投资账户余额。', entries: [{ name: '建设银行', detail: 'Bank Account · 末四位 1024', status: 'ACTIVE', metric: '¥ 12,400.00' }, { name: '现金', detail: 'Cash Account', status: 'ACTIVE', metric: '¥ 860.00' }] },
  'finance/transactions': { eyebrow: '个人记账', title: '交易', description: '记录收入、支出与转账，保留分类和来源。', entries: [{ name: '云存储订阅', detail: 'Expense · 软件服务', status: 'CONFIRMED', metric: '¥ 68.00' }, { name: '工资收入', detail: 'Income · 薪资', status: 'CONFIRMED', metric: '¥ 12,000.00' }] },
  'finance/budgets': { eyebrow: '个人记账', title: '预算与周期账', description: '按周期观察预算消耗，不把预算当作余额事实。', entries: [{ name: '软件服务预算', detail: 'Budget · 本月', status: 'ON_TRACK', metric: '¥ 68 / 300' }, { name: '餐饮预算', detail: 'Budget · 本月', status: 'WARNING', metric: '¥ 1,280 / 1,500' }] },
  'finance/reconcile': { eyebrow: '个人记账', title: '对账与导入', description: '预览导入数据、处理重复项并确认对账结果。', entries: [{ name: '银行卡流水导入', detail: 'Import · CSV', status: 'PENDING_REVIEW', metric: '24 行' }, { name: '上月对账', detail: 'Reconciliation', status: 'COMPLETED', metric: '差异 ¥ 0' }] },
  'private-notes': { eyebrow: '私密笔记', title: '私密笔记保险库', description: 'Secure Domain 已锁定；解锁后才读取标题与正文。', entries: [{ name: 'Vault 内容', detail: '受保护元数据不可见', status: 'LOCKED', metric: '需要解锁' }], locked: true },
  'private-notes/conflicts': { eyebrow: '私密笔记', title: '版本与同步冲突', description: '仅展示安全状态，不泄露未解密的笔记内容。', entries: [{ name: '待处理冲突', detail: 'Secure Sync', status: 'LOCKED', metric: '解锁后查看' }], locked: true },
  'private-notes/recovery': { eyebrow: '私密笔记', title: '恢复与导出', description: 'Account Recovery 与 Vault Recovery 分开处理。', entries: [{ name: '恢复流程', detail: 'Cryptographic Recovery', status: 'LOCKED', metric: '需要重新认证' }], locked: true },
  passwords: { eyebrow: '密码管理', title: '密码保险库', description: '密码条目默认遮罩，进入保险库需要独立解锁。', entries: [{ name: 'Password Vault', detail: 'Protected metadata', status: 'LOCKED', metric: '需要解锁' }], locked: true },
  'passwords/generator': { eyebrow: '密码管理', title: '密码生成器', description: '生成器不读取保险库内容，结果只在当前安全上下文短暂存在。', entries: [{ name: '安全生成器', detail: '长度、字符集与排除规则', status: 'READY', metric: '可生成' }] },
  'passwords/health': { eyebrow: '密码管理', title: '健康与安全发送', description: '检查重复、弱密码与安全发送链接状态。', entries: [{ name: '安全评分', detail: 'Vault health', status: 'LOCKED', metric: '解锁后计算' }], locked: true },
  'passwords/devices': { eyebrow: '密码管理', title: '设备与访问', description: '查看密码保险库授权设备与访问记录。', entries: [{ name: '当前设备', detail: 'Browser Session', status: 'AUTHORIZED', metric: '刚刚' }, { name: '旧设备', detail: 'Device Access', status: 'REVOKED', metric: '已撤销' }] },
  'ai/assistant': { eyebrow: 'AI 智能', title: 'AI Assistant', description: 'AI 建议与业务事实明确区分，Tool Call 始终受当前权限约束。', entries: [{ name: '资源整理助手', detail: 'Suggestion · 需要确认', status: 'DRAFT', metric: '3 个建议' }, { name: '最近 Tool Call', detail: 'Command execution', status: 'COMPLETED', metric: '今天' }] },
  'ai/models': { eyebrow: 'AI 智能', title: '模型与提供方', description: '管理模型能力、连接状态与外部隐私边界。', entries: [{ name: '本地模型', detail: 'Provider · Local', status: 'AVAILABLE', metric: '低延迟' }, { name: 'External Provider', detail: 'Provider · Secret masked', status: 'DISABLED', metric: '未启用' }] },
  'ai/personas': { eyebrow: 'AI 智能', title: '人格', description: '管理 Persona 定义与发布版本。', entries: [{ name: '默认助手', detail: 'Persona · v2', status: 'PUBLISHED', metric: '当前使用' }, { name: '研究模式', detail: 'Persona · v1', status: 'DRAFT', metric: '未发布' }] },
  'ai/privacy': { eyebrow: 'AI 智能', title: '上下文与隐私', description: '控制 Context 来源、Memory 与 Secure Domain 边界。', entries: [{ name: '默认上下文', detail: 'Resource + Task', status: 'ACTIVE', metric: '2 个来源' }, { name: '私密域访问', detail: 'Secure Domain', status: 'BLOCKED', metric: '默认禁止' }] },
  'ai/jobs': { eyebrow: 'AI 智能', title: '作业与用量', description: '观察 AI Job、Trace 与模型用量。', entries: [{ name: '本月用量', detail: 'Token projection', status: 'NORMAL', metric: '42%' }, { name: '索引摘要作业', detail: 'Background Job', status: 'RUNNING', metric: '68%' }] },
}
const key = computed(() => route.path.replace(/^\/console\//, '')); const page = computed(() => pages[key.value] || pages.media); const entries = computed(() => page.value.entries.filter(item => `${item.name} ${item.detail} ${item.status}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
</script>
<template><div class="domain-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">{{ page.eyebrow }}</span><span class="mini-avatar">陈</span></header><main class="catalog-main domain-main"><div class="catalog-heading"><div><p class="eyebrow">{{ page.eyebrow }}</p><h1>{{ page.title }}</h1><p>{{ page.description }}</p></div><div class="domain-actions"><button class="outlined-button" @click="notify(page.locked ? '请先完成安全解锁' : '导入流程即将打开')">{{ page.locked ? '安全解锁' : '导入' }}</button><button class="filled-button" @click="notify(page.locked ? '此操作不会泄露私密内容' : '创建流程已打开')">＋ 新建</button></div></div><div v-if="page.locked" class="locked-banner"><span>▣</span><div><strong>Locked Surface</strong><p>受保护域处于锁定状态。页面不会加载解密后的标题、正文或查询词。</p></div></div><div class="domain-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" :placeholder="page.locked ? '解锁后可搜索' : '搜索当前页面'" :disabled="page.locked" /></div><span class="status-chip neutral">{{ entries.length }} 项</span><button class="outlined-button small" @click="notify('已刷新当前状态')">⟳ 刷新</button></div><section class="domain-grid"><article v-for="entry in entries" :key="entry.name" class="domain-card surface-card"><div class="domain-card-top"><span class="domain-icon">◈</span><span class="status-chip" :class="entry.status === 'LOCKED' || entry.status === 'WARNING' || entry.status === 'PROCESSING' ? 'warning' : entry.status === 'COMPLETED' || entry.status === 'ACTIVE' || entry.status === 'Healthy' ? 'success' : 'neutral'">● {{ entry.status }}</span></div><h2>{{ entry.name }}</h2><p>{{ entry.detail }}</p><strong>{{ entry.metric }}</strong><button class="text-button" @click="notify(page.locked ? '需要解锁后查看' : `${entry.name} 详情已打开`) ">查看详情 →</button></article><div v-if="entries.length === 0" class="no-results">没有匹配项目<button class="text-button" @click="query = ''">清除筛选</button></div></section></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
