<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from './services/api'
type Space = { id: string; name: string; status: string; used: number; quota: number }
const router = useRouter(); const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const spaces = ref<Space[]>([{ id: 'demo-space', name: '主空间', status: 'ACTIVE', used: 68, quota: 100 }, { id: 'demo-archive', name: '归档空间', status: 'ACTIVE', used: 24, quota: 500 }]); const name = ref(''); const dialog = ref(false); const loading = ref(false); const toast = ref('')
const totalUsed = computed(() => spaces.value.reduce((sum, item) => sum + item.used, 0)); const totalQuota = computed(() => spaces.value.reduce((sum, item) => sum + item.quota, 0))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listDriveSpaces(actorId); if (result.length) spaces.value = result.map(item => ({ id: item.id, name: item.displayName || item.name || item.id.slice(0, 8), status: item.status || 'ACTIVE', used: Math.round((item.usedBytes || item.used_bytes || 0) / 1024 / 1024 / 1024), quota: Math.max(1, Math.round((item.quotaBytes || item.quota_bytes || 0) / 1024 / 1024 / 1024)) })) } catch { notify('Drive API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!name.value.trim()) { notify('请输入空间名称'); return } try { const item = actorId ? await api.createDriveSpace(name.value.trim(), actorId) : { id: `demo-${Date.now()}`, displayName: name.value.trim(), status: 'ACTIVE' }; spaces.value.push({ id: item.id, name: item.displayName || item.name || name.value.trim(), status: item.status || 'ACTIVE', used: 0, quota: 100 }); dialog.value = false; name.value = ''; notify('Drive Space 已创建') } catch (error) { notify(error instanceof Error ? error.message : '创建空间失败') } }
onMounted(load)
</script>
<template><div class="drive-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">个人网盘 · 本地环境</span><span class="mini-avatar">陈</span></header><main class="catalog-main drive-home-main"><div class="catalog-heading"><div><p class="eyebrow">个人网盘</p><h1>文件空间</h1><p>管理 Drive Space；文件名、目录与内容读取仍受独立权限控制。</p></div><div class="drive-actions"><button class="outlined-button" @click="router.push('/console/drive/transfers')">⇄ 传输中心</button><button class="filled-button" @click="dialog = true">＋ 新建空间</button></div></div><section class="drive-home-summary"><article class="surface-card"><span>空间数量</span><strong>{{ spaces.length }}</strong><small>当前授权范围</small></article><article class="surface-card"><span>逻辑用量</span><strong>{{ totalUsed }} GB</strong><small>不等于物理 Storage Used</small></article><article class="surface-card"><span>总配额</span><strong>{{ totalQuota }} GB</strong><small>由空间策略决定</small></article></section><div class="drive-home-toolbar"><span class="status-chip success">● 服务可用</span><button class="outlined-button small" :disabled="loading" @click="load">{{ loading ? '加载中…' : '⟳ 刷新空间' }}</button></div><section class="drive-home-grid"><article v-for="space in spaces" :key="space.id" class="surface-card drive-space-card"><div class="drive-card-top"><span class="drive-icon">☁</span><span class="status-chip success">● {{ space.status }}</span></div><h2>{{ space.name }}</h2><p>Drive Space · {{ space.id.slice(0, 8) }}</p><div class="quota-line"><span><b>{{ space.used }} GB</b> / {{ space.quota }} GB</span><span>{{ Math.round(space.used / space.quota * 100) }}%</span></div><div class="quota-bar"><span :style="{ width: `${Math.min(100, space.used / space.quota * 100)}%` }"></span></div><div class="space-actions"><button class="text-button" @click="router.push(`/console/drive/spaces/${space.id}`)">打开空间 →</button><button class="text-button" @click="notify('空间治理设置已打开')">治理</button></div></article></section></main><div v-if="dialog" class="role-create-scrim" @click.self="dialog = false"><section class="role-create-dialog"><div class="dialog-title"><div><p class="eyebrow">个人网盘</p><h2>新建 Drive Space</h2></div><button class="icon-button" @click="dialog = false">×</button></div><label>空间名称 *<input v-model="name" maxlength="128" placeholder="例如：家庭资料" @keyup.enter="create" /></label><p class="account-note">创建后会同时生成根目录和默认配额；空间与文件内容读取权限分开判断。</p><div class="dialog-actions"><button class="outlined-button" @click="dialog = false">取消</button><button class="filled-button" @click="create">创建空间</button></div></section></div><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
