<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api } from './services/api'
import { ElButton, ElInput, ElTag } from 'element-plus'

const route = useRoute(); const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const query = ref(''); const toast = ref(''); const loading = ref(false); const spaces = ref<Array<{ id: string; name: string; detail: string; status: string; metric: string }>>([]); const nodes = ref<Array<{ id: string; name: string; detail: string; status: string; metric: string }>>([]); const bindings = ref<Array<{ id: string; name: string; detail: string; status: string; metric: string }>>([]); const quotaItems = ref<Array<{ id: string; name: string; detail: string; status: string; metric: string }>>([]); const conflictItems = ref<Array<{ id: string; name: string; detail: string; status: string; metric: string }>>([])
const mode = computed(() => route.path.includes('/transfers') ? 'transfers' : route.path.includes('/sync') ? 'sync' : route.path.includes('/conflicts') ? 'conflicts' : route.path.includes('/revisions') ? 'revisions' : route.path.includes('/trash') ? 'trash' : route.path.includes('/policies') ? 'policies' : route.path.includes('/quota') ? 'quota' : 'spaces')
const catalog = computed(() => ({ spaces: { title: '文件空间', description: '管理 Drive Space 与其中的逻辑文件节点。', items: spaces.value.map(item => ({ ...item, action: '打开空间' })) }, transfers: { title: '传输中心', description: '查看上传、下载与后台传输任务的进度。', items: [] }, sync: { title: '同步关系', description: '管理设备与 Drive Space 的同步绑定。', items: [] }, conflicts: { title: '冲突处理', description: '在本地版本与云端版本之间做出明确选择。', items: [] }, revisions: { title: '版本历史', description: '查看文件历史版本；恢复会创建新的当前版本。', items: [] }, trash: { title: '回收站', description: '恢复或永久删除已移入回收站的节点。永久删除不可恢复。', items: [] }, quota: { title: '配额', description: '查看空间逻辑用量、预留量和可用配额。', items: [] }, policies: { title: 'Drive Policies', description: '查看空间保留、删除与同步治理策略；策略修改受权限与审计约束。', items: [] } }[mode.value]))
const items = computed(() => (route.params.spaceId && nodes.value.length ? nodes.value : mode.value === 'sync' && bindings.value.length ? bindings.value : mode.value === 'conflicts' && conflictItems.value.length ? conflictItems.value : mode.value === 'quota' && quotaItems.value.length ? quotaItems.value : catalog.value.items).filter(item => `${item.name} ${item.detail} ${item.status}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!['spaces', 'sync', 'quota', 'conflicts'].includes(mode.value) || !actorId) return; loading.value = true; try { if (mode.value === 'sync') { const result = await api.listDriveBindings(actorId); bindings.value = result.map(item => ({ id: item.id, name: item.localDisplayPath || item.local_display_path || `设备 ${item.deviceId || item.device_id || item.id.slice(0, 8)}`, detail: `Sync Binding · ${item.driveSpaceId || item.drive_space_id || '空间未知'}`, status: item.enabled === false ? '已暂停' : item.state || '已连接', metric: typeof item.cursor === 'number' ? `游标 ${item.cursor}` : '状态已同步' })) } else if (mode.value === 'conflicts') { const bindings = await api.listDriveBindings(actorId); const conflicts = (await Promise.all(bindings.map(binding => api.listDriveConflicts(binding.id, actorId)))).flat(); conflictItems.value = conflicts.map(item => ({ id: item.id, name: `同步冲突 ${item.id.slice(0, 8)}`, detail: `Sync Conflict · 节点 ${item.nodeId || item.node_id || '受保护'}`, status: item.state || '待处理', metric: item.detectedAt || item.detected_at ? new Date(item.detectedAt || item.detected_at || '').toLocaleString('zh-CN') : '时间不可用' })) } else if (mode.value === 'quota') { const list = await api.listDriveSpaces(actorId); const space = list[0]; if (space) { const result = await api.getDriveQuota(space.id, actorId); const limit = result.limitBytes || result.limit_bytes || 0; const used = result.usedBytes || result.used_bytes || 0; const reserved = result.reservedBytes || result.reserved_bytes || 0; const available = result.availableBytes || result.available_bytes || 0; quotaItems.value = [{ id: space.id, name: space.displayName || space.name || space.id.slice(0, 8), detail: `逻辑用量 ${used} bytes · 预留 ${reserved} bytes`, status: '已同步', metric: `可用 ${available} / 配额 ${limit} bytes` }] } } else if (route.params.spaceId) { const result = await api.listDriveChildren(String(route.params.spaceId), actorId); nodes.value = result.map(item => ({ id: item.id, name: item.name || item.id.slice(0, 8), detail: `Drive Node · ${item.nodeType || item.node_type || 'UNKNOWN'}`, status: item.lifecycle || 'ACTIVE', metric: item.updatedAt || item.updated_at ? new Date(item.updatedAt || item.updated_at || '').toLocaleDateString('zh-CN') : '已同步' })) } else { const result = await api.listDriveSpaces(actorId); if (result.length) spaces.value = result.map(item => ({ id: item.id, name: item.displayName || item.name || item.id.slice(0, 8), detail: 'Drive Space', status: item.status || 'ACTIVE', metric: `${item.usedBytes || item.used_bytes || 0} / ${item.quotaBytes || item.quota_bytes || 0} bytes` })) } } catch { notify('Drive API 暂不可用，已保留演示数据') } finally { loading.value = false } }
watch(() => route.fullPath, () => { nodes.value = []; void load() }, { immediate: true })
</script>

<template><div class="drive-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">个人网盘 · 本地环境</span><span class="mini-avatar">陈</span></header><main class="catalog-main drive-main"><div class="catalog-heading"><div><p class="eyebrow">个人网盘</p><h1>{{ catalog.title }}</h1><p>{{ catalog.description }}</p></div><div class="drive-actions"><el-button @click="notify('导入流程即将打开')">⇩ 导入</el-button><el-button v-if="mode === 'spaces'" type="primary" @click="notify('新建空间表单即将打开')">＋ 新建空间</el-button></div></div><nav class="drive-tabs"><RouterLink v-for="item in [{label:'空间',path:'/console/drive'},{label:'传输',path:'/console/drive/transfers'},{label:'同步',path:'/console/drive/sync'},{label:'冲突',path:'/console/drive/conflicts'},{label:'版本',path:'/console/drive/revisions'},{label:'回收站',path:'/console/drive/trash'},{label:'配额',path:'/console/drive/quota'}]" :key="item.path" :to="item.path" :class="{ active: (mode === 'spaces' && item.path === '/console/drive') || item.path.includes(mode) }">{{ item.label }}</RouterLink></nav><div class="drive-toolbar surface-card"><el-input v-model="query" clearable placeholder="搜索当前空间" style="max-width:360px" /><el-tag type="info">{{ items.length }} 项</el-tag><el-button :loading="loading" @click="load">刷新</el-button></div><section class="drive-grid"><article v-for="item in items" :key="item.id" class="drive-card surface-card"><div class="drive-card-top"><span class="drive-icon">{{ mode === 'spaces' ? '☁' : mode === 'transfers' ? '⇄' : mode === 'conflicts' ? '⚠' : mode === 'trash' ? '⌫' : '▰' }}</span><el-tag :type="item.status === '待处理' || item.status === '进行中' ? 'warning' : item.status === '可恢复' ? 'info' : 'success'">{{ item.status }}</el-tag></div><h2>{{ item.name }}</h2><p>{{ item.detail }}</p><strong>{{ item.metric }}</strong><el-button link type="primary" @click="notify(mode === 'conflicts' ? '冲突解决器已打开' : mode === 'trash' ? '永久删除需要二次确认' : item.action || '详情已打开')">{{ mode === 'conflicts' ? '解决冲突 →' : mode === 'trash' ? '管理项目 →' : '查看详情 →' }}</el-button></article><div v-if="items.length === 0" class="no-results">当前没有匹配项目</div></section></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
