<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from './services/api'

const route = useRoute(); const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const query = ref(''); const toast = ref(''); const loading = ref(false); const spaces = ref([{ id: 'demo-space', name: '主空间', detail: '个人文件与附件', status: '正常', metric: '68 GB / 100 GB' }, { id: 'demo-archive', name: '归档空间', detail: '低频访问资料', status: '正常', metric: '24 GB / 500 GB' }])
const mode = computed(() => route.path.includes('/transfers') ? 'transfers' : route.path.includes('/sync') ? 'sync' : route.path.includes('/conflicts') ? 'conflicts' : route.path.includes('/revisions') ? 'revisions' : route.path.includes('/trash') ? 'trash' : route.path.includes('/quota') || route.path.includes('/policies') ? 'quota' : 'spaces')
const catalog = computed(() => ({ spaces: { title: '文件空间', description: '管理 Drive Space 与其中的逻辑文件节点。', items: spaces.value.map(item => ({ ...item, action: '打开空间' })) }, transfers: { title: '传输中心', description: '查看上传、下载与后台传输任务的进度。', items: [{ id: 'upload-1', name: '资料备份.zip', detail: '上传 · 主空间', status: '进行中', metric: '68%' }, { id: 'download-1', name: '媒体缩略图', detail: '下载 · 主空间', status: '进行中', metric: '42%' }, { id: 'upload-2', name: '旧项目归档', detail: '上传 · 归档空间', status: '已完成', metric: '100%' }] }, sync: { title: '同步关系', description: '管理设备与 Drive Space 的同步绑定。', items: [{ id: 'sync-1', name: 'MacBook Pro · 主空间', detail: 'macOS · 最近同步刚刚', status: '已连接', metric: '无待处理变更' }, { id: 'sync-2', name: 'Pixel · 主空间', detail: 'Android · 最近同步昨天', status: '已暂停', metric: '3 个待同步' }] }, conflicts: { title: '冲突处理', description: '在本地版本与云端版本之间做出明确选择。', items: [{ id: 'conflict-1', name: 'Ikaros V2 产品设计', detail: '本地版本 · 昨天 18:24', status: '待处理', metric: '2 个候选版本' }, { id: 'conflict-2', name: '阅读进度', detail: '云端版本 · 2 天前', status: '待处理', metric: '2 个候选版本' }] }, revisions: { title: '版本历史', description: '查看文件历史版本；恢复会创建新的当前版本。', items: [{ id: 'revision-1', name: '资料备份.zip', detail: '版本 4 · 陈昊', status: '当前版本', metric: '刚刚' }, { id: 'revision-2', name: '资料备份.zip', detail: '版本 3 · 陈昊', status: '历史版本', metric: '昨天' }] }, trash: { title: '回收站', description: '恢复或永久删除已移入回收站的节点。永久删除不可恢复。', items: [{ id: 'trash-1', name: '旧活动周报', detail: '移入时间 7 天前', status: '可恢复', metric: '永久删除 23 天后' }, { id: 'trash-2', name: '临时导出.csv', detail: '移入时间 7 天前', status: '可恢复', metric: '永久删除 23 天后' }] }, quota: { title: '配额与策略', description: '查看空间使用量与保留策略；外部部署锁定值会明确标识。', items: [{ id: 'quota-1', name: '主空间配额', detail: '单用户默认配额', status: '平台默认', metric: '68 GB / 100 GB' }, { id: 'quota-2', name: '回收站保留期', detail: '自动清理策略', status: '部署配置', metric: '30 天' }] } }[mode.value]))
const items = computed(() => catalog.value.items.filter(item => `${item.name} ${item.detail} ${item.status}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (mode.value !== 'spaces' || !actorId) return; loading.value = true; try { const result = await api.listDriveSpaces(actorId); if (result.length) spaces.value = result.map(item => ({ id: item.id, name: item.displayName || item.name || item.id.slice(0, 8), detail: 'Drive Space', status: item.status || 'ACTIVE', metric: `${item.usedBytes || item.used_bytes || 0} / ${item.quotaBytes || item.quota_bytes || 0} bytes` })) } catch { notify('Drive API 暂不可用，已保留演示数据') } finally { loading.value = false } }
onMounted(load)
</script>

<template><div class="drive-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">个人网盘 · 本地环境</span><span class="mini-avatar">陈</span></header><main class="catalog-main drive-main"><div class="catalog-heading"><div><p class="eyebrow">个人网盘</p><h1>{{ catalog.title }}</h1><p>{{ catalog.description }}</p></div><div class="drive-actions"><button class="outlined-button" @click="notify('导入流程即将打开')">⇩ 导入</button><button v-if="mode === 'spaces'" class="filled-button" @click="notify('新建空间表单即将打开')">＋ 新建空间</button></div></div><nav class="drive-tabs"><RouterLink v-for="item in [{label:'空间',path:'/console/drive'},{label:'传输',path:'/console/drive/transfers'},{label:'同步',path:'/console/drive/sync'},{label:'冲突',path:'/console/drive/conflicts'},{label:'版本',path:'/console/drive/revisions'},{label:'回收站',path:'/console/drive/trash'},{label:'配额',path:'/console/drive/quota'}]" :key="item.path" :to="item.path" :class="{ active: (mode === 'spaces' && item.path === '/console/drive') || item.path.includes(mode) }">{{ item.label }}</RouterLink></nav><div class="drive-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" placeholder="搜索当前空间" /></div><span class="status-chip neutral">{{ items.length }} 项</span><button class="outlined-button small" :disabled="loading" @click="load">{{ loading ? '加载中…' : '⟳ 刷新' }}</button></div><section class="drive-grid"><article v-for="item in items" :key="item.id" class="drive-card surface-card"><div class="drive-card-top"><span class="drive-icon">{{ mode === 'spaces' ? '☁' : mode === 'transfers' ? '⇄' : mode === 'conflicts' ? '⚠' : mode === 'trash' ? '⌫' : '▰' }}</span><span class="status-chip" :class="item.status === '待处理' || item.status === '进行中' ? 'warning' : item.status === '可恢复' ? 'neutral' : 'success'">● {{ item.status }}</span></div><h2>{{ item.name }}</h2><p>{{ item.detail }}</p><strong>{{ item.metric }}</strong><button class="text-button" @click="notify(mode === 'conflicts' ? '冲突解决器已打开' : mode === 'trash' ? '永久删除需要二次确认' : item.action || '详情已打开')">{{ mode === 'conflicts' ? '解决冲突 →' : mode === 'trash' ? '管理项目 →' : '查看详情 →' }}</button></article><div v-if="items.length === 0" class="no-results">当前没有匹配项目</div></section></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
