<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from './services/api'
import { ElButton, ElOption, ElSelect, ElTag } from 'element-plus'
type Focus = { id: string; mode: string; status: string; planned: number; actual: number; started: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const sessions = ref<Focus[]>([{ id: 'demo-focus', mode: 'DEEP_WORK', status: 'COMPLETED', planned: 45, actual: 42, started: '今天 09:00' }, { id: 'demo-focus-2', mode: 'POMODORO', status: 'RUNNING', planned: 25, actual: 12, started: '今天 10:30' }]); const minutes = ref(25); const loading = ref(false); const toast = ref('')
const running = computed(() => sessions.value.find(item => item.status === 'RUNNING')); const completed = computed(() => sessions.value.filter(item => item.status === 'COMPLETED').length)
function notify(message: string) { if (message === '完成操作需要记录实际时长') { void complete(); return } toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function complete() { const item = running.value; if (!item) return; const actualMinutes = Math.max(1, item.actual || item.planned); try { if (actorId && !item.id.startsWith('demo-')) await api.completePlanningFocus(item.id, { actualMinutes }, actorId); item.actual = actualMinutes; item.status = 'COMPLETED'; notify(actorId && !item.id.startsWith('demo-') ? '专注会话已完成并同步' : '演示专注会话已完成（未提交后端）') } catch (error) { notify(error instanceof Error ? error.message : '完成专注会话失败') } }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listPlanningFocus(actorId); if (result.length) sessions.value = result.map(item => ({ id: item.id, mode: item.mode || 'DEEP_WORK', status: item.status || 'RUNNING', planned: item.plannedMinutes || 0, actual: item.actualMinutes || 0, started: item.startedAt ? new Date(item.startedAt).toLocaleString('zh-CN') : '刚刚' })) } catch { notify('专注 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function start() { if (minutes.value < 1) { notify('专注时长必须大于 0 分钟'); return } try { const item = actorId ? await api.startPlanningFocus({ plannedMinutes: minutes.value, mode: 'POMODORO' }, actorId) : { id: `demo-${Date.now()}`, mode: 'POMODORO', status: 'RUNNING', plannedMinutes: minutes.value, actualMinutes: 0, startedAt: new Date().toISOString() }; sessions.value.unshift({ id: item.id, mode: item.mode || 'POMODORO', status: item.status || 'RUNNING', planned: item.plannedMinutes || minutes.value, actual: item.actualMinutes || 0, started: item.startedAt ? new Date(item.startedAt).toLocaleString('zh-CN') : '刚刚' }); notify('专注会话已开始') } catch (error) { notify(error instanceof Error ? error.message : '开始专注失败') } }
onMounted(load)
</script>
<template><div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>习惯与专注</h1><p>Focus Session 是专注记录，不会自动改变 Task 或 Time Block。</p></div><div class="focus-start"><el-select v-model="minutes" style="width:140px"><el-option v-for="value in [15,25,45,60]" :key="value" :label="`${value} 分钟`" :value="value" /></el-select><el-button type="primary" :disabled="!!running" @click="start">{{ running ? '专注进行中' : '开始专注' }}</el-button></div></div><nav class="planning-tabs"><RouterLink to="/console/planning/today">今天</RouterLink><RouterLink to="/console/planning/projects">项目与任务</RouterLink><RouterLink to="/console/planning/calendar">日历与时间块</RouterLink><RouterLink to="/console/planning/goals">目标与 OKR</RouterLink><RouterLink to="/console/planning/focus" class="active">习惯与专注</RouterLink></nav><section class="planning-summary"><article class="surface-card"><span>累计会话</span><strong>{{ sessions.length }}</strong></article><article class="surface-card"><span>已完成</span><strong>{{ completed }}</strong></article><article class="surface-card"><span>当前状态</span><strong>{{ running ? '进行中' : '空闲' }}</strong></article></section><div class="planning-toolbar surface-card"><el-tag :type="running ? 'warning' : 'success'">{{ running ? 'Focus Session 进行中' : '可以开始专注' }}</el-tag><el-button :loading="loading" @click="load">刷新</el-button></div><section class="focus-list surface-card"><div v-for="session in sessions" :key="session.id" class="focus-row"><span class="focus-icon">◉</span><div><b>{{ session.mode }}</b><small>{{ session.started }} · 计划 {{ session.planned }} 分钟</small></div><el-tag :type="session.status === 'COMPLETED' ? 'success' : 'warning'">{{ session.status }}</el-tag><strong>{{ session.actual }} 分钟</strong><el-button link type="primary" @click="notify(session.status === 'RUNNING' ? '完成操作需要记录实际时长' : '专注详情已打开')">{{ session.status === 'RUNNING' ? '完成' : '查看' }} →</el-button></div><div v-if="sessions.length === 0" class="no-results">暂无专注记录</div></section></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
