<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from './services/api'
type Goal = { id: string; title: string; description: string; type: string; status: string; progress: number; deadline: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const goals = ref<Goal[]>([{ id: 'demo-goal', title: '完成 V2 Console', description: '完成后台系统主要页面与 API 联动', type: 'OBJECTIVE', status: 'ACTIVE', progress: 72, deadline: '2026-09-30' }, { id: 'demo-knowledge', title: '建立个人知识库', description: '将资源、文档和计划形成可检索体系', type: 'KEY_RESULT', status: 'ACTIVE', progress: 48, deadline: '2026-12-31' }]); const query = ref(''); const title = ref(''); const description = ref(''); const dialog = ref(false); const loading = ref(false); const toast = ref('')
const filtered = computed(() => goals.value.filter(item => `${item.title} ${item.description} ${item.status}`.toLowerCase().includes(query.value.toLowerCase()))); const average = computed(() => goals.value.length ? Math.round(goals.value.reduce((sum, item) => sum + item.progress, 0) / goals.value.length) : 0)
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listPlanningGoals(actorId); if (result.length) goals.value = result.map(item => ({ id: item.id, title: item.title || item.id.slice(0, 8), description: item.description || '暂无描述', type: item.type || 'OBJECTIVE', status: item.status || 'ACTIVE', progress: Math.round((item.progress || 0) * 100), deadline: item.deadline ? new Date(item.deadline).toLocaleDateString('zh-CN') : '未设置' })) } catch { notify('目标 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!title.value.trim()) { notify('请输入目标标题'); return } try { const item = actorId ? await api.createPlanningGoal({ title: title.value.trim(), description: description.value.trim() || undefined, type: 'OBJECTIVE' }, actorId) : { id: `demo-${Date.now()}`, title: title.value.trim(), description: description.value.trim(), type: 'OBJECTIVE', status: 'ACTIVE', progress: 0 }; goals.value.unshift({ id: item.id, title: item.title || title.value.trim(), description: item.description || '暂无描述', type: item.type || 'OBJECTIVE', status: item.status || 'ACTIVE', progress: Math.round((item.progress || 0) * 100), deadline: item.deadline ? new Date(item.deadline).toLocaleDateString('zh-CN') : '未设置' }); dialog.value = false; title.value = ''; description.value = ''; notify('目标已创建') } catch (error) { notify(error instanceof Error ? error.message : '目标创建失败') } }
onMounted(load)
</script>
<template><div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>目标与 OKR</h1><p>用 Objective、Key Result 和进度检查连接长期目标与日常项目。</p></div><button class="filled-button" @click="dialog = true">＋ 新建目标</button></div><nav class="planning-tabs"><RouterLink to="/console/planning/today">今天</RouterLink><RouterLink to="/console/planning/projects">项目与任务</RouterLink><RouterLink to="/console/planning/calendar">日历与时间块</RouterLink><RouterLink to="/console/planning/goals" class="active">目标与 OKR</RouterLink></nav><section class="planning-summary"><article class="surface-card"><span>目标总数</span><strong>{{ goals.length }}</strong></article><article class="surface-card"><span>平均进度</span><strong>{{ average }}%</strong></article><article class="surface-card"><span>进行中</span><strong>{{ goals.filter(item => item.status === 'ACTIVE').length }}</strong></article></section><div class="planning-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" placeholder="搜索目标" /></div><button class="outlined-button small" :disabled="loading" @click="load">{{ loading ? '加载中…' : '⟳ 刷新' }}</button></div><section class="goal-grid"><article v-for="goal in filtered" :key="goal.id" class="surface-card goal-card"><div class="project-card-top"><span class="project-icon">↗</span><span class="status-chip success">● {{ goal.status }}</span></div><h2>{{ goal.title }}</h2><p>{{ goal.description }}</p><div class="goal-progress"><div><span>进度</span><b>{{ goal.progress }}%</b></div><div class="quota-bar"><span :style="{ width: `${goal.progress}%` }"></span></div></div><small>{{ goal.type }} · 截止 {{ goal.deadline }}</small><button class="text-button" @click="notify('目标详情已打开')">查看详情 →</button></article><div v-if="filtered.length === 0" class="no-results">没有匹配目标<button class="text-button" @click="query = ''">清除筛选</button></div></section></main><div v-if="dialog" class="role-create-scrim" @click.self="dialog = false"><section class="role-create-dialog"><div class="dialog-title"><div><p class="eyebrow">效率与计划</p><h2>新建目标</h2></div><button class="icon-button" @click="dialog = false">×</button></div><label>目标标题 *<input v-model="title" maxlength="160" placeholder="例如：建立个人知识库" @keyup.enter="create" /></label><label>描述（可选）<textarea v-model="description" maxlength="2000" placeholder="说明目标和衡量范围…"></textarea></label><div class="dialog-actions"><button class="outlined-button" @click="dialog = false">取消</button><button class="filled-button" @click="create">创建目标</button></div></section></div><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
