<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api } from './services/api'
import { ElButton, ElDialog, ElForm, ElFormItem, ElInput, ElProgress, ElTag } from 'element-plus'
type Goal = { id: string; title: string; description: string; type: string; status: string; progress: number; deadline: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const goals = ref<Goal[]>([]); const query = ref(''); const title = ref(''); const description = ref(''); const dialog = ref(false); const loading = ref(false); const toast = ref('')
const filtered = computed(() => goals.value.filter(item => `${item.title} ${item.description} ${item.status}`.toLowerCase().includes(query.value.toLowerCase()))); const average = computed(() => goals.value.length ? Math.round(goals.value.reduce((sum, item) => sum + item.progress, 0) / goals.value.length) : 0)
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) { notify('未配置当前用户身份，无法加载目标'); return } loading.value = true; try { const result = await api.listPlanningGoals(actorId); goals.value = result.map(item => ({ id: item.id, title: item.title || item.id.slice(0, 8), description: item.description || '暂无描述', type: item.type || 'OBJECTIVE', status: item.status || 'ACTIVE', progress: Math.round((item.progress || 0) * 100), deadline: item.deadline ? new Date(item.deadline).toLocaleDateString('zh-CN') : '未设置' })) } catch { goals.value = []; notify('目标 API 加载失败，请检查后端服务') } finally { loading.value = false } }
async function create() { if (!title.value.trim()) { notify('请输入目标标题'); return } if (!actorId) { notify('未配置当前用户身份，无法创建目标'); return } try { const item = await api.createPlanningGoal({ title: title.value.trim(), description: description.value.trim() || undefined, type: 'OBJECTIVE' }, actorId); goals.value.unshift({ id: item.id, title: item.title || title.value.trim(), description: item.description || '暂无描述', type: item.type || 'OBJECTIVE', status: item.status || 'ACTIVE', progress: Math.round((item.progress || 0) * 100), deadline: item.deadline ? new Date(item.deadline).toLocaleDateString('zh-CN') : '未设置' }); dialog.value = false; title.value = ''; description.value = ''; notify('目标已创建') } catch (error) { notify(error instanceof Error ? error.message : '目标创建失败') } }
onMounted(load)
</script>
<template><div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>目标与 OKR</h1><p>用 Objective、Key Result 和进度检查连接长期目标与日常项目。</p></div><el-button type="primary" @click="dialog = true">＋ 新建目标</el-button></div><nav class="planning-tabs"><RouterLink to="/console/planning/today">今天</RouterLink><RouterLink to="/console/planning/projects">项目与任务</RouterLink><RouterLink to="/console/planning/calendar">日历与时间块</RouterLink><RouterLink to="/console/planning/goals" class="active">目标与 OKR</RouterLink></nav><section class="planning-summary"><article class="surface-card"><span>目标总数</span><strong>{{ goals.length }}</strong></article><article class="surface-card"><span>平均进度</span><strong>{{ average }}%</strong></article><article class="surface-card"><span>进行中</span><strong>{{ goals.filter(item => item.status === 'ACTIVE').length }}</strong></article></section><div class="planning-toolbar surface-card"><el-input v-model="query" clearable placeholder="搜索目标" style="max-width:360px" /><el-button :loading="loading" @click="load">刷新</el-button></div><section class="goal-grid"><article v-for="goal in filtered" :key="goal.id" class="surface-card goal-card"><div class="project-card-top"><span class="project-icon">↗</span><el-tag type="success">{{ goal.status }}</el-tag></div><h2>{{ goal.title }}</h2><p>{{ goal.description }}</p><div class="goal-progress"><div><span>进度</span><b>{{ goal.progress }}%</b></div><el-progress :percentage="goal.progress" :show-text="false" /></div><small>{{ goal.type }} · 截止 {{ goal.deadline }}</small><el-button link type="primary" @click="notify('目标详情已打开')">查看详情 →</el-button></article><div v-if="filtered.length === 0" class="no-results">没有匹配目标<el-button link type="primary" @click="query = ''">清除筛选</el-button></div></section></main><el-dialog v-model="dialog" title="新建目标" width="460px"><el-form label-position="top"><el-form-item label="目标标题 *"><el-input v-model="title" maxlength="160" placeholder="例如：建立个人知识库" @keyup.enter="create" /></el-form-item><el-form-item label="描述（可选）"><el-input v-model="description" type="textarea" maxlength="2000" placeholder="说明目标和衡量范围…" /></el-form-item><div class="dialog-actions"><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="create">创建目标</el-button></div></el-form></el-dialog><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
