<script setup lang="ts">
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElAlert, ElButton, ElCheckbox, ElForm, ElFormItem, ElInput } from 'element-plus'
import { api, saveAuthSession } from './services/api'
const route = useRoute(); const router = useRouter(); const email = ref(''); const password = ref(''); const remember = ref(true); const error = ref(''); const loading = ref(false)
async function submit() { error.value = ''; if (!email.value.trim()) { error.value = '请输入用户名'; return } if (password.value.length < 8) { error.value = '密码至少需要 8 位'; return }; loading.value = true; try { const session = await api.login({ username: email.value.trim(), password: password.value }); saveAuthSession(session, remember.value); router.replace(String(route.query.returnUrl || '/console/dashboard')) } catch (e) { error.value = e instanceof Error ? e.message : '登录失败，请检查用户名和密码' } finally { loading.value = false } }
</script>
<template><div class="login-page"><div class="login-decoration"><div class="login-orb one"></div><div class="login-orb two"></div><span>✦</span></div><main class="login-card"><div class="login-brand"><div class="brand-mark">i</div><div><strong>Ikaros</strong><small>Console</small></div></div><p class="eyebrow">安全访问</p><h1>欢迎回来</h1><p class="login-subtitle">登录你的 Ikaros 工作空间</p><el-form label-position="top" @submit.prevent="submit"><el-form-item label="用户名"><el-input v-model="email" type="text" autocomplete="username" placeholder="输入用户名" /></el-form-item><el-form-item label="密码"><el-input v-model="password" type="password" show-password autocomplete="current-password" placeholder="至少 8 位" /></el-form-item><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" /><div class="login-options"><el-checkbox v-model="remember">记住此设备</el-checkbox><el-button link @click="router.push('/setup')">注册账户</el-button></div><el-button class="login-button" :loading="loading" type="primary" native-type="submit">登录 <span>→</span></el-button></el-form><p class="login-footnote">认证由 Ikaros 后端 Authentication Service 处理。</p></main></div></template>
