<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api } from './services/api'

const route = useRoute(); const filter = ref('全部'); const toast = ref(''); const refreshedAt = ref('刚刚'); const providerItems = ref<Array<{ id: string; name: string; detail: string; status: string; metric: string }>>([])
const running = ref<Record<string, boolean>>({ 'weekly-backup': true, 'metadata-sync': false, 'activity-report': true })
const catalog = computed(() => route.path.includes('storage-health') ? { title: '存储健康', eyebrow: '系统运维', description: '查看 Provider、附件索引和缓存空间的可用性与容量状态。', items: [{ id: 'object-storage', name: '对象存储 Provider', detail: '默认层 · 116 ms', status: '健康', metric: '99.98% 可用' }, { id: 'blob-index', name: 'Blob 元数据索引', detail: '一致性检查 · 刚刚', status: '健康', metric: '12,486 条' }, { id: 'download-cache', name: '下载缓存', detail: '本地缓存目录', status: '注意', metric: '68% 已使用' }] } : route.path.includes('plugins') ? { title: '插件运行时', eyebrow: '系统运维', description: '监控扩展运行时、连接器网关和隔离执行器。', items: [{ id: 'runtime', name: 'Plugin Runtime', detail: 'Core extension host', status: '健康', metric: '12 个已加载' }, { id: 'gateway', name: '连接器网关', detail: 'External providers', status: '健康', metric: '8 个在线' }, { id: 'sandbox', name: '隔离执行器', detail: 'Plugin task sandbox', status: '注意', metric: '1 个待更新' }] } : route.path.includes('jobs') ? { title: '定时任务', eyebrow: '系统运维', description: '查看调度计划与最近执行结果；失败运行会关联后台任务。', items: [{ id: 'weekly-backup', name: '每周资料备份', detail: '每周一 02:00 · 最近成功昨天', status: running.value['weekly-backup'] ? '已启用' : '已暂停', metric: '下次 5 天后' }, { id: 'metadata-sync', name: '资源元数据同步', detail: '每 30 分钟 · 增量同步', status: running.value['metadata-sync'] ? '已启用' : '已暂停', metric: '下次 18 分钟后' }, { id: 'activity-report', name: '活动周报', detail: '每周一 09:00 · 最近失败', status: running.value['activity-report'] ? '已启用' : '已暂停', metric: '下次 6 天后' }] } : { title: '子系统', eyebrow: '系统运维', description: '按子系统查看核心能力健康状态与最近响应指标。', items: [{ id: 'content', name: 'Content & Library', detail: '资源、文档与媒体', status: '健康', metric: '42 ms' }, { id: 'planning', name: 'Planning', detail: '任务、日历与目标', status: '健康', metric: '18 ms' }, { id: 'scheduler', name: 'Scheduler / Worker', detail: '调度与后台执行', status: '降级', metric: '队列 12' }] })
const activeItems = computed(() => route.path.includes('storage-health') && providerItems.value.length ? providerItems.value : catalog.value.items)
const items = computed(() => activeItems.value.filter(item => filter.value === '全部' || item.status === filter.value))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function loadProviders() { if (!route.path.includes('storage-health')) return; try { const providers = await api.listStorageProviders(); providerItems.value = providers.map(item => ({ id: item.id, name: item.providerKey || item.id.slice(0, 8), detail: `${item.providerType || 'Storage Provider'} · ${item.tier || '未分层'}`, status: item.status || 'UNKNOWN', metric: item.updatedAt ? new Date(item.updatedAt).toLocaleDateString('zh-CN') : '已同步' })); refreshedAt.value = '刚刚' } catch { notify('存储 Provider API 暂不可用，已保留演示数据') } }
function refresh() { refreshedAt.value = '刚刚'; void loadProviders(); if (!route.path.includes('storage-health')) notify('运维状态已刷新') }
function toggleJob(id: string) { running.value[id] = !running.value[id]; notify(running.value[id] ? '定时任务已启用' : '定时任务已暂停') }
watch(() => route.path, () => { filter.value = '全部'; void loadProviders() }, { immediate: true })
</script>

<template><div class="ops-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">系统运维 · 本地环境</span><span class="mini-avatar">陈</span></header><main class="ops-main"><div class="catalog-heading"><div><p class="eyebrow">{{ catalog.eyebrow }}</p><h1>{{ catalog.title }}</h1><p>{{ catalog.description }}</p></div><div class="ops-actions"><button class="outlined-button" @click="refresh">⟳ 刷新</button><button v-if="route.path.includes('jobs')" class="filled-button" @click="notify('已打开新建定时任务表单')">＋ 新建任务</button></div></div><div class="ops-summary"><div class="mini-kpi"><span>当前条目</span><b>{{ activeItems.length }}</b><small>最近刷新 {{ refreshedAt }}</small></div><div class="mini-kpi"><span>健康状态</span><b class="success-text">{{ activeItems.filter(item => item.status === '健康' || item.status === '已启用' || item.status === 'ENABLED' || item.status === 'ACTIVE').length }}</b><small>可正常提供服务</small></div><div class="mini-kpi"><span>需关注</span><b class="warning-text">{{ activeItems.filter(item => item.status === '注意' || item.status === '降级' || item.status === 'WARNING' || item.status === 'DISABLED').length }}</b><small>建议及时处理</small></div></div><div class="ops-filter"><button v-for="value in ['全部','健康','已启用','注意','降级','已暂停']" :key="value" class="filter-chip" :class="{ active: filter === value }" @click="filter = value">{{ value }}</button></div><section class="ops-grid"><article v-for="item in items" :key="item.id" class="ops-card surface-card"><div class="ops-card-top"><span class="service-icon">{{ route.path.includes('plugins') ? '⊕' : route.path.includes('storage') ? '▥' : route.path.includes('jobs') ? '◷' : '◇' }}</span><span class="status-chip" :class="item.status === '健康' || item.status === '已启用' || item.status === 'ENABLED' || item.status === 'ACTIVE' ? 'success' : item.status === '已暂停' ? 'neutral' : 'warning'">● {{ item.status }}</span></div><h3>{{ item.name }}</h3><p>{{ item.detail }}</p><strong>{{ item.metric }}</strong><button v-if="route.path.includes('jobs')" class="text-button" @click="toggleJob(item.id)">{{ item.status === '已启用' ? '暂停任务' : '启用任务' }}</button><button v-else class="text-button" @click="notify(item.name + '详情已打开')">查看详情 →</button></article><div v-if="items.length === 0" class="no-results">没有匹配的运维条目</div></section></main><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
