<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from './services/api'
import { ElButton, ElDialog, ElForm, ElFormItem, ElInput, ElTag } from 'element-plus'
type Project = { id: string; name: string; description: string; status: string; updated: string }
const route = useRoute(); const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const projects = ref<Project[]>([{ id: 'demo-v2', name: 'Ikaros V2', description: '产品与 Console 实施', status: 'ACTIVE', updated: '今天' }, { id: 'demo-home', name: '家庭资料整理', description: '整理文档、照片和备份', status: 'ACTIVE', updated: '昨天' }]); const query = ref(''); const name = ref(''); const description = ref(''); const dialog = ref(false); const loading = ref(false); const toast = ref('')
const filtered = computed(() => projects.value.filter(item => `${item.name} ${item.description} ${item.status}`.toLowerCase().includes(query.value.toLowerCase()))); const active = computed(() => projects.value.filter(item => item.status === 'ACTIVE').length)
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listPlanningProjects(actorId); if (result.length) projects.value = result.map(item => ({ id: item.id, name: item.name || item.id.slice(0, 8), description: item.description || '暂无描述', status: item.status || 'ACTIVE', updated: item.updatedAt ? new Date(item.updatedAt).toLocaleString('zh-CN') : '刚刚' })) } catch { notify('项目 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!name.value.trim()) { notify('请输入项目名称'); return } try { const item = actorId ? await api.createPlanningProject({ name: name.value.trim(), description: description.value.trim() || undefined }, actorId) : { id: `demo-${Date.now()}`, name: name.value.trim(), description: description.value.trim(), status: 'ACTIVE' }; projects.value.unshift({ id: item.id, name: item.name || name.value.trim(), description: item.description || '暂无描述', status: item.status || 'ACTIVE', updated: '刚刚' }); dialog.value = false; name.value = ''; description.value = ''; notify('项目已创建') } catch (error) { notify(error instanceof Error ? error.message : '项目创建失败') } }
onMounted(load)
</script>
<template><div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>项目与任务</h1><p>Project 管理任务集合；Task、Calendar Event 和 Time Block 保持独立语义。</p></div><el-button type="primary" @click="dialog = true">＋ 新建项目</el-button></div><nav class="planning-tabs"><RouterLink to="/console/planning/today">今天</RouterLink><RouterLink to="/console/planning/projects" class="active">项目与任务</RouterLink><RouterLink to="/console/planning/calendar">日历与时间块</RouterLink><RouterLink to="/console/planning/goals">目标与 OKR</RouterLink></nav><section class="planning-summary"><article class="surface-card"><span>项目总数</span><strong>{{ projects.length }}</strong></article><article class="surface-card"><span>进行中</span><strong>{{ active }}</strong></article><article class="surface-card"><span>筛选结果</span><strong>{{ filtered.length }}</strong></article></section><div class="planning-toolbar surface-card"><el-input v-model="query" clearable placeholder="搜索项目名称或描述" style="max-width:360px" /><el-button :loading="loading" @click="load">刷新</el-button></div><section class="planning-project-grid"><article v-for="project in filtered" :key="project.id" class="surface-card planning-project-card"><div class="project-card-top"><span class="project-icon">▤</span><el-tag :type="project.status === 'ACTIVE' ? 'success' : 'info'">{{ project.status }}</el-tag></div><h2>{{ project.name }}</h2><p>{{ project.description }}</p><small>最近更新 · {{ project.updated }}</small><div class="project-card-actions"><el-button link type="primary" @click="notify('项目详情已打开')">打开项目 →</el-button><el-button link @click="notify('项目状态操作已打开')">更多</el-button></div></article><div v-if="filtered.length === 0" class="no-results">没有匹配项目<el-button link type="primary" @click="query = ''">清除筛选</el-button></div></section></main><el-dialog v-model="dialog" title="新建项目" width="460px"><el-form label-position="top"><el-form-item label="项目名称 *"><el-input v-model="name" maxlength="160" placeholder="例如：家庭资料整理" @keyup.enter="create" /></el-form-item><el-form-item label="描述（可选）"><el-input v-model="description" type="textarea" maxlength="2000" placeholder="说明项目目标和范围…" /></el-form-item><div class="dialog-actions"><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="create">创建项目</el-button></div></el-form></el-dialog><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div></template>
