<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ApiError, api, type ExternalIdentityRecord, type ResourceTitleRecord } from './services/api'

const route = useRoute(); const router = useRouter(); const tab = ref('概览'); const loading = ref(false); const toast = ref(''); const favorite = ref(false); const lifecycle = ref('正常')
const resourceId = computed(() => String(route.params.id || '')); const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const title = ref(''); const type = ref(''); const description = ref(''); const createdAt = ref(''); const updatedAt = ref(''); const titles = ref<ResourceTitleRecord[]>([]); const externalIdentities = ref<ExternalIdentityRecord[]>([])
const activity = ref<Array<{ text: string; time: string; actor: string }>>([])
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
function formatDate(value: string) { if (!value) return '暂无'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString('zh-CN') }
async function load() { if (!resourceId.value) { notify('资源 ID 不存在'); return }; if (!actorId) { notify('未配置当前用户身份，无法加载资源'); return }; loading.value = true; try { const result = await api.getResource(resourceId.value, actorId); title.value = result.primaryTitle || result.title || result.id; description.value = result.summary || ''; type.value = result.type || result.resource_type || '其他'; lifecycle.value = result.lifecycle || '未知'; createdAt.value = result.createdAt || result.created_at || ''; updatedAt.value = result.updatedAt || result.updated_at || ''; titles.value = result.titles || []; externalIdentities.value = result.externalIdentities || [] } catch (error) { if (!(error instanceof ApiError && import.meta.env.DEV && error.status === 404)) notify('资源详情加载失败，请检查登录状态或后端服务') } finally { loading.value = false } }
async function toggleFavorite() { if (!actorId || !resourceId.value) { notify('未配置当前用户身份，无法修改收藏'); return }; const next = !favorite.value; try { if (next) { await api.addFavorite(resourceId.value, actorId) } else { await api.removeFavorite(resourceId.value, actorId) }; favorite.value = next; notify(next ? '资源已收藏' : '已取消收藏') } catch { notify('收藏状态更新失败，请稍后重试') } }
async function loadFavorite() { if (!actorId || !resourceId.value) return; try { const result = await api.getFavorite(resourceId.value, actorId); favorite.value = Boolean(result.favorite ?? result.favorited) } catch { /* 收藏状态不可用时不影响资源详情 */ } }
async function loadActivity() { if (!actorId || !resourceId.value) return; try { const result = await api.listRecentActivity(actorId, 50); activity.value = result.filter(item => (item.resourceId || item.resource_id) === resourceId.value).map(item => ({ text: item.details || item.type || '资源活动', time: item.occurredAt || item.occurred_at || '时间不可用', actor: actorId })) } catch { activity.value = [] } }
async function archive() { if (lifecycle.value === '已归档') return; if (!actorId || !resourceId.value) { notify('未配置当前用户身份，无法归档资源'); return } loading.value = true; try { await api.archiveResource(resourceId.value, actorId); lifecycle.value = '已归档'; notify('资源已归档，操作已写入审计') } catch (error) { notify(error instanceof ApiError && error.status === 409 ? '资源当前状态不允许归档' : '资源归档失败，请稍后重试') } finally { loading.value = false } }
load(); loadFavorite(); loadActivity()
</script>

<template>
  <div class="resource-shell">
    <header class="catalog-topbar">
      <el-button text class="resource-back" @click="router.push('/console/resources')">← 资源库</el-button>
      <div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div>
      <span class="catalog-context">资源详情 · {{ resourceId.slice(0, 8) }}</span><span class="mini-avatar">陈</span>
    </header>
    <main class="resource-main">
      <div class="resource-heading"><div><p class="eyebrow">内容与创作 · 资源详情</p><div class="resource-title-line"><h1>{{ title }}</h1><el-button text class="favorite-button" :class="{ active: favorite }" @click="toggleFavorite">{{ favorite ? '★' : '☆' }}</el-button></div><div class="resource-chips"><el-tag type="info">{{ type }}</el-tag><el-tag :type="lifecycle === '正常' ? 'success' : 'warning'">● {{ lifecycle }}</el-tag><span v-if="loading" class="muted-text">正在同步…</span></div></div><div class="resource-actions"><el-button @click="notify('编辑器即将打开')">编辑</el-button><el-button @click="notify('分享流程已打开')">分享</el-button><el-button type="primary" :disabled="lifecycle === '已归档'" @click="archive">{{ lifecycle === '已归档' ? '已归档' : '归档' }}</el-button></div></div>
      <section class="resource-overview"><article class="cover-card surface-card"><div class="cover-art">✦</div><p class="muted-text">后端未提供消费进度</p></article><article class="surface-card resource-info-card"><h2>基础信息</h2><dl><div><dt>内部 ID</dt><dd><code>{{ resourceId }}</code></dd></div><div><dt>所有者</dt><dd>当前接口未返回</dd></div><div><dt>创建时间</dt><dd>{{ formatDate(createdAt) }}</dd></div><div><dt>最近更新</dt><dd>{{ formatDate(updatedAt) }}</dd></div><div><dt>描述</dt><dd>{{ description || '暂无描述' }}</dd></div></dl></article></section>
      <el-button-group class="resource-tabs"><el-button v-for="name in ['概览','元数据','附件','关系','集合与标签','活动']" :key="name" :type="tab === name ? 'primary' : 'default'" @click="tab = name">{{ name }}</el-button></el-button-group>
      <section v-if="tab === '概览'" class="resource-panels"><article class="surface-card"><div class="card-heading"><div><h2>外部身份</h2><p>来自后端返回的关联标识</p></div></div><div v-if="externalIdentities.length"><div v-for="item in externalIdentities" :key="item.id || item.provider" class="external-row"><span>{{ item.provider || '未命名 Provider' }}</span><code>{{ [item.type, item.value].filter(Boolean).join('/') || '暂无标识' }}</code></div></div><p v-else class="placeholder-panel">暂无外部身份</p></article><article class="surface-card"><div class="card-heading"><div><h2>相关资源</h2><p>当前后端资源详情未返回关系数据</p></div></div><p class="placeholder-panel">暂无相关资源</p></article></section>
      <section v-else-if="tab === '元数据'" class="surface-card metadata-panel"><div class="card-heading"><div><h2>元数据字段</h2><p>字段来源于资源详情接口。</p></div></div><div v-if="titles.length"><div v-for="item in titles" :key="item.id || item.locale" class="metadata-row"><div><b>{{ item.locale || '未标记语言' }}</b><small>{{ item.kind || '标题' }}<span v-if="item.primary"> · 主标题</span></small></div><strong>{{ item.value || '暂无值' }}</strong></div></div><p v-else class="placeholder-panel">暂无元数据字段</p></section>
      <section v-else-if="tab === '活动'" class="surface-card activity-panel"><div v-for="item in activity" :key="item.text" class="activity-row"><span class="activity-icon teal">✓</span><div><b>{{ item.text }}</b><small>{{ item.actor }} · {{ item.time }}</small></div></div></section><section v-else class="surface-card placeholder-panel"><span>✦</span><h2>{{ tab }}</h2><p>该关系管理面板已预留安全边界，将根据后端 Schema 展示受授权的数据。</p><el-button @click="notify(tab + '面板即将开放')">了解更多</el-button></section>
    </main><div v-if="toast" class="snackbar">✓ {{ toast }}<el-button text circle @click="toast = ''">×</el-button></div>
  </div>
</template>
