<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElAlert, ElButton, ElEmpty, ElInput, ElTable, ElTableColumn, ElTag } from 'element-plus'
import { ApiError, api, type RoleRecord, type SessionRecord, type UserRecord } from './services/api'
const route = useRoute(); const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const loading = ref(false); const error = ref(''); const query = ref(''); const users = ref<UserRecord[]>([]); const roles = ref<RoleRecord[]>([]); const sessions = ref<SessionRecord[]>([])
const mode = computed(() => route.path.endsWith('/permissions') ? 'permissions' : route.path.endsWith('/sessions') ? 'sessions' : 'users')
const title = computed(() => mode.value === 'users' ? '用户与角色' : mode.value === 'permissions' ? '权限矩阵' : '活跃会话')
const rows = computed(() => mode.value === 'users' ? users.value : mode.value === 'permissions' ? roles.value : sessions.value)
const filtered = computed(() => rows.value.filter(item => JSON.stringify(item).toLowerCase().includes(query.value.toLowerCase())))
async function loadEfficient() { if (!actorId) return; loading.value = true; error.value = ''; try { if (mode.value === 'users') { const result = await api.listUsers('?page=0&size=100'); users.value = Array.isArray(result) ? result : result.items || result.content || [] } else if (mode.value === 'permissions') roles.value = await api.listRoles(); else sessions.value = await api.listSessions(actorId) } catch (e) { error.value = e instanceof ApiError ? e.message : '安全数据加载失败' } finally { loading.value = false } }
async function toggleUser(user: UserRecord) { if (!actorId) return; try { await api.changeUserStatus(user.id, String(user.status).toUpperCase() === 'ACTIVE' ? 'DISABLED' : 'ACTIVE', actorId); await loadEfficient() } catch (e) { error.value = e instanceof Error ? e.message : '账户状态更新失败' } }
async function revoke(session: SessionRecord) { if (!actorId) return; try { await api.revokeSession(actorId, session.id, actorId); await loadEfficient() } catch (e) { error.value = e instanceof Error ? e.message : '会话撤销失败' } }
watch(mode, loadEfficient); onMounted(loadEfficient)
</script>
<template><main class="security-workspace"><header class="dashboard-header"><div><p class="eyebrow">身份与安全</p><h1>{{ title }}</h1><p>所有管理操作遵循 Capability、Scope、Secure Session 与审计策略。</p></div><el-button :loading="loading" @click="loadEfficient">刷新</el-button></header><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" /><el-input v-model="query" clearable placeholder="筛选当前安全数据" style="max-width:420px;margin:20px 0" /><el-table v-if="mode === 'users'" v-loading="loading" :data="filtered as UserRecord[]" stripe empty-text="暂无用户"><el-table-column prop="display_name" label="用户" min-width="220" /><el-table-column prop="username" label="登录标识" min-width="220" /><el-table-column prop="status" label="状态" width="140"><template #default="{ row }"><el-tag :type="String(row.status).toUpperCase() === 'ACTIVE' ? 'success' : 'warning'">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="120"><template #default="{ row }"><el-button link type="primary" @click="toggleUser(row)">{{ String(row.status).toUpperCase() === 'ACTIVE' ? '禁用' : '启用' }}</el-button></template></el-table-column></el-table><el-table v-else-if="mode === 'permissions'" v-loading="loading" :data="filtered as RoleRecord[]" stripe empty-text="暂无角色"><el-table-column prop="name" label="角色" min-width="200" /><el-table-column prop="code" label="编码" min-width="180" /><el-table-column label="权限数" width="120"><template #default="{ row }">{{ row.permissions?.length || 0 }}</template></el-table-column><el-table-column label="类型" width="140"><template #default="{ row }"><el-tag :type="row.builtIn ? 'info' : 'success'">{{ row.builtIn ? '系统角色' : '自定义' }}</el-tag></template></el-table-column></el-table><el-table v-else v-loading="loading" :data="filtered as SessionRecord[]" stripe empty-text="暂无会话"><el-table-column prop="loginMethod" label="登录方式" width="160" /><el-table-column prop="currentSvl" label="会话摘要" min-width="220" /><el-table-column label="状态" width="140"><template #default="{ row }"><el-tag :type="row.expiresAt && new Date(row.expiresAt) > new Date() ? 'success' : 'info'">{{ row.expiresAt && new Date(row.expiresAt) > new Date() ? '活跃' : '已过期' }}</el-tag></template></el-table-column><el-table-column label="操作" width="120"><template #default="{ row }"><el-button link type="danger" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table><el-empty v-if="!loading && filtered.length === 0" description="暂无匹配数据" /></main></template>
