<script setup lang="ts">
import { computed, ref } from 'vue'
import { api } from './services/api'
import { ElButton, ElDialog, ElForm, ElFormItem, ElInput, ElOption, ElSelect, ElTag } from 'element-plus'
type Task = { id: string; title: string; priority: string; status: string; due: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const tasks = ref<Task[]>([]); const query = ref(''); const dialog = ref(false); const title = ref(''); const description = ref(''); const priority = ref('普通'); const loading = ref(false); const toast = ref('')
const filtered = computed(() => tasks.value.filter(item => `${item.title} ${item.priority} ${item.status}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) { notify('未配置当前用户身份，无法加载任务'); return } loading.value = true; try { const result = await api.listTodayTasks(actorId); tasks.value = result.map(item => ({ id: item.id, title: item.title || item.id.slice(0, 8), priority: item.priority || '普通', status: item.status || 'OPEN', due: item.due_at ? new Date(item.due_at).toLocaleString('zh-CN') : '今天' })) } catch { tasks.value = []; notify('任务 API 加载失败，请检查后端服务') } finally { loading.value = false } }
async function create() { if (!title.value.trim()) { notify('请输入任务标题'); return } try { const item = actorId ? await api.createPlanningTask({ title: title.value.trim(), description: description.value.trim() || undefined, priority: priority.value }, actorId) : { id: `demo-${Date.now()}`, title: title.value.trim(), priority: priority.value, status: 'OPEN', due_at: '' }; tasks.value.unshift({ id: item.id, title: item.title || title.value.trim(), priority: item.priority || priority.value, status: item.status || 'OPEN', due: item.due_at ? new Date(item.due_at).toLocaleString('zh-CN') : '今天' }); dialog.value = false; title.value = ''; description.value = ''; notify(actorId ? '任务已创建' : '演示任务已创建（未提交后端）') } catch (error) { notify(error instanceof Error ? error.message : '任务创建失败') } }
load()
</script>
<template>
  <div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>收集箱与今天</h1><p>聚合今天到期、收集箱和待执行任务。</p></div><el-button type="primary" @click="dialog = true">＋ 新建任务</el-button></div><nav class="planning-tabs"><RouterLink to="/console/planning/today" class="active">今天</RouterLink><RouterLink to="/console/planning/projects">项目与任务</RouterLink><RouterLink to="/console/planning/calendar">日历与时间块</RouterLink><RouterLink to="/console/planning/goals">目标与 OKR</RouterLink></nav><div class="planning-toolbar surface-card"><el-input v-model="query" clearable placeholder="搜索今天的任务" style="max-width:360px" /><el-tag type="info">{{ filtered.length }} 项</el-tag><el-button :loading="loading" @click="load">刷新</el-button></div><section class="planning-project-grid"><article v-for="item in filtered" :key="item.id" class="surface-card planning-project-card"><div class="project-card-top"><span class="project-icon">✓</span><el-tag :type="item.status === '已完成' || item.status === 'COMPLETED' ? 'success' : item.priority === '高' ? 'warning' : 'info'">{{ item.status }}</el-tag></div><h2>{{ item.title }}</h2><p>{{ item.priority }}优先级 · {{ item.due }}</p><el-button link type="primary" @click="notify('任务详情已打开')">查看详情 →</el-button></article><div v-if="filtered.length === 0" class="no-results">今天没有匹配任务</div></section></main><el-dialog v-model="dialog" title="新建任务" width="460px"><el-form label-position="top"><el-form-item label="标题 *"><el-input v-model="title" maxlength="160" placeholder="例如：整理本周阅读清单" /></el-form-item><el-form-item label="描述（可选）"><el-input v-model="description" type="textarea" maxlength="2000" placeholder="补充任务说明…" /></el-form-item><el-form-item label="优先级"><el-select v-model="priority" style="width:100%"><el-option v-for="value in ['高','普通','低']" :key="value" :label="value" :value="value" /></el-select></el-form-item><div class="dialog-actions"><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="create">创建任务</el-button></div></el-form></el-dialog><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div>
</template>
