<script setup lang="ts">
import { computed, ref } from 'vue'
import { api } from './services/api'
type Task = { id: string; title: string; priority: string; status: string; due: string }
const actorId = String(import.meta.env.VITE_ACTOR_ID || ''); const tasks = ref<Task[]>([{ id: 'demo-today-1', title: '完成 Console 权限审阅', priority: '高', status: '进行中', due: '今天 16:00' }, { id: 'demo-today-2', title: '整理本周阅读清单', priority: '普通', status: '待开始', due: '今天 18:00' }, { id: 'demo-today-3', title: '提交活动周报', priority: '低', status: '已完成', due: '今天 09:30' }]); const query = ref(''); const dialog = ref(false); const title = ref(''); const description = ref(''); const priority = ref('普通'); const loading = ref(false); const toast = ref('')
const filtered = computed(() => tasks.value.filter(item => `${item.title} ${item.priority} ${item.status}`.toLowerCase().includes(query.value.toLowerCase())))
function notify(message: string) { toast.value = message; window.setTimeout(() => toast.value = '', 2400) }
async function load() { if (!actorId) return; loading.value = true; try { const result = await api.listTodayTasks(actorId); tasks.value = result.map(item => ({ id: item.id, title: item.title || item.id.slice(0, 8), priority: item.priority || '普通', status: item.status || 'OPEN', due: item.due_at ? new Date(item.due_at).toLocaleString('zh-CN') : '今天' })) } catch { notify('任务 API 暂不可用，已保留演示数据') } finally { loading.value = false } }
async function create() { if (!title.value.trim()) { notify('请输入任务标题'); return } try { const item = actorId ? await api.createPlanningTask({ title: title.value.trim(), description: description.value.trim() || undefined, priority: priority.value }, actorId) : { id: `demo-${Date.now()}`, title: title.value.trim(), priority: priority.value, status: 'OPEN', due_at: '' }; tasks.value.unshift({ id: item.id, title: item.title || title.value.trim(), priority: item.priority || priority.value, status: item.status || 'OPEN', due: item.due_at ? new Date(item.due_at).toLocaleString('zh-CN') : '今天' }); dialog.value = false; title.value = ''; description.value = ''; notify(actorId ? '任务已创建' : '演示任务已创建（未提交后端）') } catch (error) { notify(error instanceof Error ? error.message : '任务创建失败') } }
load()
</script>
<template>
  <div class="planning-shell"><header class="catalog-topbar"><div class="catalog-brand"><span class="brand-mark">i</span><strong>Ikaros <small>Console</small></strong></div><span class="catalog-context">效率与计划</span><span class="mini-avatar">陈</span></header><main class="catalog-main planning-main"><div class="catalog-heading"><div><p class="eyebrow">效率与计划</p><h1>收集箱与今天</h1><p>聚合今天到期、收集箱和待执行任务。</p></div><button class="filled-button" @click="dialog = true">＋ 新建任务</button></div><nav class="planning-tabs"><RouterLink to="/console/planning/today" class="active">今天</RouterLink><RouterLink to="/console/planning/projects">项目与任务</RouterLink><RouterLink to="/console/planning/calendar">日历与时间块</RouterLink><RouterLink to="/console/planning/goals">目标与 OKR</RouterLink></nav><div class="planning-toolbar surface-card"><div class="search-inline"><span>⌕</span><input v-model="query" placeholder="搜索今天的任务" /></div><span class="status-chip neutral">{{ filtered.length }} 项</span><button class="outlined-button small" :disabled="loading" @click="load">{{ loading ? '加载中…' : '⟳ 刷新' }}</button></div><section class="planning-project-grid"><article v-for="item in filtered" :key="item.id" class="surface-card planning-project-card"><div class="project-card-top"><span class="project-icon">✓</span><span class="status-chip" :class="item.status === '已完成' || item.status === 'COMPLETED' ? 'success' : item.priority === '高' ? 'warning' : 'neutral'">● {{ item.status }}</span></div><h2>{{ item.title }}</h2><p>{{ item.priority }}优先级 · {{ item.due }}</p><button class="text-button" @click="notify('任务详情已打开')">查看详情 →</button></article><div v-if="filtered.length === 0" class="no-results">今天没有匹配任务</div></section></main><div v-if="dialog" class="role-create-scrim" @click.self="dialog = false"><section class="role-create-dialog"><div class="dialog-title"><div><p class="eyebrow">效率与计划</p><h2>新建任务</h2></div><button class="icon-button" @click="dialog = false">×</button></div><label>标题 *<input v-model="title" maxlength="160" placeholder="例如：整理本周阅读清单" /></label><label>描述（可选）<textarea v-model="description" maxlength="2000" placeholder="补充任务说明…"></textarea></label><label>优先级<select v-model="priority"><option>高</option><option>普通</option><option>低</option></select></label><div class="dialog-actions"><button class="outlined-button" @click="dialog = false">取消</button><button class="filled-button" @click="create">创建任务</button></div></section></div><div v-if="toast" class="snackbar">✓ {{ toast }}<button @click="toast = ''">×</button></div></div>
</template>
