<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const tab = ref("restore"); const restores = ref<Row[]>([]); const candidates = ref<Row[]>([]); const loading = ref(false); const error = ref(""); const attachmentId = ref(""); const targetTier = ref("HOT"); const submitting = ref(false);
async function load() { loading.value = true; error.value = ""; try { const [restore, gc] = await Promise.all([http.get<unknown, unknown>("/storage/restore-requests"), http.get<unknown, unknown>("/storage/gc/candidates")]); restores.value = Array.isArray(restore) ? restore as Row[] : []; candidates.value = Array.isArray(gc) ? gc as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "归档与恢复数据加载失败"; } finally { loading.value = false; } }
async function requestRestore() { if (!attachmentId.value.trim()) { error.value = "请输入 Attachment ID"; return; } submitting.value = true; try { await http.post("/storage/restore-requests/attachments", { data: { attachmentId: attachmentId.value.trim(), targetTier: targetTier.value } }); attachmentId.value = ""; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "恢复请求提交失败"; } finally { submitting.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">归档、恢复与回收站</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">恢复是异步后台操作；Blob 清理候选仅供人工审核，不代表已经删除。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="已归档资源" name="archived"><el-empty description="暂无可展示的归档资源" /></el-tab-pane><el-tab-pane label="恢复队列" name="restore"><div class="flex flex-wrap gap-2 mb-4"><el-input v-model="attachmentId" placeholder="Attachment ID" clearable /><el-button type="primary" :loading="submitting" @click="requestRestore">发起恢复</el-button></div><el-skeleton v-if="loading" :rows="5" animated/><el-empty v-else-if="!restores.length" description="暂无恢复任务"/><el-table v-else :data="restores" stripe><el-table-column prop="id" label="任务" min-width="220"/><el-table-column prop="scope" label="范围" width="130"/><el-table-column prop="totalItems" label="目标数量" width="100"/><el-table-column prop="completedItems" label="已完成" width="100"/><el-table-column prop="totalBytes" label="总字节数" width="140"/><el-table-column prop="status" label="阶段" width="150"/><el-table-column prop="createdAt" label="开始时间" min-width="180"/></el-table></el-tab-pane><el-tab-pane label="回收站 / GC 候选" name="trash"><p class="text-sm text-[var(--el-text-color-secondary)] mb-4">候选必须没有有效 Attachment 引用并超过保留期。提交清理请求后仍由受控后台任务执行。</p><el-skeleton v-if="loading" :rows="5" animated/><el-empty v-else-if="!candidates.length" description="暂无 Blob 清理候选"/><el-table v-else :data="candidates" stripe><el-table-column prop="blobId" label="Blob ID" min-width="240"/><el-table-column prop="sha256" label="SHA-256" min-width="260"/><el-table-column prop="sizeBytes" label="大小（Bytes）" width="150"/><el-table-column prop="createdAt" label="创建时间" min-width="180"/><el-table-column prop="eligibleAt" label="可清理时间" min-width="180"/></el-table></el-tab-pane></el-tabs></el-card></main></template>
