<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const rows = ref<Row[]>([]); const loading = ref(false); const error = ref("");
const published = computed(() => rows.value.filter(row => String(row.state).toUpperCase() === "PUBLISHED").length); const verified = computed(() => rows.value.filter(row => String(row.verificationStatus).toUpperCase() === "PASSED").length);
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/admin/backup/restore-points"); rows.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "备份集加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">备份与恢复</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理恢复点、完整性验证和发布状态。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><section class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">恢复点总数</div><div class="text-2xl font-semibold mt-2">{{ rows.length }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">已发布</div><div class="text-2xl font-semibold mt-2">{{ published }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">验证通过</div><div class="text-2xl font-semibold mt-2">{{ verified }}</div></el-card></section><el-card shadow="never"><template #header><span class="font-medium">备份集 / 恢复点</span></template><el-skeleton v-if="loading" :rows="6" animated/><el-empty v-else-if="!rows.length" description="暂无备份恢复点"/><el-table v-else :data="rows" stripe><el-table-column prop="id" label="Restore Point ID" min-width="230"/><el-table-column prop="formatVersion" label="格式" width="120"/><el-table-column prop="sourceInstanceId" label="来源实例" min-width="180"/><el-table-column prop="state" label="状态" width="130"/><el-table-column prop="verificationStatus" label="校验" width="130"/><el-table-column prop="manifestDigest" label="Manifest 摘要" min-width="220"/><el-table-column prop="createdAt" label="创建时间" min-width="180"/></el-table></el-card></main></template>
