<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const deviceId = ref(""); const tab = ref("cache"); const cache = ref<Row[]>([]); const downloads = ref<Row[]>([]); const loading = ref(false); const error = ref(""); const queried = ref(false);
async function load() { if (!deviceId.value.trim()) { error.value = "请输入 Device ID"; return; } loading.value = true; error.value = ""; try { const query = `?deviceId=${encodeURIComponent(deviceId.value.trim())}`; const [c, d] = await Promise.all([http.get<unknown, unknown>(`/offline/cache${query}`), http.get<unknown, unknown>(`/offline/downloads${query}`)]); cache.value = Array.isArray(c) ? c as Row[] : []; downloads.value = Array.isArray(d) ? d as Row[] : []; queried.value = true; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "缓存与下载数据加载失败"; } finally { loading.value = false; } }
onMounted(() => { });
</script>
<template><main class="p-4 md:p-6"><div class="flex flex-wrap justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">缓存与我的下载</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理服务端缓存和客户端下载元数据，不展示客户端私有路径。</p></div><div class="flex gap-2"><el-input v-model="deviceId" placeholder="Device ID" clearable @keyup.enter="load"/><el-button type="primary" :loading="loading" @click="load">查询</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="服务端缓存" name="cache"><div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4"><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">缓存对象</div><div class="text-2xl font-semibold mt-2">{{ cache.length }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">缓存字节数</div><div class="text-2xl font-semibold mt-2">{{ cache.reduce((sum, row) => sum + Number(row.sizeBytes || 0), 0).toLocaleString() }}</div></el-card><el-card shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">状态</div><div class="mt-2">仅影响缓存，不影响持久化数据</div></el-card></div><el-empty v-if="!queried" description="输入 Device ID 查询缓存"/><el-empty v-else-if="!cache.length" description="暂无服务端缓存"/><el-table v-else :data="cache" stripe><el-table-column prop="resourceId" label="Resource" min-width="220"/><el-table-column prop="attachmentId" label="Attachment" min-width="220"/><el-table-column prop="sizeBytes" label="大小（Bytes）" width="140"/><el-table-column prop="state" label="状态" width="140"/><el-table-column prop="lastAccessedAt" label="最近访问" min-width="180"/></el-table></el-tab-pane><el-tab-pane label="客户端下载" name="downloads"><el-empty v-if="!queried" description="输入 Device ID 查询下载"/><el-empty v-else-if="!downloads.length" description="暂无客户端下载记录"/><el-table v-else :data="downloads" stripe><el-table-column prop="deviceId" label="设备" min-width="220"/><el-table-column prop="resourceId" label="Resource" min-width="220"/><el-table-column prop="attachmentId" label="Attachment" min-width="220"/><el-table-column prop="kind" label="类型" width="130"/><el-table-column prop="state" label="状态" width="140"/><el-table-column prop="createdAt" label="下载时间" min-width="180"/></el-table></el-tab-pane></el-tabs></el-card></main></template>
