<script setup lang="ts">
import { ref } from "vue";
import { http } from "@/utils/http";
type Row = Record<string, any>;
const tab = ref("integrity"); const resourceId = ref(""); const attachmentId = ref(""); const blobId = ref(""); const rows = ref<Row[]>([]); const loading = ref(false); const error = ref("");
async function inspect(path: string) { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>(path); rows.value = Array.isArray(result) ? result as Row[] : result ? [result as Row] : []; } catch (e: any) { error.value = e?.response?.data?.detail || "诊断数据加载失败；当前状态为 Unknown。"; rows.value = []; } finally { loading.value = false; } }
function inspectBusinessObject() { const id = resourceId.value.trim() || attachmentId.value.trim(); if (!id) { error.value = "请输入 Resource ID 或 Attachment ID"; return; } inspect(resourceId.value.trim() ? `/storage/maintenance/resources/${encodeURIComponent(id)}` : `/storage/maintenance/attachments/${encodeURIComponent(id)}`); }
function inspectBlob() { const id = blobId.value.trim(); if (!id) { error.value = "请输入 Blob ID"; return; } inspect(`/storage/blobs/${encodeURIComponent(id)}/placements`); }
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">Storage Maintenance</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">高级诊断区：完整性、GC、Placement / Replica 与 Delivery 故障路径。</p></div></div><el-alert v-if="error" :title="error" type="warning" show-icon :closable="false" class="mb-4"/><el-card shadow="never"><el-tabs v-model="tab"><el-tab-pane label="Integrity / Reference" name="integrity"><p class="text-sm text-[var(--el-text-color-secondary)] mb-4">优先按业务对象排障；不会要求用户先知道 Blob ID。</p><div class="flex flex-wrap gap-3"><el-input v-model="resourceId" placeholder="Resource ID" class="w-72" clearable/><el-input v-model="attachmentId" placeholder="Attachment ID" class="w-72" clearable/><el-button type="primary" :loading="loading" @click="inspectBusinessObject">诊断对象</el-button></div></el-tab-pane><el-tab-pane label="Blob / Placement" name="advanced"><p class="text-sm text-[var(--el-text-color-secondary)] mb-4">仅用于高级排障：Blob ID、Placement、Replica 和 Object Key 不属于 Storage 首页任务。</p><div class="flex gap-3"><el-input v-model="blobId" placeholder="Blob ID（高级）" class="w-80" clearable/><el-button :loading="loading" @click="inspectBlob">查询副本</el-button></div></el-tab-pane><el-tab-pane label="GC / Delivery" name="operations"><el-empty description="GC、Repair、Promotion 和 Delivery 深度操作将在确认权限后创建后台任务，并进入 /activity。"/></el-tab-pane></el-tabs><el-divider/><el-empty v-if="!rows.length && !loading" description="暂无诊断结果；未探测字段显示为 Unknown"/><el-table v-else :data="rows" stripe><el-table-column prop="status" label="状态" width="140"/><el-table-column prop="health" label="Health" width="140"/><el-table-column prop="tier" label="Tier" width="120"/><el-table-column prop="providerId" label="Provider" min-width="220"/><el-table-column prop="checkedAt" label="最近校验" min-width="180"/></el-table></el-card></main></template>
