<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Provider = Record<string, any>;
const providerTypes = ["S3", "ALIYUN_OSS_S3", "TENCENT_COS_S3"];
const tierOptions = ["HOT", "WARM", "COLD", "ARCHIVE", "DEEP_ARCHIVE"];
const providers = ref<Provider[]>([]); const loading = ref(false); const error = ref(""); const dialog = ref(false); const credentialDialog = ref(false); const saving = ref(false); const credentialSaving = ref(false); const selectedProvider = ref<Provider | null>(null);
const form = ref({ providerKey: "s3-main", providerType: "S3", tier: "HOT", secretReference: "", accessKeyId: "", secretAccessKey: "", sessionToken: "", endpoint: "", bucket: "", region: "" });
const credentialForm = ref({ accessKeyId: "", secretAccessKey: "", sessionToken: "" });
const tiers = computed(() => tierOptions.map(tier => ({ tier, items: providers.value.filter(item => String(item.tier || "").toUpperCase() === tier) })));

async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/storage/providers"); providers.value = Array.isArray(result) ? result as Provider[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "存储 Provider 加载失败"; } finally { loading.value = false; } }
onMounted(load);
async function save() { const value = form.value; const directCredentials = Boolean(value.accessKeyId && value.secretAccessKey); if (!value.providerKey || !value.endpoint || !value.bucket || !value.region || (!directCredentials && !value.secretReference)) { error.value = "Provider Key、Endpoint、Bucket、Region，以及 Secret 引用或 AccessKey/SecretKey 均不能为空"; return; } if (!directCredentials && !value.secretReference.startsWith("secret://")) { error.value = "Secret 引用必须使用 secret:// URI"; return; } try { new URL(value.endpoint); } catch { error.value = "Endpoint 必须是合法 URL"; return; } saving.value = true; try { await http.post("/storage/providers", { data: { providerKey: value.providerKey, providerType: value.providerType, tier: value.tier, secretReference: directCredentials ? undefined : value.secretReference, accessKeyId: directCredentials ? value.accessKeyId : undefined, secretAccessKey: directCredentials ? value.secretAccessKey : undefined, sessionToken: directCredentials ? value.sessionToken || undefined : undefined, metadata: { endpoint: value.endpoint, bucket: value.bucket, region: value.region } } }); dialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Provider 配置失败"; } finally { saving.value = false; } }
async function toggleProvider(row: Provider) { try { if (String(row.status).toUpperCase() === "ENABLED") await http.request("delete", `/storage/providers/${row.id}`); else await http.post(`/storage/providers/${row.id}/enable`); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Provider 状态更新失败"; } }
function openCredentialDialog(row: Provider) { selectedProvider.value = row; credentialForm.value = { accessKeyId: "", secretAccessKey: "", sessionToken: "" }; credentialDialog.value = true; }
async function replaceCredentials() { const value = credentialForm.value; if (!value.accessKeyId || !value.secretAccessKey || !selectedProvider.value?.id) { error.value = "AccessKey ID 和 SecretKey 不能为空"; return; } credentialSaving.value = true; try { await http.post(`/storage/providers/${selectedProvider.value.id}/credentials`, { data: value }); credentialDialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "凭据更新失败"; } finally { credentialSaving.value = false; } }
</script>

<template>
  <main class="p-4 md:p-6">
    <div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">持久化存储层</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">管理对象存储 Provider 与持久化层级。</p></div><div class="flex gap-2"><el-button @click="dialog = true">添加对象存储 Provider</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" />
    <el-skeleton v-if="loading" :rows="8" animated />
    <template v-else>
      <section class="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6"><el-card v-for="item in tiers" :key="item.tier" shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.tier }}</div><div class="text-2xl font-semibold mt-2">{{ item.items.length }}</div><div class="text-sm mt-1">Provider</div></el-card></section>
      <el-card shadow="never"><template #header><span class="font-medium">存储 Backend</span></template><el-empty v-if="!providers.length" description="暂无存储 Provider" /><el-table v-else :data="providers" stripe><el-table-column prop="providerKey" label="名称" min-width="200" /><el-table-column prop="providerType" label="Backend 类型" width="160" /><el-table-column prop="tier" label="Tier" width="160" /><el-table-column prop="status" label="健康/读写状态" width="160"><template #default="{ row }"><el-tag :type="String(row.status).toUpperCase() === 'ENABLED' ? 'success' : 'warning'">{{ row.status || '未知' }}</el-tag></template></el-table-column><el-table-column prop="secretReference" label="Credential" min-width="180"><template #default="{ row }">{{ row.secretReference ? '已配置（引用）' : '未配置' }}</template></el-table-column><el-table-column prop="updatedAt" label="最近更新" min-width="180" /><el-table-column label="操作" width="160"><template #default="{ row }"><el-button link @click="openCredentialDialog(row)">凭据</el-button><el-button link @click="toggleProvider(row)">{{ String(row.status).toUpperCase() === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></el-card>
     </template>
    <el-dialog v-model="dialog" title="配置对象存储 Provider" width="520px"><el-form label-position="top"><el-form-item label="Provider Key" required><el-input v-model="form.providerKey" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">系统内部的唯一名称，上传附件时用它选择目标存储，例如 s3-main。</div></el-form-item><el-form-item label="Provider 类型" required><el-select v-model="form.providerType" class="w-full"><el-option v-for="type in providerTypes" :key="type" :label="type" :value="type" /></el-select><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">选择对象存储厂商使用的协议适配器；Aliyun OSS 和 Tencent COS 使用各自的 S3 兼容适配器。</div></el-form-item><el-form-item label="Storage Tier" required><el-select v-model="form.tier" class="w-full"><el-option v-for="tier in tierOptions" :key="tier" :label="tier" :value="tier" /></el-select><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">业务存储层级，不代表浏览器缓存或下载状态；上传后的 Placement 会继承此层级。</div></el-form-item><el-form-item label="AccessKey ID"><el-input v-model="form.accessKeyId" autocomplete="off" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">云厂商访问身份标识。填写 AccessKey/SecretKey 后，后端会加密保存。</div></el-form-item><el-form-item label="SecretKey"><el-input v-model="form.secretAccessKey" type="password" show-password autocomplete="new-password" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">云厂商访问密钥，只在提交时传输，接口列表不会返回明文。</div></el-form-item><el-form-item label="SessionToken（可选）"><el-input v-model="form.sessionToken" type="password" show-password autocomplete="off" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">临时安全凭证才需要填写；长期 AccessKey 通常留空。</div></el-form-item><el-form-item label="或使用 Secret 引用"><el-input v-model="form.secretReference" placeholder="例如 secret://default 或 secret://env/NAME" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">不直接填写密钥时使用。secret://default 使用 SDK 默认凭据链，secret://env/NAME 从环境变量读取。</div></el-form-item><el-form-item label="Endpoint" required><el-input v-model="form.endpoint" placeholder="https://s3.example.com" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">对象存储 API 地址。请填写厂商 S3 endpoint，不是控制台网页地址。</div></el-form-item><el-form-item label="Bucket" required><el-input v-model="form.bucket" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">实际保存附件对象的 Bucket/存储桶名称。</div></el-form-item><el-form-item label="Region" required><el-input v-model="form.region" placeholder="例如 us-east-1" /><div class="text-xs text-[var(--el-text-color-secondary)] mt-1">Bucket 所在地域标识，必须与云厂商配置一致。</div></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存配置</el-button></template></el-dialog>
    <el-dialog v-model="credentialDialog" title="更新 Provider 凭据" width="520px"><el-alert title="新凭据会使用当前服务端主密钥重新加密；原密文无需先解密。" type="info" :closable="false" class="mb-4" /><el-form label-position="top"><el-form-item label="Provider ID" required><el-input :model-value="selectedProvider?.id || ''" disabled /></el-form-item><el-form-item label="AccessKey ID" required><el-input v-model="credentialForm.accessKeyId" autocomplete="off" /></el-form-item><el-form-item label="SecretKey" required><el-input v-model="credentialForm.secretAccessKey" type="password" show-password autocomplete="new-password" /></el-form-item><el-form-item label="SessionToken（可选）"><el-input v-model="credentialForm.sessionToken" type="password" show-password autocomplete="off" /></el-form-item></el-form><template #footer><el-button @click="credentialDialog = false">取消</el-button><el-button type="primary" :loading="credentialSaving" @click="replaceCredentials">保存凭据</el-button></template></el-dialog>
  </main>
</template>
