<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Provider = Record<string, any>;
const providers = ref<Provider[]>([]); const loading = ref(false); const error = ref("");
const tiers = computed(() => ["HOT", "WARM", "COLD", "ARCHIVE"].map(tier => ({ tier, items: providers.value.filter(item => String(item.tier || "").toUpperCase() === tier) })));
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/storage/providers"); providers.value = Array.isArray(result) ? result as Provider[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "存储 Provider 加载失败"; } finally { loading.value = false; } }
onMounted(load);
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">持久化存储层</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">Hot、Warm、Cold/Archive 与 Provider 健康状态。Cache 不属于持久化存储层。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="8" animated/><template v-else><section class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6"><el-card v-for="item in tiers" :key="item.tier" shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.tier }}</div><div class="text-2xl font-semibold mt-2">{{ item.items.length }}</div><div class="text-sm mt-1">Provider</div></el-card></section><el-card shadow="never"><template #header><span class="font-medium">存储 Backend</span></template><el-empty v-if="!providers.length" description="暂无存储 Provider"/><el-table v-else :data="providers" stripe><el-table-column prop="providerKey" label="名称" min-width="200"/><el-table-column prop="providerType" label="Backend 类型" width="160"/><el-table-column prop="tier" label="Tier" width="120"/><el-table-column prop="status" label="健康/读写状态" width="160"><template #default="{ row }"><el-tag :type="String(row.status).toUpperCase() === 'ENABLED' ? 'success' : 'warning'">{{ row.status || '未知' }}</el-tag></template></el-table-column><el-table-column prop="secretReference" label="Credential" min-width="180"><template #default="{ row }">{{ row.secretReference ? '已配置（引用）' : '未配置' }}</template></el-table-column><el-table-column prop="updatedAt" label="最近更新" min-width="180"/></el-table></el-card></template></main></template>
