<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { http } from "@/utils/http";
type Provider = Record<string, any>;
const providers = ref<Provider[]>([]); const loading = ref(false); const error = ref(""); const dialog = ref(false); const saving = ref(false); const form = ref({ providerKey: "s3-main", providerType: "S3", tier: "HOT", secretReference: "", endpoint: "", bucket: "", region: "" });
const tiers = computed(() => ["HOT", "WARM", "COLD", "ARCHIVE"].map(tier => ({ tier, items: providers.value.filter(item => String(item.tier || "").toUpperCase() === tier) })));
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/storage/providers"); providers.value = Array.isArray(result) ? result as Provider[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "存储 Provider 加载失败"; } finally { loading.value = false; } }
onMounted(load);
async function save() { if (!form.value.providerKey || !form.value.secretReference) { error.value = "Provider Key 和 Secret 引用不能为空"; return; } saving.value = true; try { await http.post("/storage/providers", { data: { providerKey: form.value.providerKey, providerType: form.value.providerType, tier: form.value.tier, secretReference: form.value.secretReference, metadata: { endpoint: form.value.endpoint, bucket: form.value.bucket, region: form.value.region } } }); dialog.value = false; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Provider 配置失败"; } finally { saving.value = false; } }
async function toggleProvider(row: Provider) { try { if (String(row.status).toUpperCase() === "ENABLED") await http.request("delete", `/storage/providers/${row.id}`); else await http.post(`/storage/providers/${row.id}/enable`); await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Provider 状态更新失败"; } }
</script>
<template><main class="p-4 md:p-6"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold">持久化存储层</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">Hot、Warm、Cold/Archive 与 Provider 健康状态。Cache 不属于持久化存储层。</p></div><div class="flex gap-2"><el-button @click="dialog = true">添加 S3 Provider</el-button><el-button :loading="loading" @click="load">刷新</el-button></div></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4"/><el-skeleton v-if="loading" :rows="8" animated/><template v-else><section class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6"><el-card v-for="item in tiers" :key="item.tier" shadow="never"><div class="text-sm text-[var(--el-text-color-secondary)]">{{ item.tier }}</div><div class="text-2xl font-semibold mt-2">{{ item.items.length }}</div><div class="text-sm mt-1">Provider</div></el-card></section><el-card shadow="never"><template #header><span class="font-medium">存储 Backend</span></template><el-empty v-if="!providers.length" description="暂无存储 Provider"/><el-table v-else :data="providers" stripe><el-table-column prop="providerKey" label="名称" min-width="200"/><el-table-column prop="providerType" label="Backend 类型" width="160"/><el-table-column prop="tier" label="Tier" width="120"/><el-table-column prop="status" label="健康/读写状态" width="160"><template #default="{ row }"><el-tag :type="String(row.status).toUpperCase() === 'ENABLED' ? 'success' : 'warning'">{{ row.status || '未知' }}</el-tag></template></el-table-column><el-table-column prop="secretReference" label="Credential" min-width="180"><template #default="{ row }">{{ row.secretReference ? '已配置（引用）' : '未配置' }}</template></el-table-column><el-table-column prop="updatedAt" label="最近更新" min-width="180"/><el-table-column label="操作" width="110"><template #default="{ row }"><el-button link @click="toggleProvider(row)">{{ String(row.status).toUpperCase() === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></el-card></template><el-dialog v-model="dialog" title="配置 S3 Provider" width="520px"><el-form label-position="top"><el-form-item label="Provider Key" required><el-input v-model="form.providerKey" /></el-form-item><el-form-item label="Secret 引用" required><el-input v-model="form.secretReference" placeholder="例如 secret/s3-main" /></el-form-item><el-form-item label="Endpoint"><el-input v-model="form.endpoint" placeholder="https://s3.example.com" /></el-form-item><el-form-item label="Bucket"><el-input v-model="form.bucket" /></el-form-item><el-form-item label="Region"><el-input v-model="form.region" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存配置</el-button></template></el-dialog></main></template>
