export type SecureDomain = 'public' | 'finance' | 'private_notes' | 'passwords' | 'security'
export type ConsoleRouteMeta = { subsystem: string; requiredCapability: string; secureDomain: SecureDomain; breadcrumb: string[] }

const meta: Record<string, ConsoleRouteMeta> = {
  dashboard: { subsystem: 'workbench', requiredCapability: 'workbench.read', secureDomain: 'public', breadcrumb: ['工作台', '概览'] },
  search: { subsystem: 'workbench', requiredCapability: 'search.read', secureDomain: 'public', breadcrumb: ['工作台', '全局搜索'] },
  library: { subsystem: 'content', requiredCapability: 'resource.read', secureDomain: 'public', breadcrumb: ['内容与创作', '统一资源库'] },
  attachments: { subsystem: 'storage', requiredCapability: 'attachment.read', secureDomain: 'public', breadcrumb: ['附件与存储', '附件与 Blob'] },
  'private-notes': { subsystem: 'private-notes', requiredCapability: 'private_note.read', secureDomain: 'private_notes', breadcrumb: ['私密笔记', '保险库'] },
  passwords: { subsystem: 'passwords', requiredCapability: 'password_vault.read', secureDomain: 'passwords', breadcrumb: ['密码管理', '密码保险库'] },
  'security/users': { subsystem: 'identity-security', requiredCapability: 'user.read', secureDomain: 'security', breadcrumb: ['身份与安全', '用户与角色'] },
  'security/permissions': { subsystem: 'identity-security', requiredCapability: 'permission.read', secureDomain: 'security', breadcrumb: ['身份与安全', '权限矩阵'] },
  'ops/health': { subsystem: 'system-operations', requiredCapability: 'system.health.read', secureDomain: 'security', breadcrumb: ['系统运维', '系统健康与告警'] },
  'ops/background': { subsystem: 'system-operations', requiredCapability: 'system.task.read', secureDomain: 'security', breadcrumb: ['系统运维', '后台任务'] }
}

for (const [path, subsystem, capability, domain, group, label] of [
  ['activity', 'workbench', 'activity.read', 'public', '工作台', '我的活动与收藏'],
  ['collections', 'content', 'collection.read', 'public', '内容与创作', '集合与标签'], ['documents', 'content', 'document.read', 'public', '内容与创作', '文章与文档'], ['media', 'content', 'media.read', 'public', '内容与创作', '媒体消费'], ['sharing', 'content', 'share.read', 'public', '内容与创作', '分享与协作'],
  ['drive', 'drive', 'drive.read', 'public', '个人网盘', '文件空间'], ['drive/spaces', 'drive', 'drive.space.read', 'public', '个人网盘', '空间治理'], ['drive/transfers', 'drive', 'drive.transfer.read', 'public', '个人网盘', '传输中心'], ['drive/sync', 'drive', 'drive.sync.read', 'public', '个人网盘', '同步关系'], ['drive/conflicts', 'drive', 'drive.conflict.read', 'public', '个人网盘', '冲突处理'], ['drive/revisions', 'drive', 'drive.revision.read', 'public', '个人网盘', '版本历史'], ['drive/trash', 'drive', 'drive.trash.read', 'public', '个人网盘', '回收站'], ['drive/quota', 'drive', 'drive.quota.read', 'public', '个人网盘', '配额与策略'], ['drive/policies', 'drive', 'drive.policy.manage', 'public', '个人网盘', 'Drive Policies'],
  ['storage/tiers', 'storage', 'storage.provider.read', 'security', '附件与存储', '存储层'], ['storage/cache', 'storage', 'storage.cache.read', 'public', '附件与存储', '缓存与下载'], ['storage/archive', 'storage', 'storage.archive.read', 'public', '附件与存储', '归档与恢复'], ['storage/backup', 'storage', 'storage.backup.read', 'security', '附件与存储', '备份与恢复'],
  ['planning/today', 'planning', 'task.read', 'public', '效率与计划', '收集箱与今天'], ['planning/projects', 'planning', 'project.read', 'public', '效率与计划', '项目与任务'], ['planning/calendar', 'planning', 'calendar.read', 'public', '效率与计划', '日历与时间块'], ['planning/goals', 'planning', 'goal.read', 'public', '效率与计划', '目标与 OKR'], ['planning/focus', 'planning', 'focus.read', 'public', '效率与计划', '习惯与专注'],
  ['finance', 'finance', 'finance.read', 'finance', '个人记账', '账本总览'], ['finance/accounts', 'finance', 'finance.account.read', 'finance', '个人记账', '账户'], ['finance/transactions', 'finance', 'finance.transaction.read', 'finance', '个人记账', '交易'], ['finance/budgets', 'finance', 'finance.budget.read', 'finance', '个人记账', '预算与周期账'], ['finance/reconcile', 'finance', 'finance.reconcile.read', 'finance', '个人记账', '对账与导入'],
  ['private-notes/conflicts', 'private-notes', 'private_note.conflict.read', 'private_notes', '私密笔记', '版本与冲突'], ['private-notes/recovery', 'private-notes', 'private_note.recovery.read', 'private_notes', '私密笔记', '恢复与导出'], ['passwords/generator', 'passwords', 'password.generator.use', 'passwords', '密码管理', '生成器'], ['passwords/health', 'passwords', 'password.health.read', 'passwords', '密码管理', '健康与安全发送'], ['passwords/devices', 'passwords', 'password.device.read', 'passwords', '密码管理', '设备与访问'],
  ['ai/assistant', 'ai', 'ai.assistant.use', 'public', 'AI 智能', '助手'], ['ai/models', 'ai', 'ai.model.read', 'public', 'AI 智能', '模型与提供方'], ['ai/personas', 'ai', 'ai.persona.read', 'public', 'AI 智能', '人格'], ['ai/privacy', 'ai', 'ai.privacy.read', 'private_notes', 'AI 智能', '上下文与隐私'], ['ai/jobs', 'ai', 'ai.job.read', 'public', 'AI 智能', '作业与用量'],
  ['analytics', 'analytics', 'analytics.read', 'public', '数据分析', '个人概览'], ['analytics/content', 'analytics', 'analytics.content.read', 'public', '数据分析', '内容分析'], ['analytics/storage', 'analytics', 'analytics.storage.read', 'public', '数据分析', '存储分析'], ['analytics/planning', 'analytics', 'analytics.planning.read', 'public', '数据分析', '效率分析'], ['analytics/system', 'analytics', 'analytics.system.read', 'security', '数据分析', '系统历史'], ['analytics/metrics', 'analytics', 'analytics.metric.read', 'security', '数据分析', '指标目录'], ['analytics/reports', 'analytics', 'analytics.report.manage', 'security', '数据分析', '报表与重建'],
  ['integration/automation', 'integration', 'integration.automation.read', 'security', '集成与自动化', '自动化规则'], ['integration/executions', 'integration', 'integration.execution.read', 'security', '集成与自动化', '执行与 Trace'], ['integration/events', 'integration', 'integration.event.read', 'security', '集成与自动化', '事件与失败队列'], ['integration/sync', 'integration', 'integration.sync.read', 'public', '集成与自动化', '导入与同步'], ['integration/plugins', 'integration', 'integration.plugin.read', 'security', '集成与自动化', '插件与连接器'],
  ['security/sessions', 'identity-security', 'session.read', 'security', '身份与安全', '活跃会话'], ['security/authentication', 'identity-security', 'authentication.read', 'security', '身份与安全', '认证、密钥与恢复'], ['platform/parameters', 'platform', 'platform.parameter.read', 'security', '平台配置', '参数'], ['platform/dictionaries', 'platform', 'platform.dictionary.read', 'security', '平台配置', '字典'], ['platform/menus', 'platform', 'platform.menu.manage', 'security', '平台配置', '菜单'],
  ['communications/announcements', 'communications', 'announcement.manage', 'security', '沟通与审计', '公告'], ['communications/notifications', 'communications', 'notification.read', 'public', '沟通与审计', '通知中心'], ['communications/audit', 'communications', 'audit.read', 'security', '沟通与审计', '审计日志'], ['ops/jobs', 'system-operations', 'system.schedule.read', 'security', '系统运维', '定时任务']
] as const) meta[path] = { subsystem, requiredCapability: capability, secureDomain: domain, breadcrumb: [group, label] }

export function getRouteMeta(path: string): ConsoleRouteMeta {
  return meta[path] || { subsystem: 'console', requiredCapability: 'console.read', secureDomain: 'public', breadcrumb: ['Console', path] }
}
