name: Create Draft Release

on:
  push:
    tags:
      - "v[0-9]*"

permissions:
  contents: write

jobs:
  create-release:
    if: github.repository == 'ikaros-dev/ikaros'
    runs-on: ubuntu-latest
    steps:
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
