# This is a basic workflow to help you get started with Actions

name: Build FastJar

# Controls when the workflow will run
on:
  release:
    types: [published]

jobs:

  release:
    if: github.repository == 'ikaros-dev/ikaros'
    name: Build with java 17 and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Git submodule init
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Reduce pnpm concurrency
        run: pnpm config set fetch-retries 5 && pnpm config set fetch-timeout 60000 && pnpm config set max-concurrent-requests 6
      - name: Use npm mirror
        run: |
          npm config set registry https://registry.npmmirror.com
          pnpm config set registry https://registry.npmmirror.com
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Clean with gradle
        run: |
          ./gradlew clean
      - name: Build console with npm
        run: |
          ./gradlew buildFrontend -x test
      - name: Build server with gradle
        run: |
          ./gradlew build -x test
      - name: Build server fast jar
        run: |
          ./gradlew bootJar -x test
      - name: Upload fast jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.LI_GUOHAO_TOKEN }}
          file: /home/runner/work/ikaros/ikaros/server/build/libs/ikaros-server.jar
          asset_name: ikaros-server.jar




